import type { TocIndustry } from "./types"

/** v37 — Services: people businesses where revenue follows time, patients,
 *  students and guests. Common audit textures: service revenue timing,
 *  payroll intensity, third-party payer settlements, prepaid course
 *  income, and occupancy-driven cost leverage. */
export const SERVICES_INDUSTRIES: TocIndustry[] = [
  {
    id: "healthcare",
    sector: "services",
    name: "Healthcare Providers & Hospitals",
    icon: "stethoscope",
    blurb: "Hospitals, clinics, labs and pharmacy chains — insurer/patient/government revenue streams.",
    risks: ["Billing compliance (coding and charge capture)", "Third-party payer settlements", "Medical-legal liabilities", "Pharmacy inventory"],
    procedures: [
      "Test charge capture: sample episodes (encounters, procedures) to charge master application and invoicing.",
      "Reperform payer settlement reconciliations (insurer remittances vs claims, contractual disallowances) for a sample month.",
      "Inspect the coding-compliance function: coder qualifications, audit sampling programme, and outlier review.",
      "Test pharmacy/medical supplies: perpetual records, controlled-substance registers, and physical verification.",
      "Inspect the malpractice/claims register and the provision computation with actuarial/expert input.",
      "Inquire of revenue cycle: how are denials analyzed and appealed, and what is the aged-denial write-off policy?",
    ],
    questions: [
      { id: "hlt-01", domain: "control-activities", q: "Is every service event (encounter, procedure, test) charge-captured automatically from clinical systems, with a completeness reconciliation (activity vs charges) daily?", hint: "The gap between clinical activity and billing is the revenue leak. Ask for the activity-to-charge reconciliation and its exception handling.", weight: 3, critical: true },
      { id: "hlt-02", domain: "control-activities", q: "Is coding (ICD/CPT or equivalent) performed by qualified coders with an ongoing audit programme (sample re-coding), error feedback and correction loops?", hint: "Ask for the coding audit results — accuracy rate and the last correction cycle.", weight: 3, critical: true },
      { id: "hlt-03", domain: "control-activities", q: "Are payer contracts (tariffs, disallowances, bundling) maintained centrally, and are settlements reconciled claim-by-claim with contractual adjustments posted correctly (gross vs net)?", hint: "Ask for the contract matrix and the settlement reconciliation file; gross-up errors misstate revenue.", weight: 3 },
      { id: "hlt-04", domain: "control-activities", q: "Are controlled substances and high-value drugs tracked from receipt to administration (double-lock, waste witnessing, perpetual counts) with variance investigation?", hint: "Diversion is the sector's quiet theft. Ask for the last controlled-substance count and discrepancy log.", weight: 3, critical: true },
      { id: "hlt-05", domain: "control-activities", q: "Is the medical-liability (malpractice) provision computed from incident data with expert/actuarial input, reviewed quarterly, and covering reported + IBNR incidents?", hint: "Ask for the claims register and the IBNR methodology.", weight: 3 },
      { id: "hlt-06", domain: "control-activities", q: "Are staff credentialing and licence verification maintained (expiry tracking, privilege renewals) so services are delivered by qualified practitioners?", hint: "Unqualified practice voids billing and creates liability. Ask for the credentialing register and expiry alerts.", weight: 2 },
      { id: "hlt-07", domain: "info-communication", q: "Is patient-data privacy governed (access on need, breach response tested, consent management) with access logs monitored?", hint: "Ask for the last access-log review and breach drill.", weight: 2 },
      { id: "hlt-08", domain: "monitoring", q: "Are denials, days in A/R, cost per case, and length of stay tracked with thresholds and action protocols?", hint: "Ask for the revenue-cycle dashboard and one denial-rate action plan.", weight: 2 },
      { id: "hlt-09", domain: "control-activities", q: "Are government-programme billings (where applicable) supported by eligible documentation, with audits and repayment provisions for identified overbillings?", hint: "Overbilling recovery claws back revenue years later. Ask for the last programme audit and its findings.", weight: 3 },
      { id: "hlt-10", domain: "control-activities", q: "Is consumables/supplies inventory managed with par levels, expiry tracking and usage-to-activity analytics?", hint: "Supplies are the cost engine — ask for usage vs activity analytics (e.g., implants per procedure).", weight: 2 },
      { id: "hlt-11", domain: "risk-assessment", q: "Is clinical risk assessed systematically — incident reporting, morbidity/mortality review, infection-control surveillance — with actions tracked and lessons fed back to practice?", hint: "Ask for the incident register and one recent event's root-cause analysis and resulting change.", weight: 3 },
      { id: "hlt-12", domain: "it-cyber", q: "Are clinical systems (EHR, LIS, PACS) access-controlled with role-based permissions, break-the-glass logging, and audit-trail review for inappropriately accessed records?", hint: "Celebrity-record snooping is the classic breach. Ask who reviews access logs and what happened on the last flagged access.", weight: 3 },
    ],
  },
  {
    id: "education",
    sector: "services",
    name: "Education & Training",
    icon: "graduation-cap",
    blurb: "Schools, universities, institutes and corporate-training providers — prepaid tuition and term structures.",
    risks: ["Deferred tuition revenue over the academic term", "Student refunds and withdrawals", "Accreditation compliance", "Related-party facilities and services"],
    procedures: [
      "Test deferred-tuition computation (straight-line or term-pattern) for a sample of programmes and the roll-forward reconciliation.",
      "Inspect refund/withdrawal policy applications and the accrued liability for in-course withdrawals.",
      "Test scholarship/discount approvals against policy and their revenue-net treatment.",
      "Inspect accreditation status and the compliance obligations register.",
      "Test related-party leases/services (buildings, management fees) for approval, disclosure and arm's-length evidence.",
      "Inquire of registry: how are enrolment numbers reconciled to billing and attendance records?",
    ],
    questions: [
      { id: "edu-01", domain: "control-activities", q: "Is tuition revenue deferred and recognized over the instructional period (term/year) using a documented pattern, with the deferred-revenue roll-forward reconciled to enrolments monthly?", hint: "Cash-basis tuition recognition is the classic error. Ask for the deferral schedule and its reconciliation to the registry.", weight: 3, critical: true },
      { id: "edu-02", domain: "control-activities", q: "Is enrolment data (registrations, drops, transfers) reconciled from the student-information system to billing monthly, with no manual invoicing outside the SIS?", hint: "Ask for the SIS-to-billing reconciliation and who can raise a manual invoice.", weight: 3, critical: true },
      { id: "edu-03", domain: "control-activities", q: "Are scholarships, discounts and staff-fee waivers approved per policy, and recorded as revenue reductions (not expenses)?", hint: "Gross-up: waivers in an expense line misstate both revenue and cost. Ask for the discount policy and its application trail.", weight: 2 },
      { id: "edu-04", domain: "control-activities", q: "Are refund liabilities for withdrawals computed from policy and historical behaviour, with in-term withdrawals processed promptly and consistently?", hint: "Ask for the refund computation and the last term's actual refunds vs provision.", weight: 2 },
      { id: "edu-05", domain: "control-environment", q: "Are accreditation/licensing conditions (staff qualifications, facilities, curriculum) tracked with evidence files ready for inspection?", hint: "Lost accreditation is lost revenue. Ask for the accreditation obligations register and status.", weight: 2 },
      { id: "edu-06", domain: "control-activities", q: "Are related-party arrangements (owner buildings leased to the school, management companies) approved by the board, benchmarked, and disclosed?", hint: "The sector's classic profit-extraction channel. Ask for the related-party schedule and benchmarking evidence.", weight: 3 },
      { id: "edu-07", domain: "control-activities", q: "Are exam/assessment fees collected and remitted to awarding bodies reconciled, and are certification claims verified before invoicing students?", hint: "Ask for the awarding-body reconciliation.", weight: 2 },
      { id: "edu-08", domain: "monitoring", q: "Are enrolment, retention/continuation rates, and cost per student tracked against budget with action when off-plan?", hint: "Falling continuation rates hit next year's deferred revenue. Ask for the retention dashboard.", weight: 2 },
      { id: "edu-09", domain: "info-communication", q: "Is student data (minors included) protected — access on need, parental consents, retention schedules — with a data inventory?", hint: "Ask for the privacy inventory and consent tracking.", weight: 2 },
      { id: "edu-10", domain: "control-activities", q: "Are government grants/capitation (per-student funding) claims computed from verified attendance/enrolment data with conditions tracked?", hint: "Attendance-driven funding must survive audit. Ask for the last funding audit.", weight: 2 },
    ],
  },
  {
    id: "hospitality",
    sector: "services",
    name: "Hotels & Hospitality",
    icon: "bed",
    blurb: "Hotels, resorts and serviced apartments — room revenue, F&B and events under brand or franchise flags.",
    risks: ["PMS-to-ledger revenue integrity", "F&B cost controls", "OTA and channel commissions", "Guest deposits and loyalty points"],
    procedures: [
      "Test the PMS-to-ledger nightly reconciliation: room revenue, tax, city ledger, and deposits.",
      "Observe an F&B stocktake (bar and kitchen) and test the cost-of-sales (theoretical vs actual) analytics.",
      "Recompute OTA commission accruals and channel net rates for a sample month against reservation records.",
      "Inspect the guest-deposit and event/banquet advance ledger and the liability reconciliation.",
      "Test loyalty-point liability (earned, redeemed, expiry) and the breakage assumption.",
      "Inquire of front office: how are rebates, allowances and late charges approved and reviewed daily?",
    ],
    questions: [
      { id: "hos-01", domain: "control-activities", q: "Is the PMS revenue reconciled daily to the ledger (rooms, F&B, other) with a night-audit process, and are rebates/allowances approved by a second person and reviewed daily?", hint: "Ask for the night-audit pack and the rebate log. Front-desk rebates are the classic skim.", weight: 3, critical: true },
      { id: "hos-02", domain: "control-activities", q: "Are F&B costs controlled — standard recipes/portion control, receiving with invoices, storeroom locks, monthly stocktakes, and cost-percentage analytics by outlet?", hint: "Ask for the last F&B cost report vs theoretical and the variance follow-up.", weight: 3 },
      { id: "hos-03", domain: "control-activities", q: "Are OTA/channel commissions and net-rate terms reconciled from reservation records, with commission accruals matching settlement statements?", hint: "Ask for the channel reconciliation and the last OTA statement tie-out.", weight: 2 },
      { id: "hos-04", domain: "control-activities", q: "Are guest deposits, event advances and prepaid packages held as liabilities and recognized on consumption, reconciled monthly?", hint: "Ask for the deposits ledger and the package-revenue recognition schedule.", weight: 2 },
      { id: "hos-05", domain: "control-activities", q: "Is the loyalty-programme liability computed from points earned/redeemed/expired with reviewed breakage assumptions?", hint: "Ask for the points roll-forward and the breakage study.", weight: 2 },
      { id: "hos-06", domain: "control-activities", q: "Are cashiers' floats and house banks controlled — counted at handover, over/short logged, and daily banking reconciled?", hint: "Ask for the over/short log and its investigation pattern.", weight: 2 },
      { id: "hos-07", domain: "control-activities", q: "For franchised/managed properties: are management fees and brand/royalty fees computed from contract formulas and reconciled independently?", hint: "Ask for the fee computation and the owner's-operator reconciliation (if owner side).", weight: 2 },
      { id: "hos-08", domain: "monitoring", q: "Are RevPAR, occupancy, ADR and GOPPAR tracked daily/weekly against budget and competitive set, with revenue-management actions evidenced?", hint: "Ask for the revenue-management meeting and one pricing action's rationale.", weight: 2 },
      { id: "hos-09", domain: "risk-assessment", q: "Is seasonal and event-exposure assessed in cash-flow planning, with cancellation/attrition clauses in group contracts monitored?", hint: "Group attrition claims must be enforced to be recovered. Ask for the group attrition log.", weight: 1 },
      { id: "hos-10", domain: "control-environment", q: "Are safety, licensing and food-hygiene inspections maintained with findings tracked to closure?", hint: "License lapses close outlets. Ask for the inspection register.", weight: 2 },
    ],
  },
  {
    id: "restaurants",
    sector: "services",
    name: "Restaurants & Food Service",
    icon: "chef",
    blurb: "QSR, casual dining, catering and delivery-first kitchens — cash-dense, inventory-light, labor-heavy.",
    risks: ["Cash and POS integrity", "Food cost and portion control", "Delivery-platform settlements", "Payroll intensity and tips"],
    procedures: [
      "Analyse POS voids/refunds/discounts by employee and daypart, inspecting the exception review evidence.",
      "Test theoretical-vs-actual food cost for a sample of menu items and the variance investigation records.",
      "Reconcile delivery-platform settlements (orders, commissions, marketing fees) to the internal order data.",
      "Inspect the tip-pooling and service-charge records for payroll and tax compliance.",
      "Observe a full stocktake (including a surprise count of high-value items) and test cut-off of deliveries.",
      "Inquire of operations: how are transfers between branches and waste recorded and reviewed?",
    ],
    questions: [
      { id: "res-01", domain: "control-activities", q: "Is daily cash from each store reconciled to POS sales (Z-reports) with independent review, and are voids/refunds/discounts exception-reported by employee with action?", hint: "Ask for a week of daily reconciliation packs and the void-by-employee report.", weight: 3, critical: true },
      { id: "res-02", domain: "control-activities", q: "Are food costs controlled — recipes/portion standards, receiving checked against invoices, waste logged, and cost-of-sales % reviewed weekly per store?", hint: "Ask for the weekly food-cost report and the worst store's action plan.", weight: 3, critical: true },
      { id: "res-03", domain: "control-activities", q: "Are delivery-platform settlements reconciled monthly (orders, commission, marketing deductions, refunds) to internal sales records?", hint: "Ask for the platform reconciliation and the treatment of platform-funded discounts.", weight: 2 },
      { id: "res-04", domain: "control-activities", q: "Are tips and service charges collected, pooled and distributed per policy with tax treatment handled and documented?", hint: "Ask for the tip-pool records and the payroll integration.", weight: 2 },
      { id: "res-05", domain: "control-activities", q: "Are store-level inventory counts (weekly high-value, monthly full) performed with variance thresholds, and are store-to-store transfers documented?", hint: "Undocumented transfers make every store's cost wrong. Ask for the transfer log.", weight: 2 },
      { id: "res-06", domain: "control-activities", q: "Is payroll controlled — clock-ins verified to rota, overtime approved, ghost-employee checks (headcount to payroll) periodic?", hint: "Ask for the rota-to-payroll reconciliation and the last ghost-employee sweep.", weight: 2 },
      { id: "res-07", domain: "risk-assessment", q: "Are food-safety obligations (HACCP-lite, hygiene scores, temperature logs) maintained with inspection readiness?", hint: "A failed hygiene score posts to social media before it posts to the ledger. Ask for the temperature log and inspection history.", weight: 2 },
      { id: "res-08", domain: "monitoring", q: "Are store P&Ls (sales per labor hour, prime cost, contribution) reviewed weekly with underperformers actioned?", hint: "Ask for the weekly scorecard and one turnaround case.", weight: 2 },
      { id: "res-09", domain: "control-activities", q: "Are supplier pricing (contract vs invoice), rebates and rebillings reconciled, with new supplier approvals per matrix?", hint: "Ask for the price-variance report and the supplier approval file.", weight: 2 },
      { id: "res-10", domain: "info-communication", q: "Is the POS master data (menu prices, tax rates, service-charge flags) change-controlled with approvals and rollout logs?", hint: "Wrong tax flags accumulate liabilities. Ask for the menu-change log.", weight: 2 },
    ],
  },
  {
    id: "professional-services",
    sector: "services",
    name: "Professional Services",
    icon: "briefcase",
    blurb: "Law, consulting, accounting, engineering and architecture firms — time-based revenue and partner economics.",
    risks: ["WIP realization and billing cut-off", "Contingent/fixed-fee engagements", "Partner current accounts and distributions", "Client disbursements"],
    procedures: [
      "Test WIP ageing and the realization analysis: billed vs written-down time, with approval evidence for write-offs.",
      "Inspect fixed-fee/contingent engagement terms and test the revenue recognition basis against delivered milestones.",
      "Reconcile client disbursement records to vendor invoices and the markup policy application.",
      "Test partner drawing/distribution computations to the partnership deed.",
      "Inspect the unbilled receivable ageing and the invoicing cycle's completeness (delivered work → draft bill → invoice).",
      "Inquire of partners: how is work-in-progress reviewed before being raised to bills, and who approves discounts?",
    ],
    questions: [
      { id: "prf-01", domain: "control-activities", q: "Is time recorded to matters daily/weekly with partner or manager approval, locked after period close, and is WIP aged with write-downs approved above thresholds?", hint: "Ask for the WIP ageing and the write-down approval log. Eternal WIP is fictional profit.", weight: 3, critical: true },
      { id: "prf-02", domain: "control-activities", q: "Are fixed-fee and capped engagements recognized per progress (milestones or costs incurred), with estimates reviewed by someone other than the responsible partner?", hint: "Ask for the fixed-fee portfolio report and one engagement's estimate review.", weight: 3 },
      { id: "prf-03", domain: "control-activities", q: "Are contingent-fee engagements (where permitted) identified, tracked, and recognized only when the outcome is probable, with disclosure where ethics rules require?", hint: "Ask for the contingency register and the recognition gate applied.", weight: 3 },
      { id: "prf-04", domain: "control-activities", q: "Are client disbursements tracked per matter (third-party costs recharged), with markup policy applied and recoverability assessed (WIP recoverable vs not)?", hint: "Unrecoverable disbursements must not sit as assets. Ask for the disbursement ageing and the recoverability test.", weight: 2 },
      { id: "prf-05", domain: "control-activities", q: "Are partner current accounts, drawings, and profit-share distributions computed per the partnership deed, and reconciled to equity annually?", hint: "Ask for the distribution computation and the last accountant's reconciliation to the deed.", weight: 3 },
      { id: "prf-06", domain: "risk-assessment", q: "Is professional-indemnity coverage maintained and claims experience tracked, with the insurance schedule matching the risk profile?", hint: "Ask for the PI schedule, the claims history, and tail coverage for departed partners.", weight: 2 },
      { id: "prf-07", domain: "monitoring", q: "Are utilization, realization, lockup days (WIP + debtors) and matter profitability tracked monthly with partner accountability?", hint: "Lockup is the sector's cash disease. Ask for the lockup report and the last improvement action.", weight: 2 },
      { id: "prf-08", domain: "control-environment", q: "Are conflicts-of-interest and independence checks run at intake and on new matters, with an independence register maintained?", hint: "Ask for the conflicts database and the escalation trail of the last identified conflict.", weight: 2 },
      { id: "prf-09", domain: "control-activities", q: "Is client money held in separate client accounts (where rules require), reconciled per matter with interest treatment per regulation?", hint: "Client-account discipline is regulator-enforced. Ask for the last three-way client-account reconciliation.", weight: 3, critical: true },
      { id: "prf-10", domain: "info-communication", q: "Are matter-management and billing systems reconciled to the ledger monthly, and are billing rates controlled (rate cards approved, overrides logged)?", hint: "Ask for the rate-override report and its review.", weight: 2 },
    ],
  },
  {
    id: "tourism",
    sector: "services",
    name: "Travel & Tourism",
    icon: "palmtree",
    blurb: "Tour operators, travel agencies, DMCs and attraction operators — other people's inventory sold on margin.",
    risks: ["Agency vs principal (gross vs net revenue)", "Supplier settlements (hotels, airlines)", "Customer deposits and refunds", "Seasonality and FX"],
    procedures: [
      "Test principal-vs-agent classification across product lines (packaged tours vs agency bookings) with the control analysis documented.",
      "Reconcile supplier statements (hotel/air) to internal booking records and the payable ledger for a sample month.",
      "Inspect the customer-deposit liability reconciliation and the refund pipeline's ageing.",
      "Test FX exposure on package pricing and the hedging/rate policy application.",
      "Inspect the unearned-revenue recognition schedule for packages (over the trip dates) and events.",
      "Inquire of operations: how are group block bookings and attrition clauses tracked?",
    ],
    questions: [
      { id: "trv-01", domain: "control-activities", q: "Is each product line classified principal or agent per IFRS 15 control analysis, and is revenue computed gross or net accordingly — consistently, with the analysis documented?", hint: "Packages (we control the service pre-delivery) vs agency bookings (we arrange). Ask for the classification memo per product line.", weight: 3, critical: true },
      { id: "trv-02", domain: "control-activities", q: "Are supplier confirmations reconciled to bookings (rooms, seats) before customer travel, with discrepancies chased daily?", hint: "Overbooking incidents become refunds and liabilities. Ask for the reconciliation process in the reservation system.", weight: 2 },
      { id: "trv-03", domain: "control-activities", q: "Are customer deposits tracked per booking, recognized over the trip dates (or at service), with refunds accrued per policy and cancellation curves?", hint: "Ask for the deposits ledger and the cancellation-provision computation.", weight: 3, critical: true },
      { id: "trv-04", domain: "control-activities", q: "Are supplier payables reconciled monthly to statements (hotels, DMCs, carriers) with disputed items logged and aged?", hint: "Ask for the supplier reconciliation and the largest open dispute.", weight: 2 },
      { id: "trv-05", domain: "risk-assessment", q: "Is FX risk on foreign-currency package pricing identified with a rate policy (hedging, surcharge clauses) approved and applied?", hint: "Ask for the FX policy and the last period's realized FX variance.", weight: 2 },
      { id: "trv-06", domain: "control-activities", q: "Are commissions to sub-agents and referral partners computed from reported sales, with anti-fraud cross-checks (booking existence) before payment?", hint: "Sub-agent commission fraud (phantom bookings) is the sector's scam. Ask for the pre-payment verification.", weight: 3 },
      { id: "trv-07", domain: "monitoring", q: "Are booking volumes, average package value, cancellation rates and source-market mix tracked against plan with margin analysis?", hint: "Ask for the monthly trading pack and one margin action.", weight: 2 },
      { id: "trv-08", domain: "control-environment", q: "Are licensing and consumer-protection schemes (travel-guarantee funds, insurance) maintained and evidence filed?", hint: "Consumer-protection lapses void operating licences. Ask for the fund/insurance status.", weight: 2 },
      { id: "trv-09", domain: "info-communication", q: "Is the reservation system reconciled to the ledger daily (bookings, payments, changes, cancellations) with exception queues cleared?", hint: "Ask who does the daily rec and the size of the exception queue.", weight: 2 },
      { id: "trv-10", domain: "control-activities", q: "For events/MICE: are group attrition, cancellation and force-majeure clauses tracked per contract with provisions for expected cancellations?", hint: "Ask for the group contract register and attrition watchlist.", weight: 2 },
    ],
  },
]
