import type { TocIndustry } from "./types"

/** v37 — Transport & Logistics: revenue follows vehicles, vessels and
 *  cargo. Common audit textures: consignment/freight liability, fuel and
 *  maintenance costs, sub-carrier payable accruals, and asset-utilization
 *  analytics that double as completeness tests. */
export const TRANSPORT_INDUSTRIES: TocIndustry[] = [
  {
    id: "logistics-3pl",
    sector: "transport",
    name: "Logistics & 3PL Warehousing",
    icon: "truck",
    blurb: "Freight forwarding, contract logistics, warehousing and last-mile delivery operators.",
    risks: ["Consignment goods (own vs held)", "Sub-carrier payable completeness", "Fuel and driver cost controls", "Customer SLA credit liability"],
    procedures: [
      "Observe a client-stock count in the warehouse and test the reconciliation to the WMS and to client statements.",
      "Reperform the sub-carrier accrual: dispatch records vs carrier invoices vs the payable ledger for a sample month.",
      "Test fuel-card analytics: fill events per vehicle vs distance/telemetry, with exception reports reviewed.",
      "Inspect the SLA/penalty clauses in customer contracts and test the accrual for service credits.",
      "Trace a sample of warehouse activity (inbounds, outbounds, storage days) to client invoices.",
      "Inquire of operations: how is cargo loss/damage reported, costed, recovered and disclosed?",
    ],
    questions: [
      { id: "log-01", domain: "control-activities", q: "Are customer-owned goods in the warehouse tracked in a WMS with cycle counts, damage/quarantine handling, and monthly statements reconciled to client records?", hint: "We hold other people's inventory: count it like our own. Ask for the last cycle-count results and client statement reconciliations.", weight: 3, critical: true },
      { id: "log-02", domain: "control-activities", q: "Are sub-carrier ( subcontracted transport ) liabilities complete — dispatches recorded, invoices matched to the dispatch log, with period-end accruals for runs completed but unbilled?", hint: "The payables side of freight is the completeness battleground. Ask for the dispatch-to-invoice reconciliation and the accrual method.", weight: 3, critical: true },
      { id: "log-03", domain: "control-activities", q: "Is billing driven by the operational systems (milestones, weight/volume, storage days) with an exception queue for unbilled activity cleared weekly?", hint: "Unbilled storage and missed accessorials (detention, demurrage) are silent revenue leaks. Ask for the unbilled-activity report.", weight: 3 },
      { id: "log-04", domain: "control-activities", q: "Are fuel cards and tolls controlled per vehicle with analytics (litres per 100km vs route) and exceptions investigated?", hint: "Fuel is the top divertible cost. Ask for the fuel analytics report and the last exception investigated.", weight: 2 },
      { id: "log-05", domain: "control-activities", q: "Are driver payroll variables (trips, overtime, per-diem) computed from verified trip records and cross-checked to delivery evidence (PODs)?", hint: "Payroll from unverified trip sheets inflates both payroll and trip revenue risk. Ask who audits PODs.", weight: 2 },
      { id: "log-06", domain: "risk-assessment", q: "Are customer SLA/penalty regimes mapped (service credits, claims exposure) and accrued when triggered, with claims logs reconciled to the ledger?", hint: "Service credits usually flow only when customers claim them — the liability must be self-estimated. Ask for the SLA liability model.", weight: 2 },
      { id: "log-07", domain: "control-activities", q: "Is cargo claims handling controlled — claim intake, liability assessment, recovery from insurers/carriers — with provisions for expected claims?", hint: "Ask for the open claims register and the expected-cost assessment.", weight: 2 },
      { id: "log-08", domain: "control-environment", q: "Are customs/trade-compliance functions (broker licences, HS classification, AEO status) maintained with internal checks on declarations?", hint: "Misclassification penalties land years later. Ask who audits customs declarations.", weight: 2 },
      { id: "log-09", domain: "monitoring", q: "Is fleet/warehouse utilization (truck fill, pallet positions, cost per delivery) tracked and benchmarked monthly with actions?", hint: "Utilization analytics double as revenue-completeness tests. Ask for the monthly operations review pack.", weight: 2 },
      { id: "log-10", domain: "it-cyber", q: "Are WMS/TMS access rights role-based, with shipping and inventory adjustments requiring approval and an audit trail reviewed periodically?", hint: "Inventory adjustments and shipment edits are the WMS's sensitive transactions. Ask for the change log review.", weight: 2 },
      { id: "log-11", domain: "control-activities", q: "Is cross-dock / in-transit stock identified and reconciled (goods between sites) at each period end?", hint: "In-transit goods vanish from both ends' counts. Ask for the in-transit reconciliation.", weight: 2 },
    ],
  },
  {
    id: "aviation",
    sector: "transport",
    name: "Airlines & Aviation",
    icon: "plane",
    blurb: "Passenger and cargo airlines, ground handling and MRO (maintenance-repair-overhaul) shops.",
    risks: ["Revenue integrity (tickets, interline, refunds)", "Fleet maintenance and lease returns", "Frequent-flyer liabilities", "Fuel hedging and FX"],
    procedures: [
      "Test revenue integrity: sample flown coupons to the revenue accounting pipeline, interline billing matches, and the proration model.",
      "Inspect the MRO records: airworthiness directives closure, component lifecycles, and maintenance accruals (power-by-the-hour).",
      "Reperform the loyalty-programme liability (points earned, breakage, deferred revenue allocation for miles sold to partners).",
      "Test lease-return conditions and end-of-lease provisions (redelivery checks, expected restoration costs).",
      "Inspect fuel-hedge documentation, effectiveness, and the derivative positions vs the risk policy.",
      "Inquire of revenue accounting: how are unused tickets, refunds and chargebacks reconciled and accrued?",
    ],
    questions: [
      { id: "av-01", domain: "control-activities", q: "Is flown revenue captured automatically from the departure-control / revenue-accounting system, with interline billings reconciled to clearing-house settlements monthly?", hint: "Ask for the ICH/ACH reconciliation and the proration review. Manual revenue adjustments are the risk gate.", weight: 3, critical: true },
      { id: "av-02", domain: "control-activities", q: "Are unused-ticket liabilities, refunds and agency/chargeback credits reconciled monthly to the BSP/ARC settlement statements, with the liability actuarially assessed?", hint: "Refund leakage and stale liabilities both misstate. Ask for the unused-ticket liability roll-forward.", weight: 3 },
      { id: "av-03", domain: "control-activities", q: "Is maintenance accounting controlled — component life tracking, heavy-check accruals (or power-by-the-hour), and rotable pool valuations — reconciled to the engineering system?", hint: "Ask who reconciles the AMOS/trax engineering data to the maintenance liability and rotable assets.", weight: 3, critical: true },
      { id: "av-04", domain: "control-activities", q: "Is the loyalty-programme liability computed from earned/deferred points, breakage analysis and partner-sold miles pricing, reviewed by finance each period?", hint: "Ask for the breakage study vintage — using 5-year-old breakage flatters profit.", weight: 3 },
      { id: "av-05", domain: "control-activities", q: "Are aircraft lease and purchase obligations tracked in a register with return conditions, and are end-of-lease restoration obligations provisioned?", hint: "Redelivery disputes are expensive. Ask for the lease-return condition file and provisioning.", weight: 2 },
      { id: "av-06", domain: "risk-assessment", q: "Are fuel-price and FX exposures measured and hedged per board policy, with derivative documentation and effectiveness testing for hedge accounting?", hint: "Ask for the hedging policy, positions, and last effectiveness test.", weight: 2 },
      { id: "av-07", domain: "control-activities", q: "Is ground/handling and slot expenditure reconciled to handling agents' invoices with volume cross-checks (turnarounds, passengers)?", hint: "Handling bills are messy — reconciling to traffic data is the control. Ask for the last handling-invoice audit.", weight: 2 },
      { id: "av-08", domain: "control-environment", q: "Are safety-management-system findings and regulator (civil aviation authority) oversight items tracked to closure with board visibility?", hint: "Safety findings carry both operational and financial (grounding) consequences. Ask for the SMS register and overdue items.", weight: 2 },
      { id: "av-09", domain: "monitoring", q: "Are yield, load factor, on-time performance and unit cost (CASK) tracked against network plan with action when off-plan?", hint: "These metrics are also accounting integrity signals (revenue per ASK drifting down unbeknownst = revenue leakage).", weight: 2 },
      { id: "av-10", domain: "control-activities", q: "Are cargo revenue and interline/interlining partners' liabilities reconciled, with ULD (container/pallet) assets tracked?", hint: "ULDs are assets with a life of their own — ask for the ULD register.", weight: 1 },
    ],
  },
  {
    id: "shipping-ports",
    sector: "transport",
    name: "Shipping & Ports",
    icon: "ship",
    blurb: "Container and bulk shipping lines, port terminals, stevedores and ship agencies.",
    risks: ["Vessel revenue and voyage accounting", "Bunker fuel measurement and hedging", "Container fleet tracking and leasing", "Laytime/demurrage settlements"],
    procedures: [
      "Reperform a voyage account: freight revenue, address-commission, bunker consumption, port costs and the cut-off between voyages.",
      "Test bunker deliveries: mass-flow meter / barge receipts to the vessel log, price index to invoice, and consumption per day at sea.",
      "Inspect the container register (owned/leased) and reconcile lease-in/lease-out statements and repositioning costs.",
      "Test laytime/demurrage calculations from the statement of facts for a sample of port calls.",
      "Inspect charter-party terms and test hire payments, off-hire claims and speed-consumption warranties.",
      "Inquire of operations: how is stowage/stevedore damage recorded and recovered?",
    ],
    questions: [
      { id: "shp-01", domain: "control-activities", q: "Is vessel revenue controlled through the shipping system (bill of lading data → revenue accounting) with a monthly reconciliation of freight, demurrage and address commissions to the ledger?", hint: "BL-level data must land in the ledger per voyage. Ask for the voyage reconciliation and the handling of part-cargoes and dead freight.", weight: 3, critical: true },
      { id: "shp-02", domain: "control-activities", q: "Are bunker purchases measured on delivery (BDN, mass-flow meters), priced per contract index, and reconciled to consumption logs per voyage?", hint: "Bunker fraud (short deliveries, clogged sounding) is endemic. Ask who verifies the BDN vs the vessel's figures.", weight: 3, critical: true },
      { id: "shp-03", domain: "control-activities", q: "Is the container fleet tracked (owned, leased-in, leased-out, off-hire) with monthly reconciliations to lessor statements and damage-repair costs recovered?", hint: "Container leasing statements and actual boxes drift apart. Ask for the box reconciliation and the damage-claim process.", weight: 2 },
      { id: "shp-04", domain: "control-activities", q: "Are laytime/demurrage and dispatch computations prepared from the statement of facts with independent review, and claims tracked to collection?", hint: "Demurrage revenue requires the SOF discipline. Ask for the laytime module and open claims ageing.", weight: 2 },
      { id: "shp-05", domain: "risk-assessment", q: "Are charter-party exposures (hire, ballast bonuses, speed warranties, early redelivery) tracked with a charter register that finance reconciles to?", hint: "The charter terms are contractual cash flows. Ask for the charter register and its reconciliation to hire payments.", weight: 2 },
      { id: "shp-06", domain: "control-activities", q: "For terminals: are throughput volumes measured (gate, crane moves) and reconciled to customer invoices, including free-time expiries?", hint: "Every crane move is revenue. Ask for the terminal operating system to billing reconciliation.", weight: 3 },
      { id: "shp-07", domain: "control-activities", q: "Are port/concession agreements (minimum guarantees, revenue shares) accounted for with periodic re-assessment of onerous terms?", hint: "Volume guarantees in downturns become onerous. Ask for the concession liability review.", weight: 2 },
      { id: "shp-08", domain: "control-environment", q: "Are maritime compliance regimes (ISM, ISPS, sanctions screening of counterparties/cargoes) maintained with internal audit of screening logs?", hint: "Sanctions breaches freeze assets and trigger fines. Ask who owns sanctions screening and the last audit.", weight: 3 },
      { id: "shp-09", domain: "monitoring", q: "Are vessel performance metrics (speed, consumption, utilization, idle days) tracked with deviation investigation?", hint: "Performance drift signals both commercial and measurement problems. Ask for the fleet report.", weight: 2 },
      { id: "shp-10", domain: "control-activities", q: "Is dry-dock and special-survey planning accounted for (accruals/deferred over the cycle) consistently, with vendors reconciled?", hint: "Dry-dock amortization methods must be consistent. Ask for the policy and the current cycle's accounting.", weight: 2 },
    ],
  },
  {
    id: "ground-transport",
    sector: "transport",
    name: "Ground Transport & Rail",
    icon: "train",
    blurb: "Trucking fleets, bus and coach operators, rail freight and passenger operators.",
    risks: ["Fleet utilization and revenue per km", "Fuel and tire costs", "Maintenance lifecycle and safety", "Accessorial and damage claims"],
    procedures: [
      "Test toll/fuel/telemetry analytics per vehicle for a sample month against trip records and customer billing.",
      "Inspect the maintenance system: service intervals, defect closure, and the repair-vs-capital split with policy evidence.",
      "Reconcile drivers' trip sheets to customer invoices and payroll for a sample of routes.",
      "Inspect the concession/franchise (for rail) obligations and their revenue and cost recognition.",
      "Test insurance claims register to the ledger (third-party damage, cargo claims) and provisions.",
      "Inquire of dispatch: how are empty runs minimized and unauthorized use of vehicles detected?",
    ],
    questions: [
      { id: "grt-01", domain: "control-activities", q: "Is every trip recorded (telemetry, trip sheets) and reconciled to customer billing and driver payroll, so revenue and cost per trip tie to operations?", hint: "Trip sheets nobody reconciles = payroll and revenue both leak. Ask for the trip-to-invoice-to-payroll triangle check.", weight: 3, critical: true },
      { id: "grt-02", domain: "control-activities", q: "Is fuel controlled per vehicle (cards, litres per km analytics, route norms) with monthly exception review and discipline for off-norm vehicles?", hint: "Ask for the fuel league table and the consequence for the worst vehicle three months running.", weight: 2 },
      { id: "grt-03", domain: "control-activities", q: "Is the maintenance regime enforced — service intervals by km/hours tracked, defects logged and closed, and unsafe vehicles immobilized?", hint: "Safety-critical and cost-critical. Ask for the overdue-service report and who can override an immobilization.", weight: 3, critical: true },
      { id: "grt-04", domain: "control-activities", q: "Are tire, spare-parts and consumables inventories held in stores with issue records to vehicles, and cycle counts?", hint: "Tires and parts are the fleet's petty cash. Ask for the last parts-store count.", weight: 2 },
      { id: "grt-05", domain: "control-activities", q: "Is the repair-vs-capitalization line (overhauls, rebuilds, modifications) governed by policy and applied consistently with approval thresholds?", hint: "Component overhauls have their own accounting (capitalization vs expense, useful lives). Ask for the policy and recent examples.", weight: 2 },
      { id: "grt-06", domain: "control-activities", q: "Are customer damage claims, accessorial charges (waiting time, detention) and penalties recorded via the operations system with approval before credit?", hint: "Accessorial revenue unbilled and credits unapproved are the two ends of leakage. Ask for the detention report and credit notes log.", weight: 2 },
      { id: "grt-07", domain: "risk-assessment", q: "For rail/franchise operations: are concession obligations (pensions, track access, rolling-stock leases, minimum service) tracked with onerous-contract review?", hint: "Franchises are long-dated obligations. Ask for the concession-compliance review.", weight: 2 },
      { id: "grt-08", domain: "control-environment", q: "Are driving-hours and licensing compliance monitored (tachograph/ELD analysis) with violations managed?", hint: "Regulatory breach both endangers the licence and signals operational discipline. Ask for the tacho exception review.", weight: 2 },
      { id: "grt-09", domain: "monitoring", q: "Is fleet utilization (loaded-km ratio, deadhead) and cost per km tracked monthly against budget with corrective action?", hint: "Idle fleet still depreciates. Ask for the utilization report and the action on the worst route.", weight: 2 },
      { id: "grt-10", domain: "control-activities", q: "Are vehicle disposals approved, valuations obtained for trades, and proceeds reconciled to the asset register?", hint: "Trade-in valuation is the soft spot — ask who verifies trade-in values against market.", weight: 2 },
    ],
  },
]
