import type { TocIndustry } from "./types"

/** v37 — Primary & Extractive industries: things grown, caught, felled,
 *  dug and pumped. Common audit textures: biological assets (IAS 41),
 *  commodity price exposure, remote sites, government quotas and
 *  subsidies, and heavy reliance on physical stock counts. */
export const PRIMARY_INDUSTRIES: TocIndustry[] = [
  {
    id: "agriculture",
    sector: "primary",
    name: "Agriculture & Farming",
    icon: "sprout",
    blurb: "Crop production, livestock, dairy and mixed farms — from smallholder suppliers to industrial estates.",
    risks: ["Biological asset valuation (IAS 41)", "Unrecorded cash sales of harvest", "Government subsidy compliance", "Weather and commodity price volatility"],
    procedures: [
      "Inspect the biological-asset register and reconcile physically-verified heads/hectares to the valuation working at period end.",
      "Observe the harvest or livestock count at a sample of sites and trace the tally sheets into sales and inventory records.",
      "Reperform the fair-value-less-costs-to-sell computation for one harvested crop, including the active-market quote used.",
      "Inspect subsidy claims against the scheme rules and confirm receipts to bank statements.",
      "Test completeness of sales: sequence sales receipts/weights tickets around harvest dates and investigate gaps.",
      "Inquire of agronomists and buyers: how are off-take prices set, and who can override them?",
    ],
    questions: [
      { id: "agr-01", domain: "control-activities", q: "Are biological assets (crops, livestock) counted and reconciled to a register at least annually, with variances investigated?", hint: "Ask who counts, how often, and to see the last count sheet with sign-off. Counts by the custodian alone are weak.", weight: 3, critical: true },
      { id: "agr-02", domain: "control-activities", q: "Is there a fair-value measurement process for biological assets that uses observable market prices, documented at each reporting date?", hint: "Probe the price source (market board, cooperative quotes) and who reviews it. Manager-invented prices are a valuation risk under IAS 41.", weight: 3 },
      { id: "agr-03", domain: "risk-assessment", q: "Are government grants and subsidies identified, claimed by an owner, and their conditions tracked so repayment triggers are not missed?", hint: "Grant conditions often carry inspection/compliance clauses. Ask for the grant file and the compliance evidence.", weight: 2 },
      { id: "agr-04", domain: "control-activities", q: "Are harvest and sales proceeds recorded at the point of delivery — weighbridge/dockets or buyer statements matched to the ledger daily?", hint: "The classic fraud is a cash buyer at the farm gate. Ask how a sale could happen with no docket and who would notice.", weight: 3, critical: true },
      { id: "agr-05", domain: "control-activities", q: "Are seed, feed, fertilizer and chemical inventories stored under custody controls with issue records to fields/herds?", hint: "Expensive inputs are easily diverted and resold. Ask for the stock card and the last physical count of the input store.", weight: 2 },
      { id: "agr-06", domain: "control-activities", q: "Is livestock mortality, birth and movement recorded as it happens, with vet or third-party corroboration available?", hint: "Unrecorded births + phantom deaths = untraceable sales. Ask who reports events and how the register is updated.", weight: 2 },
      { id: "agr-07", domain: "risk-assessment", q: "Is there a documented process for weather, disease and price shocks — insurance, hedging or diversification — reviewed with the board?", hint: "Farming risk management is often informal. Ask what happened in the last bad year and what changed.", weight: 1 },
      { id: "agr-08", domain: "info-communication", q: "Are contracts with cooperatives, off-take buyers and landlords centrally filed with key terms (price formulas, quantities) summarized for finance?", hint: "Side agreements on price formulas distort revenue timing. Ask how finance learns of a renegotiated contract.", weight: 2 },
      { id: "agr-09", domain: "control-activities", q: "Is fuel, machinery and spare-parts use on remote sites logged and reviewed against activity (hectares worked, hours run)?", hint: "Fuel diversion is the most common rural theft. Fuel draw vs. tractor hours analytics are the tell.", weight: 1 },
      { id: "agr-10", domain: "monitoring", q: "Are yields per hectare and cost per unit tracked and benchmarked year-on-year, with unexplained swings investigated?", hint: "A falling yield with steady input purchases can hide input theft or unrecorded sales.", weight: 2 },
      { id: "agr-11", domain: "control-activities", q: "Are pesticide and veterinary-medicine purchases and usage logged for residue/traceability compliance, with retention periods respected?", hint: "Food-safety audits and export certificates depend on these logs. Missing application records can void contracts.", weight: 1 },
      { id: "agr-12", domain: "control-environment", q: "Where farms operate across scattered sites, is there a site manager accountability structure with regular management visits and reporting?", hint: "Distance kills control. Ask how often head office physically attends each site and what they check.", weight: 2 },
    ],
  },
  {
    id: "fishing",
    sector: "primary",
    name: "Fishing & Aquaculture",
    icon: "fish",
    blurb: "Wild-catch fleets and fish farms — quota fisheries, processors at dockside and aquaculture estates.",
    risks: ["Quota and license compliance", "Unrecorded catch sales (black fish)", "Biomass estimation in farms", "Fuel and crew cost controls"],
    procedures: [
      "Inspect quota statements and reconcile landings (logbooks, VMS data) against the quota allocated and sales invoices.",
      "Observe a landing: compare the auction/processor weighment with the vessel's logbook entry for the same haul.",
      "Reperform farm biomass estimates (sample counts x average weight) and challenge the mortality assumptions.",
      "Test the completeness of catch sales by sequencing processor settlement statements to the cash book.",
      "Inspect vessel maintenance and fuel records for reasonableness against days-at-sea.",
      "Inquire of skippers and farm managers: who can sell fish outside the normal settlement route, and what would catch it?",
    ],
    questions: [
      { id: "fsh-01", domain: "control-activities", q: "Are all catch landings recorded through verified weighment (auction, dock scale) and reconciled to vessel logbooks and sales records?", hint: "The 'black fish' risk: landings sold off-the-books for cash. Ask what stops a skipper selling a pallet directly.", weight: 3, critical: true },
      { id: "fsh-02", domain: "control-activities", q: "Is quota usage tracked in near-real-time against licenses, with a stop-fishing escalation before limits are breached?", hint: "Over-quota fishing creates regulatory penalties and contingent liabilities. Ask who watches the tracker and what happened last time the fleet approached the limit.", weight: 3 },
      { id: "fsh-03", domain: "control-activities", q: "For aquaculture: are biomass estimates (stock counts, average weights, mortality) performed on a defined methodology and independently checked?", hint: "Fish in a pen are an estimate, not a count — the biological asset number is management's model. Probe who reviews the sampling and mortality assumptions.", weight: 3 },
      { id: "fsh-04", domain: "risk-assessment", q: "Are disease outbreaks, algae events and escapes planned for — with insurance, contingency and disclosure triggers mapped?", hint: "One pen wipe-out can end a farm. Ask for the last incident and how it was detected, reported and accounted.", weight: 2 },
      { id: "fsh-05", domain: "control-activities", q: "Is crew payroll (shares, trip bonuses) computed from the same verified landings data that feeds sales?", hint: "Two payroll bases — one for crew, one for the ledger — is a classic mismatch fraud. The settlement sheet must tie to both.", weight: 2 },
      { id: "fsh-06", domain: "control-activities", q: "Are vessel fuel bunkering, provisions and repairs procured through approved suppliers with engine-log cross-checks?", hint: "Skippers with open fuel cards and no logs invite diversion. Fuel-per-day-at-sea analytics flag it.", weight: 1 },
      { id: "fsh-07", domain: "info-communication", q: "Do processors/off-take contracts get signed before the season, with pricing formulas given to finance — so side deals are visible?", hint: "Oral price top-ups to favoured buyers are unrecordable. Ask how finance would know if the settlement price changed mid-season.", weight: 2 },
      { id: "fsh-08", domain: "monitoring", q: "Is catch-per-unit-effort and feed-conversion-ratio monitored against benchmarks, with deviations investigated?", hint: "In farms, feed conversion is the master ratio — drifting FCR hides theft of feed or fish.", weight: 2 },
      { id: "fsh-09", domain: "it-cyber", q: "Are vessel monitoring and traceability systems (VMS, e-logbooks) integrated or at least reconciled to the accounting system monthly?", hint: "Two systems never reconciled = completeness gap. Ask who does the reconciliation and where the differences land.", weight: 2 },
      { id: "fsh-10", domain: "control-environment", q: "Is there chain-of-custody certification (MSC or equivalent) maintained with its own internal audit trail?", hint: "Certification loss collapses premium pricing. Ask for the last chain-of-custody audit result.", weight: 1 },
      { id: "fsh-11", domain: "control-activities", q: "Are ice, packaging and cold-chain costs at landing sites controlled through issue records and waste reviews?", hint: "Cash purchases of ice at the dock without receipts are a leakage point and an expense-understatement tell.", weight: 1 },
    ],
  },
  {
    id: "forestry",
    sector: "primary",
    name: "Forestry & Timber",
    icon: "trees",
    blurb: "Timber harvesting, plantations and sawmills — standing-timber assets, harvesting contractors and log sales.",
    risks: ["Standing-timber valuation (IAS 41)", "Theft of logs and under-declared harvest", "Reforestation obligations", "Chain-of-custody certification"],
    procedures: [
      "Inspect harvesting permits and reconcile permitted volume to harvested volume in the timber ledger.",
      "Observe a log-yard scaling (measurement) operation and trace scale tickets to sales invoices.",
      "Reperform the standing-timber fair-value roll-forward for one plantation block including growth, harvest and loss lines.",
      "Test contractor harvesting statements against independently scaled volumes (third-party scaler).",
      "Inspect the reforestation obligation computation and the underlying planting contracts.",
      "Inquire how logs move from forest to mill: what physical or documentary control gates each transfer?",
    ],
    questions: [
      { id: "frs-01", domain: "control-activities", q: "Is every harvested log measured by an independent scaler (or calibrated weighbridge) and matched to a scale ticket that feeds both sales and inventory?", hint: "Self-scaling by the harvesting contractor invites under-declaration. Ask who scales and whether the scaler is independent of the cutter.", weight: 3, critical: true },
      { id: "frs-02", domain: "control-activities", q: "Are harvesting volumes reconciled to the permit/allowable-cut, with breaches escalated and documented?", hint: "Over-cutting is both a regulatory breach and a revenue-completeness risk. Ask for the last reconciliation and any variance letters to the regulator.", weight: 3 },
      { id: "frs-03", domain: "control-activities", q: "Is standing timber carried at fair value with a documented growth model, harvest plan and discount assumptions reviewed by someone with forestry expertise?", hint: "The valuation is a model on a model. Probe who challenges the growth curves and the discount rate at each reporting date.", weight: 3 },
      { id: "frs-04", domain: "risk-assessment", q: "Are fire, pest and storm risks assessed per block with mitigation (firebreaks, insurance) and loss events measured and reported?", hint: "Ask for the last loss event and how the standing-timber number was adjusted (or not).", weight: 2 },
      { id: "frs-05", domain: "control-activities", q: "Are harvesting, hauling and road contractors engaged under signed rate contracts with volume reconciliation and independent measurement?", hint: "Contractor self-reported truckloads are the leak. Weighbridge or gate-log reconciliation is the compensator.", weight: 2 },
      { id: "frs-06", domain: "info-communication", q: "Does the log traceability / chain-of-custody system (harvest block → mill gate) reconcile monthly to the accounting records?", hint: "Certified-sustainable volumes sold above non-certified price must be provable. Ask who reconciles the two ledgers.", weight: 2 },
      { id: "frs-07", domain: "control-activities", q: "Is the reforestation obligation (replanting, silviculture) accrued from the harvest plan with costs tracked against it?", hint: "Under-provisioning replanting costs inflates profit. Ask for the obligation computation and the last actual spend.", weight: 2 },
      { id: "frs-08", domain: "control-activities", q: "Are log sales priced from a published index or price list, with discounts to buyers approved and recorded?", hint: "Off-index discounts to related buyers move revenue to friends. Ask who can discount and by how much.", weight: 2 },
      { id: "frs-09", domain: "monitoring", q: "Are sawmill recovery rates (log-in vs lumber-out) tracked and benchmarked, with unexplained falls investigated?", hint: "Falling recovery with steady input hides chip-theft or unrecorded lumber sales.", weight: 2 },
      { id: "frs-10", domain: "control-environment", q: "Are remote harvesting crews subject to rotation, surprise visits and gps/telemetry on haul trucks?", hint: "Isolated operations with the same crew and no spot checks are the classic theft setup.", weight: 2 },
      { id: "frs-11", domain: "it-cyber", q: "Is the timber/GIS inventory system access-controlled so harvest blocks and volumes cannot be edited after period-end close?", hint: "Post-close edits to harvested volumes rewrite history. Ask for the change log and who can see it.", weight: 2 },
    ],
  },
  {
    id: "mining",
    sector: "primary",
    name: "Mining & Metals",
    icon: "mountain",
    blurb: "Open-pit and underground mines, concentrators and smelters — from industrial minerals to precious metals.",
    risks: ["Ore reserve and resource estimates", "Production reporting (reconciliation to plant)", "Royalty and government take", "Tailings and closure obligations"],
    procedures: [
      "Inspect the mine plan and reconcile surveyed extraction to mill feed and sales volumes (metal accounting).",
      "Reperform the closure and rehabilitation provision using the mine plan areas and reclamation quotes.",
      "Observe a gold-bar/precious-metal pour or shipment and trace the bar list to the refinery settlement.",
      "Inspect royalty filings and reconcile production declarations to sales and inventory movements.",
      "Test the metal-accounting ledger (weighed, sampled, assayed) to the financial ledger monthly reconciliation.",
      "Inquire of the competent person: how are reserve estimate changes governed and who approves disclosure?",
    ],
    questions: [
      { id: "min-01", domain: "control-activities", q: "Is production measured through a metal-accounting chain — weight, moisture, assay — where each link is independently performed and signed?", hint: "The value is grade x tonnage x price; whoever controls sampling controls profit. Ask who takes and assays samples and whether umpire (duplicate) assays happen.", weight: 3, critical: true },
      { id: "min-02", domain: "control-activities", q: "Is there a monthly reconciliation of ore mined, milled, sold and stockpiled — with variances investigated and evidenced?", hint: "Ask for the last metal-balancing pack. Unexplained mill-feed losses usually mean measurement tampering or theft of high-grade ore.", weight: 3, critical: true },
      { id: "min-03", domain: "control-activities", q: "Are royalties, production levies and government share computed by a named owner from verified production data and paid on time?", hint: "Mis-declared production understates royalties — a compliance and fraud exposure. Trace one royalty computation end-to-end.", weight: 3 },
      { id: "min-04", domain: "risk-assessment", q: "Is the mineral reserve/resource statement prepared or reviewed by a competent person, with governance sign-off before any public disclosure?", hint: "Reserves are the company's bank account. Ask who signs the statement and whether the board sees changes before investors do.", weight: 3 },
      { id: "min-05", domain: "risk-assessment", q: "Is the closure and rehabilitation provision updated at each period from an engineering plan and independent cost estimate?", hint: "Closure provisions are big, judgmental and under-pressure. Probe the discount rate, the cost base and who reviews it.", weight: 2 },
      { id: "min-06", domain: "control-activities", q: "Are precious-metal doré or refined shipments under dual custody, sealed containers and insured transport, with the refiner's settlement reconciled to the shipment assay?", hint: "High-value, portable, anonymous — the perfect theft object. Ask to trace one pour from furnace to cash.", weight: 3 },
      { id: "min-07", domain: "control-activities", q: "Are contractor mining volumes (pay-per-tonne) verified against the mine survey or truck counts before payment?", hint: "Contractors who self-report truckloads get paid twice for one load. The survey reconciliation is the control.", weight: 2 },
      { id: "min-08", domain: "monitoring", q: "Are tailings dam, safety and environmental inspections performed on schedule with findings tracked to closure?", hint: "A tailings failure is existential — and the related provision/disclosure is an audit issue. Ask for the inspection calendar and open findings.", weight: 2 },
      { id: "min-09", domain: "info-communication", q: "Does the technical (mine/mill) reporting system reconcile to the financial ledger monthly, with owners for each side?", hint: "Two universes — tonnes in the mine system, money in the ERP — must meet monthly. Ask who signs the bridge.", weight: 2 },
      { id: "min-10", domain: "control-activities", q: "Is fuel, explosives and cyanide/chemical usage under license, custody and usage logs reconciled to blast plans and plant throughput?", hint: "Explosives and process chemicals are regulated for good reason; diversions are both theft and safety events.", weight: 2 },
      { id: "min-11", domain: "control-environment", q: "In artisanal-adjacent operations, are there controls over gold/ore purchases from third-party small miners (identity, source, cash limits)?", hint: "Cash buying of artisanal ore carries fraud, smuggling and AML exposure. Ask for the buying procedure and its documentation.", weight: 2 },
      { id: "min-12", domain: "monitoring", q: "Is unit-cost-per-tonne and grade reconciliation monitored against plan, with geology/finance joint review?", hint: "Grade drift versus plan that nobody challenges hides either bad reserves or ore theft.", weight: 2 },
    ],
  },
  {
    id: "oil-gas",
    sector: "primary",
    name: "Oil & Gas (Upstream)",
    icon: "fuel",
    blurb: "Exploration and production — onshore and offshore fields, joint ventures, and the fiscals (PSAs, concessions) around them.",
    risks: ["Reserve and production reporting", "Joint-venture cost recovery", "Custody transfer and measurement", "Decommissioning provisions"],
    procedures: [
      "Inspect the custody-transfer meter calibration certificates and witness/report the periodic proving.",
      "Reperform one joint-operating-account (JOA) billing: cost recovery categories, ownership shares, non-recoverable items.",
      "Reconcile field production to liftings/sales and inventory (tank, pipeline, ullage) for a sample month.",
      "Inspect the decommissioning provision assumptions (cost estimate, discount rate, timing) and their governance review.",
      "Test the reserve-reporting governance: competent person sign-off, audit committee review of changes.",
      "Inquire who can approve non-routine procurement in the field above thresholds and how JV partners audit it.",
    ],
    questions: [
      { id: "oil-01", domain: "control-activities", q: "Is every custody transfer (wellhead to pipeline to terminal) measured by calibrated meters with independent proving/verification and witnessed tallies?", hint: "Custody transfer is where money changes hands on volume. Ask for the last meter-proving certificate and who witnessed it.", weight: 3, critical: true },
      { id: "oil-02", domain: "control-activities", q: "Are joint-operating-account billings to partners prepared from approved work-programme costs, with non-recoverable items correctly excluded and audited by partners?", hint: "Cost recovery disputes with JV partners and the state are constant. Ask for the last partner audit and open exceptions.", weight: 3 },
      { id: "oil-03", domain: "control-activities", q: "Is production reconciled monthly from well tests through gathering systems to sales and storage, with losses (flare, shrinkage, ullage) measured and benchmarked?", hint: "Flaring and shrinkage are the hiding places. Ask for the hydrocarbon-accounting reconciliation and the loss thresholds.", weight: 3, critical: true },
      { id: "oil-04", domain: "risk-assessment", q: "Is the decommissioning/abandonment provision updated at each reporting date from costed plans, with discount-rate and timing governance?", hint: "Massive judgement, decades of horizon. Probe who reviews the cost base and how sensitive the provision is.", weight: 2 },
      { id: "oil-05", domain: "control-activities", q: "Are field procurement and service-company contracts subject to competitive tender and technical approval, with call-off orders reconciled to contracts?", hint: "Rig-service spend is where field managers can direct work. Ask for the last tender file and a call-off audit.", weight: 2 },
      { id: "oil-06", domain: "info-communication", q: "Does the production-reporting system (hydrocarbon accounting) reconcile to the financial ERP monthly, with named owners on both sides?", hint: "Barrels vs money: the two systems must meet. Ask for the reconciliation evidence and the escalation path for breaks.", weight: 2 },
      { id: "oil-07", domain: "control-environment", q: "Are reserve estimates and any public reporting governed by a competent-person regime with board audit-committee review of changes?", hint: "Reserve restatements destroy companies. Ask who signs and what the committee minutes show for the last review.", weight: 2 },
      { id: "oil-08", domain: "control-activities", q: "Are crude sales and liftings priced from verified index/platts references, with pricing Notices reconciled to invoices?", hint: "One basis point on a cargo is real money. Ask who checks the price-recap against the contract formula.", weight: 2 },
      { id: "oil-09", domain: "risk-assessment", q: "Are HSE incidents (spills, gas releases) logged, investigated, and their financial effects (provisions, fines, remediation) captured in the ledger?", hint: "Ask for the incident register and trace one incident's cost into the accounts.", weight: 2 },
      { id: "oil-10", domain: "monitoring", q: "Is operating cost per barrel and production uptime tracked against plan with variance review at management level?", hint: "Cost creep is the E&P disease; the monitoring that catches it is the control.", weight: 1 },
      { id: "oil-11", domain: "it-cyber", q: "Are OT/ICS systems (SCADA, metering) segregated from IT networks, with access control and change management on measurement configurations?", hint: "A tampered flow computer is the perfect theft. Ask what controls meter configuration changes and who can see the audit trail.", weight: 3 },
    ],
  },
]
