import type { TocIndustry } from "./types"

/** v37 — Public Sector & Non-Profit: budget discipline, donor and public
 *  money stewardship, procurement probity, and fund accounting. Common
 *  audit textures: budget-vs-actual authorization, grants with conditions,
 *  procurement thresholds, beneficiary databases, and transparency
 *  reporting. */
export const PUBLIC_INDUSTRIES: TocIndustry[] = [
  {
    id: "government",
    sector: "public",
    name: "Government & Public Sector",
    icon: "landmark",
    blurb: "Ministries, agencies, municipalities and state-owned enterprises executing public budgets.",
    risks: ["Budget appropriation discipline", "Public procurement probity", "Grants and transfer conditions", "Assets and inventory stewardship"],
    procedures: [
      "Test commitment control: sample purchase orders against budget appropriation and the release authority for virements.",
      "Inspect the procurement cycle above thresholds: tender documentation, bid evaluation minutes, and award approvals.",
      "Test grant/subsidy disbursements to beneficiary eligibility files and the payment authorization chain.",
      "Inspect the public asset register (vehicles, land, buildings) and the custodian assignments, with the last verification.",
      "Test payroll-to-headcount reconciliation (HR database vs payroll vs staff IDs).",
      "Inquire of internal audit: what is the plan coverage and the last report's follow-up status?",
    ],
    questions: [
      { id: "gov-01", domain: "control-activities", q: "Is spending committed only against approved budget appropriations, with virements (budget transfers) authorized at the right level before commitment?", hint: "Ask for the commitment-control system's enforcement evidence (or the manual equivalent) and the last virement approvals.", weight: 3, critical: true },
      { id: "gov-02", domain: "control-activities", q: "Does public procurement follow the legal framework — thresholds, competitive tender, bid evaluation committees, and documented award rationale — with exceptions reported?", hint: "Ask for a sample tender file above the threshold and the single-source exceptions log.", weight: 3, critical: true },
      { id: "gov-03", domain: "control-activities", q: "Are grants, subsidies and social transfers paid against verified eligibility (means tests, beneficiary lists), with duplicate/beneficiary-database checks before disbursement?", hint: "Ghost beneficiaries are the sector's leakage. Ask for the last database de-duplication and eligibility re-validation.", weight: 3, critical: true },
      { id: "gov-04", domain: "control-activities", q: "Is payroll reconciled to an independent HR headcount (with identity verification) periodically, and are appointments supported by approved establishment lists?", hint: "Ask for the last payroll-to-headcount reconciliation and its variance sign-off.", weight: 3 },
      { id: "gov-05", domain: "control-activities", q: "Is the state asset register complete and verified cyclically, with disposals (auctions, transfers, write-offs) approved per public-asset rules?", hint: "Ask for the verification cycle plan and the last disposal approval file.", weight: 2 },
      { id: "gov-06", domain: "monitoring", q: "Is budget execution monitored and reported (monthly/quarterly) to the legislature/board with variance explanations and corrective actions?", hint: "Ask for the last budget-execution report and one variance action.", weight: 2 },
      { id: "gov-07", domain: "risk-assessment", q: "Is there an institutionalized internal audit function with a risk-based plan, reporting to the governing body, and findings followed to closure?", hint: "Ask for the internal audit charter, the annual plan, and the open findings ageing.", weight: 3 },
      { id: "gov-08", domain: "info-communication", q: "Are revenue streams (fees, fines, leases of public property) captured centrally and reconciled to collections (cashier systems, e-payment) daily?", hint: "Collections leakage is most likely at the front line (cash desks, market fees). Ask for the daily collection reconciliation.", weight: 3 },
      { id: "gov-09", domain: "control-environment", q: "Are conflict-of-interest and asset declarations required for officials with procurement/payment authority, and are they monitored?", hint: "Ask for the declaration register and the consequence process.", weight: 2 },
      { id: "gov-10", domain: "control-activities", q: "Are advances and imprest accounts settled within required timelines, with standing advances renewed and accounted for?", hint: "Permanent floating advances become slush funds. Ask for the advance ageing.", weight: 2 },
      { id: "gov-11", domain: "control-activities", q: "Are donor/loan-funded programmes' covenants (procurement rules, reporting, audits) tracked and evidenced to the funder's satisfaction?", hint: "Funder audits drive repayment triggers. Ask for the covenants register and the last funder audit.", weight: 2 },
    ],
  },
  {
    id: "nonprofits",
    sector: "public",
    name: "NGOs & Non-Profits",
    icon: "heart-handshake",
    blurb: "Charities, foundations and development NGOs — donor-restricted funds and volunteer ecosystems.",
    risks: ["Donor restriction compliance", "Beneficiary targeting integrity", "Field cash and procurement", "Recognition of contributions (gifts in kind, volunteers)"],
    procedures: [
      "Test a donor-restricted fund: expenses charged against the right fund/purpose, and the interim/final reporting pack to the ledger.",
      "Inspect beneficiary selection: targeting criteria, lists, and verification (spot visits) for a sample programme.",
      "Test field procurement and petty cash for a sample of project sites: thresholds, documentation and the three-quote rule.",
      "Inspect gifts-in-kind valuation policy and its application (food, medicine, land).",
      "Test the fundraising revenue recognition: pledges, conditional/unconditional promises, and the reconciliation to the CRM.",
      "Inquire of finance: how are allocations of shared costs to grants computed, and are they approved by donors where required?",
    ],
    questions: [
      { id: "ngo-01", domain: "control-activities", q: "Are donor-restricted funds tracked by fund/donor with expenses charged only to permitted purposes, and are donor reports reconciled to the ledger before submission?", hint: "Ask for the fund accounting structure and the last donor report's reconciliation to the GL.", weight: 3, critical: true },
      { id: "ngo-02", domain: "control-activities", q: "Is beneficiary selection documented against criteria (targeting, lists, committee decisions) with independent verification or spot checks?", hint: "Inflated beneficiary lists are the sector's fraud classic. Ask for the verification evidence — and who does it besides the list-maker.", weight: 3, critical: true },
      { id: "ngo-03", domain: "control-activities", q: "Are field cash and procurement controlled — thresholds, quotes, authorized approvers, original documentation — with periodic field visits and reconciliations?", hint: "Ask for the last field-visit financial review and the issues raised.", weight: 3 },
      { id: "ngo-04", domain: "control-activities", q: "Are conditional contributions recognized only when conditions are met, with unconditional promises receivable assessed for collectability?", hint: "Ask for the revenue-recognition policy for grants (conditional vs restricted vs unconditional).", weight: 3 },
      { id: "ngo-05", domain: "control-activities", q: "Are gifts-in-kind valued per policy (fair value at receipt) and recognized/used in the right programmes, with quality controls (expiry, suitability)?", hint: "GIK valuation is judgement plus logistics. Ask for the valuation method and the last large donation's accounting.", weight: 2 },
      { id: "ngo-06", domain: "info-communication", q: "Is fundraising data (donor CRM) reconciled to the finance ledger periodically, with donation-channel fees and refunds handled correctly?", hint: "Ask for the CRM-to-GL reconciliation and its frequency.", weight: 2 },
      { id: "ngo-07", domain: "control-environment", q: "Is there a board with genuine oversight (meeting minutes, finance committee review, conflict policy) rather than a dominant founder with unchallenged authority?", hint: "Founder dominance is the sector's control-environment risk. Ask how the board challenges spending decisions.", weight: 3, critical: true },
      { id: "ngo-08", domain: "risk-assessment", q: "Is safeguarding (protection of beneficiaries, especially children) embedded — policies, training, reporting channels, case handling?", hint: "Safeguarding failures halt programmes and funding. Ask for the policy, training records, and the reporting channel.", weight: 3 },
      { id: "ngo-09", domain: "monitoring", q: "Are programme-versus-budget reports (burn rate, outputs vs plan) reviewed monthly with management action?", hint: "Slow burn discovered at year-end is unspent grants that must be returned. Ask for the burn-rate report.", weight: 2 },
      { id: "ngo-10", domain: "control-activities", q: "Are staff and volunteer reimbursements (travel, per diem) governed by policy with documentation and approval limits?", hint: "Ask for the per-diem policy and a sample claim's evidence.", weight: 1 },
    ],
  },
  {
    id: "awqaf",
    sector: "public",
    name: "Awqaf, Mosques & Religious Bodies",
    icon: "moon",
    blurb: "Endowments (awqaf), religious institutions and faith-based charities — perpetual-purpose assets and donations.",
    risks: ["Endowment (waqf) asset stewardship and purpose preservation", "Donation channels (boxes, online) completeness", "Zakat calculation and distribution compliance", "Related-party leases of endowed property"],
    procedures: [
      "Inspect the waqf asset register: properties, purposes, terms, and the lease/supervision arrangements against the waqf deed.",
      "Test donation-box collection controls: two-person counting, seals, and the reconciliation to bankings.",
      "Reperform zakat distribution: eligibility files (the eight categories), disbursement evidence, and the annual fund statement.",
      "Inspect leases of endowed properties: approvals per governance rules, market-rate benchmarking, and collection reconciliations.",
      "Test online donation platforms' settlement reconciliation to the ledger and the donor-receipt integrity.",
      "Inquire of the board/nazir: how are investment income and spending from endowment returns separated from principal?",
    ],
    questions: [
      { id: "awk-01", domain: "control-activities", q: "Is every waqf asset registered (deed terms, purpose, boundaries, custodian) with expenditures respecting the donor's purpose and the deed's conditions?", hint: "The waqf deed is the constitution of the asset. Ask for the register and how spending purposes are checked against deeds.", weight: 3, critical: true },
      { id: "awk-02", domain: "control-activities", q: "Are donation collections (boxes, envelopes, online) counted by two unrelated persons, recorded on signed sheets, and reconciled to bank deposits promptly?", hint: "Anonymous cash is the highest-risk revenue. Ask for the count sheets and the two-person rule evidence.", weight: 3, critical: true },
      { id: "awk-03", domain: "control-activities", q: "Are leases of endowment properties approved per governance rules, benchmarked to market rates, and are collections reconciled monthly with arrears followed up?", hint: "Below-market leases of endowed property to connected parties is the sector's leakage channel. Ask for the lease schedule and benchmarking.", weight: 3 },
      { id: "awk-04", domain: "control-activities", q: "Is zakat collected and distributed per the required categories with eligibility verification, documentation, and an annual fund statement?", hint: "Ask for the distribution list governance — who verifies eligibility and how duplicate recipients are controlled.", weight: 3, critical: true },
      { id: "awk-05", domain: "control-activities", q: "Is endowment principal segregated from income/investment returns, with accounting that preserves principal and reports returns usage?", hint: "Principal must not be spent as income. Ask for the fund structure separating them.", weight: 3 },
      { id: "awk-06", domain: "control-environment", q: "Is there a governing board (or nazir oversight) with documented decisions, conflict-of-interest rules for property and vendor dealings, and independence in financial matters?", hint: "One-person control over property and vendors is the risk pattern. Ask for the decision-minutes trail.", weight: 3 },
      { id: "awk-07", domain: "risk-assessment", q: "Are safeguarding and financial policies proportionate to size (cash handling, procurement thresholds, whistleblowing) adopted and trained?", hint: "Ask for the policy pack and the last training session's attendance.", weight: 2 },
      { id: "awk-08", domain: "info-communication", q: "Are online fundraising and payment platforms reconciled monthly to the ledger, and are donor-receipt records complete and accurate?", hint: "Ask for the platform settlement reconciliation.", weight: 2 },
      { id: "awk-09", domain: "monitoring", q: "Are annual reports (activities, funds received and applied) prepared and shared with the community/regulator as required?", hint: "Transparency is both a duty and a control. Ask for the last annual report and its fund statement.", weight: 2 },
      { id: "awk-10", domain: "control-activities", q: "Are maintenance and improvement spends on endowed properties budgeted and approved, preserving the asset's perpetual productivity?", hint: "Deferred maintenance quietly destroys endowment value. Ask for the maintenance plan and budget.", weight: 2 },
    ],
  },
]
