import type { TocIndustry } from "./types"

/** v37 — Construction & Real Estate: long-dated contracts, percentage of
 *  completion, off-plan sales and property portfolios. Common audit
 *  textures: cost-to-cost estimates (IFRS 15), retentions, subcontractor
 *  accruals, escrowed off-plan collections, and capitalized borrowing. */
export const PROPERTY_INDUSTRIES: TocIndustry[] = [
  {
    id: "construction",
    sector: "property",
    name: "Construction & Contracting",
    icon: "hard-hat",
    blurb: "Building and infrastructure contractors — main contractors, specialist subcontractors and EPC firms.",
    risks: ["Percentage-of-completion estimates", "Subcontractor liabilities and certification", "Variation and claim recognition", "Retention and defect liabilities"],
    procedures: [
      "Reperform cost-to-cost POC for a sample of contracts: forecast total cost support, cost-to-date completeness, and loss-making-job scan.",
      "Inspect subcontractor certified-vs-paid reconciliations and the accrual for uncertified work.",
      "Test variation/claim files: entitlement evidence, client instruction, and the revenue gate (probable up-side) versus cost recognition.",
      "Observe a site stock count (materials on site) and test the cut-off of deliveries and site transfers.",
      "Inspect the contract ledger ageing and cash-flow projections for going-concern evidence.",
      "Inquire of project managers: who can revise a forecast total cost, and who challenges it?",
    ],
    questions: [
      { id: "con-01", domain: "control-activities", q: "Is contract revenue recognized on a documented percentage-of-completion basis, with forecast total costs prepared by the project engineer and independently reviewed by finance before each period close?", hint: "Whoever owns the forecast owns the profit. Ask who reviews the POC pack and what evidence of challenge exists (review notes, revisions log).", weight: 3, critical: true },
      { id: "con-02", domain: "control-activities", q: "Are loss-making contracts identified and provided for at the first sign (IAS 37 onerous contract test), not when the job ends?", hint: "Ask for the current job list with forecast margins — any negative-margin job must already carry a provision.", weight: 3, critical: true },
      { id: "con-03", domain: "control-activities", q: "Are subcontractor liabilities complete — certified amounts, retention, back-charges, and accruals for work done but uncertified — reconciled per subcontractor monthly?", hint: "The unrecorded sub-contractor payable is the classic construction misstatement. Ask for the sub-ledger reconciliation.", weight: 3 },
      { id: "con-04", domain: "control-activities", q: "Are variations and claims recognized only when entitlement is documented (signed instruction) and outcome probable — with a claims register showing status and evidence?", hint: "Ask to see the claims register: which claims are billed, which are in revenue, and why.", weight: 3 },
      { id: "con-05", domain: "control-activities", q: "Is materials-on-site inventory controlled — custody, cut-off between sites, and reconciliation to job cost reports?", hint: "Materials moved between jobs distort both jobs' POC. Ask how inter-site transfers are documented.", weight: 2 },
      { id: "con-06", domain: "control-activities", q: "Are mobilization advances, performance bonds and guarantees tracked in a register and their release/refund monitored?", hint: "Bank guarantees left forgotten tie up facilities; advances unamortized misstate assets. Ask for the guarantees register.", weight: 2 },
      { id: "con-07", domain: "control-activities", q: "Is payroll (site labour, daily workers) computed from approved timesheets/attendance verified by site engineers, with headcount reconciliation between sites and payroll?", hint: "Daily-hire labour is easy to inflate. Ask for the site attendance sheet to payroll reconciliation.", weight: 2 },
      { id: "con-08", domain: "risk-assessment", q: "Is contract tendering controlled — bid approval matrix, margin floors, and bond/cash-flow exposure assessed before bidding?", hint: "Underpriced wins become next year's loss provisions. Ask for the bid-approval evidence.", weight: 2 },
      { id: "con-09", domain: "monitoring", q: "Is a project profitability report (budget vs forecast vs actual) reviewed monthly by management, with action on deteriorating jobs?", hint: "Ask for the last month's review pack and one escalated job's minutes.", weight: 2 },
      { id: "con-10", domain: "info-communication", q: "Is the contract-cost ledger reconciled to the general ledger monthly, with WIP ageing and unbillable amounts identified?", hint: "Costs parked in WIP that will never be billed are phantom assets. Ask for the WIP ageing review.", weight: 3 },
      { id: "con-11", domain: "control-activities", q: "Are retentions receivable tracked per contract (release conditions, due dates) and provisioned for collectability like other receivables?", hint: "Retentions on dead contracts are often worthless. Ask for the retention ageing and allowance treatment.", weight: 2 },
    ],
  },
  {
    id: "real-estate-dev",
    sector: "property",
    name: "Real Estate Development",
    icon: "building",
    blurb: "Residential and commercial developers — off-plan and ready sales, land banks and project finance.",
    risks: ["Off-plan revenue recognition (IFRS 15)", "Escrow and trust-account compliance", "Land bank valuation", "Cost capitalization and borrowing costs"],
    procedures: [
      "Inspect the off-plan revenue model: unit deliveries x percentage, contract terms (instalments, defaults), and reconcile to the revenue calendar.",
      "Test escrow/trust accounts: statements, withdrawal approvals, project spend eligibility, and reconciliation to project cash flows.",
      "Reperform land-bank carrying value: cost registers, impairment indicators (stalled approvals, market prices per sqm), and board review evidence.",
      "Sample construction-cost capitalization: invoices to project, borrowing-cost allocation (IAS 23), and selling-costs expensed.",
      "Test the deferred-revenue and receivable ageing against contract payment plans, including default/forfeiture clauses.",
      "Inquire of sales: how are discounts, payment-plan restructurings and unit swaps approved?",
    ],
    questions: [
      { id: "dev-01", domain: "control-activities", q: "Is off-plan revenue recognized under a documented policy (delivery of unit / percentage of construction per contract) applied consistently, with the revenue computation reconciled to the construction progress reports monthly?", hint: "The revenue trigger is the entire audit. Ask for the policy, the progress reports (engineer-signed), and the reconciliation to the ledger.", weight: 3, critical: true },
      { id: "dev-02", domain: "control-activities", q: "Where law requires off-plan collections into escrow/trust accounts, are they maintained per project, withdrawn only for project costs with approvals, and reconciled monthly to the project spend?", hint: "Escrow breach is both regulatory and going-concern territory. Ask for the escrow statements and the withdrawal approval file.", weight: 3, critical: true },
      { id: "dev-03", domain: "control-activities", q: "Is the land bank carried at cost with impairment reviewed (planning status, market comparables) — and is any revaluation policy applied consistently with valuer evidence?", hint: "Old land at cost that no longer has a viable project is an impairment waiting. Ask for the impairment review and the planning status table.", weight: 3 },
      { id: "dev-04", domain: "control-activities", q: "Are project costs capitalized per project (direct costs + allocated borrowing per IAS 23), with selling, admin and idle-time costs expensed and the policy applied consistently?", hint: "Corporate overhead creeping into project cost inflates inventory and profit. Ask for the capitalization policy memo and the allocation basis.", weight: 3 },
      { id: "dev-05", domain: "control-activities", q: "Is the sales register complete and reconciled to contracts, broker reports, escrow receipts and the revenue ledger — with unit statuses (available, reserved, contracted, delivered) tracked?", hint: "The unit status board must match finance. Ask for the reconciliation between the sales CRM and the deferred revenue ledger.", weight: 2 },
      { id: "dev-06", domain: "control-activities", q: "Are customer defaults and instalment restructurings monitored — late-payment charges billed, forfeiture applied per contract, and credit-loss allowances assessed?", hint: "Ask for the receivable ageing against payment plans and the ECL policy for instalment receivables.", weight: 2 },
      { id: "dev-07", domain: "control-activities", q: "Are broker commissions and channel incentives approved per contract, accrued with sales, and reconciled to broker statements?", hint: "Commissions paid on deals that later cancel need clawbacks — ask for the clawback process.", weight: 2 },
      { id: "dev-08", domain: "risk-assessment", q: "Is project-level viability monitored (updated cost-to-sell, price realization, absorption rates) with impairment triggers reviewed at each period end?", hint: "Falling market prices make yesterday's project marginal. Ask for the viability update and its evidence.", weight: 2 },
      { id: "dev-09", domain: "info-communication", q: "Are construction progress certifications from the independent engineer (or consultant) obtained monthly and used for both revenue and cost cut-off?", hint: "Self-certified progress is an estimate without brakes. Ask who signs the progress certificates.", weight: 2 },
      { id: "dev-10", domain: "monitoring", q: "Is a per-project dashboard (units sold, collections, cost-to-complete, breakeven) reviewed by management monthly?", hint: "Ask for the dashboard and one project's variance story.", weight: 2 },
      { id: "dev-11", domain: "control-activities", q: "Are related-party sales (to owners, directors, affiliates) identified, approved by the board, and disclosed with arm's-length evidence?", hint: "Related-party unit swaps and discounts are the sector's disclosure landmine. Ask how such deals are flagged to finance.", weight: 3 },
    ],
  },
  {
    id: "property-mgmt",
    sector: "property",
    name: "Property Management & REITs",
    icon: "key",
    blurb: "Leasing, facility management and REIT administration — rent rolls, CAM charges and investor reporting.",
    risks: ["Rent-roll completeness and billing", "CAM/operating-cost recovery computations", "Tenant deposits and liabilities", "Valuation of investment property (IFRS 13/40)"],
    procedures: [
      "Test rent-roll completeness: physically inspect a sample of lettable units against the rent roll and billing.",
      "Reperform the CAM recovery computation for one building: actual costs, pools, gross-up rules, and the reconciliation to charges billed.",
      "Inspect tenant deposit ledgers and the segregation between own funds and tenants' trust monies.",
      "Test the investment-property fair-value movement: valuer credentials, key inputs, management's challenge of the valuer's assumptions.",
      "Sample lease modifications through the IFRS 16/investment-property accounting gates.",
      "Inquire of property managers: how are vacancy, incentives (rent-free periods) and fit-out contributions captured?",
    ],
    questions: [
      { id: "pmg-01", domain: "control-activities", q: "Is the rent roll (units, tenants, rates, escalations, expiry) reconciled monthly to invoicing and the ledger, with voids and concessions visible?", hint: "Occupied units missing from the rent roll = stolen rent. Ask for the last reconciliation and the physical vacancy report.", weight: 3, critical: true },
      { id: "pmg-02", domain: "control-activities", q: "Are common-area maintenance and service-charge recoveries computed from actual costs per the lease formulas, reconciled to expenditure, and shortfalls explained?", hint: "CAM formulas (pro-rata, gross-up, caps) are per-lease law. Ask for the CAM model and the leakage report.", weight: 3 },
      { id: "pmg-03", domain: "control-activities", q: "Are tenant deposits and prepaid rents held in separate/trust accounts with interest treatment per contract and monthly statements to tenants?", hint: "Deposits mingled with operating cash are a fiduciary breach. Ask for the trust account reconciliations.", weight: 2 },
      { id: "pmg-04", domain: "control-activities", q: "Is investment property (or the REIT's portfolio) revalued by an independent, professionally-qualified valuer with the key assumptions (cap rates, market rents, vacancy) documented and challenged by management?", hint: "Ask for the valuation report, the valuer's independence statement, and management's challenge memo.", weight: 3, critical: true },
      { id: "pmg-05", domain: "control-activities", q: "Are lease incentives (rent-free, fit-out contributions, caps) identified and straight-lined per IFRS 16 / IFRS 15 consistently, with a lease-incentive register?", hint: "Incentives change effective rent materially. Ask who extracts them from new leases.", weight: 2 },
      { id: "pmg-06", domain: "control-activities", q: "Is utilities re-billing to tenants (sub-metering) reconciled to utility invoices, with losses on master-metered common areas charged correctly?", hint: "Unbilled utility consumption is margin bleed. Ask for the sub-meter reconciliation.", weight: 2 },
      { id: "pmg-07", domain: "info-communication", q: "For REITs/funds: are investor reports (NAV, distributions) prepared from the same ledger that the auditor audits, with distribution calculations independently checked?", hint: "Two NAVs (investor-facing vs statutory) is a red flag. Ask who reconciles them.", weight: 3 },
      { id: "pmg-08", domain: "control-activities", q: "Are property-management contracts and fee schedules (of external PMs) reconciled to fee billings, with performance obligations verified?", hint: "Fees double-charged across entities are common in PM groups. Ask for the fee reconciliation.", weight: 2 },
      { id: "pmg-09", domain: "monitoring", q: "Are occupancy, collections (DSO), arrears ageing, and opex per sqm tracked and benchmarked across the portfolio monthly?", hint: "Arrears creeping while occupancy is flat = collections control failure. Ask for the arrears report and the escalation ladder (reminder → legal).", weight: 2 },
      { id: "pmg-10", domain: "risk-assessment", q: "Is capital expenditure on buildings (roofs, HVAC, elevators) planned, approved per thresholds, and correctly split between repairs and capital?", hint: "The repair-vs-capital line moves both profit and property value. Ask for the policy and borderline cases.", weight: 2 },
    ],
  },
]
