import type { TocIndustry } from "./types"

/** v37 — Financial Services: regulated balance sheets where the product is
 *  money itself. Common audit textures: expected credit losses (IFRS 9),
 *  regulatory reporting (capital, liquidity, reserves), AML/KYC and
 *  sanctions, fair valuation of instruments, and fiduciary segregation of
 *  client assets. */
export const FINANCE_INDUSTRIES: TocIndustry[] = [
  {
    id: "banking",
    sector: "finance",
    name: "Banking & Retail Lending",
    icon: "landmark",
    blurb: "Deposit-taking banks, mortgage and consumer lenders under central-bank regulation.",
    risks: ["IFRS 9 ECL model governance", "Regulatory capital and reserve compliance", "AML/CFTR and sanctions", "Segregation of duties in the core banking system"],
    procedures: [
      "Inspect the ECL model governance: model documentation, validation (independent), back-testing, and management overlay approvals.",
      "Reperform regulatory returns for one month (capital adequacy, liquidity ratios, reserve requirement) to the GL.",
      "Test the loan-file flow: disbursement authority, collateral perfection, and covenant monitoring for a sample of corporate loans.",
      "Inspect AML transaction-monitoring rule coverage and the alert-handling SLA with sample case files.",
      "Observe teller/cash operations: dual control, vault limits, and the suspense-account clearance discipline.",
      "Inquire of treasury: who confirms deals, and how is the front-back office segregation enforced?",
    ],
    questions: [
      { id: "bnk-01", domain: "control-activities", q: "Is the ECL/impairment model (staging, PD/LGD, overlays) governed by model risk management with independent validation, back-testing, and a documented approval trail for management overlays?", hint: "Overlays moved ECL by billions in recent years. Ask who approves overlays and where the board sees them.", weight: 3, critical: true },
      { id: "bnk-02", domain: "control-activities", q: "Are regulatory submissions (capital, liquidity, reserve requirements, prudential returns) prepared from a documented reconciliation to the general ledger, with sign-offs and late-change governance?", hint: "Ask for the regulator-return pack and the GL reconciliation worksheet behind it.", weight: 3, critical: true },
      { id: "bnk-03", domain: "control-activities", q: "Is the core banking system subject to strict segregation of duties and access control (maker-checker on parameter changes, limit changes, interest-rate changes) with periodic access reviews?", hint: "Whoever can change an interest parameter or a limit without dual control can create money invisibly. Ask for the parameter-change log review.", weight: 3, critical: true },
      { id: "bnk-04", domain: "risk-assessment", q: "Is AML/CFT embedded — KYC onboarding, transaction monitoring rules, sanctions screening, STR filing — with an independent compliance function and tested by audit?", hint: "Ask for the monitoring-rule inventory and the last AML audit's findings.", weight: 3, critical: true },
      { id: "bnk-05", domain: "control-activities", q: "Are credit approvals tiered by exposure with documented credit-committee minutes, and are limit excesses and policy exceptions logged and reported?", hint: "Exceptions that nobody count are pre-default losses. Ask for the exception register and its reporting.", weight: 3 },
      { id: "bnk-06", domain: "control-activities", q: "Are teller and vault operations under dual control (two-person vault opening, cash limits, surprise counts) with suspense accounts cleared daily?", hint: "Ask for the last surprise cash count and the ageing of the largest suspense items.", weight: 2 },
      { id: "bnk-07", domain: "control-activities", q: "Is treasury front/back office segregation enforced — deal confirmation by an independent function, deal blotters reconciled to the accounting system daily?", hint: "Ask who confirms deals and whether back office is independent of the dealers.", weight: 3 },
      { id: "bnk-08", domain: "monitoring", q: "Are early-warning indicators (past-due migration, NPL ratio, restructuring volumes, sector concentration) tracked with thresholds and action protocols?", hint: "Ask for the EWI dashboard and one threshold-breach story.", weight: 2 },
      { id: "bnk-09", domain: "info-communication", q: "Is the chart of accounts and product-parameter setup (fees, rates) controlled so new products must pass a check-list that includes accounting treatment?", hint: "New products deployed before accounting mapping creates reconciliation chaos. Ask for the last product launch's accounting sign-off.", weight: 2 },
      { id: "bnk-10", domain: "it-cyber", q: "Are payment systems (SWIFT, ACH, instant payments) controlled with dual authorization, call-back verification for instruction changes, and tested fraud monitoring?", hint: "Payment-fraud controls must be evidenced, not asserted. Ask for the last penetration test on payment rails and the SWIFT RMA/CSP status.", weight: 3, critical: true },
      { id: "bnk-11", domain: "control-activities", q: "Are restructured and forbearing exposures identified in the system, tracked, and reported for both accounting (ECL) and regulation?", hint: "Hidden forbearance is how NPLs are swept. Ask for the forbearance register.", weight: 3 },
      { id: "bnk-12", domain: "control-environment", q: "Is there a compliance function with independence, direct board reporting, and the authority to block transactions?", hint: "Compliance that can't say no is decoration. Ask for the escalation and veto evidence.", weight: 2 },
    ],
  },
  {
    id: "islamic-banking",
    sector: "finance",
    name: "Islamic Banking & Finance",
    icon: "moon",
    blurb: "Sharia-compliant banks and windows — murabaha, ijara, musharaka, sukuk and takaful products.",
    risks: ["Sharia board governance (fatwa compliance)", "Murabaha/ijara accounting (AAOIFI/IFAS)", "Commingling of restricted vs unrestricted investment pools", "Sukuk structuring and recognition"],
    procedures: [
      "Inspect the Sharia board minutes and compliance-monitoring function: how are non-compliant incomes quarantined?",
      "Test murabaha accounting: purchase-order-to- possession cut-off, deferred profit schedules, and EAR/APR regulatory reporting.",
      "Reconcile the restricted (mudaraba muqayada / POS pools) vs unrestricted investment pools and the profit-distribution waterfall.",
      "Inspect the sukuk portfolio: beneficial interest analysis (asset vs liability consolidation) and profit recognition.",
      "Test Sharia-non-compliant income treatment (purification) in the P&L and its disclosure.",
      "Inquire of Sharia review: what was the last product found non-compliant, and what happened to its income?",
    ],
    questions: [
      { id: "isb-01", domain: "control-environment", q: "Is there an active Sharia supervisory board with documented fatwas per product, an internal Sharia review function, and a quarantine process for non-compliant income?", hint: "Ask for the Sharia audit report and where non-compliant income was booked (it must be purified/charity — not P&L).", weight: 3, critical: true },
      { id: "isb-02", domain: "control-activities", q: "Is murabaha accounting controlled — commodity purchase, client possession, deferred profit schedule — with the recognition events system-driven from the transaction dates?", hint: "The murabaha timeline (bank buys, then sells) is the recognition spine. Ask how the system prevents recognizing profit before ownership passes.", weight: 3, critical: true },
      { id: "isb-03", domain: "control-activities", q: "Are restricted investment pools (customers' funds tied to specific assets) segregated from the bank's own funds, with separate profit-distribution computations and no commingling?", hint: "Commingling breaks both Sharia and fiduciary rules. Ask for the pool reconciliations.", weight: 3 },
      { id: "isb-04", domain: "control-activities", q: "Is the profit-distribution rate (PDR/weightages) governed — methodology approved, applied by the system, and benchmark reports reviewed before crediting customer profits?", hint: "Ask for the PDR committee minutes and the payout run evidence.", weight: 2 },
      { id: "isb-05", domain: "risk-assessment", q: "Is Islamic-finance regulatory reporting (central bank's Islamic banking return, AAOIFI-aligned disclosures) prepared and reconciled with the same discipline as conventional returns?", hint: "Two parallel reporting regimes must both tie to the GL. Ask for the dual-return reconciliation.", weight: 2 },
      { id: "isb-06", domain: "control-activities", q: "Are ijara (lease) assets held and depreciated as the lessor's assets, with lease schedules reconciled to the property register?", hint: "Ijara assets belong on our balance sheet (with our depreciation), unlike finance leases. Ask for the ijara asset register.", weight: 2 },
      { id: "isb-07", domain: "control-activities", q: "Are sukuk holdings and issuances classified correctly (asset vs liability, beneficial control), with profit/loss recognition per the structure?", hint: "Sukuk classification drives consolidation. Ask for the structure files and the accounting memos.", weight: 3 },
      { id: "isb-08", domain: "monitoring", q: "Are Sharia-compliance KPIs (non-compliant income, purification amounts, late-payment charge treatment) reported to the board with thresholds?", hint: "Ask for the Sharia-compliance dashboard in board packs.", weight: 2 },
      { id: "isb-09", domain: "control-activities", q: "Are commodity-trading legs (tawarruq/murabaha underlying) reconciled to broker confirmations, with custody and title transfer evidenced?", hint: "The commodity must really trade. Ask for the broker statements reconciliation.", weight: 2 },
      { id: "isb-10", domain: "info-communication", q: "Do the core system's Islamic modules (profit schedules, pools, purification) reconcile to the GL monthly with documented break clearance?", hint: "Islamic modules bolted onto conventional cores often break. Ask for the module reconciliation.", weight: 2 },
    ],
  },
  {
    id: "insurance",
    sector: "finance",
    name: "Insurance & Takaful",
    icon: "umbrella",
    blurb: "Property & casualty, life, health insurers and reinsurers — premium flows, claims and reserves.",
    risks: ["Claims reserve adequacy (actuarial)", "Premium recognition and unearned premiums", "Reinsurance recoverables", "Solvency/regulatory capital"],
    procedures: [
      "Inspect the actuarial reserve certification: methodology, data reconciliation to the ledger, and management's response to AOPs.",
      "Reperform unearned-premium computation for a sample of policies (pro-rata vs 365ths) to the liability roll-forward.",
      "Test claims: sample reported claims to the claims system, payment authorization matrix, and late-claim analysis for IBNR reasonableness.",
      "Test reinsurance ceded: treaties to statements, commission income, and recoverable recognition on ceded claims.",
      "Inspect premium-to-policy reconciliation: policy administration system to bordereaux to the ledger.",
      "Inquire of underwriting: who can deviate from rates/limits, and where is the deviation log?",
    ],
    questions: [
      { id: "ins-01", domain: "control-activities", q: "Are claims reserves certified by a qualified actuary whose data reconciles to the audited ledger, with management approval of any deviation from the actuarial recommendation documented?", hint: "Ask for the actuarial data-tie-out schedule and the last AOP (analysis of operations) review.", weight: 3, critical: true },
      { id: "ins-02", domain: "control-activities", q: "Is premium revenue recognized per policy terms with unearned-premium liabilities computed systematically (pro-rata/365th) and reconciled from the policy system monthly?", hint: "Ask for the UPR roll-forward and the policy-system-to-GL reconciliation.", weight: 3, critical: true },
      { id: "ins-03", domain: "control-activities", q: "Are claims payments authorized per a matrix (thresholds, dual approval above limits), with fraud indicators screened and duplicate-payment detection run?", hint: "Ask for the claims-payment authority matrix and the last fraud-screening report.", weight: 3 },
      { id: "ins-04", domain: "control-activities", q: "Are reinsurance treaties and facultative placements documented, ceded premiums/recoverables reconciled to broker statements, and disputed balances aged and assessed?", hint: "Reinsurance recoverables are receivables with credit risk — ask for the ageing and the ECL treatment.", weight: 2 },
      { id: "ins-05", domain: "risk-assessment", q: "Is underwriting discipline enforced — rate deviations, limit authorizations, referral rules — with a deviation register reported to the risk committee?", hint: "Ask for the underwriting authority matrix and the deviation log.", weight: 2 },
      { id: "ins-06", domain: "monitoring", q: "Are loss ratios, expense ratios and combined ratio tracked by line monthly against pricing assumptions, with remediation when they breach?", hint: "Ask for the monthly underwriting results and one remediation case.", weight: 2 },
      { id: "ins-07", domain: "control-activities", q: "Are client premium fiduciary funds segregated from the company's own funds where required, with reconciliations and investment restrictions on those balances?", hint: "Premiums held for insurers/clients are trust money. Ask for the fiduciary account reconciliations.", weight: 3 },
      { id: "ins-08", domain: "control-environment", q: "Does the Appointed Actuary/Chief Actuary have independence and direct board access, including a duty to report reserve concerns?", hint: "Ask for the actuary's direct reporting line and the last reserved-concern communication.", weight: 2 },
      { id: "ins-09", domain: "info-communication", q: "Is regulatory/solvency reporting (RBC, Solvency II, local returns) prepared with documented data lineage and reconciled to the GL before submission?", hint: "Ask for the solvency-return workpack and its sign-off chain.", weight: 3 },
      { id: "ins-10", domain: "it-cyber", q: "Are policy/claims systems access-controlled with maker-checker on claims setup, payment files, and reserve adjustments, plus audit trails reviewed?", hint: "Reserve adjustments by unreviewed hands move the year's profit. Ask for the claims-system access review.", weight: 2 },
      { id: "ins-11", domain: "control-activities", q: "For takaful: are participant risk funds segregated from shareholder funds, with the surplus/deficit sharing mechanism computed and reported per the model?", hint: "Ask for the takaful fund reconciliations and the surplus-distribution computation.", weight: 2 },
    ],
  },
  {
    id: "asset-mgmt",
    sector: "finance",
    name: "Asset & Wealth Management",
    icon: "chart",
    blurb: "Mutual funds, discretionary portfolios, wealth managers and fund administrators.",
    risks: ["NAV computation and pricing governance", "Client asset segregation and custody", "Fee computation (management/performance)", "Trade allocation and best execution"],
    procedures: [
      "Reperform a NAV: holdings to custodian statements, corporate-action processing, and the fee accrual for one fund.",
      "Inspect the segregation of client assets: custody arrangements, per-client ledgers, and the reconciliations regime.",
      "Test fee computations for a sample of mandates (tiered, performance-fee watermarks and crystallization).",
      "Inspect trade-allocation records for a sample of block trades across client orders (fair allocation test).",
      "Test best-execution monitoring: broker panel reviews and execution-quality evidence.",
      "Inquire of compliance: how are personal-account dealing and gifts/entertainment monitored?",
    ],
    questions: [
      { id: "ast-01", domain: "control-activities", q: "Is the NAV computed from custodian-confirmed holdings with independent pricing (valuation committee for level-3), a maker-checker process, and error-correction governance?", hint: "Ask for the NAV sign-off pack, the pricing-source hierarchy, and the last NAV error's remediation.", weight: 3, critical: true },
      { id: "ast-02", domain: "control-activities", q: "Are client assets fully segregated (custodian accounts, per-client ledgers) with daily/weekly reconciliations and breach escalation — no mingling with house assets?", hint: "Ask for the reconciliation calendar and the last break's escalation.", weight: 3, critical: true },
      { id: "ast-03", domain: "control-activities", q: "Are management and performance fees computed per mandate terms (tiers, hurdle rates, high-water marks, crystallization dates) and independently re-calculated before billing?", hint: "Performance-fee watermarks are a recurring error. Ask who re-performs the fee calc and the last variance.", weight: 3 },
      { id: "ast-04", domain: "control-activities", q: "Are block trades allocated across client orders on a documented fair-allocation policy (pro-rata, not favouring house or preferred accounts), with exception reporting?", hint: "Ask for the allocation policy and a sample block trade's allocation evidence.", weight: 3 },
      { id: "ast-05", domain: "risk-assessment", q: "Is best execution monitored — broker panel, execution quality reviews — with outcomes documented?", hint: "Ask for the last best-execution committee review.", weight: 2 },
      { id: "ast-06", domain: "control-environment", q: "Are personal-account dealing, gifts and outside interests restricted with pre-clearance and compliance monitoring evidence?", hint: "Front-running lives here. Ask for the PA-dealing log and the last surveillance report.", weight: 2 },
      { id: "ast-07", domain: "control-activities", q: "Are corporate actions captured per event (dividends, splits, defaults) and reconciled to custodian records before NAV release?", hint: "Ask for the corporate-action calendar and the last event's processing evidence.", weight: 2 },
      { id: "ast-08", domain: "info-communication", q: "Are fund reports (factsheets, KIIDs, investor statements) reconciled to the audited NAV/ledger data with a documented sign-off?", hint: "Two NAV universes (marketing vs accounting) is an integrity failure. Ask who ties them.", weight: 2 },
      { id: "ast-09", domain: "monitoring", q: "Are compliance breaches (mandate limits, concentration caps, guideline breaches) tracked, and repeat breaches escalated with consequence?", hint: "Ask for the breach register and its escalation history.", weight: 2 },
      { id: "ast-10", domain: "it-cyber", q: "Are order-management and portfolio systems access-controlled with maker-checker on trades, and disaster recovery for NAV-critical systems tested?", hint: "Ask for the last DR test on the portfolio system and its RTO result.", weight: 2 },
    ],
  },
  {
    id: "fintech-payments",
    sector: "finance",
    name: "FinTech & Payments",
    icon: "wallet",
    blurb: "Payment processors, wallets, BNPL lenders and neobanks — settlement flows and platform lending.",
    risks: ["Client-money segregation and safeguarding", "Settlement reconciliation (three-way)", "Credit model governance (BNPL/lending)", "IT change and uptime controls"],
    procedures: [
      "Test the safeguarding/segregation of client balances: accounts, daily reconciliations, and the excess/shortfall treatment.",
      "Reperform the three-way settlement reconciliation (internal ledger, acquirer/PSP, bank) for a sample week including fees and refunds.",
      "Inspect the credit-model governance for lending products: documentation, validation, monitoring of default rates vs expectation.",
      "Test the interchange/MDR revenue computation from scheme statements to the ledger.",
      "Inspect the change-management records for a sample of production releases affecting money flows.",
      "Inquire of operations: how are stuck/failed payments identified, retried, and reconciled to resolution?",
    ],
    questions: [
      { id: "fin-01", domain: "control-activities", q: "Are client funds safeguarded — segregated accounts, daily reconciliation of client balances to liabilities, and any surplus/deficit resolved by the same day?", hint: "Ask for the daily client-money reconciliation and the escalation for a shortfall.", weight: 3, critical: true },
      { id: "fin-02", domain: "control-activities", q: "Is there a three-way daily reconciliation of every settlement flow — internal ledger, acquirer/PSP reports, and the bank — with break ownership and ageing limits?", hint: "Settlement breaks are where missing money hides. Ask for the reconciliation dashboard and the oldest break.", weight: 3, critical: true },
      { id: "fin-03", domain: "control-activities", q: "For lending products, is the credit-decision model governed — documented, independently validated, monitored for drift/discrimination — with manual overrides limited and logged?", hint: "Ask for the model-validation report and the override-rate metric.", weight: 3 },
      { id: "fin-04", domain: "control-activities", q: "Are fee revenues (MDR, interchange, FX markup, late fees) computed from scheme/processor statements and reconciled monthly, with rate changes controlled?", hint: "Ask who verifies the interchange bill and how rate changes reach the ledger.", weight: 2 },
      { id: "fin-05", domain: "risk-assessment", q: "Is regulatory status maintained (licences, e-money/sandbox conditions, complaints handling) with a compliance calendar and reporting to the board?", hint: "Ask for the licence obligations register and the last regulatory correspondence.", weight: 2 },
      { id: "fin-06", domain: "it-cyber", q: "Is production change management controlled — peer review, approvals, segregated deploy rights — with money-flow changes requiring dual sign-off?", hint: "Ask for a sample release's approval trail affecting payment logic.", weight: 3 },
      { id: "fin-07", domain: "monitoring", q: "Are fraud and chargeback rates, approval rates, and dispute outcomes tracked with thresholds and immediate action protocols?", hint: "Ask for the fraud ops dashboard and the last threshold breach action.", weight: 2 },
      { id: "fin-08", domain: "control-activities", q: "Are refunds, reversals and chargebacks authorized per matrix and reconciled to the original transactions (no refund without a purchase)?", hint: "Refund fraud needs a lonely refund button. Ask for the refund authorization log.", weight: 3 },
      { id: "fin-09", domain: "info-communication", q: "Is customer data handled per privacy law (consent, retention, deletion) with a data inventory and breach-response tested?", hint: "Ask for the last data-mapping exercise and breach drill.", weight: 2 },
      { id: "fin-10", domain: "control-environment", q: "Are treasury/parking of own funds in interest-bearing instruments governed by policy with counterparty limits?", hint: "Fintechs dying from treasury misplacement is recent history. Ask for the treasury policy and limits.", weight: 2 },
    ],
  },
  {
    id: "crypto",
    sector: "finance",
    name: "Crypto & Digital Assets",
    icon: "coin",
    blurb: "Exchanges, custodians, stablecoin issuers and tokenized-asset platforms.",
    risks: ["Proof of reserves / wallet reconciliation", "Client asset segregation (on-chain)", "Token valuation (fair value, illiquidity)", "Sanctions and AML for on-chain flows"],
    procedures: [
      "Perform wallet reconciliation: on-chain balances (block explorers, signed proof) to the internal ledger, per asset, cold and hot.",
      "Test client-asset segregation on-chain: client deposit addresses to client sub-ledgers, and rehypothecation analysis.",
      "Inspect the reserve attestation for stablecoin issuance (composition, custody, publication cadence).",
      "Test AML/sanctions controls: chain-analytics coverage, wallet screening, and travel-rule implementation.",
      "Test token valuation: price sources, illiquidity haircuts, and level-3 transfers for restricted tokens.",
      "Inquire of security: cold-storage governance, multi-sig ceremonies, and the last proof-of-reserves exercise.",
    ],
    questions: [
      { id: "cry-01", domain: "control-activities", q: "Are on-chain wallet balances reconciled to the internal ledger daily per asset (hot, warm, cold), with variance thresholds, and are signed proofs retained?", hint: "The chain is the ultimate bank statement. Ask for the daily reconciliation and the last unreconciled variance.", weight: 3, critical: true },
      { id: "cry-02", domain: "control-activities", q: "Are client crypto assets segregated on-chain (client addresses/sub-ledgers), with rehypothecation prohibited or disclosed and reconciled per client daily?", hint: "Commingling client coins with house coins is the FTX pattern. Ask for the segregation map and per-client reconciliation.", weight: 3, critical: true },
      { id: "cry-03", domain: "it-cyber", q: "Is cold-storage custody governed — multi-sig/quorum, geographic key-sharding, withdrawal ceremonies dual-authorized and logged, with key-ceremony audits?", hint: "Ask for the withdrawal-authorization procedure and the last ceremony's evidence.", weight: 3, critical: true },
      { id: "cry-04", domain: "risk-assessment", q: "Is AML/sanctions adapted to on-chain reality — chain analytics, wallet screening at deposit and withdrawal, travel-rule compliance — with the compliance function independent?", hint: "Ask for the analytics tool coverage and the last sanctions-testing exercise.", weight: 3 },
      { id: "cry-05", domain: "control-activities", q: "Are token valuations governed — price sources hierarchy, illiquidity/stale-price haircuts, and escalation when a holding exceeds market depth?", hint: "Pricing the illiquid bag at the last trade is how balance sheets lie. Ask for the valuation policy and the haircut table.", weight: 3 },
      { id: "cry-06", domain: "info-communication", q: "For issuers: is the reserve composition attested at a stated cadence, published, and reconciled to custody statements and the ledger?", hint: "Ask for the last attestation and its reconciliation workpapers.", weight: 3 },
      { id: "cry-07", domain: "control-activities", q: "Are listing/delisting decisions governed by documented criteria (liquidity, legal review, custody capability) with committee approval?", hint: "Listings move markets and custody risk. Ask for the listing committee minutes.", weight: 2 },
      { id: "cry-08", domain: "monitoring", q: "Are platform solvency metrics (liabilities vs reserves, withdrawal queue, large-exposure concentration) monitored in real time with escalation triggers?", hint: "Ask for the treasury dashboard and the last bank-run drill or stress test.", weight: 2 },
      { id: "cry-09", domain: "control-environment", q: "Is there a governance structure where segregation of trading, custody and treasury is enforced (no proprietary trading against client assets)?", hint: "Ask how the policy is evidenced technically, not just verbally.", weight: 3 },
      { id: "cry-10", domain: "risk-assessment", q: "Is regulatory status tracked across jurisdictions (licences, travel-rule deadlines, marketing rules) with a compliance map and horizon-scanning?", hint: "Ask who owns the regulatory map and its last update.", weight: 2 },
    ],
  },
]
