import type { TocIndustry } from "./types"

/** v37 — Energy & Utilities: regulated network businesses and generation.
 *  Common audit textures: regulated tariffs and revenue caps, RAB
 *  (regulated-asset-base) capitalization, PPAs, availability incentives,
 *  environmental obligations, and very large capex programmes. */
export const ENERGY_INDUSTRIES: TocIndustry[] = [
  {
    id: "power-utilities",
    sector: "energy",
    name: "Power Generation & Utilities",
    icon: "zap",
    blurb: "Thermal generation, transmission and distribution utilities, and electricity/gas retailers.",
    risks: ["Regulated tariff and revenue-cap accounting", "Large capex capitalization", "Fuel procurement and PPAs", "Network losses and metering"],
    procedures: [
      "Inspect the tariff/regulatory filing and reconcile billed volumes x approved tariff to revenue by customer class.",
      "Test capitalization: sample major projects for capitalization policy compliance, borrowing costs (IAS 23) and asset-component splits.",
      "Reperform network loss calculations (technical vs non-technical) and their revenue effect.",
      "Inspect fuel-supply contracts: take-or-pay minimums, pricing indexes, and hedge accounting documentation.",
      "Observe a meter-to-bill test: sample meters, read data through to the billing system and the ledger.",
      "Inquire of the regulatory team: how are regulatory deferral accounts / assets tracked and reviewed?",
    ],
    questions: [
      { id: "pwr-01", domain: "control-activities", q: "Is revenue computed from metered consumption x approved tariffs, with billing-system-to-ledger reconciliations and unbilled accruals computed monthly?", hint: "Unbilled energy is the accrual that swings profit. Ask for the unbilled model (period consumption estimation) and who reviews it.", weight: 3, critical: true },
      { id: "pwr-02", domain: "control-activities", q: "Is major capital programme spend controlled — approved budgets, project-stage reviews, capitalization policy, and borrowing-cost capitalization per IAS 23?", hint: "Capex is where utilities' profit lives or dies. Ask for the capitalization policy, the project-stage gate evidence, and who approves stage progression.", weight: 3, critical: true },
      { id: "pwr-03", domain: "control-activities", q: "Are regulatory mechanisms (tariff adjustments, revenue caps, deferral accounts) identified, computed by a named owner, and reconciled to the regulator's determinations?", hint: "Regulatory assets/deferrals are judgement-heavy balances. Ask for the last regulatory reconciliation and board review.", weight: 3 },
      { id: "pwr-04", domain: "control-activities", q: "Is fuel procurement under contracts with approved pricing mechanisms, and are take-or-pay/minimum-offtake commitments disclosed and provisioned where onerous?", hint: "Onerous PPA/coal contracts must move to provisions. Ask for the contract register scan for onerous-ness.", weight: 2 },
      { id: "pwr-05", domain: "control-activities", q: "Are network losses (technical and non-technical/theft) measured, analyzed and included in tariff filings and the accounts consistently?", hint: "Losses feed both revenue and regulatory numbers. Ask for the loss study and its vintage.", weight: 2 },
      { id: "pwr-06", domain: "risk-assessment", q: "Is plant availability and outage planning controlled so that availability incentives/penalties are forecast and accrued?", hint: "Availability payments are revenue. Ask for the outage plan versus incentive thresholds.", weight: 2 },
      { id: "pwr-07", domain: "control-activities", q: "Is meter data (smart/head-end systems) integrity-controlled — estimation rules, gap handling, and audit trails — before it reaches billing?", hint: "Estimated reads not flagged become unbilled errors. Ask about estimation rates and exception queues.", weight: 2 },
      { id: "pwr-08", domain: "info-communication", q: "Are environmental emissions (SOx, NOx, CO2) monitored under compliance systems, with allowances tracked and accounted (free allocation, trading)?", hint: "Emissions allowance accounting has its own traps. Ask who owns the emissions inventory and its audit.", weight: 2 },
      { id: "pwr-09", domain: "monitoring", q: "Are capex projects tracked against approved budgets with variance escalation, and are in-service dates reviewed for depreciation starts?", hint: "Depreciation starting late flatters profit. Ask for the in-service commissioning evidence trail.", weight: 2 },
      { id: "pwr-10", domain: "control-environment", q: "Is there a regulatory-compliance function with horizon-scanning for tariff resets, licensing conditions and decarbonization mandates?", hint: "Regulatory surprises reprice utilities. Ask for the compliance calendar.", weight: 2 },
      { id: "pwr-11", domain: "control-activities", q: "Are large customer/dealer collections (industrial, distribution companies) credit-controlled with deposits and disconnection governance?", hint: "Utility receivables blow up on large insolvent dealers. Ask for the ageing and the deposit policy.", weight: 2 },
    ],
  },
  {
    id: "renewables",
    sector: "energy",
    name: "Renewables & Solar",
    icon: "leaf",
    blurb: "Wind and solar power producers, storage, and the developers/EPFs behind them.",
    risks: ["PPA revenue recognition", "Construction-period accounting (PPAs vs EPC)", "Certificates (RECs/GOs) tracking", "Availability and curtailment"],
    procedures: [
      "Inspect the PPA portfolio register (price, tenor, indexation, availability clauses) and reconcile the revenue calendar to the ledger.",
      "Test construction-phase accounting: EPC contract progress, capitalized costs vs expensed development, and impairment triggers for stalled projects.",
      "Reperform the unbilled-energy accrual for a sample of plants (meter data vs settlement statements).",
      "Inspect REC/GO registries and reconcile certificates earned, sold and banked to the accounts.",
      "Test curtailment compensation claims against grid-operator data.",
      "Inquire of asset management: how are plant availability guarantees monitored and liquidated-damages tracked?",
    ],
    questions: [
      { id: "ren-01", domain: "control-activities", q: "Is the PPA portfolio governed by a register (price, tenor, index, availability clauses) that finance uses to bill and accrue, reconciled monthly to settlement statements?", hint: "The PPA terms are the revenue law. Ask who maintains the register and how indexation is applied each year.", weight: 3, critical: true },
      { id: "ren-02", domain: "control-activities", q: "Is construction-period accounting controlled — costs accumulated per project, EPC milestone evidence, and policy gates between development expense and capitalized asset?", hint: "Failed projects' costs must be expensed/impaired, not parked in CIP. Ask for the CIP ageing and stalled-project review.", weight: 3, critical: true },
      { id: "ren-03", domain: "control-activities", q: "Are unbilled energy and curtailment/grid-compensation accruals computed from meter/grid data monthly, with estimates trued up on settlement?", hint: "The gap between generation and settlement is where revenue sits unrecorded. Ask for the accrual model and last true-up.", weight: 3 },
      { id: "ren-04", domain: "control-activities", q: "Are renewable certificates (RECs/GOs/GO-Egypt) tracked from issuance through sale or banking, with revenue recognized per policy and certificates physically/reconcilably held?", hint: "Certificates are a second invisible product line. Ask for the registry reconciliation.", weight: 2 },
      { id: "ren-05", domain: "risk-assessment", q: "Are merchant-price and volume risks (for uncontracted output) assessed with hedging strategy and disclosure of sensitivity?", hint: "Ask for the merchant-exposure report and hedge policy.", weight: 2 },
      { id: "ren-06", domain: "control-activities", q: "Are availability guarantees, liquidated damages and bonus schemes in PPAs/O&M contracts tracked to settlement, with O&M contractor performance verified independently?", hint: "O&M contractors self-report availability — their report drives our revenue. Ask for the independent verification (SCADA analytics).", weight: 3 },
      { id: "ren-07", domain: "control-activities", q: "Is asset impairment monitored (curtailment changes, PPA counterparty credit, technology shifts) with triggers reviewed at each period?", hint: "Curtailment rule changes have impaired whole portfolios. Ask for the impairment-trigger review.", weight: 2 },
      { id: "ren-08", domain: "control-activities", q: "Are tax-equity, lease (IFRS 16) and project-finance structures' accounting reviewed by specialists with compliance covenants tracked?", hint: "Complex structures = deferred revenue allocations, lease/loan splits, covenant breach tests. Ask who maps them.", weight: 2 },
      { id: "ren-09", domain: "monitoring", q: "Is per-plant performance (PR ratio, availability, revenue per MW) benchmarked across the fleet with variance investigation?", hint: "One underperforming plant in a portfolio hides in averages. Ask for the fleet league table.", weight: 2 },
      { id: "ren-10", domain: "it-cyber", q: "Is SCADA/plant telemetry data used for billing protected against modification, with access logs and independent backups?", hint: "If plant data drives revenue, it is financial data. Ask about its integrity controls.", weight: 2 },
    ],
  },
  {
    id: "water-waste",
    sector: "energy",
    name: "Water & Waste Management",
    icon: "recycle",
    blurb: "Water and wastewater utilities plus solid-waste collection, recycling and landfill operators.",
    risks: ["Concession/PPP accounting", "Landfill closure and aftercare provisions", "Tipping-volume measurement", "Recycled-material pricing"],
    procedures: [
      "Inspect concession agreements and test the intangible/financial-asset model boundary and periodic re-assessment.",
      "Reperform the landfill provision (remaining capacity, capping and aftercare costs, inflation, discounting).",
      "Observe weighbridge operations for a day: ticket sequence, tamper-evidence, reconciliation to billing.",
      "Test metered-water billing: estimation rates, meter-read cycles, and the unbilled accrual model.",
      "Inspect environmental permits and the compliance monitoring data feeding provisions.",
      "Inquire of operations: how is illegal dumping detected and quantified (revenue leakage)?",
    ],
    questions: [
      { id: "wat-01", domain: "control-activities", q: "Is waste intake measured by calibrated weighbridge with sequenced tickets, and is the weighbridge-to-invoice-to-ledger chain reconciled daily?", hint: "Every tonne is revenue. Ask for the ticket-sequence check and the last calibration certificate.", weight: 3, critical: true },
      { id: "wat-02", domain: "control-activities", q: "Is the landfill closure and aftercare provision updated periodically (remaining capacity survey, cost estimates, inflation, discounting) with expert involvement?", hint: "This provision runs decades. Ask for the last engineer's report and the sensitivity table.", weight: 3, critical: true },
      { id: "wat-03", domain: "control-activities", q: "For concessions/PPPs: is the accounting model (intangible vs financial asset) assessed and monitored, with contract modifications re-assessed?", hint: "Model misclassification moves whole balance sheets. Ask who performed the assessment and when it was last revisited.", weight: 3 },
      { id: "wat-04", domain: "control-activities", q: "Is metered water revenue controlled — read cycles, estimation rules, unbilled accruals, and leakage/water-balance analysis feeding tariffs?", hint: "Non-revenue water is the sector's core metric. Ask for the water balance and unbilled model.", weight: 3 },
      { id: "wat-05", domain: "control-activities", q: "Are recycled-commodity sales (paper, metals, RDF) priced from index-linked contracts or spot approvals, with inventory (bales) counted and valued at NRV?", hint: "Recyclate prices swing; NRV matters. Ask for the commodity price file and the bale inventory count.", weight: 2 },
      { id: "wat-06", domain: "risk-assessment", q: "Are environmental compliance risks (effluent limits, landfill gas, leachate) monitored with violations tracked and costed?", hint: "Fines and remediation follow violations. Ask for the permit compliance register and open exceedances.", weight: 2 },
      { id: "wat-07", domain: "control-activities", q: "Is collection-route completeness controlled (vehicle telemetry/ manifests reconciled to customers billed), so skipped collections don't leak revenue or trigger service credits?", hint: "GPS-telemetry to billing reconciliation is the modern control. Ask who reviews route completion reports.", weight: 2 },
      { id: "wat-08", domain: "control-activities", q: "Are capex programmes for networks (mains, plants) subject to stage-gate approval and regulatory-allowance tracking?", hint: "Allowed capex vs actual drives future tariffs and current depreciation. Ask for the allowance tracking.", weight: 2 },
      { id: "wat-09", domain: "monitoring", q: "Are operating ratios (cost per tonne, cost per m3 treated) benchmarked and reviewed with corrective action?", hint: "Sector benchmarking (e.g., per-connection cost) exposes both inefficiency and accounting oddities.", weight: 1 },
      { id: "wat-10", domain: "control-environment", q: "Is there a stakeholder/grievance and illegal-dumping reporting process feeding both operations and finance?", hint: "Unreported dumping is both an environmental liability and lost revenue. Ask for the incident log.", weight: 1 },
    ],
  },
]
