import type { TocIndustry } from "./types"

/** v37 — Technology & Media: deferred revenue, usage-based billing,
 *  capitalized development (IAS 38 / SaaS costs), content production
 *  accounting and infrastructure capex. */
export const TECH_INDUSTRIES: TocIndustry[] = [
  {
    id: "saas",
    sector: "tech",
    name: "Software & SaaS",
    icon: "cloud",
    blurb: "Subscription software, platforms and enterprise SaaS — ARR engines with deferred revenue and capitalized engineering.",
    risks: ["Revenue recognition (subscription + usage + setup)", "Deferred revenue and contract liabilities", "Capitalization of development costs (IAS 38 / CAC)", "Churn and renewal assumptions"],
    procedures: [
      "Reperform revenue allocation for multi-element contracts (license + subscription + services + credits) using SSP evidence.",
      "Test the deferred-revenue roll-forward: billings, revenue recognized, and usage/consumption trues for a sample month.",
      "Inspect the capitalization policy for engineering (criteria, labour capture) and test a sample of capitalized sprints to time records.",
      "Test commission (CAC) capitalization and amortization against contract terms.",
      "Inspect the churn/cohort analytics used in impairment and CLV models for reasonableness.",
      "Inquire of finance and engineering leads: who gates the capitalizable-vs-expense decision, and how are estimates monitored?",
    ],
    questions: [
      { id: "sas-01", domain: "control-activities", q: "Is revenue recognized per the five-step model for each element (subscription ratabable, usage as consumed, setup/services by progress), with SSP allocation documented for bundles?", hint: "Ask for the revenue-waterfall report and the SSP policy evidence (standalone sales, cost-plus, residual).", weight: 3, critical: true },
      { id: "sas-02", domain: "control-activities", q: "Is the deferred-revenue balance reconciled monthly (opening, billings, revenue, FX/credits) to the sub-ledger of contracts, with unbilled receivables separately identified?", hint: "Ask for the contract sub-ledger to GL reconciliation and the unbilled ageing.", weight: 3, critical: true },
      { id: "sas-03", domain: "control-activities", q: "Is engineering-labour capitalization governed — capitalizable projects pre-approved, time capture reliable, amortization lives reviewed — and tested for consistency with the policy?", hint: "Capitalizing too much engineering flatters both profit and assets. Ask who approves a project as capitalizable and the last audit of time allocation.", weight: 3 },
      { id: "sas-04", domain: "control-activities", q: "Are sales commissions (including renewals) capitalized and amortized on a consistent basis (with the practical expedient, if used, applied consistently)?", hint: "Ask for the CAC policy memo and its amortization period rationale.", weight: 2 },
      { id: "sas-05", domain: "monitoring", q: "Are ARR bridge, churn by cohort, net revenue retention and CAC payback tracked monthly, with assumptions feeding impairment testing re-based on evidence?", hint: "Deteriorating cohort data is both a business and an intangible-impairment signal. Ask for the cohort report.", weight: 2 },
      { id: "sas-06", domain: "control-activities", q: "Is usage-based billing driven by metered consumption data with integrity controls (meter gaps, backfills, credits) and exception queues cleared before invoicing?", hint: "Metering breaks = billing breaks. Ask about the meter-data completeness checks.", weight: 3 },
      { id: "sas-07", domain: "control-activities", q: "Are customer contracts' auto-renewals, price escalators and ramp deals captured in the billing system from the executed contract (not manually keyed) with a verification step?", hint: "Manual contract entry is where revenue terms mutate. Ask for the contract-to-system control.", weight: 2 },
      { id: "sas-08", domain: "risk-assessment", q: "Is data protection and cybersecurity risk formally managed (SOC 2 / ISO 27001 roadmap, pen tests, incident response tested), with customer security-questionnaire answers controlled?", hint: "A breach is revenue + liability + reputation in one. Ask for the last pen test and the ISMS status.", weight: 2 },
      { id: "sas-09", domain: "info-communication", q: "Are product usage/telemetry metrics used in board reporting reconciled in definition to the billed data in the ledger?", hint: "Two definitions of 'active customer' is an integrity gap. Ask who maps metric definitions.", weight: 2 },
      { id: "sas-10", domain: "control-activities", q: "Are R&D grants/tax credits (where claimed) computed from the same time-and-project records as capitalization, and are their conditions tracked?", hint: "Grant/tax-credit claims must survive audit as much as the accounts. Ask for the claim computation basis.", weight: 2 },
    ],
  },
  {
    id: "telecom",
    sector: "tech",
    name: "Telecommunications",
    icon: "tower",
    blurb: "Mobile and fixed operators, ISPs and tower companies — billing millions of subscribers.",
    risks: ["Rating and billing integrity", "Revenue share and interconnect settlements", "Dealer commissions and prepaid distribution", "Spectrum licences and network capex"],
    procedures: [
      "Test the rating engine: sample CDRs through rating to the invoice, including bundles, promotions and roundings.",
      "Reconcile interconnect/roaming settlements (TAP/RAP files, clearing house) to the ledger for a sample month.",
      "Test dealer commission computations to agreements and the clawback mechanism evidence.",
      "Inspect spectrum-licence accounting (intangible recognition, useful lives, activation timing) and the renewal/technology-migration analysis.",
      "Observe a network element count (towers, radios) or reconcile to the fixed-asset register via OSS data.",
      "Inquire of revenue assurance: what controls exist for SMS/voice/zero-rating leaks, and who reviews them?",
    ],
    questions: [
      { id: "tel-01", domain: "control-activities", q: "Is the rating and billing chain integrity-controlled — CDR completeness (sequence checks), rating rules versioned with approvals, and revenue-assurance reconciliations (network vs billed) performed monthly?", hint: "Ask for the revenue-assurance report comparing network usage to billed usage and its variance thresholds.", weight: 3, critical: true },
      { id: "tel-02", domain: "control-activities", q: "Are interconnect, roaming and wholesale settlements reconciled monthly to clearing-house/partner statements, with disputes logged and accrued?", hint: "Ask for the interconnect reconciliation and the open-dispute ageing.", weight: 3 },
      { id: "tel-03", domain: "control-activities", q: "Are dealer commissions (activation-based) computed from validated activations (not raw sales), with clawbacks for early churn evidenced and reconciled?", hint: "Ask for the clawback mechanism and the last commission audit.", weight: 2 },
      { id: "tel-04", domain: "control-activities", q: "Is the prepaid ecosystem controlled — voucher lifecycle (print, stock, activation, expiry), e-top-up reconciliations to the ledger, and float accounting?", hint: "Voucher stock is cash-equivalent. Ask for the voucher reconciliation and destruction of expired stock.", weight: 3, critical: true },
      { id: "tel-05", domain: "control-activities", q: "Are spectrum licences recognized as intangibles with defensible useful lives, and is impairment reviewed for technology shifts (sunsetting generations)?", hint: "Ask for the useful-life analysis and the last impairment review of spectrum.", weight: 3 },
      { id: "tel-06", domain: "control-activities", q: "Is network capex (equipment, sites, fiber) capitalized with cut-off controls (acceptance/handover documents) and depreciation aligned to in-service dates?", hint: "Equipment in service but not depreciating flatters profit. Ask for the acceptance-to-asset-registry control.", weight: 2 },
      { id: "tel-07", domain: "risk-assessment", q: "Are regulatory obligations (coverage, quality-of-service, lawful intercept, data retention) tracked to compliance with evidence?", hint: "QOS penalties and licence conditions are money. Ask for the compliance register.", weight: 2 },
      { id: "tel-08", domain: "monitoring", q: "Are ARPU, churn, gross adds and network utilization tracked with thresholds and action protocols, and do the operational metrics tie to financial trends?", hint: "Divergence between subscriber metrics and revenue is an integrity signal. Ask who reconciles them.", weight: 2 },
      { id: "tel-09", domain: "control-activities", q: "Are tower/site costs (leases, utilities) reconciled to contracts, and site decommissioning liabilities assessed?", hint: "IFRS 16 leases + decommissioning provisions live here. Ask for the site-liability schedule.", weight: 2 },
      { id: "tel-10", domain: "it-cyber", q: "Are subscriber-data systems (PII at national scale) protected with access governance, and are SS7/diameter network fraud controls monitored?", hint: "Ask for the last fraud-pattern report (Wangiri, SIM-swap) and access review of the customer base.", weight: 2 },
    ],
  },
  {
    id: "it-services",
    sector: "tech",
    name: "IT Services & Outsourcing",
    icon: "network",
    blurb: "System integrators, managed services, BPO and consulting firms selling time and outcomes.",
    risks: ["Revenue over time (input method) and unbilled WIP", "Utilization and payroll cost capture", "Fixed-price contract estimation", "Subcontractor costs"],
    procedures: [
      "Reperform revenue over time for T&M contracts: approved timesheets to invoices to receivables, and the WIP ageing.",
      "Test fixed-price contracts' estimates-to-complete for a sample, with loss-provision testing.",
      "Inspect the utilization report: billable hours to payroll hours to payroll cost, and write-offs approved.",
      "Test subcontractor accruals to delivery evidence (their timesheets under our statement of work).",
      "Inspect the milestone-billing versus milestone-delivery (delivery notes/client acceptance) for a sample.",
      "Inquire of delivery managers: who approves a milestone as delivered, and could it be approved before completion?",
    ],
    questions: [
      { id: "its-01", domain: "control-activities", q: "Is time-and-materials revenue driven from approved timesheets (client-approved where contracts require), with unbilled WIP aged and reviewed monthly?", hint: "Ask for the WIP ageing and the write-off/write-down approval log. Unbilled old WIP is phantom revenue.", weight: 3, critical: true },
      { id: "its-02", domain: "control-activities", q: "Are fixed-price contracts' percent-complete and estimates-to-complete prepared by delivery and reviewed by finance independently, with onerous-contract testing?", hint: "Ask for the fixed-price portfolio report with margins at inception vs latest forecast.", weight: 3, critical: true },
      { id: "its-03", domain: "control-activities", q: "Is the time-capture system controlled (project codes, approvals, lock after period close) with utilization analytics reconciled to payroll cost?", hint: "Unbilled time leakage and bench-cost misclassification both distort. Ask for the utilization report and period lock evidence.", weight: 3 },
      { id: "its-04", domain: "control-activities", q: "Are milestone billings supported by delivery evidence (acceptance certificates, go-live sign-offs) before invoicing?", hint: "Ask for the acceptance-certificate file for the last quarter's milestone invoices.", weight: 2 },
      { id: "its-05", domain: "control-activities", q: "Are subcontractor costs accrued from delivery evidence and reconciled to their invoices, with rate cards enforced?", hint: "Ask for the subcontract accrual computation and one vendor's reconciliation.", weight: 2 },
      { id: "its-06", domain: "control-activities", q: "Are recruitment costs, bench time and training expensed consistently (not parked in project cost), with the policy documented?", hint: "Bench cost hidden in billable projects understates bench cost and overstates project margin. Ask for the policy.", weight: 2 },
      { id: "its-07", domain: "risk-assessment", q: "Are delivery risks (client credit, key-person, scope creep) assessed per engagement with escalation triggers?", hint: "Ask for the engagement risk log and one escalation story.", weight: 1 },
      { id: "its-08", domain: "monitoring", q: "Are utilization, realization rates (billed vs cost rate), and project margins tracked weekly/monthly with action loops?", hint: "Realization rate is the sector's pulse. Ask for the realization report by client/practice.", weight: 2 },
      { id: "its-09", domain: "info-communication", q: "Are client data and access (privileged access on client systems) governed — access logs, least privilege, offboarding evidence?", hint: "We sit inside clients' systems; a control failure there is contractual. Ask for the last client security audit.", weight: 2 },
      { id: "its-10", domain: "control-activities", q: "Are third-party software resale and licence costs recognized gross where we are principal, with vendor rebate/truing reconciled?", hint: "Ask for the resale margin report and vendor reconciliation.", weight: 2 },
    ],
  },
  {
    id: "data-centers",
    sector: "tech",
    name: "Data Centers & Cloud",
    icon: "server",
    blurb: "Colocation, hyperscale and edge facilities — power, cooling and interconnection revenue.",
    risks: ["Power/cooling cost pass-through", "Customer contract revenue (colocation + interconnect)", "Construction and fit-out capitalization", "Capacity and utilization reporting"],
    procedures: [
      "Reperform the pass-through computation (metered power at PDU vs utility invoice) for a sample of customers.",
      "Test colocation revenue: rack/circuit inventory to contracts to invoices, including cross-connects.",
      "Inspect construction/fit-out capitalization (shell vs fit-out vs customer-specific) and the in-service depreciation starts.",
      "Reconcile PUE (power usage effectiveness) reporting and energy contracts (hedged tariffs) to cost.",
      "Test the customer churn/renewal analytics and right-to-use capacity commitments.",
      "Inquire of operations: how are remote hands / smart hands service orders priced, approved and billed?",
    ],
    questions: [
      { id: "dct-01", domain: "control-activities", q: "Is customer power billing driven by independently-metered usage (PDU/RPP meters) reconciled to utility invoices monthly, with pass-through rates per contract enforced?", hint: "Power is both the top cost and a billed line. Ask for the meter-to-invoice reconciliation and loss factor treatment.", weight: 3, critical: true },
      { id: "dct-02", domain: "control-activities", q: "Is the installed-capacity inventory (racks, kW, circuits, cross-connects) reconciled monthly between the DCIM system, contracts and billing?", hint: "Every cross-connect is recurring revenue — and often unbilled. Ask for the DCIM-to-billing reconciliation.", weight: 3, critical: true },
      { id: "dct-03", domain: "control-activities", q: "Is construction and fit-out capex governed — project-stage approvals, customer-specific vs general infrastructure split, borrowing costs — with in-service dates documented for depreciation?", hint: "Ask for the capitalization policy and a sample project's stage-gate evidence.", weight: 3 },
      { id: "dct-04", domain: "control-activities", q: "Are long-term energy contracts (fixed price, hedged volumes) tracked with onerous-contract review when market prices move?", hint: "Power contracts made onerous by market swings must hit P&L. Ask for the energy contract register and last review.", weight: 2 },
      { id: "dct-05", domain: "control-activities", q: "Are remote-hands/smart-hands service orders captured with approval (customer ticket), priced per schedule and invoiced completely?", hint: "Unbilled labour is margin bleed. Ask for the ticket-to-invoice reconciliation.", weight: 2 },
      { id: "dct-06", domain: "risk-assessment", q: "Is resilience and uptime risk managed (N+1 design, maintenance windows, single points of failure) with SLA credits accrued when availability targets are missed?", hint: "Ask for the SLA-credit accrual and the last outage's customer-impact accounting.", weight: 2 },
      { id: "dct-07", domain: "monitoring", q: "Are utilization metrics (occupied kW vs contracted, rack utilization, PUE) tracked with capacity forecasting reviewed by management?", hint: "Capacity planning is the revenue pipeline. Ask for the capacity forecast and its accuracy trend.", weight: 2 },
      { id: "dct-08", domain: "info-communication", q: "Are sustainability/ESG metrics (PUE, renewable %, water) published from metered data with governance over public disclosure?", hint: "Published ESG numbers must trace to meters. Ask for the ESG data lineage.", weight: 2 },
      { id: "dct-09", domain: "it-cyber", q: "Is physical security integrated with logical (biometric + badge + visitor escorts, CCTV retention) and are cage-to-cage customer segregation controls audited?", hint: "Ask for the last physical security audit and customer-cage access review.", weight: 2 },
      { id: "dct-10", domain: "control-activities", q: "Are property taxes, levies and utility pass-through taxes per jurisdiction computed on the right bases and reconciled?", hint: "Multi-jurisdiction facilities make utility taxes a trap. Ask who owns the levy reconciliation.", weight: 1 },
    ],
  },
  {
    id: "media-ent",
    sector: "tech",
    name: "Media, Entertainment & Gaming",
    icon: "clapperboard",
    blurb: "Studios, publishers, streamers and game companies — content economics and player accounts.",
    risks: ["Content cost capitalization and amortization", "Participant/royalty residuals", "Player deposits and in-game virtual items", "Rights licensing windows"],
    procedures: [
      "Reperform content amortization (individual-asset or portfolio) for a sample title against exploitation patterns.",
      "Test participant-residual computations to contracts and reported revenues (sample pipeline).",
      "Inspect the player-deposit liability reconciliation and refund/chargeback handling for a gaming platform.",
      "Test licensing revenue by window (theatrical → home → streaming) including holdbacks and exclusivity terms.",
      "Inspect the development-cost capitalization for a game project (technical feasibility gate) and milestone evidence.",
      "Inquire of rights management: how are music/image clearances tracked to avoid unlicensed use?",
    ],
    questions: [
      { id: "med-01", domain: "control-activities", q: "Is content cost capitalized per title (or defensible portfolio groups) and amortized on the pattern of economic consumption, with impairment triggers (performance vs expectation) reviewed each period?", hint: "Ask for the amortization model and the last title-level impairment review.", weight: 3, critical: true },
      { id: "med-02", domain: "control-activities", q: "Are participant points, residuals and royalties computed from contractual formulas applied to reported revenues, accrued monthly, and reconciled to participant statements?", hint: "Ask for the residuals accrual computation and the last guild/audit settlement.", weight: 3 },
      { id: "med-03", domain: "control-activities", q: "For gaming: are player deposits held as liabilities, virtual-item sales deferred until consumption or expiry, and refund/chargeback policies accrued — with geographic restrictions on redeemable items?", hint: "Ask for the virtual-currency liability roll-forward (issued, consumed, expired, refunded).", weight: 3, critical: true },
      { id: "med-04", domain: "control-activities", q: "Are licensing deals governed by a rights matrix (territories, windows, exclusivity, holdbacks) that billing follows automatically?", hint: "Ask for the rights-management system and how a breach of exclusivity would be detected.", weight: 2 },
      { id: "med-05", domain: "control-activities", q: "Is game/software development capitalized only after the technical-feasibility gate (per policy), with project milestone evidence and cancellation write-offs approved?", hint: "Ask for the capitalization gate memo on the latest project and any cancelled project's treatment.", weight: 2 },
      { id: "med-06", domain: "risk-assessment", q: "Are rights clearances (music, footage, images) tracked per asset used in productions to avoid infringement claims?", hint: "One uncleared song in a hit is a lawsuit. Ask for the clearance database and its reconciliation to delivered content.", weight: 2 },
      { id: "med-07", domain: "monitoring", q: "Are audience/player metrics (MAU, ARPU, engagement, churn) tracked and tied to the revenue ledger's trends, with assumptions in any user-base valuation re-based on evidence?", hint: "Ask for the metrics-to-revenue reconciliation and the cohort behaviour evidence.", weight: 2 },
      { id: "med-08", domain: "control-activities", q: "Are marketing and user-acquisition costs recognized appropriately (expense vs capitalized where amortization is demonstrably probable), with channel ROI monitored?", hint: "Ask for the UA cost policy and the last review.", weight: 2 },
      { id: "med-09", domain: "control-environment", q: "Is content compliance (age ratings, gambling-adjacent mechanics, loot-box rules by jurisdiction) assessed before release with documented sign-off?", hint: "Regulatory reclassification can kill monetization models. Ask for the jurisdiction compliance matrix.", weight: 2 },
      { id: "med-10", domain: "info-communication", q: "Are royalty/participant reporting packages reconciled to the audited financial data, and are third-party audit rights honoured (participants' right to audit)?", hint: "Ask how participant audits are handled and their latest findings.", weight: 2 },
    ],
  },
]
