import type { TocIndustry } from "./types"

/** v37 — Retail & Wholesale: high-volume, thin-margin, cash-rich. Common
 *  audit textures: POS integrity and cash handling, inventory shrinkage,
 *  gift-card and loyalty liabilities, supplier rebates and markdown
 *  provisioning. */
export const TRADE_INDUSTRIES: TocIndustry[] = [
  {
    id: "retail-stores",
    sector: "trade",
    name: "Retail (Stores)",
    icon: "store",
    blurb: "Supermarkets, chains, franchisees and mixed physical retail — POS-driven operations and DC networks.",
    risks: ["POS voids, refunds and cash theft", "Shrinkage and inventory accuracy", "Gift cards and loyalty liabilities", "Supplier rebates and listing fees"],
    procedures: [
      "Analyse POS data: void/no-sale/refund patterns by cashier and till, and inspect the exception report governance.",
      "Observe a stock count at a store and test the shrinkage accrual computation and its analysis.",
      "Reperform the gift-card/loyalty liability roll-forward (sales, redemptions, breakage) to bank/POS data.",
      "Test supplier rebate and income recognition: agreements to accrual computation to supplier statements.",
      "Trace a sample of store banking to POS takings (Z-reports) and the ledger, including cash-in-transit.",
      "Inquire of loss prevention: what analytics run on sweethearting and refund fraud, and who reviews them?",
    ],
    questions: [
      { id: "ret-01", domain: "control-activities", q: "Are POS transactions integrity-controlled — voids, discounts, refunds and no-sales require supervisor authorization and are reviewed daily by exception?", hint: "Ask for the daily exception report and who signs it. Refunds without goods returning is the classic till fraud.", weight: 3, critical: true },
      { id: "ret-02", domain: "control-activities", q: "Is store cash handled per a segregation discipline (till counts witnessed, banking reconciled to Z-reports, CIT custody logged) with daily reconciliation?", hint: "Cash reconciliation must happen same-day per till per cashier. Ask to see a week of banking reconciliations.", weight: 3, critical: true },
      { id: "ret-03", domain: "control-activities", q: "Are inventories cycle-counted with full counts on rotation, shrinkage analyzed (theft/damage/admin error) and provisions/GL adjustments approved at thresholds?", hint: "Ask for the shrinkage percentage trend and the last full-count variance approvals.", weight: 3 },
      { id: "ret-04", domain: "control-activities", q: "Is the gift-card and loyalty liability reconciled monthly (sales, redemption, expiry/breakage) with breakage assumptions reviewed annually?", hint: "Gift cards are cash received for goods later. Ask for the liability roll-forward and where unspent balances sit.", weight: 2 },
      { id: "ret-05", domain: "control-activities", q: "Are supplier rebates, listing fees and marketing contributions accrued from signed agreements and reconciled to supplier statements on receipt?", hint: "Rebates recognized late or by receipt-of-invoice distort margin. Ask for the rebate accrual model.", weight: 3 },
      { id: "ret-06", domain: "control-activities", q: "Is markdown and clearance pricing governed — approvals per depth, system-enforced, and recorded — with markdown provisioning on aged stock?", hint: "Markdown is where margin goes to die. Ask for the markdown approval matrix and the aged-stock report.", weight: 2 },
      { id: "ret-07", domain: "info-communication", q: "Are store goods-receiving and transfers documented (GRNs, transfer notes) and reconciled to the DC despatches daily?", hint: "Inter-store transfer leakage needs two-sided matching. Ask for the transfer reconciliation.", weight: 2 },
      { id: "ret-08", domain: "risk-assessment", q: "Is fraud risk at the POS and receiving dock assessed with loss-prevention analytics (cashier scorecards, receiving variances) reviewed by management?", hint: "Ask for the LP meeting minutes and the top red-flag cases investigated.", weight: 2 },
      { id: "ret-09", domain: "monitoring", q: "Are like-for-like sales, gross margin by category, stock cover and shrinkage tracked weekly with action loops?", hint: "Weekly trading reviews are the sector's heartbeat — and its monitoring control. Ask for the weekly pack.", weight: 2 },
      { id: "ret-10", domain: "control-activities", q: "Are franchisee/consignment operations (stock held, sales reported, commissions) reconciled to their POS data where we hold the stock?", hint: "If their tills report our revenue, who audits their POS? Ask for the franchise settlement reconciliation.", weight: 2 },
      { id: "ret-11", domain: "it-cyber", q: "Are POS and payment systems PCI-DSS compliant (or evidenced equivalently) with segmentation from corporate IT and incident response tested?", hint: "Card-data breaches end brands. Ask for the last PCI assessment's scope and status.", weight: 2 },
    ],
  },
  {
    id: "e-commerce",
    sector: "trade",
    name: "E-Commerce & Marketplaces",
    icon: "cart",
    blurb: "Online stores, marketplaces and D2C brands — platform revenue, fulfilment and digital payments.",
    risks: ["Gross vs net revenue (marketplace vs principal)", "Refund/chargeback liabilities", "Unfulfilled orders and deferred revenue", "Promo and coupon abuse"],
    procedures: [
      "Test principal-vs-agent analysis on a sample of revenue streams (marketplace commissions, shipping, ads) against the control criteria.",
      "Reperform the refund and chargeback accrual from historical redemption curves by payment method.",
      "Inspect the order-to-cash chain: payment gateway settlements to bank to ledger, including fees and reserves held.",
      "Test gift-card/promotional liability: issuance, redemption, expiry, and abuse monitoring.",
      "Inspect the fulfilment cut-off at period end (orders shipped vs orders recognized).",
      "Inquire of fraud/risk team: what automated controls gate payment fraud, promo abuse and account takeover?",
    ],
    questions: [
      { id: "eco-01", domain: "control-activities", q: "Is revenue split gross vs net per IFRS 15 control analysis (principal vs agent) for every stream — 1P sales, commissions, shipping, ads — with the analysis documented and re-assessed on model changes?", hint: "Marketplace commission vs 1P resale changes revenue entirely. Ask for the revenue-stream register with the P/A conclusion per stream.", weight: 3, critical: true },
      { id: "eco-02", domain: "control-activities", q: "Are payment-gateway settlements reconciled daily to orders and bank (amounts, fees, rolling reserves), with reserve releases tracked?", hint: "Gateways hold reserves and net fees — the bank statement alone lies. Ask for the gateway reconciliation file.", weight: 3, critical: true },
      { id: "eco-03", domain: "control-activities", q: "Is the refund/return liability accrued from historical return curves by category, with chargebacks provisioned separately and reconciled monthly?", hint: "Returns rates must come from data, not optimism. Ask for the return-curve study and its vintage.", weight: 3 },
      { id: "eco-04", domain: "control-activities", q: "Are promotional liabilities (coupons, store credit, loyalty points) computed with abuse monitoring, and expiries handled per policy?", hint: "Promo abuse (self-referral, stacking) burns margin invisibly. Ask for the abuse rules and the liability computation.", weight: 2 },
      { id: "eco-05", domain: "control-activities", q: "Is the order-fulfilment status reconciled to revenue cut-off at each period end (shipped vs pending), including drop-ship confirmation evidence?", hint: "Recognizing on order-not-shipment is the classic e-commerce error. Ask for the cut-off memo.", weight: 3 },
      { id: "eco-06", domain: "it-cyber", q: "Are customer accounts and payment flows protected (MFA options, velocity checks, fraud scoring) with a tested incident-response plan for data breaches?", hint: "Ask for the last fraud-chargeback trend and the incident-response test date.", weight: 2 },
      { id: "eco-07", domain: "control-activities", q: "Is sales-tax/VAT determination automated by tax engine with rates reviewed for changes, and filings reconciled to the ledger?", hint: "Multi-jurisdiction tax is a liability machine. Ask who owns the tax engine's rate table.", weight: 2 },
      { id: "eco-08", domain: "info-communication", q: "Are the platform's metrics (GMV, AOV, conversion) reconciled to the audited ledger definitions, with any investor-facing dashboard tied to the same data?", hint: "Two truths (metrics vs accounts) is an integrity breach. Ask who maps GMV definitions to revenue.", weight: 2 },
      { id: "eco-09", domain: "monitoring", q: "Are unit economics (contribution margin, CAC, fulfillment cost per order) tracked with escalation when they breach thresholds?", hint: "Growth masking negative contribution is the sector's tombstone. Ask for the unit-economics report.", weight: 2 },
      { id: "eco-10", domain: "control-activities", q: "Is vendor/drop-shipper inventory (where we sell before we own) identified with title-transfer terms mapped and reflected in cut-off?", hint: "Drop-ship title terms decide both inventory and liability cut-off. Ask for the drop-ship terms summary.", weight: 2 },
    ],
  },
  {
    id: "wholesale",
    sector: "trade",
    name: "Wholesale & Distribution",
    icon: "warehouse",
    blurb: "Importers, distributors and cash-and-carry operators selling to trade customers on credit terms.",
    risks: ["Credit control and receivables quality", "Rebates and volume discounts", "Warehouse inventory accuracy", "Diversion and grey-market sales"],
    procedures: [
      "Test the credit-control workflow: new-customer approvals, limit setting, blocked-order release authority.",
      "Reperform the volume-rebate accrual for top customers from the tiered agreements against YTD sales.",
      "Observe a warehouse cycle-count programme and test adjustment approvals.",
      "Sample the sales-returns process: credit notes to original invoices, goods received back, and inspection evidence.",
      "Test gross-margin analytics by SKU/customer for outlier pricing (possible kickbacks or diversion).",
      "Inquire of sales management: how are exclusivity/territory terms monitored for diversion breaches?",
    ],
    questions: [
      { id: "who-01", domain: "control-activities", q: "Are customer credit limits set from a documented credit assessment, enforced automatically at order entry, with blocked-order releases restricted to named authority?", hint: "Whoever can release a blocked order owns the credit risk. Ask for the release log and its approvals.", weight: 3, critical: true },
      { id: "who-02", domain: "control-activities", q: "Are volume rebates, retrospective discounts and price protection accrued monthly from agreements (not when claimed), with year-end true-ups evidenced?", hint: "Ask for the rebate accrual computation for the top customer and the agreement it came from.", weight: 3, critical: true },
      { id: "who-03", domain: "control-activities", q: "Is warehouse inventory cycle-counted on a published programme with accuracy targets, investigations and approved adjustments?", hint: "Ask for the cycle-count calendar, hit-rate, and who approves adjustments — and the last month's adjustment value.", weight: 3 },
      { id: "who-04", domain: "control-activities", q: "Are sales returns controlled — RMA authorization, goods receipt and inspection, credit approval — with returns analytics by customer?", hint: "Credit notes without goods returning are theft's best friend. Ask for the credit-note approval file.", weight: 2 },
      { id: "who-05", domain: "monitoring", q: "Is gross margin analyzed by product and customer with outlier investigation (negative or abnormally low margins)?", hint: "A customer buying consistently below floor price is either a diversion channel or a kickback. Ask for the margin-outlier report.", weight: 3 },
      { id: "who-06", domain: "control-activities", q: "Are slow-moving, dated and damaged stocks identified monthly with provisioning at NRV and write-off approvals per threshold?", hint: "Distribution stock ages fast. Ask for the ageing buckets and the provision policy.", weight: 2 },
      { id: "who-07", domain: "risk-assessment", q: "Is supplier/manufacturer dependence (exclusive territories, quota, brand risk) assessed with the distributorship agreements' compliance monitored?", hint: "Losing a principal franchise is a going-concern event. Ask for the key-agreements register and expiry horizon.", weight: 2 },
      { id: "who-08", domain: "control-activities", q: "Are imports and the associated costs (freight, duty, clearance) accumulated into inventory cost, with customs valuations reviewed?", hint: "Landed-cost completeness is the inventory-valuation half of the business. Ask for the landed-cost model check.", weight: 2 },
      { id: "who-09", domain: "info-communication", q: "Is the sales-order-to-invoice chain (price list, contract price, invoice) automatically enforced with manual price overrides logged and approved?", hint: "Manual price overrides are the diversion door. Ask for the override report and its review.", weight: 3 },
      { id: "who-10", domain: "control-activities", q: "Are warehouse expense recoveries (customer co-op marketing, slotting) documented in agreements and reconciled to spend evidence?", hint: "Undocumented trade-spend leak is unrecorded expense. Ask for the co-op marketing reconciliation.", weight: 2 },
    ],
  },
]
