import type { TocIndustry } from "./types"

/** v37 — Manufacturing: physical transformation of inputs into product.
 *  Common audit textures: inventory existence and costing (IAS 2), WIP and
 *  overhead absorption, standard-cost variances, warranty provisions,
 *  capex capitalization, and shop-floor payroll. */
export const MANUFACTURING_INDUSTRIES: TocIndustry[] = [
  {
    id: "discrete-mfg",
    sector: "manufacturing",
    name: "Discrete Manufacturing",
    icon: "factory",
    blurb: "Machines, equipment, furniture, components — job shops, make-to-order and serial production plants.",
    risks: ["WIP valuation and overhead absorption", "Scrap and rework leakage", "Standard-cost variances", "Warranty provisions"],
    procedures: [
      "Observe a period-end physical inventory count at the WIP stage and test the cut-off of jobs in process.",
      "Reperform the overhead-absorption rate (budgeted overhead / budgeted hours) for one cost pool and its application.",
      "Inspect the standard-cost roll and its variance postings for the year, including who approves standards changes.",
      "Trace a sample of warranty claims to the provision computation and test the historical-claims assumption.",
      "Test scrap: weigh/measure scrap sales proceeds to the ledger and reconcile to production reports.",
      "Inquire of production planners: how are job status and progress (percent complete) evidenced for finance?",
    ],
    questions: [
      { id: "mfg-01", domain: "control-activities", q: "Are raw-material, WIP and finished-goods inventories physically counted at least annually under documented instructions (blind counts, second counts, cut-off control)?", hint: "Ask for the count instructions and the last count file: blind count sheets? recounts signed? cut-off tags at receiving/shipping?", weight: 3, critical: true },
      { id: "mfg-02", domain: "control-activities", q: "Is the perpetual inventory record reconciled to the general ledger monthly, with adjustments above thresholds investigated and approved?", hint: "The bridge between warehouse and finance is where shrinkage hides. Ask for the last three monthly reconciliations and the adjustment log.", weight: 3, critical: true },
      { id: "mfg-03", domain: "control-activities", q: "Are overhead rates computed from a documented annual budget and applied to WIP systematically, with variances reviewed monthly?", hint: "Over-absorption flatters margin; under-absorption hides idle capacity. Ask who recomputes rates and when.", weight: 3 },
      { id: "mfg-04", domain: "control-activities", q: "Is scrap and rework recorded, valued and either stored under custody or sold through approved channels?", hint: "Scrap sold to a cousin's yard at friendly prices is a classic. Ask for the scrap sales log and pricing evidence.", weight: 2 },
      { id: "mfg-05", domain: "control-activities", q: "Are standard costs reviewed and updated at least annually, with changes approved by finance (not just production or purchasing)?", hint: "Stale standards distort COGS and inventory. Probe who owns the standard roll and the last update evidence.", weight: 2 },
      { id: "mfg-06", domain: "control-activities", q: "Is warranty provision based on historical claims experience or engineering estimates, computed monthly and reviewed by finance?", hint: "Ask for the provision model and its back-test: did last year's provision cover actual claims?", weight: 2 },
      { id: "mfg-07", domain: "control-activities", q: "Are tooling, molds and dies tracked in a register with custody, maintenance and retirement decisions approved?", hint: "Tooling is expensive, portable and easily 'retired'. Ask for the register and the last disposal approval.", weight: 1 },
      { id: "mfg-08", domain: "control-activities", q: "Is production payroll (piece rates, overtime, shift premiums) computed from approved production data and time records, with anomaly review?", hint: "Ghost shifts and inflated piece-rates: reconcile direct-labour hours to machine hours or output for reasonableness.", weight: 2 },
      { id: "mfg-09", domain: "risk-assessment", q: "Is supplier concentration and single-source risk assessed, with qualified alternates for critical components?", hint: "One bankrupt supplier stops the line — a going-concern and disclosure issue. Ask for the critical-parts list and alternates.", weight: 1 },
      { id: "mfg-10", domain: "monitoring", q: "Are yield, first-pass-quality and rework percentages tracked to targets with corrective action when they drift?", hint: "Quality metrics feed warranty and inventory valuation. Ask who reviews the quality dashboard.", weight: 2 },
      { id: "mfg-11", domain: "control-activities", q: "Is capitalization of machinery and its installation/commissioning costs separated from repairs, with a capitalization policy and threshold applied consistently?", hint: "The capitalization policy is a judgement line that moves profit. Ask for the policy and one borderline case's treatment.", weight: 2 },
      { id: "mfg-12", domain: "info-communication", q: "Does the production planning system feed actual output and scrap data to finance daily, so inventory and cost of sales reflect the shop floor rather than month-end estimates?", hint: "Ask how finance learns about a halted line or an emergency rework — if the answer is 'at month-end', the ledger lags reality.", weight: 2 },
      { id: "mfg-13", domain: "it-cyber", q: "Are changes to the ERP's bills of material, routings and standard costs controlled through change management with maker-checker approval?", hint: "A quiet BOM change rewrites COGS silently. Ask for the change log and who reviews it.", weight: 2 },
    ],
  },
  {
    id: "food-beverage",
    sector: "manufacturing",
    name: "Food & Beverage Processing",
    icon: "utensils",
    blurb: "Dairies, mills, beverage bottlers, packaged-food plants — perishable inventory, batch traceability and heavy regulation.",
    risks: ["Batch traceability and recall", "Perishable inventory and obsolescence", "Food-safety compliance (HACCP)", "Commodity input price risk"],
    procedures: [
      "Inspect HACCP monitoring records ( CCP logs, temperature charts) for a sample month for completeness of signatures.",
      "Reperform the obsolescence provision: FEFO ageing of finished goods, trade returns, and expected-waste factors.",
      "Trace one batch end-to-end: raw lot in → production batch → distribution → invoice (traceability test).",
      "Test commodity hedging: inspect the hedge documentation and effectiveness for a sample of contracts.",
      "Observe a physical stock count in cold storage including the thermometer/calibration evidence.",
      "Inquire of QA: how is a recall rehearsed and how fast could a lot be pulled from trade?",
    ],
    questions: [
      { id: "fnb-01", domain: "control-activities", q: "Is every batch traceable one-up and one-down (raw lot → batch → customer), with the traceability tested at least annually?", hint: "Ask for the last mock-recall and the hours it took. Regulators expect hours, not days.", weight: 3, critical: true },
      { id: "fnb-02", domain: "control-activities", q: "Are HACCP/food-safety critical control points monitored with signed records, independent verification, and corrective actions when limits are breached?", hint: "Look for signed CCP logs with real values (not ticks) and a deviation file. Pencil-whipped logs are common.", weight: 3, critical: true },
      { id: "fnb-03", domain: "control-activities", q: "Is perishable inventory managed FEFO with expiry-date tracking, and is obsolescence provided from the ageing report monthly?", hint: "Expired stock on the books at cost is an IAS 2 violation and a profit balloon. Ask for the expiry report and the last provision.", weight: 3 },
      { id: "fnb-04", domain: "control-activities", q: "Are production yields (raw → finished) tracked by product line with loss analysis beyond normal shrinkage?", hint: "Yield leakage can be theft, mismeasurement or recipe drift. Ask what yield triggers investigation.", weight: 2 },
      { id: "fnb-05", domain: "risk-assessment", q: "Is commodity price risk (wheat, milk, sugar, packaging) identified with a hedging or pass-through strategy approved by the board?", hint: "Unhedged input spikes wreck margin and covenants. Ask for the policy and last review.", weight: 2 },
      { id: "fnb-06", domain: "control-activities", q: "Are trade returns and rework captured, credited to customers properly, and either destroyed under supervision or reprocessed with records?", hint: "The returns bay is a known theft channel — product 'destroyed' that reappears in the market. Ask for the destruction certificate process.", weight: 2 },
      { id: "fnb-07", domain: "info-communication", q: "Are customer complaints logged, categorized (foreign matter, quality, illness) and escalated to QA and finance for provision/disclosure?", hint: "Illness complaints can be litigation and disclosure events. Ask who reads the complaints log monthly.", weight: 2 },
      { id: "fnb-08", domain: "control-activities", q: "Is water, energy and refrigeration consumption tracked against production volumes with anomalies investigated?", hint: "Cold-chain energy per tonne is a strong integrity signal; tampering with storage conditions shows here first.", weight: 1 },
      { id: "fnb-09", domain: "control-environment", q: "Are regulatory inspections (food safety, weights & measures) responded to with findings tracked to closure, including labeling compliance?", hint: "Labeling errors trigger recalls. Ask for the last inspection findings and their closure evidence.", weight: 2 },
      { id: "fnb-10", domain: "monitoring", q: "Is giveaway (overfill) and underfill monitored against legal metrology limits with scale calibration current?", hint: "Overfill is margin loss; underfill is a legal violation. Ask for the fill-control charts.", weight: 2 },
      { id: "fnb-11", domain: "control-activities", q: "Are recipes/BOMs access-controlled in the ERP, with changes approved by QA and production jointly?", hint: "BOM changes alter COGS silently. Ask who can edit a BOM and what evidence QA signs.", weight: 2 },
    ],
  },
  {
    id: "pharma",
    sector: "manufacturing",
    name: "Pharmaceuticals & Life Sciences",
    icon: "pill",
    blurb: "Drug substance and product manufacturers, CDMOs and medical-device makers under GMP regulation.",
    risks: ["GMP/data-integrity compliance", "Batch release controls", "R&D capitalization and milestones", "Returns, recalls and expiry"],
    procedures: [
      "Inspect the last regulatory (GMP) inspection report and remediation evidence for open findings.",
      "Test data integrity: audit trails on chromatography systems, ALCOA+ review by QA, samples of raw data to reported results.",
      "Reperform the inventory expiry analysis (dead-stock and expiring within 12 months) against the obsolescence provision.",
      "Trace one batch record through release (QPs signature), distribution and revenue recognition.",
      "Inspect R&D project files for the capitalization gate (development criteria) and stage-gate approvals.",
      "Inquire of QA: who can release a batch, and is that power independent of production pressure?",
    ],
    questions: [
      { id: "phr-01", domain: "control-activities", q: "Is batch release performed by Qualified Persons/QA independent of production, with documented review of the full batch record?", hint: "Release under production pressure is the industry's cardinal sin. Ask who signs and whether they report outside production.", weight: 3, critical: true },
      { id: "phr-02", domain: "it-cyber", q: "Is GMP data integrity managed — audit trails enabled, reviewed, and access to raw data restricted (ALCOA+)?", hint: "Ask for a chromatography audit-trail review record. Disabled or never-reviewed audit trails are a 483/critical-finding classic.", weight: 3, critical: true },
      { id: "phr-03", domain: "control-environment", q: "Are regulatory inspection findings (FDA 483s, EMEA GMP non-compliance) logged with CAPA tracked to verified closure?", hint: "Open CAPAs past due are a compliance and disclosure risk. Ask for the CAPA log and overdue count.", weight: 3 },
      { id: "phr-04", domain: "control-activities", q: "Is expiry-dated inventory managed with monthly ageing, quarantine of expired stock, and an obsolescence provision that reflects realistic disposal?", hint: "Slow-moving SKUs at full cost inflate assets. Ask for the last expiry report vs provision.", weight: 2 },
      { id: "phr-05", domain: "risk-assessment", q: "Is R&D spend split research vs development against IAS 38 criteria, with stage-gate evidence for capitalization decisions?", hint: "Capitalization gates are judgement-heavy. Ask for the policy and one project's stage-gate file.", weight: 2 },
      { id: "phr-06", domain: "control-activities", q: "Are product returns and recalls controlled — identification, segregation, destruction or rework decisions documented — with credits authorized?", hint: "Recalled product re-entering the grey market is both a safety crime and an accounting exposure.", weight: 2 },
      { id: "phr-07", domain: "control-activities", q: "Are promotion, rebate and chargeback agreements with distributors/pharma customers computed from verified sell-through data and accrued monthly?", hint: "Revenue gross vs net and rebate accruals are the revenue-recognition battleground. Ask who verifies the data behind rebate invoices.", weight: 3 },
      { id: "phr-08", domain: "control-environment", q: "Is there a pharmacovigilance process with adverse-event capture feeding legal-provision assessment?", hint: "Litigation provisions from adverse events need the PV database. Ask how legal and finance exchange information.", weight: 2 },
      { id: "phr-09", domain: "info-communication", q: "Are serialization/track-and-trace (DSCSA, FMD) systems reconciled to distribution and sales records?", hint: "Serialization is now a legal chain-of-custody. Ask for the last reconciliation or alert-handling report.", weight: 2 },
      { id: "phr-10", domain: "control-activities", q: "Is reference/retention sample storage controlled (environmental monitoring, access log) as GMP requires?", hint: "Retained samples are legal evidence; casual storage is a finding.", weight: 1 },
      { id: "phr-11", domain: "monitoring", q: "Are deviation and out-of-specification rates trended with quality-management review at management level?", hint: "Rising OOT/OOS trends precede big failures. Ask for the quality metrics pack.", weight: 2 },
    ],
  },
  {
    id: "chemicals",
    sector: "manufacturing",
    name: "Chemicals & Plastics",
    icon: "flask",
    blurb: "Basic and specialty chemicals, resins, fertilizers, paints and plastics converters.",
    risks: ["Process safety (Seveso/PSM)", "Environmental liabilities", "Hazardous inventory measurement", "Bulk custody transfer"],
    procedures: [
      "Inspect the process-safety management audits and the closure status of findings.",
      "Observe a bulk tank gauging and reconcile the tank strapping table and temperature corrections to the custody meter.",
      "Reperform the environmental provision (emissions, remediation) from permits and monitoring data.",
      "Test reagent/intermediate consumption vs production for completeness (mass-balance test).",
      "Inspect the transport/dangerous-goods documentation chain for a sample of shipments.",
      "Inquire who can override a batch specification and what QA evidence is required.",
    ],
    questions: [
      { id: "chm-01", domain: "control-activities", q: "Are bulk inventories (tanks, silos) measured by calibrated gauges or weighbridges with temperature/SG corrections, and reconciled monthly to the ledger?", hint: "Tank measurement is the inventory basis. Ask for calibration certificates and the last mass-balance reconciliation.", weight: 3, critical: true },
      { id: "chm-02", domain: "risk-assessment", q: "Is process safety (hazards studies, safety-instrumented systems testing, permits) managed on a schedule with management review?", hint: "A runaway reaction is existential. Ask for the HAZOP review cycle and SIS proof-test records.", weight: 3, critical: true },
      { id: "chm-03", domain: "control-activities", q: "Are environmental obligations (emissions, effluent, remediation) identified from permits, monitored, and accrued/provided for in the accounts?", hint: "Ask for the permit register and the last environmental provision computation.", weight: 3 },
      { id: "chm-04", domain: "control-activities", q: "Are dangerous-goods shipments documented (transport classification, placarding, manifests) and reconciled to sales?", hint: "Regulatory duty and completeness of despatch in one control. Missing manifests = missing revenue or compliance breach.", weight: 2 },
      { id: "chm-05", domain: "control-activities", q: "Is batch quality control enforced — release against specification by QA with authority to block and disposition (regrade/blend/destroy) documented?", hint: "Who can ship off-spec product to a friendly customer at full price? Ask for the disposition log.", weight: 2 },
      { id: "chm-06", domain: "control-activities", q: "Is raw-material consumption reconciled to production mass balances, with unexplained losses investigated?", hint: "Chemistry obeys stoichiometry: material in vs out should close. Ask for the mass-balance report and loss thresholds.", weight: 2 },
      { id: "chm-07", domain: "risk-assessment", q: "Is product-stewardship and regulatory status (REACH, TSCA registrations) tracked with compliance evidence per substance?", hint: "Registration loss kills a product line. Ask who owns the substance compliance register.", weight: 2 },
      { id: "chm-08", domain: "control-activities", q: "Are high-value catalysts, precious metals and additives under special custody with lifecycle tracking?", hint: "Precious-metal catalysts are embezzlement targets. Ask for the catalyst register and recovery records.", weight: 2 },
      { id: "chm-09", domain: "monitoring", q: "Are plant utilization, yield and first-quality rates tracked against plan with monthly operations review?", hint: "Off-spec production parked in 'work in process' is a common inventory overstatement.", weight: 2 },
      { id: "chm-10", domain: "info-communication", q: "Is the manufacturing execution system (MES) / lab system integrated or reconciled to the ERP, with batch data locked after period close?", hint: "Post-close edits to batch data rewrite COGS. Ask about change control on MES records.", weight: 2 },
    ],
  },
  {
    id: "automotive",
    sector: "manufacturing",
    name: "Automotive & Parts",
    icon: "car",
    blurb: "Vehicle assembly and the tier-1/2 component supply chain — JIT flows, tooling and PPAP launches.",
    risks: ["Warranty and recalls", "Tooling ownership and capitalization", "PPAP/launch cost controls", "Volume-rebate and pricing-back claims with OEMs"],
    procedures: [
      "Reperform the warranty provision: claims history by part, plant and model against the recorded liability.",
      "Inspect customer-owned vs supplier-owned tooling registers and their contractual treatment.",
      "Trace launch (PPAP) costs to the capitalization policy and sample pre-production builds charged to P&L or assets.",
      "Test a sample of OEM price-claim-backs and annual volume rebates to agreements and settlement statements.",
      "Observe a shipping-dock audit for ASN cut-off at period end.",
      "Inquire of program managers: how is a launch delay's cost (idle labour, premium freight) captured?",
    ],
    questions: [
      { id: "aut-01", domain: "control-activities", q: "Is the warranty provision computed from actual claims history and engineering data (failure rates, cost per repair), reviewed quarterly against claims run-rate?", hint: "Ask for the provision model and its back-cast. Systematic under-provisioning of warranty is a classic earnings tool.", weight: 3, critical: true },
      { id: "aut-02", domain: "control-activities", q: "Are recalls and field actions identified, costed (parts, labour, logistics) and accrued when the obligation arises — with disclosure triggers mapped?", hint: "Ask for the last field action and how fast finance got the cost estimate.", weight: 3 },
      { id: "aut-03", domain: "control-activities", q: "Is tooling (customer-owned and supplier-owned) tracked in registers reconciled to the balance sheet, with ownership evidence in contracts?", hint: "OEM-owned tooling is not your asset; supplier-owned tooling often is. Mismatches misstate both sides.", weight: 2 },
      { id: "aut-04", domain: "control-activities", q: "Are price-down obligations to OEMs and volume rebates accrued from agreements as sales occur, with quarterly true-ups evidenced?", hint: "Annual retrospective rebates must be accrued as the year's sales build. Ask who computes the run-rate and from what volumes.", weight: 3 },
      { id: "aut-05", domain: "control-activities", q: "Is shipping cut-off controlled at period end (ASN, freight documents, Incoterms) and reconciled between the plant and finance?", hint: "One day of despatch error swings a quarter. Ask for the last cut-off memo and its checks.", weight: 2 },
      { id: "aut-06", domain: "control-activities", q: "Are launch/PPAP costs tracked per programme against budget, with accounting treatment (expensed vs capitalized assets) decided by policy?", hint: "Launch spend is easy to bury in inventory. Ask for the programme cost report.", weight: 2 },
      { id: "aut-07", domain: "risk-assessment", q: "Is customer concentration and platform-dependence assessed, with single-customer loss modelled in going-concern analysis?", hint: "A lost platform is a plant closure. Ask for the revenue concentration table.", weight: 2 },
      { id: "aut-08", domain: "control-activities", q: "Is premium freight (expedited logistics) authorized, tracked and analyzed monthly as a symptom metric?", hint: "Rising premium freight flags broken processes — and hides cost that belongs in root-cause fixes.", weight: 1 },
      { id: "aut-09", domain: "monitoring", q: "Are quality PPM (defective parts per million) and OEM scorecards reviewed by management with corrective plans?", hint: "Scorecard failure leads to loss of business and the 8D claims that follow. Ask for the scorecard file.", weight: 2 },
      { id: "aut-10", domain: "it-cyber", q: "Is EDI with OEMs (forecast, release, billing) reconciled to the ERP, with monitoring of schedule-change anomalies?", hint: "EDI is the blood supply; unreconciled EDI = phantom inventory. Ask who monitors the EDI error queue.", weight: 2 },
      { id: "aut-11", domain: "control-activities", q: "Is consignment stock at customer/OEM sites identified, counted and reconciled monthly, with revenue recognized on draw?", hint: "Consignment blur = revenue timing errors. Ask for the consignment agreement and the last statement reconciliation.", weight: 3 },
    ],
  },
  {
    id: "textile-apparel",
    sector: "manufacturing",
    name: "Textile & Apparel",
    icon: "shirt",
    blurb: "Spinners, weavers, dyers, garment factories and cut-make-trim contractors serving brands and retailers.",
    risks: ["Licensed/subcontracted production", "Slow-moving fashion inventory", "Cotton/commodity sourcing", "Customer chargebacks"],
    procedures: [
      "Inspect the subcontracting approval file: brand consents, capability checks, and the audit trail of orders farmed out.",
      "Reperform the finished-goods ageing and the markdown/obsolescence provision against last season's actual sell-through.",
      "Test a sample of customer chargebacks (late delivery, quality) to contracts and evidence of acceptance.",
      "Observe a fabric roll count and reconcile meters to the cutting-room reports (fabric utilization).",
      "Trace commissioned/licensed production inputs to the licensed operator's records (where our capital sits in someone else's factory).",
      "Inquire of merchandisers: who decides a quality B-grade lot's customer and price?",
    ],
    questions: [
      { id: "txt-01", domain: "control-activities", q: "Is subcontracting of production controlled — brand approval where required, approved factory lists, and traceability of farmed-out orders?", hint: "Unauthorized subcontracting breaches compliance (and headlines). Ask for the approved-subcontractor list and consent evidence.", weight: 3, critical: true },
      { id: "txt-02", domain: "control-activities", q: "Is finished-goods ageing reviewed monthly with markdown/obsolescence provisions for past-season stock based on expected sell-through?", hint: "Last season's styles at cost is a fiction. Ask for the ageing report and the markdown model.", weight: 3, critical: true },
      { id: "txt-03", domain: "control-activities", q: "Are fabric and trim inventories counted (rolls, kg, meters) and reconciled to cutting-room consumption and the ledger?", hint: "Fabric utilization reports (marker efficiency) are the completeness check. Ask for the last utilization report.", weight: 2 },
      { id: "txt-04", domain: "control-activities", q: "Is commissioned production (our material in a CMT factory) tracked: inputs issued, output received, wastage limits enforced?", hint: "Material out, fewer garments back — the leakage is invisible without issue/receipt reconciliation. Ask for the CMT ledger.", weight: 2 },
      { id: "txt-05", domain: "control-activities", q: "Are customer chargebacks (quality, late delivery, compliance) validated against the contract before acceptance and accrued monthly?", hint: "Brands apply chargebacks aggressively; unchallenged acceptance is money given away. Ask who disputes them.", weight: 2 },
      { id: "txt-06", domain: "control-activities", q: "Are second-grade / B-class lots identified, segregated, and sold only through authorized channels with pricing approval?", hint: "B-grade sold at 'friendly' discounts is a kickback channel. Ask for the B-grade sales log.", weight: 2 },
      { id: "txt-07", domain: "risk-assessment", q: "Is cotton/yarn price risk managed (forward buying, contracts) and its accounting (hedge or embedded derivative) considered with finance?", hint: "Commodity swings hit gross margin fast. Ask for the sourcing policy and last season's price variance.", weight: 2 },
      { id: "txt-08", domain: "control-environment", q: "Are social-compliance audits (customer codes of conduct) maintained with corrective action plans tracked to closure?", hint: "Failed social audits cancel orders and trigger customer exit clauses. Ask for the open CAP list.", weight: 2 },
      { id: "txt-09", domain: "monitoring", q: "Are order-book margins tracked by style/customer at order intake, with cancellation of loss-making styles escalated?", hint: "Fashion's loss is decided at order placement. Ask for the order-margin gate.", weight: 2 },
      { id: "txt-10", domain: "control-activities", q: "Is cut-and-sew payroll (piece rates) computed from approved production tickets with reconciliation to output shipped?", hint: "Piece-rate tickets are the payroll base; inflated tickets = payroll fraud + cost distortion.", weight: 2 },
    ],
  },
  {
    id: "electronics",
    sector: "manufacturing",
    name: "Electronics & Semiconductors",
    icon: "cpu",
    blurb: "PCB assembly, contract electronics manufacturing, semiconductor device and module makers.",
    risks: ["Component obsolescence and price volatility", "Consignment and vendor-managed inventory", "Yield/quality cost accounting", "Export controls and IP protection"],
    procedures: [
      "Reperform the excess-and-obsolete inventory computation (demand look-up, last-time-buy exposures) and its provision.",
      "Inspect consignment/VMI agreements and the monthly stock statements exchanged with partners.",
      "Trace a sample of engineering-change-order (ECO) costs to the accounting treatment.",
      "Test export-control screening (denied-party, license determination) on a sample of international shipments.",
      "Observe the secure storage of high-value components (tapes, trays) and the access log.",
      "Reconcile the shop-floor kitting transactions to the ERP material issues for a sample of work orders.",
    ],
    questions: [
      { id: "ele-01", domain: "control-activities", q: "Is component inventory subject to a monthly excess & obsolescence review (demand netting, lifecycle status) with provisions approved by finance?", hint: "Electronic components age like milk. Ask for the E&O report and how demand forecasts feed it.", weight: 3, critical: true },
      { id: "ele-02", domain: "control-activities", q: "Is consignment and vendor-managed inventory (ours at customers, suppliers' at our site) identified, counted, statement-reconciled monthly, and correctly owned on the balance sheet?", hint: "VMI confusion double-counts inventory. Ask for the consignment map and last statements.", weight: 2 },
      { id: "ele-03", domain: "control-activities", q: "Are high-value, portable components (chips, memory) under access-controlled storage with CCTV and issue logs?", hint: "Memory chips are cash-equivalent and globally fenced. Ask for the cage access log and the last cycle count.", weight: 3 },
      { id: "ele-04", domain: "control-activities", q: "Are engineering-change-order costs captured to programmes and classified (R&D vs cost of programmes) per policy?", hint: "ECOs blur NRE, warranty and customer-recovery accounting. Ask for the ECO log and treatment.", weight: 2 },
      { id: "ele-05", domain: "risk-assessment", q: "Is export-control compliance (dual-use screening, denied-party lists, licences) embedded in the order-to-ship flow?", hint: "A single unscreened shipment can bring penalties. Ask who owns screening and the last audit.", weight: 2 },
      { id: "ele-06", domain: "control-activities", q: "Are yields and test escapes tracked by product, with failure analysis feeding warranty and reliability reserves?", hint: "Field failures surface quarters later; reserves must anticipate. Ask for the reliability model.", weight: 2 },
      { id: "ele-07", domain: "info-communication", q: "Is shop-floor kitting and backflushing reconciled to the ERP with error queues cleared daily?", hint: "Backflushing errors create phantom inventory that surfaces at count time. Ask who clears the error log and how fast.", weight: 2 },
      { id: "ele-08", domain: "it-cyber", q: "Are customer designs, test programs and IP under access control with NDA governance and exfiltration monitoring?", hint: "IP theft is the industry's quiet loss. Ask for the design-data access review.", weight: 2 },
      { id: "ele-09", domain: "control-activities", q: "Are returns/RMA flows controlled: authorization, root-cause coding, disposition (scrap/refurb/repackage), and credit approval?", hint: "RMAs are both a returns-fraud channel and a quality signal. Ask for the RMA log and disposition evidence.", weight: 2 },
      { id: "ele-10", domain: "monitoring", q: "Are on-time delivery and quality PPM tracked per customer with escalation before scorecard failure?", hint: "Scorecards drive allocation of scarce demand. Ask for the OTD report.", weight: 1 },
    ],
  },
]
