/** v22–v25 — previous-exam papers (ACCA + IFRS diploma + Egyptian) for the
 *  Exam Center.
 *
 *  Full past papers are adapted for AuditEdge in past-paper STYLE of the
 *  named professional exams (scenario MCQs, 2-mark single-topic items,
 *  examiner-style distractors). Each paper maps to a fixed slice of the
 *  bank via its `source` label, sits under a timed session and feeds the
 *  same results / mistakes / spaced-repetition machinery as any exam.
 *
 *  v24 — the whole ACCA syllabus is covered: every Applied Knowledge,
 *  Applied Skills and Strategic Professional paper (BT, MA, FA, LW, PM,
 *  TX, FR, AA, FM, SBL, SBR, AFM, APM, ATX, AAA) plus the Egyptian
 *  state-sector paper.
 *
 *  v25 — FIVE YEARS OF PAPERS PER EXAM: every family gains four dated
 *  sittings (Dec 2021, June 2022, Sept 2023, June 2024) generated by the
 *  v25 seed (scripts/seed/v25), on top of its flagship paper. A brand-new
 *  findable "IFRS diploma" family (DipIFR style) ships its own flagship
 *  (24 questions) + the four dated sittings — so an "IFRS exam" is now
 *  impossible to miss. `group` drives the grouped papers grid.
 *
 *  v26 — PAST PAPERS FOR EVERY COURSE TRACK: six new families join the 17 —
 *  CPA AUD / FAR / REG, CFA Level I, and CMA Part 1 & Part 2 — each with
 *  its own 24-question flagship plus the four dated sittings (seeded by
 *  scripts/seed/v26). Every track you can study now has an exam shelf. */

import type { BankArea } from "@/lib/exam-blueprint"

export type PaperGroup = "ifrs" | "knowledge" | "skills" | "strategic" | "egypt" | "cpa" | "cfa" | "cma"

export type PastPaper = {
  id: string
  titleEn: string
  titleAr: string
  /** body label shown on the card */
  body: string
  area: BankArea
  /** BankQuestion.source filter that selects this paper's questions */
  source: string
  count: number
  durationMin: number
  difficulty: 1 | 2 | 3
  /** v24 — syllabus level the paper belongs to (grouped UI) */
  group: PaperGroup
  blurbEn: string
  blurbAr: string
}

export const PAPER_GROUPS: { id: PaperGroup; labelEn: string; labelAr: string }[] = [
  { id: "ifrs", labelEn: "IFRS diploma — DipIFR style", labelAr: "دبلومة IFRS — بنمط DipIFR" },
  { id: "knowledge", labelEn: "ACCA — Applied Knowledge", labelAr: "ACCA — المستوى المعرفي" },
  { id: "skills", labelEn: "ACCA — Applied Skills", labelAr: "ACCA — المستوى المهاري" },
  { id: "strategic", labelEn: "ACCA — Strategic Professional", labelAr: "ACCA — المستوى الاستراتيجي" },
  { id: "egypt", labelEn: "Egyptian practice", labelAr: "التطبيق المصري" },
  // v26 — past papers for every course track ("like CPA and CFA for example")
  { id: "cpa", labelEn: "CPA — AUD · FAR · REG", labelAr: "CPA — المراجعة والمحاسبة والتنظيم" },
  { id: "cfa", labelEn: "CFA — Level I", labelAr: "CFA — المستوى الأول" },
  { id: "cma", labelEn: "CMA — Part 1 & Part 2", labelAr: "CMA — الجزءان الأول والثاني" },
]

/* ---------------- family table (v25) ---------------- */

type FamilyDef = {
  /** flagship paper id */
  flagship: string
  /** family id base for dated sittings */
  base: string
  titleEn: string
  titleAr: string
  body: string
  area: BankArea
  sourceLabel: string
  group: PaperGroup
  difficulty: 1 | 2 | 3
  /** dated-sitting question count (default 18; APM 15) */
  sittingCount?: number
}

const FAMILIES: FamilyDef[] = [
  { flagship: "acca-bt", base: "acca-bt", titleEn: "Business & Technology (BT)", titleAr: "الأعمال والتكنولوجيا (BT)", body: "ACCA BT style", area: "accounting", sourceLabel: "ACCA BT past paper", group: "knowledge", difficulty: 1 },
  { flagship: "acca-ma", base: "acca-ma", titleEn: "Management Accounting (MA)", titleAr: "المحاسبة الإدارية (MA)", body: "ACCA MA style", area: "accounting", sourceLabel: "ACCA MA past paper", group: "knowledge", difficulty: 1 },
  { flagship: "acca-fa", base: "acca-fa", titleEn: "Financial Accounting (FA)", titleAr: "المحاسبة المالية (FA)", body: "ACCA FA style", area: "accounting", sourceLabel: "ACCA FA past paper", group: "knowledge", difficulty: 1 },
  { flagship: "acca-lw", base: "acca-lw", titleEn: "Corporate & Business Law (LW)", titleAr: "قانون الشركات والأعمال (LW)", body: "ACCA LW style", area: "ethics", sourceLabel: "ACCA LW past paper", group: "skills", difficulty: 2 },
  { flagship: "acca-pm", base: "acca-pm", titleEn: "Performance Management (PM)", titleAr: "إدارة الأداء (PM)", body: "ACCA PM style", area: "accounting", sourceLabel: "ACCA PM past paper", group: "skills", difficulty: 2 },
  { flagship: "acca-tx", base: "acca-tx", titleEn: "Taxation (TX)", titleAr: "الضرائب (TX)", body: "ACCA TX style", area: "accounting", sourceLabel: "ACCA TX past paper", group: "skills", difficulty: 2 },
  { flagship: "acca-fr", base: "acca-fr", titleEn: "Financial Reporting (IFRS)", titleAr: "إعداد التقارير المالية (IFRS)", body: "ACCA FR style", area: "accounting", sourceLabel: "ACCA FR past paper", group: "skills", difficulty: 2 },
  { flagship: "acca-aa", base: "acca-aa", titleEn: "Audit & Assurance", titleAr: "المراجعة والتأكيد", body: "ACCA AA style", area: "auditing", sourceLabel: "ACCA AA past paper", group: "skills", difficulty: 2 },
  { flagship: "acca-fm", base: "acca-fm", titleEn: "Financial Management (FM)", titleAr: "الإدارة المالية (FM)", body: "ACCA FM style", area: "accounting", sourceLabel: "ACCA FM past paper", group: "skills", difficulty: 2 },
  { flagship: "acca-sbl", base: "acca-sbl", titleEn: "Strategic Business Leader", titleAr: "القائد التجاري الاستراتيجي", body: "ACCA SBL style", area: "ethics", sourceLabel: "ACCA SBL past paper", group: "strategic", difficulty: 3 },
  { flagship: "acca-sbr", base: "acca-sbr", titleEn: "Strategic Business Reporting", titleAr: "التقارير الاستراتيجية", body: "ACCA SBR style", area: "accounting", sourceLabel: "ACCA SBR past paper", group: "strategic", difficulty: 3 },
  { flagship: "acca-afm", base: "acca-afm", titleEn: "Advanced Financial Management (AFM)", titleAr: "الإدارة المالية المتقدمة (AFM)", body: "ACCA AFM style", area: "accounting", sourceLabel: "ACCA AFM past paper", group: "strategic", difficulty: 3 },
  { flagship: "acca-apm", base: "acca-apm", titleEn: "Advanced Performance Management (APM)", titleAr: "إدارة الأداء المتقدمة (APM)", body: "ACCA APM style", area: "accounting", sourceLabel: "ACCA APM past paper", group: "strategic", difficulty: 3, sittingCount: 15 },
  { flagship: "acca-atx", base: "acca-atx", titleEn: "Advanced Taxation (ATX)", titleAr: "الضرائب المتقدمة (ATX)", body: "ACCA ATX style", area: "accounting", sourceLabel: "ACCA ATX past paper", group: "strategic", difficulty: 3 },
  { flagship: "acca-aaa", base: "acca-aaa", titleEn: "Advanced Audit & Assurance", titleAr: "المراجعة والتأكيد المتقدمة", body: "ACCA AAA style", area: "auditing", sourceLabel: "ACCA AAA past paper", group: "strategic", difficulty: 3 },
  { flagship: "soe-audit", base: "soe-audit", titleEn: "Egyptian state-sector audit", titleAr: "مراجعة قطاع الأعمال العام", body: "SOE / EEC style", area: "egypt", sourceLabel: "Egypt SOE audit past paper", group: "egypt", difficulty: 2 },
  { flagship: "ifrs-dip", base: "ifrs-dip", titleEn: "IFRS diploma — financial reporting", titleAr: "دبلومة IFRS — التقارير المالية", body: "DipIFR style", area: "accounting", sourceLabel: "IFRS diploma past paper", group: "ifrs", difficulty: 2 },
  /* v26 — the CPA / CFA / CMA course tracks (seeded by scripts/seed/v26) */
  { flagship: "cpa-aud", base: "cpa-aud", titleEn: "CPA Auditing & Attestation (AUD)", titleAr: "CPA المراجعة والتأكيد (AUD)", body: "CPA AUD style", area: "auditing", sourceLabel: "CPA AUD past paper", group: "cpa", difficulty: 2 },
  { flagship: "cpa-far", base: "cpa-far", titleEn: "CPA Financial Accounting & Reporting (FAR)", titleAr: "CPA المحاسبة والتقارير المالية (FAR)", body: "CPA FAR style", area: "accounting", sourceLabel: "CPA FAR past paper", group: "cpa", difficulty: 3 },
  { flagship: "cpa-reg", base: "cpa-reg", titleEn: "CPA Regulation (REG)", titleAr: "CPA التنظيم والضرائب (REG)", body: "CPA REG style", area: "accounting", sourceLabel: "CPA REG past paper", group: "cpa", difficulty: 2 },
  { flagship: "cfa-l1", base: "cfa-l1", titleEn: "CFA Level I — financial reporting & analysis", titleAr: "CFA المستوى الأول — التقارير والتحليل المالي", body: "CFA Level I style", area: "accounting", sourceLabel: "CFA Level I past paper", group: "cfa", difficulty: 2 },
  { flagship: "cma-p1", base: "cma-p1", titleEn: "CMA Part 1 — financial reporting, planning & performance", titleAr: "CMA الجزء الأول — التقارير والتخطيط والأداء", body: "CMA Part 1 style", area: "accounting", sourceLabel: "CMA Part 1 past paper", group: "cma", difficulty: 2 },
  { flagship: "cma-p2", base: "cma-p2", titleEn: "CMA Part 2 — financial decision making", titleAr: "CMA الجزء الثاني — القرارات المالية", body: "CMA Part 2 style", area: "accounting", sourceLabel: "CMA Part 2 past paper", group: "cma", difficulty: 3 },
]

/** The four dated sittings added to every family (v25 seed). */
export const PAPER_SITTINGS: { label: string; labelAr: string; slug: string }[] = [
  { label: "June 2024", labelAr: "يونيو 2024", slug: "2024j" },
  { label: "Sept 2023", labelAr: "سبتمبر 2023", slug: "2023s" },
  { label: "June 2022", labelAr: "يونيو 2022", slug: "2022j" },
  { label: "Dec 2021", labelAr: "ديسمبر 2021", slug: "2021d" },
]

/** A family groups its flagship paper + the four dated sittings. */
export type PaperFamily = {
  id: string
  titleEn: string
  titleAr: string
  group: PaperGroup
  /** the flagship entry (the fullest paper) */
  flagship: PastPaper
  /** dated sittings, newest first */
  sittings: PastPaper[]
}

/** Build the dated-sitting paper entries for one family. */
function sittingPapers(f: FamilyDef): PastPaper[] {
  const count = f.sittingCount ?? 18
  const duration = Math.round(count * 3) // 18Q → 54 min, 15Q → 45 min
  return PAPER_SITTINGS.map((s) => ({
    id: `${f.base}-${s.slug}`,
    titleEn: `${f.titleEn} — ${s.label} sitting`,
    titleAr: `${f.titleAr} — جلسة ${s.labelAr}`,
    body: f.body,
    area: f.area,
    source: `${f.sourceLabel} — ${s.label} (adapted)`,
    count,
    durationMin: duration,
    difficulty: f.difficulty,
    group: f.group,
    blurbEn: `The ${s.label} sitting — ${count} fresh scenario questions in the ${f.titleEn} style.`,
    blurbAr: `جلسة ${s.labelAr} — ${count === 15 ? "١٥" : "١٨"} سؤال سيناريو جديد بأسلوب ${f.titleAr}.`,
  }))
}

/* ---------------- flagship papers (existing + IFRS) ---------------- */

const FLAGSHIPS: PastPaper[] = [
  /* ==================== IFRS diploma (v25 — findable first) ==================== */
  {
    id: "ifrs-dip",
    titleEn: "IFRS diploma — financial reporting (full paper)",
    titleAr: "دبلومة IFRS — التقارير المالية (ورقة كاملة)",
    body: "DipIFR style",
    area: "accounting",
    source: "IFRS diploma past paper (adapted)",
    count: 24,
    durationMin: 72,
    difficulty: 2,
    group: "ifrs",
    blurbEn:
      "The dedicated IFRS paper you were looking for — DipIFR-style reporting at full length: consolidation, financial instruments, leases, revenue, impairments and first-time adoption.",
    blurbAr:
      "ورقة IFRS المخصصة التي تبحث عنها — تقارير بنمط DipIFR بطول كامل: التجميع والأدوات المالية والإيجارات والإيرادات والاضمحلال والتطبيق الأول.",
  },
  /* ==================== Applied Knowledge ==================== */
  {
    id: "acca-bt",
    titleEn: "Business & Technology (BT) — past paper",
    titleAr: "الأعمال والتكنولوجيا (BT) — امتحان سابق",
    body: "ACCA BT style",
    area: "accounting",
    source: "ACCA BT past paper (adapted)",
    count: 18,
    durationMin: 54,
    difficulty: 1,
    group: "knowledge",
    blurbEn:
      "The ACCA gateway paper — governance, stakeholders, organisation structure, leadership, teams, macro-economics, marketing and technology risks.",
    blurbAr:
      "ورقة بوابة ACCA — الحوكمة وأصحاب المصلحة وهيكل المنظمة والقيادة والفرق والاقتصاد الكلي والتسويق ومخاطر التكنولوجيا.",
  },
  {
    id: "acca-ma",
    titleEn: "Management Accounting (MA) — past paper",
    titleAr: "المحاسبة الإدارية (MA) — امتحان سابق",
    body: "ACCA MA style",
    area: "accounting",
    source: "ACCA MA past paper (adapted)",
    count: 18,
    durationMin: 54,
    difficulty: 1,
    group: "knowledge",
    blurbEn:
      "Cost behaviour, absorption and marginal costing, ABC, process costing, CVP, variances, budgeting and divisional measures.",
    blurbAr:
      "سلوك التكاليف والتحميل والحدية وABC والتكاليف المرحلية والتعادل والانحرافات والموازنات ومقاييس الأقسام.",
  },
  {
    id: "acca-fa",
    titleEn: "Financial Accounting (FA) — past paper",
    titleAr: "المحاسبة المالية (FA) — امتحان سابق",
    body: "ACCA FA style",
    area: "accounting",
    source: "ACCA FA past paper (adapted)",
    count: 18,
    durationMin: 54,
    difficulty: 1,
    group: "knowledge",
    blurbEn:
      "The ACCA foundations paper — double entry, control accounts, bank reconciliations, depreciation, accruals, IAS 2 inventory and basic ratios. The perfect first paper.",
    blurbAr:
      "ورقة ACCA التأسيسية — القيد المزدوج وحسابات المراقبة والتسويات البنكية والإهلاك والمصروفات المستحقة ومخزون IAS 2 والنسب الأساسية. الورقة الأولى المثالية.",
  },
  /* ==================== Applied Skills ==================== */
  {
    id: "acca-lw",
    titleEn: "Corporate & Business Law (LW) — past paper",
    titleAr: "قانون الشركات والأعمال (LW) — امتحان سابق",
    body: "ACCA LW style",
    area: "ethics",
    source: "ACCA LW past paper (adapted)",
    count: 24,
    durationMin: 72,
    difficulty: 2,
    group: "skills",
    blurbEn:
      "Contract formation and terms, negligence, employment law, company formation, directors' duties, share capital, insolvency and partnership/agency law.",
    blurbAr:
      "انعقاد العقد وشروطه والإهمال وقانون العمل وتأسيس الشركات وواجبات المديرين ورأس المال والتفسير وقانون الشراكة والوكالة.",
  },
  {
    id: "acca-pm",
    titleEn: "Performance Management (PM) — past paper",
    titleAr: "إدارة الأداء (PM) — امتحان سابق",
    body: "ACCA PM style",
    area: "accounting",
    source: "ACCA PM past paper (adapted)",
    count: 24,
    durationMin: 72,
    difficulty: 2,
    group: "skills",
    blurbEn:
      "The specialist techniques paper — ABC, target and lifecycle costing, throughput, pricing, mix & yield variances, planning variances, transfer pricing and the balanced scorecard.",
    blurbAr:
      "ورقة التقنيات المتخصصة — ABC والتكلفة المستهدفة ودورة الحياة والإنتاجية والتسعير وانحرافات المزيج والمردود والانحرافات التخطيطية وأسعار النقل وبطاقة الأداء المتوازن.",
  },
  {
    id: "acca-tx",
    titleEn: "Taxation (TX) — past paper",
    titleAr: "الضرائب (TX) — امتحان سابق",
    body: "ACCA TX style",
    area: "accounting",
    source: "ACCA TX past paper (adapted)",
    count: 24,
    durationMin: 72,
    difficulty: 2,
    group: "skills",
    blurbEn:
      "Trading-income adjustments, capital allowances, employment income and benefits, corporation tax, VAT, capital gains, loss relief and tax ethics.",
    blurbAr:
      "تسويات دخل النشاط وبدلات رأس المال ودخل التوظيف ومزاياه وضريبة الشركات والقيمة المضافة والمكاسب الرأسمالية وتخفيف الخسائر وأخلاقيات الضرائب.",
  },
  {
    id: "acca-fr",
    titleEn: "Financial Reporting (IFRS) — full past paper",
    titleAr: "إعداد التقارير المالية (IFRS) — امتحان سابق كامل",
    body: "ACCA FR style",
    area: "accounting",
    source: "ACCA FR past paper (adapted)",
    count: 30,
    durationMin: 90,
    difficulty: 2,
    group: "skills",
    blurbEn:
      "A FULL 30-question IFRS reporting paper — leases, impairments, revenue, financial instruments, deferred tax, groups and presentation.",
    blurbAr:
      "ورقة IFRS كاملة بثلاثين سؤالًا — الإيجارات والاضمحلال والإيرادات والأدوات المالية والضريبة المؤجلة والمجموعات والعرض.",
  },
  {
    id: "acca-aa",
    titleEn: "Audit & Assurance — full past paper",
    titleAr: "المراجعة والتأكيد — امتحان سابق كامل",
    body: "ACCA AA style",
    area: "auditing",
    source: "ACCA AA past paper (adapted)",
    count: 30,
    durationMin: 90,
    difficulty: 2,
    group: "skills",
    blurbEn:
      "A FULL Section-A length paper in the style of ACCA's Audit & Assurance exam — 30 scenario MCQs covering risk assessment, internal control, evidence, review and reporting.",
    blurbAr:
      "ورقة كاملة بطول القسم الأول من امتحان المراجعة والتأكيد لدى ACCA — ٣٠ سؤال سيناريو تغطي تقييم المخاطر والرقابة الداخلية والأدلة والمراجعة والتقرير.",
  },
  {
    id: "acca-fm",
    titleEn: "Financial Management (FM) — past paper",
    titleAr: "الإدارة المالية (FM) — امتحان سابق",
    body: "ACCA FM style",
    area: "accounting",
    source: "ACCA FM past paper (adapted)",
    count: 18,
    durationMin: 54,
    difficulty: 2,
    group: "skills",
    blurbEn:
      "The financial-management paper — NPV and IRR, WACC and CAPM, working capital, forex and interest-rate risk, plus Islamic finance (murabaha, ijara, sukuk).",
    blurbAr:
      "ورقة الإدارة المالية — NPV وIRR، وWACC وCAPM، ورأس المال العامل، ومخاطر الصرف والفائدة، مع التمويل الإسلامي (المرابحة والإجارة والصكوك).",
  },
  /* ==================== Strategic Professional ==================== */
  {
    id: "acca-sbl",
    titleEn: "Strategic Business Leader — past paper",
    titleAr: "القائد التجاري الاستراتيجي — امتحان سابق",
    body: "ACCA SBL style",
    area: "ethics",
    source: "ACCA SBL past paper (adapted)",
    count: 24,
    durationMin: 72,
    difficulty: 3,
    group: "strategic",
    blurbEn:
      "The scenario-led essentials paper — leadership, governance and committees, risk responses, strategy tools, technology and data, and professional-skills judgement.",
    blurbAr:
      "الورقة الجوهرية القائمة على السيناريو — القيادة والحوكمة واللجان واستجابات المخاطر وأدوات الاستراتيجية والتكنولوجيا والبيانات والحكم المهني.",
  },
  {
    id: "acca-sbr",
    titleEn: "Strategic Business Reporting — full past paper",
    titleAr: "التقارير الاستراتيجية — امتحان سابق كامل",
    body: "ACCA SBR style",
    area: "accounting",
    source: "ACCA SBR past paper (adapted)",
    count: 24,
    durationMin: 72,
    difficulty: 3,
    group: "strategic",
    blurbEn:
      "The strategic reporting paper at full length — complex consolidation issues, ECL and hedge accounting, share-based payments, deferred tax and IFRS 18.",
    blurbAr:
      "ورقة التقارير الاستراتيجية بطول كامل — مشكلات التجميع المعقدة، وECL ومحاسبة التحوّط، والدفع بالأسهم، والضريبة المؤجلة وIFRS 18.",
  },
  {
    id: "acca-afm",
    titleEn: "Advanced Financial Management (AFM) — past paper",
    titleAr: "الإدارة المالية المتقدمة (AFM) — امتحان سابق",
    body: "ACCA AFM style",
    area: "accounting",
    source: "ACCA AFM past paper (adapted)",
    count: 18,
    durationMin: 54,
    difficulty: 3,
    group: "strategic",
    blurbEn:
      "The treasury paper at advanced level — APV, M&M and capital structure, options and futures, swaps, FRAs, currency hedging, sukuk and MBO finance.",
    blurbAr:
      "ورقة الخزانة المتقدمة — القيمة المعدلة وهيكل رأس المال والخيارات والمستقبليات والمقايضات والاتفاقيات الآجلة والتحوط من العملة والصكوك وتمويل شراء الإدارة.",
  },
  {
    id: "acca-apm",
    titleEn: "Advanced Performance Management (APM) — past paper",
    titleAr: "إدارة الأداء المتقدمة (APM) — امتحان سابق",
    body: "ACCA APM style",
    area: "accounting",
    source: "ACCA APM past paper (adapted)",
    count: 18,
    durationMin: 54,
    difficulty: 3,
    group: "strategic",
    blurbEn:
      "The performance-thinking paper — frameworks (BSC, building blocks, prism), value-based management, dysfunctional behaviour, VFM in NFPs and incentive design.",
    blurbAr:
      "ورقة تفكير الأداء — الأطر (البطاقة واللبنات والمنشور) والإدارة القائمة على القيمة والسلوك الخللي والاقتصادية في غير الربحي وتصميم الحوافز.",
  },
  {
    id: "acca-atx",
    titleEn: "Advanced Taxation (ATX) — past paper",
    titleAr: "الضرائب المتقدمة (ATX) — امتحان سابق",
    body: "ACCA ATX style",
    area: "accounting",
    source: "ACCA ATX past paper (adapted)",
    count: 18,
    durationMin: 54,
    difficulty: 3,
    group: "strategic",
    blurbEn:
      "The advisory tax paper — estate and gifts planning, reorganisations, incorporation, thin capitalisation, VAT on business sales, APAs and tax ethics.",
    blurbAr:
      "ورقة الضرائب الاستشارية — تخطيط التركات والهبات وإعادة الهيكلة والتحول والرسملة الهزيلة والضريبة على بيع الأنشطة والاتفاقيات المسبقة وأخلاقيات الضريبة.",
  },
  {
    id: "acca-aaa",
    titleEn: "Advanced Audit & Assurance — full past paper",
    titleAr: "المراجعة والتأكيد المتقدمة — امتحان سابق كامل",
    body: "ACCA AAA style",
    area: "auditing",
    source: "ACCA AAA past paper (adapted)",
    count: 24,
    durationMin: 72,
    difficulty: 3,
    group: "strategic",
    blurbEn:
      "The harder, judgement-heavy AA upgrade at full length — engagement acceptance, professional ethics, group audits, going concern and modified opinions.",
    blurbAr:
      "النسخة الأصعب الغنية بالحكم المهني وبطول كامل — قبول المهمة، أخلاقيات المهنة، مراجعة المجموعات، الاستمرارية وآراء المراجعة المعدلة.",
  },
  /* ==================== Egyptian practice ==================== */
  {
    id: "soe-audit",
    titleEn: "Egyptian state-sector audit — full past paper",
    titleAr: "مراجعة قطاع الأعمال العام — امتحان سابق كامل",
    body: "SOE / EEC style",
    area: "egypt",
    source: "Egypt SOE audit past paper (adapted)",
    count: 24,
    durationMin: 72,
    difficulty: 2,
    group: "egypt",
    blurbEn:
      "The full Egyptian practice paper for state-owned enterprises — EAS/ISA alignment, governance, syndicate rules, review engagements and public-sector audit types.",
    blurbAr:
      "الورقة المصرية الكاملة لشركات قطاع الأعمال العام — التوافق بين المعايير المصرية والدولية، الحوكمة، قواعد النقابة، الفحص المحدود وأنواع مراجعة القطاع العام.",
  },
  /* ==================== v26 — CPA / CFA / CMA course tracks ==================== */
  {
    id: "cpa-aud",
    titleEn: "CPA Auditing & Attestation (AUD) — full past paper",
    titleAr: "CPA المراجعة والتأكيد (AUD) — امتحان سابق كامل",
    body: "CPA AUD style",
    area: "auditing",
    source: "CPA AUD past paper (adapted)",
    count: 24,
    durationMin: 72,
    difficulty: 2,
    group: "cpa",
    blurbEn:
      "The companion paper to our full Arabic CPA AUD course — engagement acceptance, risk and evidence, professional ethics, reviews and reporting, in AICPA-style scenarios.",
    blurbAr:
      "الورقة الرفيقة لكورس CPA AUD العربي الكامل لدينا — قبول الارتباط والمخاطر والأدلة وأخلاقيات المهنة والفحوص والتقارير، بمواقف بنمط معهد المحاسبين الأمريكي.",
  },
  {
    id: "cpa-far",
    titleEn: "CPA Financial Accounting & Reporting (FAR) — full past paper",
    titleAr: "CPA المحاسبة والتقارير المالية (FAR) — امتحان سابق كامل",
    body: "CPA FAR style",
    area: "accounting",
    source: "CPA FAR past paper (adapted)",
    count: 24,
    durationMin: 72,
    difficulty: 3,
    group: "cpa",
    blurbEn:
      "The FAR shelf — framework and statements, revenue, leases, financial instruments, pensions, income taxes and consolidation-style judgement items at full length.",
    blurbAr:
      "رف FAR — الإطار والقوائم والإيرادات والإيجارات والأدوات المالية والمعاشات والضرائب وبنود الحكم بأسلوب التجميع وبطول كامل.",
  },
  {
    id: "cpa-reg",
    titleEn: "CPA Regulation (REG) — full past paper",
    titleAr: "CPA التنظيم والضرائب (REG) — امتحان سابق كامل",
    body: "CPA REG style",
    area: "accounting",
    source: "CPA REG past paper (adapted)",
    count: 24,
    durationMin: 72,
    difficulty: 2,
    group: "cpa",
    blurbEn:
      "Taxation and business law for the REG section — federal taxation of individuals and entities, property transactions, ethics and professional responsibilities.",
    blurbAr:
      "الضرائب وقانون الأعمال لفرع التنظيم — الضرائب الفيدرالية للأفراد والمنشآت ومعاملات الأملاك والأخلاقيات والمسؤوليات المهنية.",
  },
  {
    id: "cfa-l1",
    titleEn: "CFA Level I — full past paper",
    titleAr: "CFA المستوى الأول — امتحان سابق كامل",
    body: "CFA Level I style",
    area: "accounting",
    source: "CFA Level I past paper (adapted)",
    count: 24,
    durationMin: 72,
    difficulty: 2,
    group: "cfa",
    blurbEn:
      "The Level I shelf for the accounting-and-finance half of the curriculum — financial reporting & analysis, corporate issuers, equity and fixed-income basics, ratios and time value.",
    blurbAr:
      "رف المستوى الأول للنصف المحاسبي والمالي من المنهج — التقارير والتحليل المالي ومصدِرو الأسهم وأساسيات الأسهم والدخل الثابت والنسب والقيمة الزمنية.",
  },
  {
    id: "cma-p1",
    titleEn: "CMA Part 1 — full past paper",
    titleAr: "CMA الجزء الأول — امتحان سابق كامل",
    body: "CMA Part 1 style",
    area: "accounting",
    source: "CMA Part 1 past paper (adapted)",
    count: 24,
    durationMin: 72,
    difficulty: 2,
    group: "cma",
    blurbEn:
      "The Part 1 companion — external financial reporting decisions, planning and budgeting, performance and cost management, and internal controls, in ICMA-style scenarios.",
    blurbAr:
      "الرفيقة للجزء الأول — قرارات التقارير المالية الخارجية والتخطيط والموازنات وإدارة الأداء والتكاليف والرقابة الداخلية، بمواقف بنمط معهد المحاسبين الإداريين.",
  },
  {
    id: "cma-p2",
    titleEn: "CMA Part 2 — full past paper",
    titleAr: "CMA الجزء الثاني — امتحان سابق كامل",
    body: "CMA Part 2 style",
    area: "accounting",
    source: "CMA Part 2 past paper (adapted)",
    count: 24,
    durationMin: 72,
    difficulty: 3,
    group: "cma",
    blurbEn:
      "The Part 2 shelf — financial statement analysis, corporate finance, decision analysis, risk management and investment decisions, at full 24-question length.",
    blurbAr:
      "رف الجزء الثاني — تحليل القوائم المالية وتمويل الشركات وتحليل القرارات وإدارة المخاطر وقرارات الاستثمار، بطول 24 سؤالًا كاملًا.",
  },
]

/* ---------------- assembled registry ---------------- */

/** Every paper: flagships + dated sittings (v25 five-years-per-exam). */
export const PAST_PAPERS: PastPaper[] = [
  ...FLAGSHIPS,
  ...FAMILIES.flatMap((f) => sittingPapers(f)),
]

/** Families for the grouped UI: flagship + four dated sittings each. */
export const PAPER_FAMILIES: PaperFamily[] = FAMILIES.map((f) => {
  const flagship = FLAGSHIPS.find((p) => p.id === f.flagship)!
  return {
    id: f.base,
    titleEn: f.titleEn,
    titleAr: f.titleAr,
    group: f.group,
    flagship,
    sittings: sittingPapers(f),
  }
})

export function getPastPaper(id: string): PastPaper | null {
  return PAST_PAPERS.find((p) => p.id === id) ?? null
}
