/** v22 — curated Arabic audit & accounting YouTube episodes for the
 *  Podcasts section ("From YouTube — بالعربي").
 *
 *  Channels chosen for clear, friendly, well-structured Arabic (the
 *  learner's request — e.g. CPA Talks), verified via YouTube search on
 *  2026-09-27. Episode data (ids, lengths) is captured from live search
 *  results; thumbnails load from i.ytimg.com. */

export type PodcastEpisode = {
  /** YouTube video id */
  id: string
  /** Original (Arabic) title */
  title: string
  channel: string
  /** "PT" style display length, e.g. "1:34:52" */
  length: string
  views: string
  category: "conversations" | "external-audit" | "ifrs" | "egypt" | "internal-audit" | "career"
  /** Short EN blurb */
  blurbEn: string
  /** Short AR blurb */
  blurbAr: string
}

export const YT_CATEGORIES: {
  id: PodcastEpisode["category"] | "all"
  labelEn: string
  labelAr: string
}[] = [
  { id: "all", labelEn: "All", labelAr: "الكل" },
  // v25 — REAL podcasts: two people talking (interviews & conversations),
  // the format the learner asked for, kept separate from the explainer videos
  { id: "conversations", labelEn: "Real podcasts · conversations", labelAr: "بودكاست حقيقي · حوارات" },
  { id: "external-audit", labelEn: "External audit", labelAr: "التدقيق الخارجي" },
  { id: "ifrs", labelEn: "IFRS & accounting", labelAr: "المعايير والمحاسبة" },
  { id: "egypt", labelEn: "Egyptian standards", labelAr: "المعايير المصرية" },
  { id: "internal-audit", labelEn: "Internal audit", labelAr: "المراجعة الداخلية" },
  { id: "career", labelEn: "Career", labelAr: "المسار المهني" },
]

export const YT_EPISODES: PodcastEpisode[] = [
  // ---- CPA Talks (the learner's requested channel) ----
  {
    id: "6sEAi4AQFAk",
    title: "Steps of External Audit لايف — أهم خطوات التدقيق لكل مدقق حسابات خارجي",
    channel: "CPA Talks",
    length: "1:34:52",
    views: "39K",
    category: "external-audit",
    blurbEn: "A friendly live session walking through the real steps of an external audit, start to finish.",
    blurbAr: "لايف ودّي يتناول خطوات التدقيق الخارجي الحقيقية من البداية للنهاية.",
  },
  {
    id: "UlXAY_gALWI",
    title: "القوائم المالية المجمعة | شرح مفصل طبقا لمعايير المحاسبة الدولية",
    channel: "CPA Talks",
    length: "2:07:03",
    views: "12K",
    category: "ifrs",
    blurbEn: "Consolidated financial statements in detail under IFRS — the deep-dive style CPA Talks is known for.",
    blurbAr: "القوائم المالية المجمعة بالتفصيل وفق المعايير الدولية — بأسلوب الدمسات العميقة.",
  },
  {
    id: "6EP6b1U9UoY",
    title: "الأدوات المالية IFRS 9 | شرح مفصل طبقا لمعايير المحاسبة الدولية",
    channel: "CPA Talks",
    length: "1:47:04",
    views: "16K",
    category: "ifrs",
    blurbEn: "Financial instruments under IFRS 9, explained patiently with examples.",
    blurbAr: "الأدوات المالية وفق IFRS 9 بشرح صبور وأمثلة.",
  },
  {
    id: "TxWRD7oKE5Y",
    title: "IFRS 16 ورشة عمل",
    channel: "CPA Talks",
    length: "2:54:00",
    views: "4.6K",
    category: "ifrs",
    blurbEn: "A full IFRS 16 leases workshop — practical journal entries and transitions.",
    blurbAr: "ورشة عمل كاملة عن IFRS 16 — قيود عملية ومعالجات الانتقال.",
  },
  {
    id: "ZS5kKewKYM0",
    title: "الأصول الثابتة والأصول غير الملموسة والاضمحلال في الأصول | شرح مفصل",
    channel: "CPA Talks",
    length: "2:11:11",
    views: "4K",
    category: "ifrs",
    blurbEn: "PPE, intangibles and impairment (IAS 16 / 38 / 36) in one detailed session.",
    blurbAr: "الأصول الثابتة وغير الملموسة والاضمحلال (IAS 16 / 38 / 36) في جلسة مفصلة واحدة.",
  },
  {
    id: "OJ1DZKbqH_I",
    title: "طريقي من التخرج حتى الآن في مجال المحاسبة والتدقيق (مصر، الإمارات وانجلترا)",
    channel: "CPA Talks",
    length: "37:59",
    views: "4K",
    category: "career",
    blurbEn: "An honest career-path conversation — graduation to practice across Egypt, the UAE and England.",
    blurbAr: "حوار صريح عن المسار المهني — من التخرج إلى الاحتراف عبر مصر والإمارات وإنجلترا.",
  },
  {
    id: "nz0cjh6Xh8c",
    title: "تدقيق 101 — (11) — فحص التكاليف وأرصدة الموردين",
    channel: "CPA Talks",
    length: "34:27",
    views: "5.7K",
    category: "external-audit",
    blurbEn: "From the Audit 101 series: testing costs and supplier balances.",
    blurbAr: "من سلسلة تدقيق 101: فحص التكاليف وأرصدة الموردين.",
  },
  {
    id: "Uspt0KvLmqI",
    title: "IAS 37 شرح معيار المخصصات والالتزامات المحتملة والأصول المحتملة",
    channel: "CPA Talks",
    length: "32:56",
    views: "3.8K",
    category: "ifrs",
    blurbEn: "IAS 37 provisions, contingent liabilities and contingent assets, clearly explained.",
    blurbAr: "المخصصات والالتزامات والأصول المحتملة وفق IAS 37 بشرح واضح.",
  },
  // ---- v23: more CPA Talks (most-viewed explainers + workshops) ----
  {
    id: "8HJK4AUrcWg",
    title: "Materiality الأهمية النسبية",
    channel: "CPA Talks",
    length: "29:17",
    views: "14K",
    category: "external-audit",
    blurbEn: "The channel's classic materiality explainer — concept, calculation and audit use.",
    blurbAr: "شرح القناة الكلاسيكي للأهمية النسبية — المفهوم والحساب والاستخدام في المراجعة.",
  },
  {
    id: "ucPoJ4Donp8",
    title: "Assertions — تأكيدات الإدارة — التعريف والأنواع",
    channel: "CPA Talks",
    length: "10:35",
    views: "10K",
    category: "external-audit",
    blurbEn: "Management assertions defined and classified — the foundation of evidence planning.",
    blurbAr: "تأكيدات الإدارة: تعريفها وأنواعها — أساس تخطيط أدلة المراجعة.",
  },
  {
    id: "Xi36nCBkEhw",
    title: "كيف تقوم بتقييم المخاطر في التدقيق الخارجي",
    channel: "CPA Talks",
    length: "27:06",
    views: "13K",
    category: "external-audit",
    blurbEn: "How to actually assess audit risk in practice — a friendly walkthrough.",
    blurbAr: "كيف تقيّم مخاطر المراجعة عمليًا — شرح ودّي خطوة بخطوة.",
  },
  {
    id: "7wwLJ3BtMkY",
    title: "تدقيق 101 — (1) — مفهوم التدقيق وقبول العميل",
    channel: "CPA Talks",
    length: "17:06",
    views: "22K",
    category: "external-audit",
    blurbEn: "Episode 1 of the beloved Audit 101 series — what auditing is and accepting a client.",
    blurbAr: "الحلقة الأولى من سلسلة تدقيق 101 المحببة — مفهوم التدقيق وقبول العميل.",
  },
  {
    id: "95M3NEvILs4",
    title: "تدقيق 101 — (10) — فحص الإيرادات وأرصدة العملاء",
    channel: "CPA Talks",
    length: "33:54",
    views: "10K",
    category: "external-audit",
    blurbEn: "The series' most-watched fieldwork episode — revenue and receivables testing.",
    blurbAr: "أشهر حلقة فحص ميداني في السلسلة — فحص الإيرادات وأرصدة العملاء.",
  },
  {
    id: "wVt-6H3rgKg",
    title: "IFRS 15 — Revenue part one — نموذج الخطوات الخمس",
    channel: "CPA Talks",
    length: "46:07",
    views: "12K",
    category: "ifrs",
    blurbEn: "The five-step revenue recognition model, CPA Talks style.",
    blurbAr: "نموذج الخطوات الخمس للاعتراف بالإيراد، بأسلوب CPA Talks.",
  },
  {
    id: "38FaKUZqAFk",
    title: "IFRS 15 — Revenue part two — معاملات معينة",
    channel: "CPA Talks",
    length: "29:55",
    views: "4K",
    category: "ifrs",
    blurbEn: "Part two — specific transactions and the tricky corners of IFRS 15.",
    blurbAr: "الجزء الثاني — المعاملات الخاصة والزوايا الدقيقة في IFRS 15.",
  },
  {
    id: "QaWORLvO12U",
    title: "IFRS 16 — Leases part one — محاسبة المستأجر",
    channel: "CPA Talks",
    length: "1:03:33",
    views: "7.6K",
    category: "ifrs",
    blurbEn: "Lessee accounting under IFRS 16 — a full hour with worked numbers.",
    blurbAr: "محاسبة المستأجر وفق IFRS 16 — ساعة كاملة بأرقام عملية.",
  },
  {
    id: "Q5dKvZUSj2E",
    title: "IFRS 16 — تجنّب هذه الأخطاء الشائعة عند تطبيق الاستثناءات",
    channel: "CPA Talks",
    length: "9:45",
    views: "2.3K",
    category: "ifrs",
    blurbEn: "The common IFRS 16 exemption mistakes — and how to avoid each one.",
    blurbAr: "أخطاء استثناءات IFRS 16 الشائعة — وكيف تتجنب كل واحدة.",
  },
  {
    id: "XBTYjqVh34Q",
    title: "Expected Credit Losses model (ECL) IFRS 9 — نموذج خسائر الائتمان المتوقعة",
    channel: "CPA Talks",
    length: "13:42",
    views: "31K",
    category: "ifrs",
    blurbEn: "The most-viewed CPA Talks IFRS 9 clip — ECL in one sitting.",
    blurbAr: "أشهر مقطع للقناة عن IFRS 9 — نموذج الخسائر المتوقعة في جلسة واحدة.",
  },
  {
    id: "Pt5a8nL9zxk",
    title: "ECL ورشة عمل نموذج الخسائر الائتمانية المتوقعة بمثال عملي",
    channel: "CPA Talks",
    length: "1:26:40",
    views: "18K",
    category: "ifrs",
    blurbEn: "A full ECL workshop — building the model with a practical example.",
    blurbAr: "ورشة عمل كاملة عن ECL — بناء النموذج بمثال عملي.",
  },
  {
    id: "4-bibVUG7Lk",
    title: "سلسلة الشهادات المهنية — رأيه الشخصي في دبلومة معايير المحاسبة DipIFR",
    channel: "CPA Talks",
    length: "5:35",
    views: "9K",
    category: "career",
    blurbEn: "An honest take on the DipIFR — is it worth it, and for whom?",
    blurbAr: "رأي صريح في دبلومة DipIFR — هل تستحقها ولمن؟",
  },
  {
    id: "DnyRBQciaHc",
    title: "ازاي تشتغل في دول الخليج في مجال تدقيق الحسابات",
    channel: "CPA Talks",
    length: "27:26",
    views: "3.4K",
    category: "career",
    blurbEn: "How to land an audit job in the Gulf — routes, credentials and expectations.",
    blurbAr: "كيف تحصل على وظيفة تدقيق في الخليج — الطرق والشهادات والتوقعات.",
  },
  {
    id: "u1FfkVCz4A8",
    title: "ازاي تبحث عن وظيفة مناسبة في المحاسبة والتدقيق",
    channel: "CPA Talks",
    length: "13:05",
    views: "1.6K",
    category: "career",
    blurbEn: "A grounded guide to searching for the RIGHT accounting or audit role.",
    blurbAr: "دليل واقعي للبحث عن الوظيفة المناسبة في المحاسبة والتدقيق.",
  },
  {
    id: "xfjUkTrUt-w",
    title: "عن التشتت وطرق استغلال أهم وقت في حياتك المهنية",
    channel: "CPA Talks",
    length: "12:53",
    views: "1.7K",
    category: "career",
    blurbEn: "Beating distraction and using the most valuable hours of your professional life.",
    blurbAr: "التغلب على التشتت واستثمار أهم وقت في حياتك المهنية.",
  },
  // ---- Mahmoud Hamouda (Egyptian audit standards specialist) ----
  {
    id: "ub6839N_vi4",
    title: "دورة شرح معايير المراجعة المصرية",
    channel: "Mahmoud Hamouda",
    length: "1:32:54",
    views: "836",
    category: "egypt",
    blurbEn: "A full course on the Egyptian Standards on Auditing — structured, exam-oriented.",
    blurbAr: "دورة كاملة في معايير المراجعة المصرية — منظمة وموجهة للامتحانات.",
  },
  {
    id: "Qt7Hq5sZ6YE",
    title: "شرح معايير المراجعة | أسئلة اختيار من المتعدد محلولة | ازاي تذاكر",
    channel: "Mahmoud Hamouda",
    length: "33:50",
    views: "25K",
    category: "egypt",
    blurbEn: "Egyptian audit standards through solved MCQs — how to actually study them.",
    blurbAr: "معايير المراجعة المصرية عبر أسئلة محلولة — وكيف تذاكرها فعليًا.",
  },
  {
    id: "6rnyhPzHoOg",
    title: "تسلسل معايير المراجعة | دورة شرح معايير المراجعة المصرية",
    channel: "Mahmoud Hamouda",
    length: "4:56",
    views: "2.6K",
    category: "egypt",
    blurbEn: "The logical sequence of the audit standards — a perfect orientation clip.",
    blurbAr: "التسلسل المنطقي لمعايير المراجعة — مقطع تعريفي مثالي.",
  },
  // ---- ESAA EGYPT (the official society) ----
  {
    id: "Y0MS9mB-MGo",
    title: "ندوة أهم المستجدات في معايير المراجعة المصرية والفحص المحدود ومهام التأكد الأخرى",
    channel: "ESAA EGYPT — جمعية المحاسبين والمراجعين المصرية",
    length: "2:03:16",
    views: "1.1K",
    category: "egypt",
    blurbEn: "The Egyptian Society of Accountants and Auditors on the latest standard updates and assurance services.",
    blurbAr: "جمعية المحاسبين والمراجعين المصريين حول أحدث مستجدات المعايير ومهام التأكد.",
  },
  {
    id: "nuy_1rmd1Ao",
    title: "أهم التغيرات في معايير المراجعة المصرية الجديدة — ملخص ندوة الجمعية",
    channel: "Accounting forever",
    length: "6:01",
    views: "906",
    category: "egypt",
    blurbEn: "A crisp summary of the changes in the new Egyptian auditing standards.",
    blurbAr: "ملخص مركز لأهم التغيرات في معايير المراجعة المصرية الجديدة.",
  },
  // ---- Hany Sayed (IFRS educator) ----
  {
    id: "BXEW8QWOUt0",
    title: "IFRS 16 Leases — Part one — شرح معيار المحاسبة الدولي الإيجارات",
    channel: "Hany Sayed",
    length: "29:49",
    views: "55K",
    category: "ifrs",
    blurbEn: "The most-watched Arabic IFRS 16 explainer — lessee accounting part one.",
    blurbAr: "أشهر شرح عربي لمعيار الإيجارات IFRS 16 — محاسبة المستأجر (الجزء الأول).",
  },
  {
    id: "DOb0JqA3Xcc",
    title: "IFRS 15 Revenue — Part one — شرح معيار المحاسبة الدولي الإيراد",
    channel: "Hany Sayed",
    length: "21:43",
    views: "41K",
    category: "ifrs",
    blurbEn: "Revenue from contracts with customers, part one — the five-step model.",
    blurbAr: "الإيراد من العقود مع العملاء (الجزء الأول) — نموذج الخطوات الخمس.",
  },
  // ---- Hossam Saad ----
  {
    id: "hq_t4dI6nQ4",
    title: "معايير المحاسبة IAS/IFRS | عرض القوائم المالية IAS 1",
    channel: "دليلك لفهم المحاسبة — حسام سعد",
    length: "1:09:14",
    views: "63K",
    category: "ifrs",
    blurbEn: "Presentation of Financial Statements (IAS 1) — a complete lecture.",
    blurbAr: "عرض القوائم المالية وفق IAS 1 — محاضرة كاملة.",
  },
  // ---- Yazan Makdah (internal audit) ----
  {
    id: "Le1nxliKV_g",
    title: "التدقيق الداخلي | ما هو التدقيق الداخلي؟",
    channel: "Yazan Makdah | يزن مقدح",
    length: "13:55",
    views: "123K",
    category: "internal-audit",
    blurbEn: "The most popular Arabic intro to internal audit — clear and friendly.",
    blurbAr: "أشهر مقدمة عربية عن المراجعة الداخلية — واضحة وودودة.",
  },
  {
    id: "ryiKL82V3N8",
    title: "الحوكمة وإدارة المخاطر والتدقيق الداخلي — نموذج خطوط الدفاع الثلاثة",
    channel: "Yazan Makdah | يزن مقدح",
    length: "18:11",
    views: "38K",
    category: "internal-audit",
    blurbEn: "Governance, risk and internal audit — the modern Three Lines of Defense model.",
    blurbAr: "الحوكمة وإدارة المخاطر والمراجعة الداخلية — نموذج خطوط الدفاع الثلاثة الحديث.",
  },
  {
    id: "9HNTbsn4-v4",
    title: "التدقيق الداخلي | مبدأ بسيط ينقل جودة تقاريرك لمستوى احترافي",
    channel: "Yazan Makdah | يزن مقدح",
    length: "4:58",
    views: "31K",
    category: "internal-audit",
    blurbEn: "One simple principle that lifts your audit reports to a professional level.",
    blurbAr: "مبدأ بسيط واحد يرفع جودة تقارير المراجعة إلى مستوى احترافي.",
  },
  // ---- محاسبة أونلاين ----
  {
    id: "VwzNNozTP7A",
    title: "البساطة والسهولة في تلقي المعايير المحاسبية الدولية IFRS",
    channel: "محاسبة أونلاين",
    length: "25:35",
    views: "152K",
    category: "ifrs",
    blurbEn: "A gentle 25-minute orientation to the whole IFRS framework.",
    blurbAr: "تمهيد لطيف في 25 دقيقة لإطار المعايير الدولية كاملًا.",
  },
  {
    id: "jBkuxDM-Akw",
    title: "المراجعة الداخلية: ما هي الرقابة الداخلية؟ وما مهام المراجع الداخلي؟",
    channel: "محاسبة أونلاين",
    length: "31:42",
    views: "53K",
    category: "internal-audit",
    blurbEn: "Internal control and the internal auditor's mandate, calmly explained.",
    blurbAr: "الرقابة الداخلية ومهام المراجع الداخلي بشرح هادئ.",
  },
  // ---- Dr Ahmed Abdellakher ----
  {
    id: "RW8Tqd6SZ8A",
    title: "IFRS — المحاضرة الأولى في المعايير الدولية",
    channel: "Dr Ahmed Abdellakher",
    length: "2:17:34",
    views: "2.8K",
    category: "ifrs",
    blurbEn: "A university-style opening lecture on the international standards.",
    blurbAr: "محاضرة افتتاحية أكاديمية عن المعايير الدولية.",
  },
  // ---- IFRS Diploma — Abdalla Abdelnaim ----
  {
    id: "_FD3QFfiZGQ",
    title: "IFRS 15 — 2.1 — Revenue Recognition",
    channel: "IFRS Diploma — عبدالله عبدالنعيم",
    length: "9:15",
    views: "27K",
    category: "ifrs",
    blurbEn: "A focused DipIFR-style clip on revenue recognition under IFRS 15.",
    blurbAr: "مقطع مركز بنمط دبلومة IFRS عن الاعتراف بالإيراد وفق IFRS 15.",
  },

  /* ==================== v25 — REAL podcasts: two people talking ====================
   * The learner's ask: "podcasts aren't podcasts — someone illustrates. I
   * want two people talking, around the 20-minute range; keep the videos."
   * These are genuine conversation/interview episodes — guest and host (or
   * two hosts) — from real Arabic podcast shows. The Accounting Club
   * interviews run 8–20 minutes; the Qawaim and Bitrolly conversations run
   * longer but are the real two-person format. Every id verified live via
   * YouTube oEmbed on 2026-09-29. The explainer videos stay untouched in
   * their own categories above. */
  // ---- نادي المحاسبة (Accounting Club) — the ضيف_المحاسبة guest interviews ----
  {
    id: "O3yCuohfTvw",
    title: "لقاء مع أ. عبدالله الفوزان الرئيس التنفيذي لشركة KPMG",
    channel: "نادي المحاسبة",
    length: "12:57",
    views: "8.2K",
    category: "conversations",
    blurbEn: "A rare sit-down with KPMG's country CEO — the path to the top of a Big-Four firm, and what he looks for in young accountants.",
    blurbAr: "حوار نادر مع رئيس KPMG في الإقليم — الطريق إلى قمة شركة من الأربع الكبارى وماذا يبحث عنه في المحاسبين الشباب.",
  },
  {
    id: "uC8dJ92bR-c",
    title: "لقاء أ. طارق بن عبدالرحمن السدحان",
    channel: "نادي المحاسبة",
    length: "19:14",
    views: "7K",
    category: "conversations",
    blurbEn: "A 19-minute career conversation — building an accounting career, professional growth, and the habits that compound.",
    blurbAr: "حوار مهني من 19 دقيقة عن بناء المسار المحاسبي والنمو المهني والعادات التي تتراكم.",
  },
  {
    id: "WcRVDuc_j3g",
    title: "لقاء أ. محمد بن عبدالله القويز",
    channel: "نادي المحاسبة",
    length: "20:29",
    views: "1.7K",
    category: "conversations",
    blurbEn: "A full-length guest interview at the 20-minute sweet spot — leadership in finance and the profession's future.",
    blurbAr: "لقاء كامل في حدود العشرين دقيقة — القيادة في المالية ومستقبل المهنة.",
  },
  {
    id: "969x9wzkwuA",
    title: "لقاء الدكتور عبدالله الفوزان",
    channel: "نادي المحاسبة",
    length: "17:19",
    views: "1.8K",
    category: "conversations",
    blurbEn: "An interview with a leading voice of the profession — qualification, practice and giving back.",
    blurbAr: "لقاء مع أحد أبرز أصوات المهنة — المؤهلات والممارسة والعطاء.",
  },
  {
    id: "qksSUQ2Mi8E",
    title: "لقاء م. طارق بن عثمان القصبي",
    channel: "نادي المحاسبة",
    length: "12:37",
    views: "1.8K",
    category: "conversations",
    blurbEn: "The Accounting Club's guest series — a seasoned practitioner on the profession's real-world side.",
    blurbAr: "سلسلة ضيف المحاسبة — ممارس خبير عن الواجهة الحقيقية للمهنة.",
  },
  {
    id: "KseNc-kR8bk",
    title: "لقاء أ. سعد بن محمد الهويمل",
    channel: "نادي المحاسبة",
    length: "8:30",
    views: "1K",
    category: "conversations",
    blurbEn: "A short, sharp guest conversation — perfect for a coffee-break listen between study blocks.",
    blurbAr: "حوار قصير مركز — مثالي للاستماع بين جلستي مذاكرة.",
  },
  // ---- بودكاست قوائم (The Stage) — deep accounting conversations ----
  {
    id: "JEwSK7CVHBg",
    title: "بودكاست قوائم | رحلة محاسب",
    channel: "The Stage l ذا ستيج",
    length: "1:04:01",
    views: "48K",
    category: "conversations",
    blurbEn: "The most-listened Arabic accounting podcast episode: an accountant's full journey — the decisions, detours and lessons.",
    blurbAr: "أكثر حلقات البودكاست المحاسبي العربي استماعًا: رحلة محاسب كاملة — القرارات والمناطق والدروس.",
  },
  {
    id: "v50Zzhsxtjk",
    title: "بودكاست قوائم | المسارات المحاسبية؛ كما تُعاش لا كما تُدرس",
    channel: "The Stage l ذا ستيج",
    length: "1:10:33",
    views: "16K",
    category: "conversations",
    blurbEn: "Accounting career paths as they are actually lived — a candid two-person conversation that no textbook mirrors.",
    blurbAr: "المسارات المحاسبية كما تعاش فعلًا — حوار صريح لا تقلده أي محاضرة.",
  },
  {
    id: "o4jVZw-y88E",
    title: "بودكاست مجتمع قوائم | كيف تفتح مكتبك المحاسبي؟",
    channel: "The Stage l ذا ستيج",
    length: "52:22",
    views: "11K",
    category: "conversations",
    blurbEn: "How to open your own accounting firm — licences, first clients, pricing and the mistakes to avoid, from those who did it.",
    blurbAr: "كيف تفتح مكتبك المحاسبي الخاص — التراخيص وأول العملاء والتسعير والأخطاء الواجب تجنبها.",
  },
  {
    id: "fnYqTLvtc7w",
    title: "بودكاست قوائم | الاحتيال المحاسبي",
    channel: "The Stage l ذا ستيج",
    length: "45:53",
    views: "6.1K",
    category: "conversations",
    blurbEn: "Accounting fraud — how schemes are built, how they unravel, and the red flags professionals should never ignore.",
    blurbAr: "الاحتيال المحاسبي — كيف تبنى المخططات وكيف تنكشف والأعلام الحمراء التي لا يجوز تجاهلها.",
  },
  {
    id: "uFoo6WVLWfU",
    title: "بودكاست قوائم | من المحاسبة الأكاديمية إلى المهنية",
    channel: "The Stage l ذا ستيج",
    length: "59:32",
    views: "10K",
    category: "conversations",
    blurbEn: "The leap from academic accounting to professional practice — the gap nobody warns you about, discussed honestly.",
    blurbAr: "القفزة من المحاسبة الأكاديمية إلى الممارسة المهنية — الفجوة التي لا يحذرك منها أحد.",
  },
  // ---- كناز (Kenaz) · إذاعة مختلف (بترولي) · Fatih Mohamed ----
  {
    id: "NGMwBWptBtw",
    title: "تجربة حازم ومُخلص في شهادة ACCA | بودكاست كِنـــاز",
    channel: "Kenaz - كِنـــاز",
    length: "1:22:37",
    views: "7.4K",
    category: "conversations",
    blurbEn: "Two ACCA candidates sit with the host and talk honestly about how they are passing the exams — the companion listen to our ACCA papers.",
    blurbAr: "متقدما ACCA يتحدثان بوضوح عن اجتياز الامتحانات — الرفيق المسمعي لأوراق ACCA لدينا.",
  },
  {
    id: "zch1iq8LOR0",
    title: "قصة شراكة ناجحة بين أب وابنه في عالم المحاسبة | أصدقاء بترولي",
    channel: "إذاعة مختلف",
    length: "1:34:16",
    views: "10K",
    category: "conversations",
    blurbEn: "A father and son who built an accounting practice together — succession, partnership and family business, in their own words.",
    blurbAr: "أب وابن بنيا مكتب محاسبة معًا — التوريث والشراكة والعمل الأسري بألفاظهما.",
  },
  {
    id: "nPFm_CEg4go",
    title: "العمل في مجال المخاطرة المالية مع فيصل الجاسر | بودكاست بترولي",
    channel: "إذاعة مختلف",
    length: "1:38:39",
    views: "37K",
    category: "conversations",
    blurbEn: "A risk professional's career conversation — what financial-risk work really involves and how to enter it from accounting.",
    blurbAr: "حوار مساري مع أحد متخصصي المخاطرة المالية — ماذا تنطوي الوظيفة وكيف تدخلها من المحاسبة.",
  },
  {
    id: "IViBzDwpCcc",
    title: "كيف تتطور مهنيًا — بودكاست محاسبي مع أ. أحمد يوسف",
    channel: "Fatih Mohamed",
    length: "1:54:14",
    views: "6.1K",
    category: "conversations",
    blurbEn: "A host-and-guest accounting podcast — how to develop professionally, move between roles, and keep growing.",
    blurbAr: "بودكاست محاسبي بإدارة وضيف — كيف تتطور مهنيًا وتنتقل بين الوظائف وتواصل النمو.",
  },
]
