/** v27 — the new-course shelf (auto-generated from live-verified
 *  YouTube harvests; every lesson id oEmbed-verified on 2026-10-01 by
 *  scripts/yt-harvest-v27.ts, data in /tmp/h-*.json).
 *
 *  Eight additions:
 *    · Office pair the learner asked for — ADVANCED EXCEL + WORD, Arabic
 *      AND English (Al Assaal, Qonswa, TrumpExcel, Learn Skills Daily)
 *    · More Arabic accounting — the 39-hour IAS/IFRS standards library of
 *      Dr. Zuhair, financial accounting from zero (AMS), cost accounting
 *      (Essam El-Sayyad) and financial-statement analysis (Hossam Saad)
 *
 *  Imported by video-courses.ts and appended to VIDEO_COURSES. */

import type { VideoCourse } from "./video-courses"

export const VIDEO_COURSES_V27: VideoCourse[] = [
  {
    id: "alassaal-excel-complete",
    titleEn: "Master Excel — the complete Arabic Excel course",
    titleAr: "احترف أكسل — الكورس الكامل للإكسل",
    channel: "Mohamed Al Assaal - اتعلم مع العسال",
    category: "excel",
    level: "Beginner",
    language: "AR",
    hours: "~12h",
    views: "67 verified lessons",
    descEn: "The complete 67-episode Excel course in Egyptian Arabic — formulas and dates, SUMIFS, filters, formatting, charts and printing, building up lesson by lesson from zero to comfortable daily use.",
    descAr: "الكورس الكامل للإكسل بـ٦٧ حلقة بالعربية المصرية — المعادلات والتواريخ وSUMIFS والتنقية والتنسيق والرسوم البيانية والطباعة، درسًا بعد درس من الصفر حتى الاستخدام اليومي المريح.",
    lessons: [
      { id: "uRs8_EJqTFo", title: "اتعلم اكسل من الصفر للمبتدئين- الحلقه 1 - EXCEL from scratch", length: "15:02" },
      { id: "XcuXLqLNJCY", title: "اتعلم اكسل من الصفر للمبتدئين - حلقه 2: ازاي تتعامل مع التاريخ في ال اكسل و تستخدم معادلات اساسيه", length: "9:43" },
      { id: "-fQ0dblhHUM", title: "Excel Sumifs - حلقه 3 : اتعلم اكسل من الصفر معادلة", length: "3:52" },
      { id: "KoE-9Ux0AXw", title: "Excel for Beginners حلقه 4 : اتعلم اكسل من الصفر للمبتدئين - عمليات حسابيه اساسيه", length: "8:33" },
      { id: "tVa-KQhcSWA", title: "Excel for Beginners - Filters حلقه 5 : اتعلم اكسل من الصفر للمبتدئين - استخدم التنقية", length: "8:18" },
      { id: "8RQmilwZfWY", title: "حلقه 6 اتعلم اكسل من الصفر- انسخ بيانات بدون تكرار Excel for Beginners", length: "7:46" },
      { id: "DHcdXd-phx8", title: "حلقه 7  اتعلم اكسل: الرسوم  البيانية Excel Charts", length: "10:54" },
      { id: "4tMORHaUbZA", title: "حلقه 8  اتعلم اكسل معادلة Vlookup Excel", length: "7:35" },
      { id: "cvleNKP29ww", title: "حلقة 9 اكسل معادلة Subtotal - Excel - اعمل كشف مختصر لأي حاجه بسهوله", length: "7:34" },
      { id: "LS02GT5fvro", title: "حلقه 10 من اتعلم الاكسل - معادلة IF الشرطيه - Excel 2020", length: "7:21" },
      { id: "b5rD0-KSoR0", title: "اعمل احلي تنسيق لجدول في الاكسل - حلقه 11 اتعلم أكسل - Excel Conditional Formatting", length: "7:36" },
      { id: "IM666zAXFtc", title: "احترف ال Pivot Tables في الاكسل - الجزء 1  - Excel : حلقه ١٢", length: "19:19" },
      { id: "qQqv277aA5E", title: "احترف ال Pivot Tables جزء 2 من تعليم الاكسل - حلقه 13", length: "15:52" },
      { id: "PsGdCePVsPw", title: "اعمل لوحة تحكم احترافيه في الاكسل في نص ساعه - حلقه 14 من اتعلم الاكسل - Excel Dashboard", length: "32:26" },
      { id: "-E7DxYwek_8", title: "اجمع و اطرح  من التاريخ في الاكسل  - حلقه 15 - اتعلم اكسل", length: "6:16" },
      { id: "yurUrEuVmVs", title: "اتعلم تعمل قائمة منسدله - حلقة 16 اتعلم الاكسل Drop Down List - Excel", length: "3:25" },
      { id: "esVS2Gz4B90", title: "اتعلم الترتيب في الاكسل-  Excel Sorting - حلقه 17", length: "5:49" },
      { id: "hj84DqiuKTU", title: "تحدي رمضان مع الاكسل - هتحافظ علي الصلاه و القرأن بالاكسل - حلقه 18", length: "34:18" },
      { id: "lK_qJAhZpms", title: "7 مهارات احترافيه متعرفهمش في ال Pivot Tables في الاكسل", length: "12:44" },
      { id: "MSODrdO4YQk", title: "معادلة iNDEX AND mATCH في الاكسل اسهل شرح", length: "17:50" },
      { id: "v1-fPm6BbvU", title: "حل مشاكل الجمع في الاكسل بأستخدام معادلة Aggregate", length: "5:33" },
      { id: "RxqZ1_PEBKA", title: "نموزج ادخال بيانات في اكسل بسهوله و من غير برمجه", length: "6:59" },
      { id: "LAv9SAL_T8U", title: "طلع البيناتات اللي عايزها في لحظه بأستخدام ال Combo Box في الاكسل", length: "6:01" },
      { id: "5p3Fsl4Zijs", title: "اهم اختصارات الاكسل اللي هتنقذ حياتك", length: "8:35" },
      { id: "Owzx_t4onCQ", title: "ازاي تفتح شيت اكسل نسيت الباسورد بتاعته ؟ و من غير برامج", length: "6:34" },
      { id: "lV8Tt1SPYq4", title: "ازاي تحول قائمة الدخل الي رسم بياني في الاكسل", length: "5:22" },
      { id: "dN6tH5ubWeI", title: "حل مشاكل الطباعه في الاكسل", length: "13:47" },
      { id: "FZGXOrPzGi4", title: "ازاي تعمل تقرير محترف في الاكسل - باستخدام Progress Tracking Bar", length: "5:44" },
      { id: "4kZhdCNYNZM", title: "خليك صايع في الاكسل و استخدم Advanced Filters عشان توفر وقت", length: "7:00" },
      { id: "bbjTdoSwHvE", title: "نظم بياناتك صح في الاكسل بأستخدام ال Check Box", length: "10:42" },
      { id: "hPzMl-DUujQ", title: "ازاي تشيل التكرار ب 3 طرق مختلفه في الاكسل", length: "10:47" },
      { id: "Znl_KTK_3YY", title: "ازاي تحسب عدد الايام بين التاريخ", length: "6:51" },
      { id: "EApBXl4oUAo", title: "سيبك من ال Filters و استخدم الخاصيه دي احسن في الاكسل", length: "6:29" },
      { id: "xZ1-Hvo68Ak", title: "الجداول الديناميكيه في الاكسل هتغير حياتك", length: "16:08" },
      { id: "J3CpzPTFihA", title: "ازاي تستخدم ال Macros في الاكسل عشان الاعمال التكراريه", length: "9:50" },
      { id: "WrWP1ZOWEzY", title: "ازاي تربط النص بالارقام في الاكسل و كمان تعمل عليهم معادلات - Excel", length: "8:58" },
      { id: "qUGlSYbB2mM", title: "3 خواص في الاكسل مهمه جدا انت متعرفش عنهم حاجه", length: "9:55" },
      { id: "TasKTAsfj28", title: "طريقة الجمع بناءا علي فترة تاريخ في الاكسل مش هتصدق انها موجوده", length: "12:57" },
      { id: "4YcMKkbFwH4", title: "ازاي تعمل خريطة رسم بياني بالاكسل -  و ابهر المدير", length: "8:29" },
      { id: "4MIfCqf_Y8k", title: "ازاي تقارن بين ورقتين  في الاكسل", length: "8:50" },
      { id: "bpv_WleDLyc", title: "ازاي تربط الاكسل بال ورد ب 3 طرق مختلفه", length: "11:46" },
      { id: "OnKG1EYBcLw", title: "اتعلم ازاي تدمج اكتر من صفحه او ملف في الاكسل و وفر وقتك", length: "8:59" },
      { id: "27vzz4g8nbo", title: "من اقوي معادلات الاكسل اللي مش هتصدق انها موجوده", length: "13:40" },
      { id: "hhY8I0UQo5Y", title: "خاصية تنبؤ البيانات في الاكسل رهيبه - انت مش عارفها", length: "11:06" },
      { id: "hZ8ekXd6h0A", title: "أقوي 8 خصائص يستخدمها المحترفين في الاكسل", length: "12:55" },
      { id: "W0h-omHHzNg", title: "ازاي تعمل قائمة منسدلة معتمده علي قائمة منسدله تانيه", length: "15:55" },
      { id: "ShHr6DtI6bY", title: "اهم المعادلات الاحصائيه في الاكسل لتحليل البيانات", length: "13:36" },
      { id: "3dv3Jfssqc8", title: "ازاي تعمل تقرير محترف برسم بياني داخل الخليه في الاكسل", length: "10:41" },
      { id: "DhK1Hi_IRAE", title: "المعادلة السحريه في الاكسل لأستخراج البيانات", length: "9:27" },
      { id: "ik8AJXH8lNU", title: "معادلة العد الغير تكراري في الاكسل مش هتصدق انها موجوده", length: "12:58" },
      { id: "WuHKsUnd83M", title: "المعادلة الاقوي في تاريخ الاكسل للعد الغير تكراري لأي حاجه", length: "11:00" },
      { id: "CtnA8BD21pI", title: "معادلة Offset في الاكسل", length: "10:41" },
      { id: "DsfCbDxjXJs", title: "احمي بياناتك بالخاصيه الرهيبه دي الاكسل", length: "6:41" },
      { id: "XgnBlrMrVzw", title: "ازاي تعمل تقرير مختصر بناءا علي التاريخ في الاكسل بشكل احترافي", length: "9:34" },
      { id: "dT_Jv-ra9PQ", title: "اعرف 3 معادلات مهمه للأستخدام اليومي في الاكسل", length: "5:00" },
      { id: "_9peUgeHvmQ", title: "أشهر 3 معادلات مهمه لو عايز تتعلم تحليل بيانات في 2022", length: "16:11" },
      { id: "PYgZ3b1Q8s4", title: "اهم 9 اختصارات تبقي عارفهم في الاكسل", length: "6:58" },
      { id: "vdaYgkWbQog", title: "رسم بياني في الاكسل مهم جدا انت مش عارفه و هيغير حياتك", length: "6:17" },
      { id: "aklqlx4x0N0", title: "غير حياتك و نظرتك للبيانات بالرسم البياني ده في الاكسل", length: "7:07" },
      { id: "23MygSGTcUo", title: "غير حياتك بالتنسيق الشرطي بال Icon Sets", length: "5:30" },
      { id: "4uScGYjHLEs", title: "ازاي تستخدم ال Pivot Tables صح في الاكسل", length: "14:39" },
      { id: "3NwavxFjTuk", title: "معادلة Hlookup كما لم تراها من قبل", length: "8:05" },
      { id: "T_aPvYF9G98", title: "سر استخدام معادلة Index & Match بشكل صحيح", length: "12:21" },
      { id: "cjrVB2ChELs", title: "معادلة Xlookup في الاكسل", length: "12:26" },
      { id: "u08swSivQrM", title: "رسم بياني مش هتصدقه في الاكسل و هيغير تفكيرك", length: "9:08" },
      { id: "8rl4cscgKEw", title: "اهم 3 معادلات نصيه في الاكسل   هتخسر كتير لو مش عارفهم", length: "9:00" },
      { id: "xZztgHEXmGk", title: "عبر عن بياناتك بشكل مميز بال Area Chart في الاكسل", length: "10:13" },
    ],
  },
  {
    id: "qonswa-word-complete",
    titleEn: "Microsoft Word — the complete Arabic Word course",
    titleAr: "كورس برنامج مايكروسوفت وورد بالكامل",
    channel: "Mohamed Qonswa",
    category: "word",
    level: "Beginner",
    language: "AR",
    hours: "~5h",
    views: "33 verified lessons",
    descEn: "A complete 33-episode Microsoft Word course in Arabic — formatting, styles, tables, images, headers and footers, mail merge and professional report layout: the Word side of the office duo you asked for.",
    descAr: "كورس وورد كامل بـ٣٣ حلقة بالعربية — التنسيق والأنماط والجداول والصور والترويسات ودمج المراسلات وإخراج التقارير الاحترافية: واجه المكتب المكتمل الذي طلبته.",
    lessons: [
      { id: "xFKGAyou5jo", title: "تعلم برنامج الوورد بكل سهوله للمبتدئين في 20 دقيقه ✅ #word", length: "20:12" },
      { id: "s81G5_m0mfE", title: "مايكروسوفت وورد - تنسيق الكتابه بطريقه احترافيه في دقائق⏱ #word", length: "7:23" },
      { id: "9lWFlYDrpxc", title: "مايكروسوفت وورد - تنسيق الفقرات بطريقه احترافيه #world", length: "7:20" },
      { id: "KA_Z5eJQEpw", title: "الكتابه بالصوت في برنامج الوورد هتغير حياتك !!", length: "6:32" },
      { id: "8_jfeE3Kt8Y", title: "طريقه استخدام الأنماط (Styles) بكل سهوله في الوورد", length: "10:07" },
      { id: "6NCDZ1XEvh4", title: "أفضل طريقه لانشاء جدول المحتويات (الفهرس) بكل سهوله #word", length: "10:19" },
      { id: "DtTZUVIyNUk", title: "كل ما يخص إنشاء الجداول وتنسيقها بطريقه إخترافيه في الوورد #word", length: "12:39" },
      { id: "CBLwyeO58gI", title: "تصحيح الأخطاء الاملائيه في برنامج الوورد بطريقه سحريه", length: "8:33" },
      { id: "s4zZEseW0NM", title: "تعلم الرسم البياني في الوورد بكل سهوله", length: "11:28" },
      { id: "Zlz1I3r2NbY", title: "انشاء جدول (فهرس ) الصور والمحتويات بكل سهوله في برنامج الوورد #word", length: "8:51" },
      { id: "5bCT2Q-Obdk", title: "اضافه الصور والتعديل عليها في برنامج الوورد بكل سهوله 😎", length: "13:31" },
      { id: "jnPR8BWtLjU", title: "طريقه اضافه الرأس والتذييل ( Header & footer) بكل سهوله في الوورد #word", length: "9:11" },
      { id: "p8v7s6T8U3k", title: "طريقه عمل رأس وتذييل مختلف لصفحات الوورد بطريقه سحريه #word", length: "6:02" },
      { id: "LHXF2aqy-LQ", title: "أسهل طريقه لإضافه ترقيم لصفحات الوورد page numbering", length: "7:30" },
      { id: "d2Q445FXezQ", title: "بدء ترقيم صفحات الوورد من صفحه معينه في الوورد #word", length: "4:56" },
      { id: "PWsAzgyF9xQ", title: "طريقه سحريه 😎 لعمل حدود وإطارات مميزه خاصه بك في برنامج الوورد", length: "10:50" },
      { id: "B5h7MzFFybg", title: "أسهل طريقه لعمل حدود وإطارات مميزه جدا داخل برنامج الوورد ✅", length: "7:35" },
      { id: "UG9jmft_R2g", title: "أسهل 3 طرق لحفظ ملف الوود وتحويل الملف إلي PDF ✅", length: "5:39" },
      { id: "iZ6PcSbeLbE", title: "أسهل ثلاث طرق لتحويل ملف pdf إلي Word", length: "7:57" },
      { id: "aeQownpdNl8", title: "إضافه الأشكال والرسومات وتنسيقاتها بطريقه إحترافيه في برنامج الوورد✅", length: "13:34" },
      { id: "LQ-EJB6HkH4", title: "طريقه البحث والاستبدال (Find & Replace) بكل سهوله في برنامج الوورد✅", length: "6:20" },
      { id: "6M3gB85KP6Y", title: "كيفية عمل مخطط هيكلي بكل سهوله في الوورد (SmartArt)#word", length: "10:37" },
      { id: "7b1g9TNkLgY", title: "كيفيه إضافه علامه مائيه في ملفات الوورد ✅", length: "7:08" },
      { id: "58niJIYv_VA", title: "تبادل البيانات بين برنامج الإكسيل والوورد بكل سهوله ✅", length: "8:21" },
      { id: "3AY8SPeZCw8", title: "كل ما يخص ضبط إعدادات الصفحه في الوورد ✅", length: "12:20" },
      { id: "W7EtSvM9KG0", title: "تعلم طباعه ملفات الوورد بكل سهوله #word", length: "7:24" },
      { id: "s19KbwR7YXE", title: "أسهل ثلاث طرق لحذف الصفحات الفارغه في ملفات الوورد#word", length: "2:48" },
      { id: "TKR81H3XrWM", title: "طريقه عمل دمج المرسلات (Mail merge) بكل سهوله", length: "12:47" },
      { id: "T6MTiomAdP8", title: "طريقه عمل إستماره أو فورم قابل للتعديل علي برنامج الوورد بكل سهوله ✅", length: "13:30" },
      { id: "0vfRn05_zNY", title: "كيفيه إضافه قوائم منسدله وعناصر إدخال في برنامج الوورد بكل سهوله 👌", length: "4:26" },
      { id: "kfloOh79CKQ", title: "إضافه المعادلات الرياضيه بكل سهوله في برنامج الوورد", length: "9:58" },
      { id: "j9IykWG-3lg", title: "إضافه الاقتباس و المراجع في برنامج مايكرسوفت وورد #word", length: "7:38" },
      { id: "mkgQRusro9w", title: "أهم 20 إختصار لإحتراف برنامج الوورد ✅", length: "11:33" },
    ],
  },
  {
    id: "trumpexcel-basic-advanced",
    titleEn: "FREE Excel Course — Basic to Advanced (TrumpExcel)",
    titleAr: "كورس إكسل مجاني من الأساسيات إلى المتقدم (TrumpExcel)",
    channel: "TrumpExcel",
    category: "excel",
    level: "Intermediate",
    language: "EN",
    hours: "~13h",
    views: "26 verified lessons",
    descEn: "Sumit Bansal's famous free Excel course — 26 sessions from cell basics to Excel tables, PivotTables, dashboards, formulas in depth (VLOOKUP/XLOOKUP, SUMIFS, IF, dynamic arrays), data cleaning and reporting best practice.",
    descAr: "كورس الإكسل المجاني الشهير من سوميت بانسال — ٢٦ جلسة من أساسيات الخلية إلى الجداول والجداول المحورية ولوحات المتابعة والمعادلات المتقدمة (VLOOKUP وXLOOKUP وSUMIFS والمصفوفات الديناميكية) وتنظيف البيانات.",
    lessons: [
      { id: "UPABcYhugZk", title: "Getting Started with Excel | Excel For Beginners | FREE Excel Course", length: "22:17" },
      { id: "4AXAXUYZnkc", title: "[FREE Excel Course] Lesson 2 - Data Entry, Editing, and Number Formatting", length: "21:03" },
      { id: "1LgkR1R1ACU", title: "[FREE EXCEL COURSE] Lesson 3   - Data Formatting in Excel", length: "25:02" },
      { id: "B16UleW3uUM", title: "[FREE EXCEL COURSE] Lesson 4 - Working with Cells and Ranges", length: "33:39" },
      { id: "u1GZVWU7g6Q", title: "[FREE EXCEL COURSE] Lesson 5 - Managing Worksheets in Excel", length: "16:45" },
      { id: "d4yrHvcyesY", title: "[FREE EXCEL COURSE] Lesson 6  - Excel Tables Overview", length: "21:17" },
      { id: "JiRWjeYza9A", title: "[FREE EXCEL COURSE] Lesson 7 - Auto-fill, Custom Lists, and Flash Fill", length: "13:53" },
      { id: "NcqVt95jghE", title: "[FREE EXCEL COURSE] Lesson 8 - Number Formatting in Excel", length: "26:28" },
      { id: "Bv61rIeKsaI", title: "[FREE Excel Course] Lesson 9 - Excel Formula Basics", length: "26:39" },
      { id: "6GqeLXOE82Q", title: "[FREE Excel Course] Lesson 10  - Logical Formulas in Excel", length: "23:27" },
      { id: "k9aqD-ifh0k", title: "[FREE Excel Course] Lesson 11 - Math Formulas in Excel", length: "33:36" },
      { id: "qo5N8wR3rz8", title: "[FREE Excel Course] Lesson 12 - Lookup and Reference Formulas in Excel", length: "46:57" },
      { id: "DbHgv7dK0h4", title: "Stats Formulas in Excel - Explained with Examples", length: "41:37" },
      { id: "1JbR65m3bb8", title: "[FREE Excel Course] Lesson 14 - Text Formulas in Excel", length: "32:14" },
      { id: "R6O8DNWN078", title: "[FREE EXCEL COURSE] Lesson 15 - Date & Time Formulas in Excel", length: "40:53" },
      { id: "OQRt_KSHIAY", title: "10 Advanced Excel Formula Examples | FREE Excel Course", length: "45:09" },
      { id: "FKnMQ83EwBs", title: "Creating Named Ranges in Excel | Dynamic Named Range in Excel | FREE Excel Course", length: "22:43" },
      { id: "e29MMixNycI", title: "Data Validation in Excel | Drop-down lists | FREE Excel Course", length: "31:06" },
      { id: "yzH01AawU-4", title: "Data Sorting & Filtering in Excel (Basic + Advanced) | FREE Excel Course", length: "16:37" },
      { id: "WLgkCCi7H8c", title: "Excel Conditional Formatting (Overview + Advanced Examples)", length: "25:18" },
      { id: "yogxl3hMkis", title: "Introduction to Excel Charting | Excel Charts for Beginners", length: "35:49" },
      { id: "KMptCpaTApQ", title: "10 Advanced Excel Charts and Graphs (Creating from Scratch) | FREE Excel Course", length: "51:07" },
      { id: "7YTeiatoyuo", title: "Creating Dynamic Charts in Excel (Using Drop-down List and Scroll Bar) | FREE Excel Course", length: "27:24" },
      { id: "4Q0FYcvIfFg", title: "Excel Pivot Table (Intro, Formatting, Grouping, Slicers, Calculated Fields) | FREE Excel Course", length: "47:37" },
      { id: "MPlvhwb3iZw", title: "Protecting Worksheets / Workbooks in Excel | Lock Worksheets in Excel | FREE Excel Course", length: "9:17" },
      { id: "MWw3zlR3yXo", title: "Introduction to Excel Macros (For Excel VBA Beginners) | FREE Excel Course", length: "16:54" },
    ],
  },
  {
    id: "lsd-word-full",
    titleEn: "Microsoft Word — the full course",
    titleAr: "وورد — الكورس الكامل",
    channel: "Learn Skills Daily",
    category: "word",
    level: "Intermediate",
    language: "EN",
    hours: "~7h",
    views: "4 long-form sessions",
    descEn: "A four-session deep Word masterclass (nearly 7 hours) — long-document architecture, styles and templates, tables of contents, captions, sectioning, references and collaboration-ready documents.",
    descAr: "ورشة وورد متقدمة في أربع جلسات (نحو ٧ ساعات) — هندسة المستندات الطويلة والأنماط والقوالب والفهرس والتسميات والتقسيم والمراجع والمستندات الجاهزة للتعاون.",
    lessons: [
      { id: "w5YeZYgF6TQ", title: "Word Beginner Tutorial", length: "1:50:18" },
      { id: "lsX0CjHSJ5Y", title: "Word Intermediate Tutorial", length: "2:04:22" },
      { id: "TXBuw25w9Z0", title: "Word Advanced Tutorial", length: "2:18:29" },
      { id: "VIcdR9Enf8c", title: "Word Copilot Tutorial", length: "38:04" },
    ],
  },
  {
    id: "zuhair-ifrs-standards",
    titleEn: "International Accounting Standards — the complete IFRS/IAS series",
    titleAr: "معايير المحاسبة الدولية — سلسلة IFRS/IAS الكاملة",
    channel: "Dr. Zuhair Barhamzaid - د. زهير برهم زيد",
    category: "ifrs",
    level: "Advanced",
    language: "AR",
    hours: "~39h",
    views: "81 verified lessons",
    descEn: "The most complete Arabic standards library on the channel shelf — 81 lectures walking the Conceptual Framework (1989→2018) then IAS 1 through the IFRS corpus: presentation, inventory, leases, revenue, financial instruments, consolidation, with worked examples throughout.",
    descAr: "أكمل مكتبة معايير بالعربية على الرف — ٨١ محاضرة تسير بالإطار المفاهيمي (١٩٨٩ حتى ٢٠١٨) ثم معيار المحاسبة الدولي رقم ١ وما بعده عبر منظومة IFRS: العرض والمخزون والإيجارات والإيرادات والأدوات المالية والتجميع، بأمثلة محلولة.",
    lessons: [
      { id: "-cFoLG2YntY", title: "(1.1) تطور الاطار المفاهيمي خلال 1989، 2001، 2011، 2018", length: "5:52" },
      { id: "9p5AsM29ocQ", title: "(1.2) الاطار المفاهيمي للتقارير المالية 2010 - مقدمة عامة", length: "32:20" },
      { id: "ARV-aoSCA2E", title: "(1.3) الاطار المفاهيمي للتقارير المالية 2010 - التطور والهدف", length: "1:00:28" },
      { id: "uImzjOlHpI4", title: "(1.4) الاطار المفاهيمي للتقارير المالية 2010 - الخصائص والقديم", length: "58:34" },
      { id: "m3Tib7PDwgI", title: "(2.1) معيار المحاسبة الدولي رقم (1) - الهدف، النطاق، والقوائم المالية (IAS 1)", length: "47:57" },
      { id: "SZHLWO9ry2E", title: "(2.2) معيار المحاسبة الدولي رقم (1) - الملامح العامة (IAS 1)", length: "1:01:35" },
      { id: "AxANL_P9tUI", title: "(2.3) معيار المحاسبة الدولي رقم (1) - التعريف بالقوائم، الفوائد، العيوب (IAS 1)", length: "56:35" },
      { id: "T2xB5T-z2HY", title: "(2.4) معيار المحاسبة الدولي رقم (1) - الاصول المتداولة- النقدية والاستثمارات للمتاجرة  (IAS 1)", length: "57:27" },
      { id: "nEPDItE00Mc", title: "(2.5) معيار المحاسبة الدولي رقم (1) - المخزون، الذمم، المقدم، والاصول غير المتداولة  (IAS 1)", length: "35:58" },
      { id: "7EJlCxIMf7A", title: "(2.6) معيار المحاسبة الدولي رقم (1) - الالتزامات وحقوق الملكية  (IAS 1)", length: "55:35" },
      { id: "SgCgJtD0DXQ", title: "(2.7) معيار المحاسبة الدولي رقم (1) - قائمة الربح او الخسارة والدخل الشامل الاخر  (IAS 1)", length: "1:07:58" },
      { id: "BOyJRFRuOrs", title: "(2.8) معيار المحاسبة الدولي رقم (1) - قائمة التغير في حقوق الملكية (IAS 1)", length: "37:28" },
      { id: "bzbvjLkEqhM", title: "(2.9) معيار المحاسبة الدولي رقم (1) - الايضاحات المرفقة  (IAS 1)", length: "1:00:31" },
      { id: "OVZPQp15SwM", title: "(2.10) معيار المحاسبة الدولي رقم (2) - الهدف، النطاق، المبدأ، تعريفات، الملكية، الانظمه - (IAS 2)", length: "57:42" },
      { id: "qOml2831wM0", title: "(2.11) معيار المحاسبة الدولي رقم (2) -  تكلفة المخزون، اساليب قياس التكلفة (IAS 2)", length: "56:28" },
      { id: "JiAJ97XFZc8", title: "(2.12) معيار المحاسبة الدولي رقم (2) -  تقييم المخزون، الاعتراف بالمخزون كمصروف، الافصاح (IAS 2)", length: "27:38" },
      { id: "Cm3D0WEoS-Y", title: "(2.13) تمرين حول تحديد تكلفة وقيمة المخزون بالفايفو في ظل الجرد المستمر وفقا لمعيار البضاعة (IAS 2)", length: "51:54" },
      { id: "W4fsMMrluzw", title: "7.1  معيار المحاسبة الدولي رقم (7) - قائمة التدفقات النقدية - فائدتها، الهدف...... الصافي (IAS 7)", length: "50:47" },
      { id: "Wp5UggqxQFQ", title: "7.2 معيار المحاسبة الدولي رقم (7) - قائمة التدفقات النقدية - العملات الاجنبية،،،الافصاحات (IAS 7)", length: "1:06:02" },
      { id: "4xaiMli3fRQ", title: "7.3  معيار قائمة التدفقات النقدية - مثال على الطريقة المباشرة وغير المباشرة (IAS 7)", length: "58:53" },
      { id: "UtoUR0WvROg", title: "IAS 7 - تمرين 12 ‫صفحة 120 - حول التدفقات النقدية من العمليات التمويلية", length: "5:03" },
      { id: "xsC8tlnPaCo", title: "7.4  معيار قائمة التدفقات النقدية - تمرين 3 ص 125 على الطريقة غير المباشرة (IAS 7)", length: "33:24" },
      { id: "Lpr2aAVk7_Y", title: "8.1  معيار التغير في السياسات والتقديرات المحاسبية والأخطاء - الهدف، النظاق، التعريف (IAS 8)", length: "30:25" },
      { id: "i6GKs2mCQ78", title: "8.2  معيار التغير في السياسات والتقديرات المحاسبية والأخطاء - السياسات المحاسبية (IAS 8)", length: "53:10" },
      { id: "WyLj_Ap4kQg", title: "8.3  مثال حول التغيير في السياسة المحاسبية باثر رجعي من سنوات سابقة غير معروضة  (IAS 8)", length: "48:11" },
      { id: "0dMtuLeQtBo", title: "8.4)   مثال حول التغيير في السياسة المحاسبية مع التطبيق باثر مستقبلي وفقا لمعيار رقم  8  (IAS 8)", length: "7:23" },
      { id: "lqSJRRoze_I", title: "8.5  معيار التغير في السياسات والتقديرات المحاسبية والأخطاء - التغيير في التقديرات (IAS 8)", length: "14:01" },
      { id: "jSXLwzEdzx4", title: "8.6)    مثال حول التغيير في التقديرات المحاسبية مع التطبيق باثر مستقبلي وفقا لمعيار رقم  8  (IAS 8)", length: "16:51" },
      { id: "hKoI5tMWyOk", title: "8.7  معيار التغير في السياسات والتقديرات المحاسبية والأخطاء -الاخطاء (IAS 8)", length: "43:32" },
      { id: "5cmvSv-77wQ", title: "10.1 معيار الاحداث اللاحقة لفترة التقرير (IAS 10)", length: "47:07" },
      { id: "g1OzNK-66ro", title: "10.2)   معيار الاحداث اللاحقة لفترة التقرير- تمرين 2 ص 171 (IAS 10)", length: "23:21" },
      { id: "h1R25QE3CMg", title: "IFRS 1 - معيار التبني الاول لمعايير الابلاغ المالي الدولية", length: "49:01" },
      { id: "VGXbcf9cZN8", title: "IFRS 1 - معيار التبني الاول لمعايير الابلاغ المالي الدولية - تمرين اختيار من متعدد", length: "10:46" },
      { id: "ZB1AG1ihKWQ", title: "IFRS 1 - معيار التبني الاول لمعايير الابلاغ المالي الدولية - تمرين عن تاريخ التحول", length: "4:01" },
      { id: "Bx-pdwklRMo", title: "IFRS 1 - معيار التبني الاول لمعايير الابلاغ المالي الدولية - تمرين شامل", length: "17:50" },
      { id: "zvTepeY_TZM", title: "IFRS 7 - معيار افصاحات الادوات المالية - الهدف ، النطاق، افصاحات الميزانية وقائمة الدخل الشامل", length: "37:18" },
      { id: "Gk5BXpbeoqs", title: "IFRS 7 - معيار افصاحات الادوات المالية - افصاحات مخاطر الائتمان، مخاطر السيولة، ومخاطر السوق", length: "20:03" },
      { id: "b1ukx3jau7I", title: "IFRS 10 - معيار القوائم المالية الموحدة، مثال على التملك الكامل", length: "11:54" },
      { id: "Doy5_5Fr_1Y", title: "IFRS 10 - معيار القوائم المالية الموحدة، مثال على التملك غير الكامل", length: "22:20" },
      { id: "c4zlNrV94-A", title: "IFRS 10 - مثال  اعداد القوائم المالية الموحدة خلال الفترات التالية للتملك غير الكامل", length: "1:46:05" },
      { id: "sQnPMj2MwzI", title: "IFRS 10 - معيار القوائم المالية الموحدة - الهدف، النطاق، تعريفات، المتطلبات المحاسبية، الافصاح", length: "30:14" },
      { id: "iizlt-sCgaM", title: "IFRS 10 - اجراءات اعداد القوائم المالية الموحدة وطرق المعالجة المحاسبية", length: "38:04" },
      { id: "OC-P-NT_rk4", title: "IFRS 10 - تمرين 3 ص 795:  قيود طريقة الملكية، الملكية غير المكتملة، والتكلفة، وترصيد حساب الاستثمار", length: "32:51" },
      { id: "eTx0Rj5wrwU", title: "شرح معيار IAS 2 - Objective, Scope, Definitions", length: "15:00" },
      { id: "xb0DCf3UW2Y", title: "شرح معيار IAS 2 - Measurement of inventories", length: "26:56" },
      { id: "6DmUBLq4J9c", title: "شرح معيار IAS 2 - Recognition as an expense, Disclosure", length: "10:16" },
      { id: "kN0EqH9iTJ8", title: "v1- Conceptual Framework- Introduction", length: "14:04" },
      { id: "rXRMhS0QACA", title: "v2- Conceptual Framework- Objective of general purpose financial reporting", length: "25:31" },
      { id: "zjp9UfCeCjc", title: "v3- Conceptual Framework- Qualitative characteristics of financial information", length: "29:05" },
      { id: "iXYcxk9q11g", title: "v4- Conceptual Framework- Financial statements and the reporting entity", length: "9:53" },
      { id: "PpmAD_rFg6g", title: "v5- Conceptual Framework- Elements of financial statements", length: "22:23" },
      { id: "VESs0jI2Cbg", title: "v6- Conceptual Framework- Recognition and Derecognition", length: "11:34" },
      { id: "tnsTUffI11I", title: "v7- Conceptual Framework- Measurement", length: "23:38" },
      { id: "8OVVkOufyn8", title: "v8- Conceptual Framework- Presentation and disclosure", length: "13:12" },
      { id: "IlR_-kyfLHE", title: "v9- Conceptual Framework  - Concepts of capital and capital maintenance", length: "15:21" },
      { id: "hSu4-iX_6s0", title: "V1-1 - Prepare Consolidated Income Statement", length: "22:25" },
      { id: "swMJZNTs17w", title: "V1-2 - Prepare Consolidated Comprehensive Income Statement", length: "11:34" },
      { id: "rpWXB4yKtm0", title: "V1-3 - Prepare Consolidated Statement of Changes in Equity", length: "16:46" },
      { id: "HNoRTrMjARM", title: "V1-4 - Prepare Consolidated Balance Sheet", length: "7:49" },
      { id: "2U_dHuzZB-Y", title: "IAS 2 - Lower of cost and NRV", length: "13:59" },
      { id: "PftdeiSNywg", title: "V2 1  Initial Cost of Inventory", length: "6:19" },
      { id: "fj-yWzcnpCo", title: "V7-1 Prepare a statement of cash flows - the indirect and direct  method - فيديو", length: "21:31" },
      { id: "NRK93oyPOlc", title: "‫V8-1 -  IAS 8 - Errors - Retrospectively", length: "15:37" },
      { id: "90JfKmbP8s8", title: "V8-2 Changes in accounting policies - Retrospectively", length: "13:23" },
      { id: "vEu6PBlaX90", title: "V8-3 Changes in accounting policies - Prospectively", length: "2:38" },
      { id: "nxwVsnhW7T4", title: "‫V8-4 Changes in accounting estimates - Prospectively", length: "3:35" },
      { id: "jA3FkhHJGCk", title: "‫‫V10 2 Non adjusting events after the reporting period", length: "10:05" },
      { id: "BV4P253f-Z4", title: "‫V10 3 Adjusting events after the reporting period", length: "6:27" },
      { id: "1DDTA9R8jyA", title: "V10 1 Date of authorisation for issue", length: "3:20" },
      { id: "qLsfJpjOnbc", title: "1 مقدمة عن معايير المحاسبة الدولية  -  قائمة المعايير", length: "16:06" },
      { id: "EoKf26qs5D0", title: "2 - مقدمة عن معايير المحاسبة الدولية  - IASB", length: "14:03" },
      { id: "vLoO5RX5pwY", title: "3-  مقدمة عن معايير المحاسبة الدولية  -  عملية اصدار المعايير", length: "17:10" },
      { id: "BvCTDuWXun8", title: "4- مقدمة عن معايير المحاسبة الدولية -  الهدف من اصدار معايير محاسبة دولية", length: "10:39" },
      { id: "d-eS5hZE_A4", title: "فيديو  - شرح المادة النظرية للمعيار الدولي رقم 1  (IAS 1)", length: "47:08" },
      { id: "FPMrUfV1Kvc", title: "V7-2 Prepare a statement of cash flows - the indirect and direct  method -", length: "53:12" },
      { id: "2g8nH3rAV8E", title: "فيديو - الشرح النظري للمعيار الدولي رقم 16 (Property, Plant and Equipment)", length: "37:55" },
      { id: "ghRZ0aGBBfY", title: "فيديو 2- تكلة الاصل الثابت عند الاقتناء - Q16-1 Recognition of costs of PPE", length: "12:30" },
      { id: "oCMnPrIh3P8", title: "قياس الاصل الثابت بدون استهلاك وفقا للمعيار الدولي رقم 16 - MEASUREMENT (WITHOUT DIPRECIATION)", length: "26:04" },
      { id: "eU2CJuy6L_M", title: "استبعاد او تعديل مجمع الاستهلاك في اعادة تقييم الاصل الثابت وفقا للمعيار الدولي رقم 16", length: "23:13" },
      { id: "c0znwpPPpqY", title: "فائض اعادة التقييم عند اعادة تقييم الاصل الثابت المستهلك وفقا للمعيار الدولي رقم 16", length: "6:24" },
      { id: "bSK4d5Fr4gY", title: "انخاض اعادة التقييم عند اعادة تقييم الاصل الثابت المستهلك وفقا للمعيار الدولي رقم 16", length: "5:19" },
    ],
  },
  {
    id: "ams-financial-accounting",
    titleEn: "Financial accounting from zero — 2024 Arabic course",
    titleAr: "كورس محاسبة مالية من الصفر — 2024",
    channel: "AMS للمحاسبة والضرائب",
    category: "accounting",
    level: "Beginner",
    language: "AR",
    hours: "~3h",
    views: "11 verified lessons",
    descEn: "An 11-session foundation course — the accounting cycle, journals and ledgers, trial balance, adjusting entries and the basic financial statements, taught in plain Arabic with solved exercises.",
    descAr: "كورس تأسيسي من ١١ جلسة — الدورة المحاسبية واليوميات والأستاذ وميزان المراجعة والتسويات والقوائم المالية الأساسية، بشرح عربي مبسط وتمارين محلولة.",
    lessons: [
      { id: "A7M2AwuPdOI", title: "كورس محاسبة مالية - (1)", length: "17:08" },
      { id: "dWDrg3TVqzQ", title: "كورس محاسبة مالية - (2)", length: "9:32" },
      { id: "9M1tkfVzCKg", title: "كورس محاسبة مالية - (3)", length: "17:15" },
      { id: "H7qJT2Tb7-g", title: "كورس محاسبة مالية - (4)", length: "40:23" },
      { id: "vuhsa4n_hM0", title: "كورس محاسبة مالية - (5)", length: "7:08" },
      { id: "MGfIXtbLbx0", title: "كورس محاسبة مالية - (6)", length: "12:33" },
      { id: "iyxao7br2No", title: "كورس محاسبة مالية - (7)", length: "16:22" },
      { id: "iwwdzJxxPAk", title: "كورس محاسبة مالية - (8)", length: "20:28" },
      { id: "h5qpYiZorUY", title: "كورس محاسبة مالية - (9)", length: "7:42" },
      { id: "61XV6nB6e48", title: "كورس محاسبة مالية - (10)", length: "11:57" },
      { id: "Y8_xmwRu2AY", title: "كورس محاسبة مالية كامل للمبتدئين - (11)", length: "12:31" },
    ],
  },
  {
    id: "essaad-cost-accounting",
    titleEn: "Cost accounting — the Arabic series",
    titleAr: "سلسلة كورس محاسبة التكاليف",
    channel: "عصام الصياد",
    category: "accounting",
    level: "Intermediate",
    language: "AR",
    hours: "~3h",
    views: "10 verified lessons",
    descEn: "A focused cost-accounting series — cost classification, materials and labour control, overhead allocation, job and process costing — the costing base that CMA Part 1 and ACCA MA build on.",
    descAr: "سلسلة محاسبة تكاليف مركزة — تصنيف التكاليف ورقابة المواد والعمالة وتحميل التكاليف الصناعية وأوامر ومراحل الإنتاج، وهي قاعدة التكاليف التي يبني عليها CMA الجزء الأول وACCA MA.",
    lessons: [
      { id: "aeBStsHTdWc", title: "كورس محاسبة التكاليف | الحلقة الأولى", length: "14:34" },
      { id: "-8K-crub1ew", title: "كورس محاسبة التكاليف | الحلقة الثانية", length: "19:23" },
      { id: "B8U7VfbQqew", title: "كورس محاسبة التكاليف | الحلقة الثالثة", length: "8:21" },
      { id: "7Zsj9kNeEdY", title: "كورس محاسبة التكاليف | الحلقة الرابعة", length: "9:43" },
      { id: "jJdQQV9rEDo", title: "كورس محاسبة التكاليف | الحلقة الخامسة", length: "10:23" },
      { id: "DMhXVbwE4gc", title: "كورس محاسبة التكاليف | الحلقة السادسة", length: "12:11" },
      { id: "UXJHqLLpNmE", title: "كورس محاسبة التكاليف | الحلقة السابعة", length: "22:22" },
      { id: "-KBcfWIilfE", title: "كورس محاسبة التكاليف | الحلقة الثامنة", length: "12:01" },
      { id: "VKFNK-16oVk", title: "كورس محاسبة التكاليف | الحلقة التاسعة", length: "29:13" },
      { id: "40kQm8IzD-k", title: "كورس محاسبة التكاليف - الحلقة العاشرة", length: "21:11" },
    ],
  },
  {
    id: "hossam-financial-analysis",
    titleEn: "Financial statement analysis — an integrated approach",
    titleAr: "التحليل المالي — مدخل متكامل",
    channel: "دليلك لفهم المحاسبة حسام سعد hossam saad",
    category: "accounting",
    level: "Intermediate",
    language: "AR",
    hours: "~4h",
    views: "8 verified lessons",
    descEn: "Hossam Saad's integrated analysis series — reading the statements as a set, ratio families (liquidity, leverage, profitability, efficiency), horizontal and vertical analysis, and drawing conclusions a lender or investor would act on.",
    descAr: "سلسلة حسام سعد للتحليل المتكامل — قراءة القوائم كمنظومة، وأسر النسب (السيولة والرفع والربحية والكفاءة)، والتحليل الأفقي والرأسي، واستخلاص استنتاجات يبنى عليها قرار مقرض أو مستثمر.",
    lessons: [
      { id: "uK1hzsCrhPA", title: "التحليل المالى | مقدمة لفهم واهمية وطرق وخطوات التحليل المالى (1)", length: "25:40" },
      { id: "fi-DAZ1ipZs", title: "التحليل المالى| التحليل الافقى والرأسى والاتجاه لشركة دومتى لعام 2021 واسباب الخسارة (2)", length: "45:43" },
      { id: "PmcKtxXdq4s", title: "التحليل المالى| فهم مدلول النسب المالية وكيفية الموازنة بين السيولة والربحية (3)", length: "31:28" },
      { id: "Tb7Nb76d19o", title: "التحليل المالى | حالات عملية باستخدام النسب المالية لشركة دومتى فى 2021 (4)", length: "35:30" },
      { id: "h4JcP3Y-Teg", title: "التحليل المالى | التحليل المالى الاساسى والفنى للبورصة والشركات المساهمة ومؤشراتهم (5)", length: "31:53" },
      { id: "PtBlraBLSMc", title: "التحليل المالى | نماذج التنبؤ بالفشل والعسر المالى (6)", length: "25:49" },
      { id: "13wN_R2Ekm8", title: "التحليل المالى| تحليل قائمة التدفقات النقدية ومؤشراتها  وحالة عملية شاملة(7)", length: "37:59" },
      { id: "LD3oW819ArI", title: "إزاى أدخل مجال التحليل المالي Financial Analysis وأهم الشهادات المهنية؟", length: "9:12" },
    ],
  },
]
