import type { DDSection } from "./types"

/** Financial due diligence — PER ACCOUNT, because a DD team staffs, tests,
 *  and reports by account area. One section = one account workstream with
 *  every instruction for that account in one place: the analytics to run,
 *  the information to request, the step-by-step procedures, and the red
 *  flags. F-01 … F-06 here; F-07 … F-12 in financial-b.ts. */
export const DD_FINANCIAL_A: DDSection[] = [
  {
    id: "revenue-qoe",
    code: "F-01",
    scope: "financial",
    group: "accounts",
    icon: "trending-up",
    title: { en: "Revenue & Quality of Earnings", ar: "الإيرادات وجودة الأرباح" },
    scopeNote: {
      en: "The account the price is built on: what revenue is real, repeatable, and arm's-length — and what EBITDA looks like once owner effects, one-offs, and accounting choices are stripped out.",
      ar: "البند الذي يُبنى عليه السعر: أي الإيراد حقيقي ومتكرر وبمعاملة مطلقة — وكيف تبدو الأرباح التشغيلية بعد تجريد آثار المالك والبنود لمرة واحدة والاختيارات المحاسبية.",
    },
    why: [
      { en: "Separate organic growth from price, volume, FX, and acquisition effects — the buyer pays a multiple on sustainable growth only.", ar: "فصل النمو العضوي عن أثر السعر والحجم وسعر الصرف والاستحواذات — فالمشتري يدفع مضاعفًا على النمو المستدام وحده." },
      { en: "Test recognition timing against IFRS 15: cut-off, bundling, and the discipline that keeps revenue where the period it belongs.", ar: "اختبار توقيت الاعتراف مقابل IFRS 15: الاستقطاع والحزم والانضباط الذي يبقي الإيراد في فترته." },
      { en: "Build the QoE bridge: reported EBITDA adjusted for owner compensation, related-party dealings, one-offs, and run-rate anomalies — the number the valuation actually uses.", ar: "بناء جسر جودة الأرباح: الأرباح المعلنة معدلة لأثر تعويض المالك وتعاملات الأطراف ذات العلاقة والبنود لمرة واحدة وشذوذ معدل التشغيل — وهو الرقم الذي يستخدمه التقييم فعلًا." },
    ],
    documents: [
      { en: "Monthly revenue by product/service/customer segment for 3 years", ar: "الإيراد الشهري بالمنتج أو الخدمة أو شريحة العملاء لثلاث سنوات" },
      { en: "Revenue recognition policy and its application to the top revenue streams", ar: "سياسة الاعتراف بالإيراد وتطبيقها على أكبر تدفقات الإيراد" },
      { en: "Deferred revenue / contract liability roll-forward", ar: "حركة الإيراد المؤجل / التزامات العقود" },
      { en: "Price list history and discount approval matrix", ar: "تاريخ قوائم الأسعار ومصفوفة اعتماد الخصومات" },
      { en: "Sales returns, credit notes, and rebates by month for 3 years", ar: "المرتجعات وإشعارات الدائن والخصومات شهريًا لثلاث سنوات" },
      { en: "Related-party revenue contracts and their terms vs. market", ar: "عقود الإيراد مع الأطراف ذات العلاقة وشروطها مقابل السوق" },
      { en: "Management accounts vs. audited accounts reconciliation", ar: "مطابقة الحسابات الإدارية بالقوائم المدققة" },
    ],
    procedures: [
      { id: "rv-1", ref: "DD practice", text: { en: "Decompose revenue growth into price, volume, mix, FX, and new-customer effects for each of the last 3 years — then interrogate the components: price growth the market did not see is either share loss tomorrow or fiction today.", ar: "تفكيك نمو الإيراد إلى أثر السعر والحجم والتشكيلة وسعر الصرف والعملاء الجدد لكل من آخر 3 سنوات — ثم استجواب المكونات: فنمو سعر لم يشهده السوق إما خسارة حصة غدًا أو خيال اليوم." } },
      { id: "rv-2", ref: "IFRS 15", text: { en: "Re-perform recognition on the top-10 revenue streams: identify the performance obligations, the transaction price, and the timing — each stream either passes or generates a QoE adjustment.", ar: "إعادة اختبار الاعتراف على أكبر 10 تدفقات إيراد: تحديد الالتزامات الأدائية وثمن المعاملة والتوقيت — فكل تدفق إما ينجح أو يولد تعديلًا في جودة الأرباح." } },
      { id: "rv-3", ref: "IFRS 15 / ISA analog", text: { en: "Test cut-off at each year-end and at the deal's measurement date: the last 15 sales before and first 15 after — December's heroics reversed in January are the oldest trick in the book.", ar: "اختبار الاستقطاع عند نهاية كل سنة وعند تاريخ قياس الصفقة: آخر 15 عملية بيع قبلها وأول 15 بعدها — فبطولات ديسمبر المعكوسة في يناير أقدم حيلة في الكتاب." } },
      { id: "rv-4", ref: "DD practice", text: { en: "Analyze revenue quality mix: recurring vs. one-off, contracted vs. discretionary, product vs. service — and trend the retention rate of the recurring base; multiple follows the mix.", ar: "تحليل مزيج جودة الإيراد: متكرر مقابل لمرة واحدة، وتعاقدي مقابل تقديري، ومنتج مقابل خدمة — وتتبع معدل الاحتفاظ بالقاعدة المتكررة؛ فالمضاعف يتبع المزيج." } },
      { id: "rv-5", ref: "IAS 24", text: { en: "Re-run revenue excluding all related-party sales and at market terms — quantify what the group's shadow business contributes; it disappears at closing unless contracts are re-cut.", ar: "إعادة احتساب الإيراد مستبعدًا كل مبيعات الأطراف ذات العلاقة وبشروط سوقية — وتقدير ما تسهم به أعمال الظل داخل المجموعة؛ فهي تختفي عند الإغلاق ما لم تُعاد العقود." } },
      { id: "rv-6", ref: "DD practice", text: { en: "Build the returns/rebates profile: monthly rates trended, mapped to customers and seasons — a December dip in returns is revenue borrowed from January.", ar: "بناء ملف المرتجعات والخصومات: المعدلات الشهرية باتجاهها موزعة على العملاء والمواسم — فانخفاض مرتجعات ديسمبر إيراد مقترض من يناير." } },
      { id: "rv-7", ref: "DD practice", text: { en: "Reconcile management accounts to audited accounts line by line — every difference is either an adjustment timing issue or a story; both belong in the report.", ar: "مطابقة الحسابات الإدارية بالقوائم المدققة بندًا بندًا — فكل فرق إما مسألة توقيت تعديل أو قصة؛ وكلاهما مكانه التقرير." } },
      { id: "rv-8", ref: "DD practice", text: { en: "Interview sales leadership on pipeline honesty: win rates, average deal size, and the pipeline conversion history — then compare to what marketing decks claim.", ar: "مقابلة قيادة البيع عن صدق الفرص: معدلات الفوز وحجم الصفقة المتوسط وتاريخ تحول الفرص — ثم المقارنة بما تزعمه العروض التسويقية." } },
      { id: "rv-9", ref: "DD practice", text: { en: "Quantify the gross-vs-net question: agent vs. principal on the main streams — reclassifying gross revenue as net can cut the top line by half and change every ratio the deal model uses.", ar: "تقدير مسألة الإجمالي مقابل الصافي: وكيل أم أصل في التدفقات الرئيسية — فإعادة تصنيف إيراد إجمالي إلى صافٍ قد تُنصف بند الإيراد في القائمة وتغير كل نسبة في نموذج الصفقة." } },
      { id: "rv-10", ref: "DD practice", text: { en: "Feed the QoE bridge: list every revenue finding as an EBITDA adjustment with its rationale and persistence — the bridge, not the P&L, is the negotiation document.", ar: "تغذية جسر جودة الأرباح: إدراج كل ملاحظة إيراد كتعديل في الأرباح التشغيلية بمبرره واستمراريته — فالجسر لا قائمة الأرباح هو مستند التفاوض." } },
    ],
    analytics: [
      { en: "Revenue growth decomposition: price × volume × mix × FX × M&A, 3-year trend", ar: "تفكيك نمو الإيراد: سعر × حجم × تشكيلة × عملة × استحواذات، اتجاه 3 سنوات" },
      { en: "Recurring revenue share and its retention rate (net revenue retention)", ar: "حصة الإيراد المتكرر ومعدل الاحتفاظ به (صافي الاحتفاظ بالإيراد)" },
      { en: "Returns and rebates as % of gross sales, by month — seasonality and year-end shape", ar: "المرتجعات والخصومات كنسبة من إجمالي البيع شهريًا — الموسمية وشكل نهاية السنة" },
      { en: "December + first-half-January sales vs. trailing average (the cut-off stress test)", ar: "مبيعات ديسمبر ونصف يناير الأول مقابل المتوسط الزمني (اختبار إجهاد الاستقطاع)" },
      { en: "Customer concentration: top-1 / top-5 / top-10 share of revenue, trended", ar: "تركز العملاء: حصة الأول والخمسة والعشرة من الإيراد باتجاهها" },
    ],
    redFlags: [
      { text: { en: "Revenue growth that only exists in the final quarter of each year (deal-driven or window-dressed).", ar: "نمو إيراد لا يوجد إلا في الربع الأخير من كل سنة (بسبب الصفقة أو التجميل)." }, critical: true },
      { text: { en: "Related-party revenue at above-market prices or with no collection history.", ar: "إيراد أطراف ذات علاقة بأسعار فوق السوق أو بلا تاريخ تحصيل." } },
      { text: { en: "Round-sum manual journals to revenue in the last week of the year.", ar: "قيود يدوية بمبالغ مقربة على الإيراد في آخر أسبوع من السنة." } },
      { text: { en: "Management accounts showing growth the audited accounts do not confirm.", ar: "حسابات إدارية تظهر نموًا لا تؤكده القوائم المدققة." } },
    ],
  },

  {
    id: "receivables",
    code: "F-02",
    scope: "financial",
    group: "accounts",
    icon: "credit-card",
    title: { en: "Customers & Trade Receivables", ar: "العملاء والذمم المدينة" },
    scopeNote: {
      en: "The clients' account: who owes the business what, since when, at what credit terms — and whether the receivables on the balance sheet will actually convert to cash after closing.",
      ar: "حساب العملاء: من يدين للنشاط وبكم ومنذ متى وبأي شروط ائتمان — وهل الذمم المدينة في الميزانية ستنقلب فعلًا إلى نقد بعد الإغلاق.",
    },
    why: [
      { en: "Verify the receivables are real, current, and collectible — they are cash the buyer pays for on day one.", ar: "التحقق من أن الذمم صحيحة وحديثة وقابلة للتحصيل — فهي نقد يدفع المشتري ثمنه من اليوم الأول." },
      { en: "Understand the customer credit culture: terms granted vs. terms honored — DSO is a behavior metric, not a formula.", ar: "فهم ثقافة الائتمان مع العملاء: الشروط الممنوحة مقابل الشروط الملتزم بها — فمتوسط أيام التحصيل سلوك لا معادلة." },
      { en: "Test the ECL under IFRS 9 — the provision the buyer inherits is the difference between face and value.", ar: "اختبار الخسائر الائتمانية المتوقعة وفق IFRS 9 — فالمخصص الذي يرثه المشتري هو الفرق بين الاسمي والقيمة." },
    ],
    documents: [
      { en: "Aged receivables listing at the deal date, reconciled to the trial balance", ar: "كشف أعمار الذمم المدينة بتاريخ الصفقة مطابقًا لميزان المراجعة" },
      { en: "Top-25 customer balances with credit terms, last payment, and dispute status", ar: "أرصدة أكبر 25 عميلًا بالشروط وآخر سداد وحالة النزاع" },
      { en: "ECL model: segments, historical loss rates, forward-looking overlays", ar: "نموذج الخسائر المتوقعة: الشرائح ونسب الخسارة التاريخية والتعديلات المستقبلية" },
      { en: "Credit policy and the approval matrix for limits and terms", ar: "سياسة الائتمان ومصفوفة اعتماد الحدود والشروط" },
      { en: "Post-date cash receipts listing (the strongest collectibility evidence)", ar: "كشف المقبوضات النقدية بعد التاريخ (أقوى دليل على قابلية التحصيل)" },
      { en: "Bad-debt write-off history and credit-loss experience by year", ar: "تاريخ إعدام الديون وخبرة الخسائر الائتمانية سنة بسنة" },
    ],
    procedures: [
      { id: "ar-1", ref: "DD practice", text: { en: "Analyze DSO by month for 3 years and by customer segment — rising DSO with flat revenue means sales are being bought with credit; check whether that was disclosed as growth.", ar: "تحليل متوسط أيام التحصيل شهريًا لثلاث سنوات وبشريحة العملاء — فتصاعد الأيام مع ثبات الإيراد يعني أن المبيعات تُشترى بالائتمان؛ فيُفحص هل فُصح عن ذلك بوصفه نموًا." } },
      { id: "ar-2", ref: "DD practice", text: { en: "Age rigorously: buckets past terms, and within overdue — 1-30 / 31-90 / 90-180 / 180+ days — with each bucket's share of the total and its trend; 180+ trade balances are candidates for write-down, not collection.", ar: "تقادم بصرامة: شرائح متجاوزة للشروط وداخل المتأخر — 1-30 و31-90 و90-180 وأكثر من 180 يومًا — بحصة كل شريحة واتجاهها؛ فأرصدة التجارة فوق 180 يومًا مرشحة للإعدام لا للتحصيل." } },
      { id: "ar-3", ref: "DD practice", text: { en: "Confirm directly the top-25 balances (positive confirmations through the deal team's own channel) — in DD, unlike audit, this can be a closing condition.", ar: "التأكيد المباشر لأرصدة أكبر 25 عميلًا (تأكيدات إيجابية عبر قناة فريق الصفقة نفسه) — في العناية بخلاف المراجعة يمكن أن يكون هذا شرط إغلاق." } },
      { id: "ar-4", ref: "DD practice", text: { en: "Trace post-date collections against the aged listing: what percentage of the deal-date balance has converted to cash, and how long it took — the single most honest collectibility metric.", ar: "تتبع التحصيلات بعد التاريخ مقابل كشف الأعمار: كم من رصيد تاريخ الصفقة تحول نقدًا وكم استغرق — وهو أصدق مقيس لقابلية التحصيل على الإطلاق." } },
      { id: "ar-5", ref: "IFRS 9", text: { en: "Re-perform the ECL: segmentation logic, historical loss rates per bucket, forward-looking overlays, and the lifetime-vs-12-month split for impaired customers — then recompute the provision independently.", ar: "إعادة اختبار الخسائر المتوقعة: منطق التقسيم ونسب الخسارة التاريخية لكل شريحة والتعديلات المستقبلية وتوزيع العمر الكامل مقابل 12 شهرًا للمتعثرين — ثم إعادة احتساب المخصص باستقلال." } },
      { id: "ar-6", ref: "IAS 1", text: { en: "Reclassify: credit balances (customer advances) to payables, long-old debit-credit pairs per customer netted with a story, and financing-style receivables (loans to related parties disguised as trade) moved out of working capital.", ar: "إعادة التصنيف: الأرصدة الدائنة (دفعات مقدمة من العملاء) إلى الدائنين، وأزواج مدين/دائن القديمة لكل عميل مع قصة، والذمم التمويلية (قروض أطراف ذات علاقة متنكرة كتجارة) تخرج من رأس المال العامل." } },
      { id: "ar-7", ref: "IAS 24", text: { en: "Isolate related-party receivables: amounts, terms, security, and repayment history — the buyer should assume they will not be repaid unless the SPA forces settlement at closing.", ar: "عزل ذمم الأطراف ذات العلاقة: المبالغ والشروط والضمان وتاريخ السداد — ينبغي أن يفترض المشتري أنها لن تُسدد إلا إذا ألزم اتفاق البيع بتسويتها عند الإغلاق." } },
      { id: "ar-8", ref: "DD practice", text: { en: "Test dispute inventory: list balances the customer disputes (quality, delivery, pricing) with amounts and aging of the dispute — disputed revenue is neither revenue nor receivable until resolved.", ar: "اختبار جرد النزاعات: إدراج الأرصدة التي ينازع فيها العملاء (جودة أو تسليم أو تسعير) بالمبالغ وعمر النزاع — فالإيراد المتنازع ليس إيرادًا ولا مدينًا حتى يُحسم." } },
      { id: "ar-9", ref: "DD practice", text: { en: "Check the factoring and discounting pipeline: receivables sold with recourse, bills discounted, and hidden arrangements — sold-with-recourse paper is a liability wearing a receivable's clothes.", ar: "فحص مسار الخصم والتورير: الذمم المبيعة بمحق الرجوع والأوراق المخصومة والترتيبات الخفية — فالورقة المبيعة بمحق الرجوع التزام يلبس ثوب مدين." } },
      { id: "ar-10", ref: "DD practice", text: { en: "Hand the receivable findings to the price mechanism: over-aged, related-party, and disputed balances become debt-like deductions or specific indemnities — list each with its number.", ar: "تمرير ملاحظات الذمم لآلية السعر: الأرصدة المتقادمة وذات العلاقة والمتنازع عليها تصبح خصومات شبيهة بالدين أو تعويضات خاصة — تُدرج كل واحدة برقمها." } },
    ],
    analytics: [
      { en: "DSO by month (3 years) and by segment — vs. stated credit terms", ar: "متوسط أيام التحصيل شهريًا (3 سنوات) وبالشريحة — مقابل الشروط المعلنة" },
      { en: "Aging profile: % of balances current / 1-30 / 31-90 / 90-180 / 180+ days past terms", ar: "ملف الأعمار: نسبة الأرصدة ضمن الشروط وبعدها 1-30 و31-90 و90-180 وفوق 180 يومًا" },
      { en: "Post-date conversion: % of deal-date balance collected, and days to collect", ar: "التحول بعد التاريخ: نسبة رصيد تاريخ الصفقة المحصلة وأيام التحصيل" },
      { en: "ECL coverage: provision ÷ 90+-day balances — the classic adequacy lens", ar: "تغطية المخصص: المخصص ÷ أرصدة فوق 90 يومًا — عدسة الكفاية الكلاسيكية" },
      { en: "Bad-debt experience: write-offs as % of revenue, trended", ar: "خبرة الديون المعدومة: الإعدام كنسبة من الإيراد باتجاهها" },
    ],
    redFlags: [
      { text: { en: "Receivables growing materially faster than revenue for multiple periods — sales are being manufactured on credit.", ar: "الذمم تنمو أسرع بوضوح من الإيراد لفترات متتالية — فالمبيعات تُصنع بالائتمان." }, critical: true },
      { text: { en: "Round-sum balances to obscure or dormant names with no trading history.", ar: "أرصدة مقربة لأسماء غامضة أو ساكنة بلا تاريخ تعامل." } },
      { text: { en: "Related-party receivables with no repayment schedule or security.", ar: "مدينون أطراف ذات علاقة بلا جدول سداد أو ضمان." } },
      { text: { en: "Post-date returns or credit notes eroding the deal-date balance after the price was set.", ar: "مرتجعات أو إشعارات دائن بعد التاريخ تنخر رصيد تاريخ الصفقة بعد تثبيت السعر." } },
    ],
  },

  {
    id: "inventory",
    code: "F-03",
    scope: "financial",
    group: "accounts",
    icon: "package",
    title: { en: "Inventory", ar: "المخزون" },
    scopeNote: {
      en: "The account where value evaporates quietly: quantities, cost build-up, obsolescence, and the gap between what the system says and what the warehouse holds.",
      ar: "البند الذي تتبخر قيمته بهدوء: الكميات ومكونات التكلفة والتقادم والفجوة بين ما يقوله النظام وما تحويه المخازن.",
    },
    why: [
      { en: "Establish the quantity truth: system vs. physical vs. shipped — the buyer pays for countable goods.", ar: "إثبات حقيقة الكميات: النظام مقابل الجرد مقابل المشحون — فالمشتري يدفع مقابل سلع قابلة للعد." },
      { en: "Test the cost engine: standard costs, variances, and the capitalization discipline that decides whether margin is real.", ar: "اختبار محرك التكلفة: التكاليف المعيارية والانحرافات وانضباط الرسملة الذي يقرر هل الهامش حقيقي." },
      { en: "Quantify obsolescence and NRV honestly — inventory is the most common post-closing write-down.", ar: "تقدير التقادم وصافي القيمة البيعية بصدق — فالمخزون أشهر بنود الإعدام بعد الإغلاق." },
    ],
    documents: [
      { en: "Inventory listing at cost by SKU/category, reconciled to the GL", ar: "كشف المخزون بالتكلفة صنفًا أو فئة، مطابقًا للدفتر العام" },
      { en: "Last 3 physical count reports and the count-vs-book adjustments", ar: "تقارير آخر 3 جرد مادي وتسويات الجرد مقابل الدفاتر" },
      { en: "Standard cost build-ups and the variance accounts analysis", ar: "مكونات التكاليف المعيارية وتحليل حسابات الانحرافات" },
      { en: "Aging / movement analysis: last-12-months usage per SKU family", ar: "تحليل الأعمار والحركة: استخدام آخر 12 شهرًا لكل عائلة أصناف" },
      { en: "NRV support: price lists, quotations, damaged/slow-mover reports", ar: "مستندات صافي القيمة: قوائم الأسعار والعروض وتقارير البطيء والتالف" },
      { en: "Inventory count instructions for the deal-date count (if any)", ar: "تعليمات جرد المخزون لتاريخ الصفقة (إن وجد)" },
    ],
    procedures: [
      { id: "in-1", ref: "DD practice", text: { en: "Reconcile three layers: GL balance → inventory listing → last physical count (with roll-forward of movements since) — the arithmetic chain must tie, and where it does not, the gap is the finding.", ar: "مطابقة ثلاث طبقات: رصيد الدفتر العام ← كشف المخزون ← آخر جرد مادي (مع تدوير حركات ما بعده) — يجب أن تنعقد السلسلة الحسابية، وحيث لا تنعقد فالفتحة هي الملاحظة." } },
      { id: "in-2", ref: "IAS 2", text: { en: "Test the cost formula: what layers of cost are capitalized (materials, direct labor, production overhead, freight) vs. what IAS 2 allows — over-capitalized overhead is overstated inventory and overstated margin at once.", ar: "اختبار معادلة التكلفة: أي طبقات الكلفة تُرسمل (مواد وأجور مباشرة وتكاليف صناعية وشحن) مقابل ما يجيزه IAS 2 — فالتكاليف الصناعية المرسملة بزيادة مخزون مبالغ فيه وهامش مبالغ فيه معًا." } },
      { id: "in-3", ref: "IAS 2", text: { en: "Analyze movement: last-12-month usage (or cost of sales) per family vs. on-hand quantity — days-of-inventory by family; families with >270 days are candidates for NRV testing, whatever the provision says.", ar: "تحليل الحركة: استخدام آخر 12 شهرًا (أو تكلفة المبيعات) لكل عائلة مقابل الكمية المتاحة — أيام مخزون لكل عائلة؛ فالعائلات فوق 270 يومًا مرشحة لاختبار صافي القيمة أيًا كان المخصص." } },
      { id: "in-4", ref: "IAS 2", text: { en: "Re-perform NRV on a risk-weighted sample: slow movers, discontinued lines, season remnants, damaged stock — selling price less costs to sell vs. carrying amount, family by family.", ar: "إعادة اختبار صافي القيمة على عينة مرجحة بالخطر: البطيء والموقوف والمتبقي الموسمي والتالف — سعر البيع ناقص تكاليف البيع مقابل القيمة الدفترية عائلة عائلة." } },
      { id: "in-5", ref: "DD practice", text: { en: "Attend a deal-date count if there is one (or insist on one for material inventory): count instructions, auditor-free or not, blind sheets, and cut-off controls — the count is a one-chance event.", ar: "حضور جرد تاريخ الصفقة إن وجد (أو الإصرار عليه لمخزون جوهري): التعليمات وأوراق العد المكفوفة وضوابط الاستقطاع — فالجرد حدث لا يتكرر." } },
      { id: "in-6", ref: "DD practice", text: { en: "Test for consignment and third-party stock both ways: goods held for others (not an asset) and goods of the target held elsewhere (an asset the listing may miss).", ar: "اختبار الوديعة ومخزون الغير في الاتجاهين: بضاعة لدى الهدف لغيره (ليست أصلًا) وبضاعة الهدف لدى الغير (أصل قد يفوته الكشف)." } },
      { id: "in-7", ref: "DD practice", text: { en: "Review the variance accounts: PPV, absorption variances, and where they landed (inventory vs. P&L) — variances dumped to the P&L each month hide a costing problem; parked in inventory they inflate assets.", ar: "مراجعة حسابات الانحراف: انحراف السعر والامتصاص وأين استقرت (المخزون أم الأرباح) — فالانحرافات المرمية شهريًا في الأرباح تخفي مشكلة تكلفة؛ والمركونة في المخزون تنفخ الأصول." } },
      { id: "in-8", ref: "DD practice", text: { en: "Check the cut-off around the deal date: goods received notes and dispatch notes vs. accounting records in the 10 days either side — inventory cut-off errors are also COGS and margin errors.", ar: "فحص الاستقطاع حول تاريخ الصفقة: إشعارات الاستلام والإرسال مقابل القيود في عشرة أيام حوله — فأخطاء استقطاع المخزون أخطاء تكلفة مبيعات وهامش أيضًا." } },
      { id: "in-9", ref: "DD practice", text: { en: "Hand inventory findings to the price: NRV shortfalls, over-capitalized cost, and count gaps become day-one deductions — inventory is the classic source of post-closing value leakage.", ar: "تمرير ملاحظات المخزون للسعر: عجز صافي القيمة والتكلفة المرسملة بزيادة وفجوات الجرد تصبح خصومات يوم أول — فالمخزون المصدر الكلاسيكي لتسرب القيمة بعد الإغلاق." } },
    ],
    analytics: [
      { en: "Days inventory on hand by family, trended 3 years vs. the sector norm", ar: "أيام المخزون المتاح لكل عائلة، اتجاه 3 سنوات مقابل معيار القطاع" },
      { en: "Count adjustments as % of book value, per count — the accuracy trend", ar: "تسويات الجرد كنسبة من القيمة الدفترية لكل جرد — اتجاه الدقة" },
      { en: "Slow-moving share: % of value with no movement in 180 / 365 days", ar: "حصة البطيء: نسبة القيمة بلا حركة 180 / 365 يومًا" },
      { en: "Obsolescence provision vs. slow-mover value — coverage gap", ar: "مخصص التقادم مقابل قيمة البطيء — فجوة التغطية" },
      { en: "Inventory growth vs. revenue growth — the divergence flag", ar: "نمو المخزون مقابل نمو الإيراد — راية الافتراق" },
    ],
    redFlags: [
      { text: { en: "No physical count performed for years in a business with material inventory.", ar: "لا جرد مادي منذ سنوات في نشاط ذي مخزون جوهري." }, critical: true },
      { text: { en: "Inventory growing persistently faster than revenue while margin stays flat.", ar: "المخزون ينمو باستمرار أسرع من الإيراد بينما يثبت الهامش." } },
      { text: { en: "Standard costs untouched while input prices moved materially.", ar: "تكاليف معيارية لم تُمس بينما تحركت أسعار المدخلات جوهريًا." } },
      { text: { en: "Count adjustments systematically written back to inventory, never investigated.", ar: "تسويات جرد تُرحّل للمخزون دومًا ولا تُحقق أبدًا." } },
    ],
  },

  {
    id: "cash",
    code: "F-04",
    scope: "financial",
    group: "accounts",
    icon: "banknote",
    title: { en: "Cash & Bank", ar: "النقدية والبنوك" },
    scopeNote: {
      en: "The most verified account in audit becomes, in DD, the account of hidden items: restricted balances, sweeping arrangements, unrecorded facilities, and the founder's personal flows through the company account.",
      ar: "أكثر البنود تدقيقًا في المراجعة يصبح في العناية بند البنود الخفية: الأرصدة المقيدة وترتيبات التجميع والتسهيلات غير المسجلة وتدفقات المؤسس الشخصية عبر حساب الشركة.",
    },
    why: [
      { en: "Separate free cash from restricted, pledged, and compensated balances — only free cash reduces the price dollar-for-dollar.", ar: "فصل النقد الحر عن المقيد والمرهون والمقابل — فالنقد الحر وحده يخفض السعر جنيهًا بجنيه." },
      { en: "Detect undisclosed borrowings and the off-balance-sheet facilities that live between the bank statements and the ledger.", ar: "كشف الاقتراضات غير المفصح عنها والتسهيلات خارج الميزانية التي تسكن بين كشوف البنك والدفاتر." },
      { en: "Scan the flows for the founder's personal traffic and related-party passes through the company account — they define the true run-rate cost structure.", ar: "مسح التدفقات بحثًا عن حركة المؤسس الشخصية ومرور الأطراف ذات العلاقة عبر حساب الشركة — فهي تُعرّف بنية الكلفة التشغيلية الحقيقية." },
    ],
    documents: [
      { en: "All bank account listings (including closed-during-the-year and dormant accounts)", ar: "كشوف كل الحسابات البنكية (بما فيها المغلقة خلال السنة والساكنة)" },
      { en: "Bank statements for 3 years for the main accounts; 12 months minimum for the rest", ar: "كشوف الحسابات لثلاث سنوات للحسابات الرئيسية و12 شهرًا على الأقل للباقي" },
      { en: "Bank confirmations: balances, loans, guarantees, pledged deposits, drawer status", ar: "تأكيدات البنوك: الأرصدة والقروض والضمانات والودائع المرهونة ووضع السحب" },
      { en: "Loan and facility agreements with the banks, including informal/overdraft arrangements", ar: "اتفاقيات القروض والتسهيلات مع البنوك بما فيها الترتيبات غير الرسمية والسحب على المكشوف" },
      { en: "Bank reconciliations for the last 24 months", ar: "المطابقات البنكية لآخر 24 شهرًا" },
      { en: "Treasury policy: who can move money, with what dual control", ar: "سياسة الخزينة: من يحرك المال وبأي رقابة مزدوجة" },
    ],
    procedures: [
      { id: "ca-1", ref: "DD practice", text: { en: "Confirm with every bank directly: balances, loans, guarantees given, pledged deposits, and the account officer's view of the relationship — the confirmation is the spine of financial DD.", ar: "التأكيد مباشرة مع كل بنك: الأرصدة والقروض والضمانات الممنوحة والودائع المرهونة ورأي مسؤول الحساب في العلاقة — فالتأكيد هو العمود الفقري للعناية المالية." } },
      { id: "ca-2", ref: "DD practice", text: { en: "Classify every balance: free / restricted (central-bank required reserves, pledged, escrow) / compensated — then carry only free cash to the net-debt bridge.", ar: "تصنيف كل رصيد: حر / مقيد (احتياطيات إلزامية، مرهون، ضمان) / مقابل — ثم لا يُجار إلى جسر صافي الدين إلا النقد الحر." } },
      { id: "ca-3", ref: "DD practice", text: { en: "Read 12-36 months of statements for the main accounts like a book: round-sum transfers to related parties, cash withdrawals pattern, rent and school fees of private nature, and recurring payments that have no business explanation.", ar: "قراءة كشوف 12-36 شهرًا للحسابات الرئيسية كتابًا: تحويلات مقربة لأطراف ذات علاقة ونمط السحوبات النقدية وإيجارات ومصروفات مدرسية ذاتية ومدفوعات متكررة بلا تفسير تجاري." } },
      { id: "ca-4", ref: "DD practice", text: { en: "Hunt undisclosed debt: interest and repayment flows in the statements that match no recorded liability; discounted bills; and 'bridge' deposits that arrive and leave around period ends.", ar: "اقتفاء الدين غير المفصح عنه: تدفقات فوائد وسداد في الكشوف لا يقابلها التزام مسجل؛ وأوراق مخصومة؛ وودائع «الجسر» التي تصل وتغادر حول نهايات الفترات." } },
      { id: "ca-5", ref: "DD practice", text: { en: "Test the reconciliation quality: old reconciling items, duplicate recording, and items parked in suspense accounts for months — the state of the reconciliation is the state of the finance function.", ar: "اختبار جودة المطابقة: بنود مطابقة قديمة وتسجيل مزدوج وبنود مركونة في حسابات معلقة شهورًا — فحالة المطابقة حالة الوظيفة المالية." } },
      { id: "ca-6", ref: "DD practice", text: { en: "Trace the cash conversion cycle end-to-end over 3 years: DSO + DIO − DPO by month — the pattern of working capital tells the truth about growth quality that the P&L will never tell.", ar: "تتبع دورة التحويل النقدي كاملة عبر 3 سنوات: أيام التحصيل زائد أيام المخزون ناقص أيام السداد شهريًا — فنمط رأس المال العامل يقول عن جودة النمو ما لن تقوله قائمة الأرباح أبدًا." } },
      { id: "ca-7", ref: "DD practice", text: { en: "Check sweeping and pooling arrangements: cash concentrated in a group account nightly belongs to the structure, not to the target — verify the target's cash is the target's.", ar: "فحص ترتيبات التجميع والشمول: فالنقد المركز ليلا في حساب مجموعي يخص الهيكل لا الهدف — يُتحقق أن نقد الهدف للهدف." } },
      { id: "ca-8", ref: "DD practice", text: { en: "Verify the petty-cash and cash-on-hand reality: surprise counts, the vouchers behind the floats, and who personally controls the cash box.", ar: "التحقق من واقع النقدية النثرية والخزينة: جرد مفاجئ والسندات خلف السلف ومن يسيطر شخصيًا على الصندوق." } },
      { id: "ca-9", ref: "IFRS 7", text: { en: "Hand cash findings to the net-debt and QoE bridges: restricted balances reclassified, personal costs found in the flows added back as owner adjustments with tax effect.", ar: "تمرير ملاحظات النقد إلى جسري صافي الدين وجودة الأرباح: الأرصدة المقيدة يعاد تصنيفها والمكلف الشخصية في التدفقات تضاف كتعديلات مالك بأثرها الضريبي." } },
    ],
    analytics: [
      { en: "Free cash vs. total cash: restricted and compensated balances split", ar: "النقد الحر مقابل الإجمالي: انفصال المقيد والمقابل" },
      { en: "Cash conversion cycle by month (DSO + DIO − DPO), 3-year trend", ar: "دورة التحويل النقدي شهريًا (تحصيل + مخزون − سداد)، اتجاه 3 سنوات" },
      { en: "Non-business flows: value and count of round-sum transfers and personal-nature payments", ar: "التدفقات غير التجارية: قيمة وعدد التحويلات المقربة والمدفوعات ذاتية الطابع" },
      { en: "Overdraft utilization: average and peak, by month", ar: "استغلال السحب على المكشوف: المتوسط والذروة شهريًا" },
      { en: "Minimum cash balance the operations actually need (the 'trapped cash' floor)", ar: "الحد الأدنى من النقد الذي تحتاجه العمليات فعلًا (أرضية النقد المحبوس)" },
    ],
    redFlags: [
      { text: { en: "Undisclosed borrowings discovered in the statements — the balance sheet is not the whole truth.", ar: "اقتراضات غير مفصح عنها تُكتشف في الكشوف — فالميزانية ليست الحقيقة كاملة." }, critical: true },
      { text: { en: "Round-sum family/founder transfers recurring monthly through company accounts.", ar: "تحويلات أسرية أو للمؤسس مقربة متكررة شهريًا عبر حسابات الشركة." } },
      { text: { en: "Deposits arriving before each period end and leaving right after (window dressing).", ar: "ودائع تصل قبيل نهاية كل فترة وتغادر بعدها مباشرة (تجميل المراكز)." } },
      { text: { en: "A large share of cash held at banks with covenants or in restricted form the deck forgot to mention.", ar: "شريحة كبيرة من النقد لدى بنوك بشروط قيود أو بشكل مقيد نسيه العرض ذكره." } },
    ],
  },

  {
    id: "fixed-assets",
    code: "F-05",
    scope: "financial",
    group: "accounts",
    icon: "factory",
    title: { en: "Property, Plant & Equipment", ar: "الممتلكات والآلات والمعدات" },
    scopeNote: {
      en: "The heavy side of the balance sheet: what exists physically, what the company actually owns vs. leases, what it is worth, and whether the maintenance/capex split in the P&L is honest.",
      ar: "الجانب الثقيل من الميزانية: ما موجود ماديًا، وما تملكه الشركة فعلًا مقابل ما تستأجره، وقيمته، وهل فصل الصيانة عن الاستثمار في الأرباح صادق.",
    },
    why: [
      { en: "Verify existence and title: the register, the floor, and the legal file must tell one story.", ar: "التحقق من الوجود والملكية: السجل وأرض الموقع والملف القانوني يجب أن يقولوا قصة واحدة." },
      { en: "Split maintenance from growth capex — capitalized repairs overstate both EBITDA and assets.", ar: "فصل الصيانة عن الاستثمار النامي — فالإصلاحات المرسملة تبالغ في الأرباح والأصول معًا." },
      { en: "Assess the replacement horizon: aging assets with thin depreciation are a capex bill the buyer inherits.", ar: "تقييم أفق الاستبدال: فالأصول المتقادمة بإهلاك هزيل فاتورة إنفاق رأسمالي يرثها المشتري." },
    ],
    documents: [
      { en: "Fixed-asset register: description, date, cost, accumulated depreciation, location", ar: "سجل الأصول الثابتة: الوصف والتاريخ والتكلفة والإهلاك المجمع والموقع" },
      { en: "Ownership/title documents for owned land and buildings (see also L-07)", ar: "مستندات ملكية الأراضي والمباني (انظر أيضًا L-07)" },
      { en: "Lease schedule with IFRS 16 right-of-use assets and liabilities", ar: "جدول الإيجارات بأصول حق الاستخدام والتزاماته وفق IFRS 16" },
      { en: "Capex history 3-5 years, split maintenance vs. expansion", ar: "تاريخ الإنفاق الرأسمالي 3-5 سنوات مفصولًا بين الصيانة والتوسع" },
      { en: "Maintenance logs and downtime records for critical equipment", ar: "سجلات الصيانة وتوقفات المعدات الحرجة" },
      { en: "Any revaluation reports and the appraiser's basis", ar: "أي تقارير إعادة تقييم وأساس المُقيّم" },
      { en: "Insurance schedule with insured values vs. register", ar: "جدول التأمين بالقيم المؤمنة مقابل السجل" },
    ],
    procedures: [
      { id: "fa-1", ref: "DD practice", text: { en: "Physically inspect the significant assets: the register says what should be there; the floor says what is — reconcile with aging eyes (old machines still at full book value are a finding, not an asset).", ar: "الفحص المادي للأصول الجوهرية: السجل يقول ما ينبغي أن يكون؛ وأرض الموقع تقول ما هو كائن — بالمطابقة بعين فاحصة (ماكينة عتيقة بقيمة دفترية كاملة ملاحظة لا أصل)." } },
      { id: "fa-2", ref: "IAS 16", text: { en: "Test ownership vs. leasing vs. financed: for each significant asset, who holds title (especially vehicles and machinery under finance arrangements) — financed assets bring both an asset and a hidden liability.", ar: "اختبار الملكية مقابل الإيجار مقابل التمويل: لكل أصل جوهري من يحمل الملكية (خاصة المركبات والآلات تحت ترتيبات تمويلية) — فالأصول الممولة تحضر أصلًا والتزامًا خفيًا معًا." } },
      { id: "fa-3", ref: "DD practice", text: { en: "Analyze the capex/maintenance split for 3-5 years: trend, ratio to revenue, and the classification policy — capex falling while the machine park ages means the P&L is borrowing from the future.", ar: "تحليل فصل الاستثمار عن الصيانة لثلاث إلى خمس سنوات: الاتجاه والنسبة إلى الإيراد وسياسة التصنيف — فانخفاض الإنفاق مع تقادم أسطول الماكينات يعني أن الأرباح تقترض من المستقبل." } },
      { id: "fa-4", ref: "IAS 16", text: { en: "Recompute depreciation honestly: useful lives used vs. the assets' real condition — lives stretched to flatter EBITDA are a QoE adjustment in reverse.", ar: "إعادة احتساب الإهلاك بصدق: الأعمار المستخدمة مقابل الحالة الحقيقية للأصول — فالأعمار الممدودة لتجميل الأرباح تعديل جودة عكسي." } },
      { id: "fa-5", ref: "IFRS 16", text: { en: "Verify the lease perimeter: leases embedded in service contracts, renewals assumed in the ROU term, and discount rates used — every missed lease is a day-one balance-sheet adjustment.", ar: "التحقق من محيط الإيجارات: إيجارات كامنة في عقود الخدمات وتجديدات مفترضة في مدة أصل الاستخدام وأسعار الخصم المستخدمة — فكل إيجار فائت تعديل ميزانية في اليوم الأول." } },
      { id: "fa-6", ref: "IAS 36", text: { en: "Screen for impairment indicators: idle assets, machines replaced-but-not-disposed, assets supporting loss-making lines — in DD the impairment test is about the price, not the standard.", ar: "مسح مؤشرات الانخفاض: أصول عاطلة وماكينات مستبدلة لم تُستبعد وأصول تخدم خطوطًا خاسرة — في العناية يكون اختبار الانخفاض عن السعر لا عن المعيار." } },
      { id: "fa-7", ref: "DD practice", text: { en: "Reconcile the register to the insurance schedule to the tax-depreciation schedule — three views of the same assets; the differences are findings (uninsured, disposed-but-on-books, ghost assets).", ar: "مطابقة السجل بجدول التأمين بجدول الإهلاك الضريبي — ثلاث رؤى للأصول نفسها؛ والفروق ملاحظات (غير مؤمن، مستبعد وباقي بالسجل، أصول أشباح)." } },
      { id: "fa-8", ref: "IFRS 3", text: { en: "Check assets acquired in past acquisitions: the PPE that came with fair-value step-ups — the remaining uplift runs off and compresses future margins.", ar: "فحص الأصول المكتسبة باستحواذات سابقة: الأصول التي جاءت برفع القيمة العادلة — فما تبقى من الرفع ينفد ويضغط الهوامش القادمة." } },
      { id: "fa-9", ref: "DD practice", text: { en: "Estimate the replacement capex schedule for the next 5 years with the plant engineer — a number the deal model needs and the seller rarely volunteers.", ar: "تقدير جدول الإنفاق الرأسمالي الاستبدالي لخمس سنوات قادمة مع مهندس المصنع — رقم يحتاجه نموذج الصفقة ونادرًا ما يقدمه البائع." } },
    ],
    analytics: [
      { en: "Capex as % of revenue and % of depreciation, trended — the reinvestment rate", ar: "الإنفاق الرأسمالي كنسبة من الإيراد ومن الإهلاك باتجاهه — معدل إعادة الاستثمار" },
      { en: "Average asset age: accumulated depreciation ÷ annual depreciation charge", ar: "متوسط عمر الأصول: الإهلاك المجمع ÷ قيد الإهلاك السنوي" },
      { en: "Maintenance spend per machine hour (or unit output) — the condition proxy", ar: "إنفاق الصيانة لكل ساعة تشغيل (أو وحدة إنتاج) — وكيل الحالة" },
      { en: "Lease liabilities vs. owned asset value — the balance-sheet structure", ar: "التزامات الإيجار مقابل قيمة الأصول المملوكة — بنية الميزانية" },
      { en: "Downtime trend on critical equipment — the reliability curve", ar: "اتجاه التوقفات في المعدات الحرجة — منحنى الاعتمادية" },
    ],
    redFlags: [
      { text: { en: "Register assets physically missing or disposed without write-off — and vice versa.", ar: "أصول في السجل مفقودة ماديًا أو مستبعدة دون إخراج — وبالعكس." } },
      { text: { en: "Capex near zero for 3 years while the machinery park visibly ages.", ar: "إنفاق رأسمالي شبه معدوم لثلاث سنوات بينما يشيخ أسطول الماكينات ظاهريًا." }, critical: true },
      { text: { en: "Useful lives extended shortly before the deal to lift EBITDA.", ar: "أعمار الإهلاك مُددت قبيل الصفقة لرفع الأرباح التشغيلية." } },
      { text: { en: "Revaluation gains propping equity with no market transaction behind them.", ar: "أرباح إعادة تقييم تسند حقوق الملكية بلا معاملة سوقية خلفها." } },
    ],
  },

  {
    id: "intangibles",
    code: "F-06",
    scope: "financial",
    group: "accounts",
    icon: "lightbulb",
    title: { en: "Goodwill & Intangibles", ar: "الشهرة والأصول غير الملموسة" },
    scopeNote: {
      en: "The account that carries the previous deals' optimism: goodwill and acquired intangibles — their origin, their impairment history, and how much of the equity they really support.",
      ar: "البند الذي يحمل تفاؤل صفقات الماضي: الشهرة والأصول غير الملموسة المكتسبة — منشؤها وتاريخ انخفاضها وكم من حقوق الملكية تسنده فعلًا.",
    },
    why: [
      { en: "Understand the M&A history embedded in the balance sheet: past acquisitions, their pricing, and what happened after.", ar: "فهم تاريخ الاستحواذ الكامن في الميزانية: صفقات الماضي وتسعيرها وما حدث بعدها." },
      { en: "Test impairment discipline: goodwill that never fails an impairment test while the acquired business underperforms is a belief, not an accounting.", ar: "اختبار انضباط الانخفاض: شهرة لا تسقط أبدًا في اختبار الانخفاض بينما يتعثر النشاط المكتسب عقيدة لا محاسبة." },
      { en: "Separate the intangibles the deal can own and sell (brands, software, licenses — see L-04) from the accounting residue.", ar: "فصل غير الملموس الذي تستطيع الصفقة تملكه وبيعه (علامات وبرمجيات وتراخيص — انظر L-04) عن مخلفات المحاسبة." },
    ],
    documents: [
      { en: "Intangibles schedule: item, origin (acquired/developed), cost, amortization, carrying value", ar: "جدول الأصول غير الملموسة: البند ومنشؤه (مكتسب/مطور) والتكلفة والإهلاك والقيمة الدفترية" },
      { en: "Past acquisition agreements and their purchase-price allocations (IFRS 3)", ar: "اتفاقيات الاستحواذ السابقة وتوزيعات ثمن الشراء (IFRS 3)" },
      { en: "Impairment test models: cash-generating units, growth assumptions, discount rates, headroom", ar: "نماذج اختبار الانخفاض: وحدات توليد النقد وفروض النمو وأسعار الخصم والهامش" },
      { en: "Development cost capitalization policy and project files behind capitalized amounts", ar: "سياسة رسملة تكاليف التطوير وملفات المشاريع خلف المبالغ المرسملة" },
      { en: "Brand/IP valuations used for any step-up, with the appraiser's identity and basis", ar: "تقييمات العلامات والملكية المستخدمة في أي رفع قيمة، بهوية المُقيّم وأساسه" },
    ],
    procedures: [
      { id: "ia-1", ref: "IFRS 3", text: { en: "Reconstruct each past acquisition: what was bought, for how much, and how the price was allocated — then compare the acquisition business plan to what actually happened; the delta is the impairment story.", ar: "إعادة بناء كل استحواذ سابق: ماذا اشتُري وبكم وكيف وُزع الثمن — ثم مقارنة خطة الاستحواذ بما حدث فعلًا؛ فالفرق قصة الانخفاض." } },
      { id: "ia-2", ref: "IAS 36", text: { en: "Re-run the goodwill impairment test with deal-case assumptions: the buyer's own cash-flow view and discount rate — goodwill failing the buyer's test is a price reduction, discovered now rather than post-closing.", ar: "إعادة اختبار انخفاض الشهرة بفروض حالة الصفقة: رؤية المشتري نفسه للتدفقات وسعر خصمه — فالشهرة الراسبة في اختبار المشتري تخفيض في السعر يُكتشف الآن بدل ما بعد الإغلاق." } },
      { id: "ia-3", ref: "IAS 38", text: { en: "Test development capitalization: which projects, what costs capitalized vs. expensed, and the amortization lives vs. the products' real cycles — aggressive capitalization is EBITDA borrowed from the future.", ar: "اختبار رسملة التطوير: أي مشروعات وأي تكاليف مرسملة مقابل مُستنفدة وأعمار الإهلاك مقابل دورات المنتجات الحقيقية — فالرسملة المتشددة أرباح مقترضة من المستقبل." } },
      { id: "ia-4", ref: "IAS 38", text: { en: "Split the intangibles into ownable and residual: registered brands, live software, and licenses (verified in L-04) are assets the deal can sell; the rest is accounting residue the price should ignore.", ar: "فصل غير الملموس إلى قابل للتملك ومتبقي: العلامات المسجلة والبرمجيات الحية والتراخيص (المتحقق منها في L-04) أصول تستطيع الصفقة بيعها؛ والباقي مخلفات محاسبية ينبغي للسعر تجاهلها." } },
      { id: "ia-5", ref: "DD practice", text: { en: "Quantify the intangible load on future P&L: the amortization schedule the buyer inherits, mapped by year — it compresses reported margins post-closing even when cash is unaffected.", ar: "تقدير حمل الإهلاك غير الملموس على أرباح المستقبل: جدول الإهلاك الذي يرثه المشتري موزعًا بالسنة — فهو يضغط الهوامش المعلنة بعد الإغلاق ولو لم يتأثر النقد." } },
      { id: "ia-6", ref: "DD practice", text: { en: "Check for internally generated 'assets' that should not be on the books at all (brands, customer lists, teams capitalized by entry) — IAS 38 prohibits most, and their removal is a mechanical equity adjustment.", ar: "فحص «الأصول» المنشأة داخليًا التي لا ينبغي أن تكون على الدفاتر أصلًا (علامات وقوائم عملاء وفرق رُسملت بالقيد) — يمنعها IAS 38 غالبًا وإزالتها تعديل ميكانيكي على حقوق الملكية." } },
      { id: "ia-7", ref: "DD practice", text: { en: "Hand the intangibles file to the valuation workstream: the step-up opportunities (and their tax shield — see F-12) versus the impairment risk — both numbers flow into the price structure.", ar: "تمرير ملف غير الملموس لفريق التقييم: فرص رفع القيمة (ودرعها الضريبي — انظر F-12) مقابل خطر الانخفاض — وكلا الرقمين يسري في بنية السعر." } },
    ],
    analytics: [
      { en: "Goodwill and intangibles as % of total assets and of equity — the fragility ratio", ar: "الشهرة وغير الملموس كنسبة من إجمالي الأصول ومن حقوق الملكية — نسبة الهشاشة" },
      { en: "Impairment headroom: value-in-use vs. carrying value, with the assumptions used", ar: "هامش الانخفاض: قيمة الاستخدام مقابل الدفترية بفروضها المستخدمة" },
      { en: "Capitalized development as % of total opex — the capitalization appetite", ar: "التطوير المرسمل كنسبة من إجمالي المصروفات التشغيلية — شهية الرسملة" },
      { en: "Future amortization load by year, 5-year schedule", ar: "حمل الإهلاك المستقبلي بالسنة، جدول خمس سنوات" },
    ],
    redFlags: [
      { text: { en: "Goodwill from years-old acquisitions never impaired while the acquired units underperform.", ar: "شهرة من استحواذات عمرها سنوات لم تُعدم قط بينما تتعثر الوحدات المكتسبة." }, critical: true },
      { text: { en: "Development costs capitalized aggressively with long amortization lives.", ar: "تكاليف تطوير مرسملة بتشدد وبأعمار إهلاك طويلة." } },
      { text: { en: "Intangibles from step-up valuations by an appraiser with no independence from the seller.", ar: "أصول غير ملموسة من تقييمات رفع قيمة بمُقيّم غير مستقل عن البائع." } },
      { text: { en: "Impairment models with growth assumptions above the market's own forecasts.", ar: "نماذج انخفاض بفروض نمو تتجاوز توقعات السوق نفسها." } },
    ],
  },
]
