import type { DDSection } from "./types"

/** Financial due diligence, accounts F-07 … F-12: investments & group,
 *  payables, borrowings & debt-like items, equity & related parties,
 *  payroll, and taxes. Same per-account shape as financial-a.ts. */
export const DD_FINANCIAL_B: DDSection[] = [
  {
    id: "investments",
    code: "F-07",
    scope: "financial",
    group: "accounts",
    icon: "briefcase",
    title: { en: "Investments & Group Structure", ar: "الاستثمارات وهيكل المجموعة" },
    scopeNote: {
      en: "What the target holds in other companies — subsidiaries, associates, and financial portfolios — and whether those holdings earn, drain, or simply decorate the balance sheet.",
      ar: "ما يحوزه الهدف في شركات أخرى — تابعة وشركات زميلة وحقائب مالية — وهل تلك الحيازات تُكسب أو تُنزف أو تكتفي بتزيين الميزانية.",
    },
    why: [
      { en: "Verify control and consolidation: which entities are really controlled, and which are 50%-ish arrangements with their own politics.", ar: "التحقق من السيطرة والتوحيد: أي الكيانات مسيطر عليها فعلًا، وأيها ترتيبات نصفية بسياساتها الخاصة." },
      { en: "Test the earnings quality of associates and portfolio: dividends received vs. paper profits — equity-method income is not cash.", ar: "اختبار جودة أرباح الزميلات والحافظة: توزيعات مقبوضة مقابل أرباح ورقية — فإيرد طريقة الحصص ليس نقدًا." },
      { en: "Map intra-group flows: loans, guarantees, and dividends inside the group — much of it unwinds at closing.", ar: "رسم التدفقات داخل المجموعة: قروض وضمانات وتوزيعات — وكثير منها ينفسخ عند الإغلاق." },
    ],
    documents: [
      { en: "Investments schedule: entity, stake, carrying value, method, dividends received", ar: "جدول الاستثمارات: الكيان والنسبة والقيمة الدفترية والطريقة والتوزيعات المقبوضة" },
      { en: "Statutory financial statements of each significant investee (2-3 years)", ar: "القوائم المالية النظامية لكل شركة مستثمر فيها جوهريًا (سنتان إلى ثلاث)" },
      { en: "Shareholder agreements, veto maps, and drag/tag provisions", ar: "اتفاقيات المساهمين وخرائط الاعتراض وبنود الجر والاقتلاع" },
      { en: "Intercompany loan schedule with balances, terms, and interest", ar: "جدول القروض بين الشركات بالأرصدة والشروط والفوائد" },
      { en: "Guarantees and cross-collateral map across the group", ar: "خريطة الضمانات والضمانات العابرة عبر المجموعة" },
      { en: "Board seats the target holds in investees (and vice versa)", ar: "مقاعد المجالس التي يحتلها الهدف لدى الشركات المستثمر فيها (وبالعكس)" },
    ],
    procedures: [
      { id: "iv-1", ref: "IFRS 10", text: { en: "Test control honestly per investee: board seats, voting contracts, related-party stakes combined — a 40% holding with the chairman's seat and the signature authority is control whatever the percentage says.", ar: "اختبار السيطرة بصدق لكل شركة مستثمر فيها: مقاعد المجالس وعقود التصويت وتجميع حصص الأطراف ذات العلاقة — فحيازة 40% مع رئاسة المجلس وصلاحية التوقيع سيطرة أيًا كانت النسبة." } },
      { id: "iv-2", ref: "IAS 28", text: { en: "For associates: compare equity-method income booked vs. dividends ever received over 3 years — income the target cannot extract is a discounted asset at best.", ar: "للزميلات: مقارنة إيراد طريقة الحصص المقيد بالتوزيعات المقبوضة قط على ثلاث سنوات — فالإيراد الذي لا يستطيع الهدف سحبه أصل مُخصم في أحسن الأحوال." } },
      { id: "iv-3", ref: "IAS 36", text: { en: "Impairment-screen each significant holding: the investee's own results, dividends, and cash calls — investments in loss-making, dividend-silent entities belong on the findings list.", ar: "مسح الانخفاض لكل حيازة جوهرية: نتائج الشركة المستثمر فيها وتوزيعاته وطلبات زيادة رأس المال — فالاستثمارات في كيانات خاسرة صامتة التوزيع تنتمي إلى قائمة الملاحظات." } },
      { id: "iv-4", ref: "DD practice", text: { en: "Decide the perimeter with the deal team: which investees are in, which out — and for the out ones, what unwinds (loans called, guarantees released, dividends declared pre-closing to extract value).", ar: "تقرير المحيط مع فريق الصفقة: أي الشركات المستثمر فيها داخل المحيط وأيها خارجه — وللخارج منها ما الذي يُحل (قروض تُستدعى وضمانات تُفرج عنها وتوزيعات تُعلن قبل الإغلاق لسحب القيمة)." } },
      { id: "iv-5", ref: "DD practice", text: { en: "Read the shareholder agreements for the group's constitutional issues: vetoes over share transfers, pre-emption rounds that complicate the seller's title (see L-01), and state golden shares.", ar: "قراءة اتفاقيات المساهمين بحثًا عن القضايا التأسيسية للمجموعة: حق النقض على نقل الأسهم وجولات الأولوية التي تعقد ملكية البائع (انظر L-01) والأسهم الذهبية." } },
      { id: "iv-6", ref: "IAS 39 / IFRS 9", text: { en: "For the financial portfolio: classification, valuation basis, and where the marks came from — a portfolio of unlisted paper at cost with 'imminent IPO' stories is a finding, not an asset.", ar: "للحافظة المالية: التصنيف وأساس التقييم ومصدر القيم — فحافظة أوراق غير مدرجة بالتكلفة مع حكايات «طرح وشيك» ملاحظة لا أصل." } },
      { id: "iv-7", ref: "DD practice", text: { en: "Map the intercompany web before the accountants do: balances each way, interest charged or waived, and management fees — the whole web nets into the pre-closing reorganization plan.", ar: "رسم شبكة ما بين الشركات قبل المحاسبين: الأرصدة في الاتجاهين والفوائد المحملة أو المعفاة وأجور الإدارة — فالشبكة كلها تُصفى في خطة إعادة الهيكلة قبل الإغلاق." } },
    ],
    analytics: [
      { en: "Dividend yield on book: dividends received ÷ carrying value, per investee", ar: "عائد التوزيع على الدفتر: التوزيعات المقبوضة ÷ القيمة الدفترية لكل شركة مستثمر فيها" },
      { en: "Equity-method income vs. cash dividends — the paper-vs-cash gap, 3 years", ar: "إيراد طريقة الحصص مقابل التوزيعات النقدية — فجوة الورق والنقد لثلاث سنوات" },
      { en: "Intercompany balances as % of net assets — the entanglement ratio", ar: "أرصدة ما بين الشركات كنسبة من صافي الأصول — نسبة التشابك" },
      { en: "Group guarantee coverage: guarantees given ÷ net assets of the giver", ar: "تغطية ضمانات المجموعة: الضمانات الممنوحة ÷ صافي أصول الضامن" },
    ],
    redFlags: [
      { text: { en: "Investments in loss-making associates carried at cost with no impairment ever — and no way to exit.", ar: "استثمارات في زميلات خاسرة محمولة بالتكلفة بلا انخفاض قط — وبلا سبيل للخروج." } },
      { text: { en: "Group guarantees the target gave that survive closing (they move from family courtesy to stranger's liability).", ar: "ضمانات منحها الهدف للمجموعة تبقى بعد الإغلاق (تتحول من مجاملة أسرية إلى التزام غريب)." }, critical: true },
      { text: { en: "Entities in the perimeter with unaudited or missing financial statements.", ar: "كيانات داخل المحيط بقوائم مالية غير مدققة أو مفقودة." } },
      { text: { en: "Investment values resting on stale valuations or 'imminent' events.", ar: "قيم استثمارات تستند إلى تقييمات بالية أو أحداث «وشيكة»." } },
    ],
  },

  {
    id: "payables",
    code: "F-08",
    scope: "financial",
    group: "accounts",
    icon: "package-check",
    title: { en: "Suppliers & Trade Payables", ar: "الموردون والذمم الدائنة" },
    scopeNote: {
      en: "The suppliers' account: what the business owes, to whom, on what terms — and whether the DPO on the eve of the deal is the real run-rate or a pre-sale payment stretch.",
      ar: "حساب الموردين: ما على النشاط ولمن وبأي شروط — وهل أيام السداد عشية الصفقة هي المعدل التشغيلي الحقيقي أم تمديد مفتعل قبيل البيع.",
    },
    why: [
      { en: "Normalize DPO: a payment stretch before the deal flatters working capital — the buyer inherits the snap-back.", ar: "تطبيع أيام السداد: فتمديد الدفع قبل الصفقة يجمل رأس المال العامل — والمشتري يرث الارتداد." },
      { en: "Catch the unrecorded side: un invoiced goods received, accrued liabilities suppressed, and the dispute pile.", ar: "اقتناص الجانب غير المسجل: بضاعة مستلمة بلا فواتير والتزامات مستحقة مكبوتة وكومة النزاعات." },
      { en: "Identify supplier financing disguised in payables: notes, factoring, and the deferred-price arrangements that are debt wearing supplier clothes.", ar: "تحديد تمويل الموردين المتنكر في الدائنين: أوراق وتورير وترتيبات تأجيل الثمن — دين يلبس ثوب المورد." },
    ],
    documents: [
      { en: "Aged payables listing at the deal date, reconciled to the trial balance", ar: "كشف أعمار الذمم الدائنة بتاريخ الصفقة مطابقًا لميزان المراجعة" },
      { en: "Top-25 supplier balances with terms and last-payment dates", ar: "أرصدة أكبر 25 موردًا بالشروط وتاريخ آخر سداد" },
      { en: "Purchase journal for the year (to match against receiving records)", ar: "يومية المشتريات للسنة (للمطابقة بسجلات الاستلام)" },
      { en: "Goods-received-not-invoiced (GRNI) listing and its aging", ar: "كشف البضاعة المستلمة بلا فاتورة وتقادمه" },
      { en: "Notes payable to suppliers and any supply-financing arrangements", ar: "أوراق دفع للموردين وأي ترتيبات تمويل توريد" },
      { en: "Supplier dispute and debit-note correspondence", ar: "مراسلات النزاعات والإشعارات المدينة مع الموردين" },
    ],
    procedures: [
      { id: "ap-1", ref: "DD practice", text: { en: "Trend DPO by month for 3 years and by supplier tier — look for the pre-deal step-up: 85 days suddenly paid at 120 means the closing working-capital peg is overstated by the difference.", ar: "تتبع أيام السداد شهريًا لثلاث سنوات وبفئة الموردين — بحثًا عن القفزة قبيل الصفقة: فمن يدفع فجأة عند 120 بعد 85 يعني أن مرساة رأس المال عند الإغلاق مبالغ فيها بالفرق." } },
      { id: "ap-2", ref: "DD practice", text: { en: "Search for unrecorded liabilities three ways: GRNI aging, post-date payments matched to old deliveries, and accrual reversals in the last quarter — completeness is where payables break.", ar: "البحث عن التزامات غير مسجلة بثلاث طرق: تقادم المستلم بلا فاتورة، ومدفوعات ما بعد التاريخ مقيدة على توريدات قديمة، واسترجاعات المخصصات في الربع الأخير — فالاكتمال موضع انكسار الدائنين." } },
      { id: "ap-3", ref: "DD practice", text: { en: "Read the top-25 supplier terms vs. actual payment behavior: discounts taken or missed, and who gets paid first when cash is tight — the payment hierarchy tells the real story.", ar: "قراءة شروط أكبر 25 موردًا مقابل سلوك السداد الفعلي: الخصومات المأخوذة أو الفائتة ومن يُدفع له أولًا عند الضيق — فترتيب الدفع يقول القصة الحقيقية." } },
      { id: "ap-4", ref: "DD practice", text: { en: "Strip related-party payables out of the working-capital peg: balances to the founder's other companies are settled (or crystallized into debt) at closing, not inherited.", ar: "إقصاء دائني الأطراف ذات العلاقة من مرساة رأس المال: فأرصدة شركات المؤسس الأخرى تُسوى (أو تتبلور دينًا) عند الإغلاق ولا تورث." } },
      { id: "ap-5", ref: "IAS 37", text: { en: "Hunt the off-P&L side: penalty clauses matured, quality claims pending, and rebate / retro-volume liabilities owed back to suppliers — all belong in debt-like items.", ar: "اقتفاء الجانب خارج الأرباح: جزاءات نضجت ومطالبات جودة معلقة والتزامات خصومات رجعية مستحقة للموردين — كلها من بنود شبيهة بالدين." } },
      { id: "ap-6", ref: "DD practice", text: { en: "Confirm significant balances directly (or via the data room's confirmations): the supplier both confirms the balance and — in a conversation — volunteers the relationship truth the seller never would.", ar: "التأكيد المباشر للأرصدة الجوهرية (أو عبر تأكيدات غرفة البيانات): فالمورد يؤكد الرصيد ويُفصح — في حديثٍ — عن حقيقة العلاقة ما لن يفعلها البائع أبدًا." } },
      { id: "ap-7", ref: "DD practice", text: { en: "Check for capital hiding in payables: deposits from customers netted inside supplier balances, and prepayments parked as credits — the account is the balance sheet's junk drawer.", ar: "فحص رأس مال مختبئ في الدائنين: دفعات عملاء مقاصة داخل أرصدة الموردين ومدفوعات مقدمة مركونة كأرصدة دائنة — فالحساب هو درج الميزانية المختلط." } },
      { id: "ap-8", ref: "DD practice", text: { en: "Hand the payables findings to both bridges: suppressed liabilities raise net debt; stretched DPO raises the working-capital normalization adjustment — each with its own number and evidence.", ar: "تمرير ملاحظات الدائنين للجسرين: الالتزامات المكبوتة ترفع صافي الدين؛ وأيام السداد الممددة ترفع تعديل تطبيع رأس المال — كلٌ برقمه ودليله." } },
    ],
    analytics: [
      { en: "DPO by month (3 years), by supplier tier — the pre-deal stretch detector", ar: "أيام السداد شهريًا (3 سنوات) وبفئة المورد — كاشف التمديد قبيل الصفقة" },
      { en: "GRNI aging and its coverage by later invoices", ar: "تقادم المستلم بلا فاتورة وتغطيته بالفواتير اللاحقة" },
      { en: "Missed early-payment discounts: value and trend — the cost of being cash-tight", ar: "الخصومات المبكرة الفائتة: القيمة والاتجاه — كلفة ضيق السيولة" },
      { en: "Related-party payables share of total", ar: "حصة دائني الأطراف ذات العلاقة من الإجمالي" },
      { en: "Disputed and debit-note balances as % of payables", ar: "الأرصدة المتنازع عليها والمدينة كنسبة من الدائنين" },
    ],
    redFlags: [
      { text: { en: "DPO jumped materially in the 6 months before the deal with no commercial reason.", ar: "قفزة جوهرية في أيام السداد في الستة أشهر قبل الصفقة بلا سبب تجاري." }, critical: true },
      { text: { en: "Last-quarter accrual reversals propping EBITDA.", ar: "استرجاعات مخصصات في الربع الأخير تسند الأرباح التشغيلية." } },
      { text: { en: "Supplier notes or factoring buried inside trade payables.", ar: "أوراق موردون أو تورير مدفون داخل الذمم التجارية." } },
      { text: { en: "Post-date payments matched to deliveries from before the year-end (unrecorded liabilities).", ar: "مدفوعات بعد التاريخ مقابلة توريدات قبل نهاية السنة (التزامات غير مسجلة)." } },
    ],
  },

  {
    id: "debt",
    code: "F-09",
    scope: "financial",
    group: "accounts",
    icon: "landmark",
    title: { en: "Borrowings & Debt-Like Items (Net Debt)", ar: "الاقتراضات والبنود الشبيهة بالدين (صافي الدين)" },
    scopeNote: {
      en: "Every claim on the business's cash beyond trade credit: bank debt, leases, shareholder loans, guarantees, litigation, and the deferred obligations the seller hopes the buyer reads as something else.",
      ar: "كل حق على نقد النشاط غير الائتمان التجاري: ديون البنوك والإيجارات وقروض المساهمين والضمانات والتقاضي والالتزامات المؤجلة التي يأمل البائع أن يقرأها المشتري شيئًا آخر.",
    },
    why: [
      { en: "Build the true net-debt bridge: the price is enterprise value minus net debt — every debt-like item missed is cash transferred to the seller.", ar: "بناء جسر صافي الدين الحقيقي: فالسعر قيمة منشأة ناقص صافي دين — وكل بند شبيه بالدين يفوت هو نقد انتقل إلى البائع." },
      { en: "Understand change-of-control triggers: loans callable, guarantees crystallizing, and hedges terminating at closing.", ar: "فهم محفزات تغير السيطرة: قروض تستدعى وضمانات تتبلور وتغطيات تنقضي عند الإغلاق." },
      { en: "Verify the debt is refinancable on terms the model assumes — the buyer inherits the covenant calendar.", ar: "التحقق من قابلية الدين لإعادة التمويل بالشروط التي يفترضها النموذج — فالمشتري يرث تقويم الالتزامات." },
    ],
    documents: [
      { en: "Loan and facility agreements with all amendments and waivers", ar: "اتفاقيات القروض والتسهيلات بكل تعديلاتها والإعفاءات" },
      { en: "Repayment schedule and the covenant compliance certificates for 3 years", ar: "جدول السداد وشهادات الالتزام بالشروط لثلاث سنوات" },
      { en: "Security register: mortgages, pledges, assignments, and liens (with property IDs)", ar: "سجل الضمانات: رهون ورسو وتنازلات وحجوز (بأرقام العقارات)" },
      { en: "Guarantees given (to banks, group companies, customers) with exposure amounts", ar: "الضمانات الممنوحة (للبنوك وشركات المجموعة والعملاء) بمبالغ التعرض" },
      { en: "Intercompany and shareholder loan agreements with the subordination picture", ar: "اتفاقيات القروض بين الشركات ومن المساهمين مع صورة الأسبقية" },
      { en: "Derivative/hedge documentation (FX, interest rate) and mark-to-market positions", ar: "مستندات المشتقات والتغطية (عملات وفائدة) ومراكز القيمة العادلة" },
      { en: "The debt-like schedule the seller prepared (to be tested, not trusted)", ar: "جدول البنود الشبيهة بالدين الذي أعده البائع (يُختبر ولا يُؤخذ بثقة)" },
    ],
    procedures: [
      { id: "db-1", ref: "DD practice", text: { en: "Rebuild net debt from the primary documents, not the seller's schedule: every facility traced to its agreement, its utilization, and its bank confirmation — then compare; the differences are the negotiation agenda.", ar: "إعادة بناء صافي الدين من المستندات الأصلية لا جدول البائع: تتبع كل تسهيل لاتفاقه واستغلاله وتأكيده البنكي — ثم المقارنة؛ فالفروق هي جدول أعمال التفاوض." } },
      { id: "db-2", ref: "DD practice", text: { en: "Read every facility for change-of-control: acceleration clauses, consent requirements, and prepayment penalties — a callable loan is a closing condition, a liquidity plan, and a negotiation chip at once.", ar: "قراءة كل تسهيل بحثًا عن تغير السيطرة: بنود الاستحقاق الفوري ومتطلبات الموافقة وغرامات السداد المبكر — فالقرض القابل للاستدعاء شرط إغلاق وخطة سيولة وورقة تفاوض معًا." } },
      { id: "db-3", ref: "IFRS 16", text: { en: "Bring all leases into the debt side: lease liabilities per IFRS 16 plus the off-sheet leases the target missed (short-term and low-value exemptions are real money when spread across a fleet).", ar: "إدخال كل الإيجارات في جانب الدين: التزامات الإيجار وفق IFRS 16 زائد الإيجارات خارج الميزانية التي فاتتها (فإعفاءات الأجل القصير والقيمة الضئيلة مال حقيقي إذا توزع على أسطول)." } },
      { id: "db-4", ref: "DD practice", text: { en: "Compile the debt-like items inventory with amounts: overdue director fees, bonus accruals, deferred capex to suppliers, environmental and reinstatement obligations, and unfunded pension or end-of-service gaps (see L-06).", ar: "تحرير جرد البنود الشبيهة بالدين بالمبالغ: أجور مجلس متأخرة ومخصصات حوافز واستثمار رأسمالي مؤجل للموردين والتزامات بيئية وإعادة حال وفجوات نهاية الخدمة غير الممولة (انظر L-06)." } },
      { id: "db-5", ref: "IAS 37", text: { en: "Quantify guarantees and litigation exposures as debt-like items: the guaranteed amount, the probability-weighted expected outflow, and the collateral pledged for each — the three numbers together decide the treatment.", ar: "تقدير الضمانات وتعرضات التقاضي كبنود شبيهة بالدين: المبلغ المضمون والتدفق المتوقع المرجح بالاحتمال والضمان المرهون لكل منها — الأرقام الثلاثة مجتمعة تقرر المعالجة." } },
      { id: "db-6", ref: "DD practice", text: { en: "Test the shareholder loans: terms, interest, subordination, and forgiveness history — seller paper that is quasi-equity should convert to equity at closing, not ride out as debt the buyer repays.", ar: "اختبار قروض المساهمين: الشروط والفائدة والأسبقية وتاريخ الإعفاء — فورقة البائع شبه رأس المال ينبغي أن تتحول حقوق ملكية عند الإغلاق لا أن تبقى دينًا يسدده المشتري." } },
      { id: "db-7", ref: "IFRS 9", text: { en: "Verify the hedge book: instruments, notional, effectiveness, and the unwind cost at closing — hedges tied to the sold entity terminate and crystallize their mark-to-market.", ar: "التحقق من دفتر التغطية: الأدوات والقيمة الاسمية والفاعلية وكلفة الفك عند الإغلاق — فالتغطيات المرتبطة بالمنشأة المبيعة تنقضي وتُثمر قيمتها العادلة." } },
      { id: "db-8", ref: "DD practice", text: { en: "Check the covenant calendar forward: which covenants, tested when, with what headroom under the buyer's case — a covenant breached in month 3 of ownership reprices the whole deal.", ar: "فحص تقويم الالتزامات أمامًا: أي الشروط تُختبر ومتى وبأي هامش في حالة المشتري — فالالتزام المنتهك في الشهر الثالث من الملكية يعيد تسعير الصفقة كلها." } },
      { id: "db-9", ref: "DD practice", text: { en: "Confirm refinance feasibility with the target's banks before signing (through the seller): committed term sheets beat assumed terms — model the difference as a risk buffer.", ar: "تأكيد قابلية إعادة التمويل مع بنوك الهدف قبل التوقيع (عبر البائع): فخطوط الالتزام المصدقة تغلب الشروط المفترضة — والفرق يُنمذج كهامش خطر." } },
    ],
    analytics: [
      { en: "Net debt bridge: every line from the seller's figure to the buyer's figure, with evidence", ar: "جسر صافي الدين: كل سطر من رقم البائع إلى رقم المشتري بالدليل" },
      { en: "Leverage: net debt ÷ adjusted EBITDA (both as reported and as adjusted)", ar: "الرفع: صافي الدين ÷ الأرباح التشغيلية المعدلة (كما أُعلنت وكما عُدلت)" },
      { en: "Debt maturity wall: repayment profile by year vs. the business plan's free cash flow", ar: "حائط الاستحقاق: ملف السداد بالسنة مقابل التدفق النقدي الحر لخطة النشاط" },
      { en: "Covenant headroom trend — how close to the edge the business has been living", ar: "اتجاه هامش الالتزامات — كم قربت الأعمال من الحافة" },
      { en: "Guarantee exposure ÷ net assets — the contingent leverage", ar: "تعرض الضمانات ÷ صافي الأصول — الرفع المحتمل" },
    ],
    redFlags: [
      { text: { en: "Undisclosed debt found in bank confirmations or the statements.", ar: "دين غير مفصح عنه يُكتشف في تأكيدات البنوك أو الكشوف." }, critical: true },
      { text: { en: "Shareholder loans positioned as debt to be repaid by the buyer at closing.", ar: "قروض مساهمين معروضة كدين يسدده المشتري عند الإغلاق." } },
      { text: { en: "Change-of-control acceleration across the main facilities with no refinance plan.", ar: "استحقاق فوري عند تغير السيطرة عبر التسهيلات الرئيسية بلا خطة إعادة تمويل." } },
      { text: { en: "Guarantees for group companies with collateral from the target's assets.", ar: "ضمانات لشركات المجموعة بضمانات من أصول الهدف." } },
    ],
  },

  {
    id: "equity",
    code: "F-10",
    scope: "financial",
    group: "accounts",
    icon: "scale",
    title: { en: "Equity & Related Parties", ar: "حقوق الملكية والأطراف ذات العلاقة" },
    scopeNote: {
      en: "Who owns the company (again, financially this time), what has been extracted from it historically, and the web of related-party dealings that must be unwound or repriced at closing.",
      ar: "من يملك الشركة (مرة أخرى، ماليًا هذه المرة)، وما استُنزف منها تاريخيًا، وشبكة تعاملات الأطراف ذات العلاقة التي يجب حلها أو إعادة تسعيرها عند الإغلاق.",
    },
    why: [
      { en: "Reconcile equity to its components: capital, reserves, retained earnings — and the dividends that stripped it on the way to the deal.", ar: "مطابقة حقوق الملكية بمكوناتها: رأس المال والاحتياطيات والأرباح المرحلة — والتوزيعات التي نزفتها في الطريق إلى الصفقة." },
      { en: "Normalize the owner's economic footprint: salaries, benefits, personal expenses, and assets the business funds but does not use.", ar: "تطبيع الأثر الاقتصادي للمالك: الأجور والمزايا والمصروفات الشخصية والأصول التي يمولها النشاط ولا يستخدمها." },
      { en: "Re-price every related-party dealing to arm's length — the QoE bridge's largest single adjustment family.", ar: "إعادة تسعير كل تعامل مع الأطراف ذات العلاقة إلى المعاملة المطلقة — أكبر عائلة تعديلات منفردة في جسر جودة الأرباح." },
    ],
    documents: [
      { en: "Equity statement for 3 years with every movement explained", ar: "قائمة حقوق الملكية لثلاث سنوات مع تفسير كل حركة" },
      { en: "Dividend history and the distribution decisions (with the papers behind them)", ar: "تاريخ التوزيعات وقراراتها (بمستنداتها)" },
      { en: "Complete related-party transaction schedule: party, dealing, amount, terms", ar: "جدول كامل لمعاملات الأطراف ذات العلاقة: الطرف والتعامل والمبلغ والشروط" },
      { en: "Owner compensation package: salary, bonus, benefits, insurance, vehicles", ar: "حزمة تعويض المالك: الأجر والمكافأة والمزايا والتأمين والمركبات" },
      { en: "Assets of the business used personally (cars, houses, planes) and their costs", ar: "أصول النشاط المستخدمة شخصيًا (سيارات ومنازل وطائرات) وتكلفتها" },
      { en: "Any capital reduction or share buyback history", ar: "أي تاريخ تخفيض رأس مال أو إعادة شراء أسهم" },
    ],
    procedures: [
      { id: "eq-1", ref: "IAS 24", text: { en: "Reconcile the equity statement to the decisions: every dividend against the legal distributable test and the actual cash paid — dividends declared but unpaid are a debt-like item the buyer inherits.", ar: "مطابقة قائمة حقوق الملكية بالقرارات: كل توزيعة مقابل اختبار القابلية للتوزيع قانونًا والنقد المدفوع فعلًا — فالتوزيعات المعلنة غير المدفوعة بند شبيه بالدين يرثه المشتري." } },
      { id: "eq-2", ref: "DD practice", text: { en: "Build the owner-adjustment table: total owner compensation and benefits, each item with its market-rate replacement — the delta adjusts EBITDA and the pro-forma payroll simultaneously.", ar: "بناء جدول تعديلات المالك: إجمالي تعويض المالك ومزاياه، كل بند بمعدله البديل السوقي — فالفرق يعدل الأرباح التشغيلية والأجور المفترضة معًا." } },
      { id: "eq-3", ref: "IAS 24", text: { en: "Re-run each related-party dealing at arm's length: management fees, rent (to the founder's property company), purchases and sales, and loans — quantify the EBITDA effect of each repricing, both directions.", ar: "إعادة احتساب كل تعامل أطراف ذات علاقة بمعاملة مطلقة: أجور إدارة وإيجار (لشركة عقارات المؤسس) ومشتريات ومبيعات وقروض — وتقدير أثر كل إعادة تسعير على الأرباح في الاتجاهين." } },
      { id: "eq-4", ref: "DD practice", text: { en: "Identify cost structures that exist for the owner, not the business: doubled family salaries (see L-06), vanity assets, sponsorships of the family's choosing — the post-closing P&L sheds them and the QoE must show it.", ar: "تحديد بنى كلفة تقوم للمالك لا للنشاط: أجور أسرية مضاعفة (انظر L-06) وأصول بروق ومشاريع رعاية باختيار الأسرة — فالأرباح بعد الإغلاق تخلعها ويجب أن يظهر ذلك في جسر الجودة." } },
      { id: "eq-5", ref: "DD practice", text: { en: "Check for the owner's personal guarantees on the company's debt — they need release or replacement at closing, and banks price that transfer.", ar: "فحص الضمانات الشخصية للمالك على ديون الشركة — تحتاج إفراجًا أو استبدالًا عند الإغلاق، والبنوك تسعر هذا الانتقال." } },
      { id: "eq-6", ref: "IAS 24 / IAS 1", text: { en: "Verify completeness of the related-party schedule against the flows found in F-04 (cash scanning) — deals that never made the schedule are exactly the ones that matter.", ar: "التحقق من اكتمال جدول الأطراف ذات العلاقة مقابل التدفقات المكتشفة في F-04 (مسح النقد) — فالتعاملات التي لم تدخل الجدول هي التي تعني بالضبط." } },
      { id: "eq-7", ref: "DD practice", text: { en: "Draft the perimeter's unwinding plan: which related-party arrangements terminate at closing, which get re-cut at market, and which continue by design (name them in the SPA's continuing arrangements annex).", ar: "صياغة خطة حل التعاملات داخل المحيط: أي ترتيبات تنتهي عند الإغلاق وأيها يُعاد قطعها بالسوق وأيها يستمر عن قصد (تُسمى في ملحق الترتيبات المستمرة باتفاق البيع)." } },
    ],
    analytics: [
      { en: "Owner cost table: reported vs. market-based replacement cost, total delta", ar: "جدول كلفة المالك: المعلن مقابل كلفة الاستبدال السوقية والفرق الإجمالي" },
      { en: "Related-party EBITDA effect: total of all repricings, both directions", ar: "أثر الأطراف ذات العلاقة على الأرباح: مجموع كل إعادات التسعير في الاتجاهين" },
      { en: "Dividends ÷ free cash flow — the extraction rate", ar: "التوزيعات ÷ التدفق النقدي الحر — معدل الاستنزاف" },
      { en: "Personal costs in the P&L: value and trend (the QoE add-back family)", ar: "المكلف الشخصية في الأرباح: القيمة والاتجاه (عائلة الإضافات في جسر الجودة)" },
    ],
    redFlags: [
      { text: { en: "Dividend declared just before signing, stripping the cash the price assumed.", ar: "توزيعة معلنة قبيل التوقيع تستنزف النقد الذي افترضه السعر." }, critical: true },
      { text: { en: "Related-party dealings absent from the schedule but visible in the cash flows.", ar: "تعاملات أطراف ذات علاقة غائبة عن الجدول ظاهرة في التدفقات النقدية." } },
      { text: { en: "Owner compensation far below market with the gap 'compensated' by unexplained withdrawals.", ar: "تعويض مالك دون السوق بكثير والفجوة «تعوضها» سحوبات بلا تفسير." } },
      { text: { en: "Business funding personal assets or expenses with no documentation at all.", ar: "النشاط يمول أصولًا أو مصروفات شخصية بلا أي مستندات." } },
    ],
  },

  {
    id: "payroll",
    code: "F-11",
    scope: "financial",
    group: "accounts",
    icon: "users",
    title: { en: "Payroll & Personnel Costs", ar: "الأجور وتكاليف العنصر البشري" },
    scopeNote: {
      en: "The biggest controllable cost in most businesses: what the people truly cost — salaries, social insurance, payroll tax, and the promises that will come due.",
      ar: "أكبر كلفة قابلة للضبط في معظم الأعمال: الكلفة الحقيقية للأفراد — الأجور والتأمينات وضريبة المرتبات والوعود التي ستستحق.",
    },
    why: [
      { en: "Normalize the payroll to the go-forward structure: who stays, who goes, and what each costs — the pro-forma payroll is a price input, not an HR memo.", ar: "تطبيع كشف الأجور على الهيكل القادم: من يبقى ومن يرحل وكم كلفة كل واحد — فالأجور المفترضة مدخل في السعر لا مذكرة موارد بشرية." },
      { en: "Verify the statutory loadings: social insurance and payroll tax actually computed on actual wages (see L-06 for the legal side).", ar: "التحقق من الأعباء النظامية: التأمينات وضريبة المرتبات محسوبة فعلًا على الأجور الفعلية (للجانب القانوني انظر L-06)." },
      { en: "Catch the bonus and commission accruals: the formulas, the history, and the payout timing — deferred compensation is debt-like.", ar: "اقتناص مخصصات الحوافز والعمولات: المعادلات والتاريخ وتوقيت الدفع — فالتعويض المؤجل شبيه بالدين." },
    ],
    documents: [
      { en: "Payroll register for 12 months by employee (see L-06 for the roster)", ar: "سجل الأجور لاثني عشر شهرًا لكل موظف (لكشف العاملين انظر L-06)" },
      { en: "Org chart of the go-forward structure with the integration plan's roles", ar: "هيكل القادم التنظيمي بأدوار خطة الدمج" },
      { en: "Bonus, commission, and profit-share schemes with their formulas and 2-year history", ar: "خطط الحوافز والعمولات والمشاركة في الأرباح بمعادلاتها وتاريخ سنتين" },
      { en: "Social insurance and payroll tax filings vs. the payroll register reconciliation", ar: "إقرارات التأمينات وضريبة المرتبات مقابل سجل الأجور ومطابقتها" },
      { en: "Overtime and temporary/outsourced labor costs, by month", ar: "تكاليف الوقت الإضافي والعمالة المؤقتة والمسندة شهريًا" },
      { en: "Training, retention, and notice liabilities under the deal's plans", ar: "التزامات التدريب والاحتفاظ والإخطار بموجب خطط الصفقة" },
    ],
    procedures: [
      { id: "py-1", ref: "DD practice", text: { en: "Reconcile payroll expense three ways: payroll register → GL → bank transfers — then reconcile headcount: register → insurance forms → access badges; the two three-way ties catch both ghost employees and understated wages.", ar: "مطابقة مصروف الأجور ثلاثيًا: سجل الأجور ← الدفتر العام ← التحويلات البنكية — ثم مطابقة الأعداد: السجل ← نماذج التأمين ← كروت الدخول؛ فالعقدتان الثلاثيتان تكتشفان موظفي الأشباح والأجور المدرة بالباقت معًا." } },
      { id: "py-2", ref: "DD practice", text: { en: "Build the pro-forma payroll: current cost, minus leavers, plus retention packages, plus replacements at market — the number the deal model carries as run-rate, with each assumption named.", ar: "بناء الأجور المفترضة: الكلفة الحالية ناقص المغادرين زائد حزم الاحتفاظ زائد البدلاء بالسوق — الرقم الذي يحمله نموذج الصفقة كمعدل تشغيل بكل فرض مسمى." } },
      { id: "py-3", ref: "IAS 19", text: { en: "Test the bonus and commission accruals against formulas and history — and check the payout timing: accrued-but-unpaid schemes ride into the net-debt bridge as debt-like items.", ar: "اختبار مخصصات الحوافز والعمولات مقابل المعادلات والتاريخ — وفحص توقيت الدفع: فالخطط المستحقة غير المدفوعة تجار إلى جسر صافي الدين كبنود شبيهة بالدين." } },
      { id: "py-4", ref: "IAS 19", text: { en: "Quantify end-of-service and leave liabilities independently (see L-06's legal test) and compare to the books — the shortfall goes to the bridge, with the tax effect noted.", ar: "تقدير التزامات نهاية الخدمة والأجازات باستقلال (للاختبار القانوني انظر L-06) ومقارنتها بالدفاتر — فالعجز يذهب للجسر مع ملاحظة الأثر الضريبي." } },
      { id: "py-5", ref: "DD practice", text: { en: "Analyze the labor cost curve: overtime trend, temporary labor reliance, and the true cost per unit produced or per revenue pound — cost structures that lean on undocumented overtime break at the first inspection.", ar: "تحليل منحنى كلفة العمل: اتجاه الوقت الإضافي والاعتماد على العمالة المؤقتة والكلفة الحقيقية لكل وحدة منتجة أو لكل جنيه إيراد — فبنى الكلفة المتكئة على وقت إضافي غير موثق تنكسر عند أول تفتيش." } },
      { id: "py-6", ref: "DD practice", text: { en: "Check the payroll's hidden members: contractors who are employees in substance (continuity, exclusivity, direction) — the reclassification cost lands on the buyer as penalties and retro-benefits.", ar: "فحص الأعضاء الخفيين في كشف الأجور: مقاولون هم موظفون في الجوهر (استمرارية وحصرية وتبعية) — فكلفة إعادة التصنيف تحط على المشتري جزاءات ومزايا بأثر رجعي." } },
      { id: "py-7", ref: "DD practice", text: { en: "Hand the payroll package to both bridges: the pro-forma run-rate adjusts EBITDA; the accrual shortfalls and retention costs adjust net debt — one table, two destinations, no double counting.", ar: "تمرير حزمة الأجور للجسرين: المعدل المفترض يعدل الأرباح التشغيلية؛ وعجز المخصصات وكلف الاحتفاظ يعدل صافي الدين — جدول واحد ووجهتان وبلا عد مزدوج." } },
    ],
    analytics: [
      { en: "Payroll as % of revenue and of opex, trended — the cost structure signature", ar: "الأجور كنسبة من الإيراد ومن المصروفات التشغيلية باتجاهها — بصمة بنية الكلفة" },
      { en: "Average cost per employee and the spread around it (the family-salary outliers)", ar: "متوسط الكلفة للموظف وتشتتها (الشواذ الأسرية في الأجور)" },
      { en: "Statutory loading accuracy: insurance base vs. actual wages gap", ar: "دقة الأعباء النظامية: فجوة أساس التأمين مقابل الأجور الفعلية" },
      { en: "Overtime and temporary labor as % of direct labor — the fragility share", ar: "الوقت الإضافي والعمالة المؤقتة كنسبة من العمل المباشر — حصة الهشاشة" },
      { en: "Bonus payout vs. accrual history — the discipline check", ar: "مدفوعات الحوافز مقابل تاريخ المخصصات — اختبار الانضباط" },
    ],
    redFlags: [
      { text: { en: "Ghost or family payroll entries with no operational role (also L-06).", ar: "قيود أجور أشباح أو أقارب بلا دور تشغيلي (أيضًا L-06)." } },
      { text: { en: "Insurance base systematically below actual wages.", ar: "أساس التأمين دون الأجور الفعلية بانتظام." }, critical: true },
      { text: { en: "Bonus scheme changed favorably in the deal year.", ar: "تغيير خطة الحوافز لصالحها في سنة الصفقة." } },
      { text: { en: "Key staff paid significantly below market with verbal promises of post-deal riches.", ar: "كوادر جوهرية تتقاضى دون السوق بكثير مع وعود شفهية بثراء بعد الصفقة." } },
    ],
  },

  {
    id: "tax",
    code: "F-12",
    scope: "financial",
    group: "accounts",
    icon: "receipt",
    title: { en: "Taxes & Fiscal Exposure", ar: "الضرائب والتعرض الضريبي" },
    scopeNote: {
      en: "Every tax the business owes, underpaid, or disputed: income tax, VAT, payroll tax, withholding — and the step-up or carryover decision that shapes the buyer's future tax position.",
      ar: "كل ضريبة على النشاط: مستحقة أو مسددة بأقل أو متنازع عليها: ضريبة الدخل والقيمة المضافة وكسب العمل والخصم من المنبع — وقرار الاستمرار أو رفع الأساس الذي يشكل المركز الضريبي القادم للمشتري.",
    },
    why: [
      { en: "Verify the filings actually happened and match the activity: declared revenue vs. book revenue, declared VAT vs. the sales journal — the gap is the exposure.", ar: "التحقق من أن الإقرارات قُدمت فعلًا وتطابق النشاط: الإيراد المعلن مقابل الدفتري والضريبة المعلنة مقابل يومية المبيعات — فالفتحة هي التعرض." },
      { en: "Map the disputes: assessments, objections, and appeals — with the statute of limitations windows (see L-03 for procedure).", ar: "رسم خريطة المنازعات: التقييمات والاعتراضات والطعون — بنوافذ التقادم (للإجراءات انظر L-03)." },
      { en: "Model the deal's own tax mechanics: carryover basis vs. step-up, losses that survive or die, and the transfer taxes on the chosen structure.", ar: "نمذجة ميكانيكا الصفقة الضريبية: الأساس المنقول مقابل المرفوع والخسائر التي تبقى أو تموت وضرائب الانتقال على الهيكل المختار." },
    ],
    documents: [
      { en: "Tax returns for 3-5 years: income, VAT, withholding, payroll (Form 4)", ar: "الإقرارات الضريبية لثلاث إلى خمس سنوات: الدخل والقيمة المضافة والخصم وكسب العمل (نموذج 4)" },
      { en: "Tax position papers: treatments, positions taken, and advisor opinions", ar: "أوراق الموقف الضريبي: المعالجات والمواقف وآراء المستشارين" },
      { en: "Assessment notices, objections, appeals, and their status", ar: "إخطارات التقييم والاعتراضات والطعون وحالتها" },
      { en: "Tax audit history and the reconciliations produced for each audit", ar: "تاريخ الفحص الضريبي والتسويات المنتجة لكل فحص" },
      { en: "VAT reconciliation: output vs. sales, input vs. purchases, by month", ar: "تسوية القيمة المضافة: المستحق مقابل المبيعات والمدخل مقابل المشتريات شهريًا" },
      { en: "Loss carryforward schedule and its expiry", ar: "جدول الخسائر المرحلة وانتهاؤها" },
      { en: "Transfer pricing file for cross-border related-party dealings", ar: "ملف أسعار التحويل لتعاملات الأطراف ذات العلاقة العابرة للحدود" },
    ],
    procedures: [
      { id: "tx-1", ref: "Tax procedures law", text: { en: "Reconcile declarations to books for each tax and each year: declared revenue vs. book, declared taxable profit vs. the tax computation, VAT output vs. sales journal — any systematic gap is exposure with interest and penalties running.", ar: "مطابقة الإقرارات بالدفاتر لكل ضريبة وكل سنة: الإيراد المعلن مقابل الدفتري والربح الخاضع المعلن مقابل الحساب الضريبي وضريبة المخرجات مقابل يومية المبيعات — أي فجوة منتظمة تعرض بفوائد وجزاءات تسري." } },
      { id: "tx-2", ref: "IAS 12", text: { en: "Verify the deferred tax computation: temporary differences actually identified (ECL, depreciation, provisions, carryforwards) and the rate applied — deferred tax errors move equity at closing.", ar: "التحقق من احتساب الضريبة المؤجلة: الفروق المؤقتة المحددة فعلًا (مخصصات وإهلاك ومخصصات وخسائر مرحلة) والنسبة المطبقة — فأخطاء الضريبة المؤجلة تحرك حقوق الملكية عند الإغلاق." } },
      { id: "tx-3", ref: "DD practice", text: { en: "Build the exposure schedule: each open year, each open dispute, the amount assessed or at risk, the probability, and the interest/penalty tail — the schedule prices the tax indemnity and the escrow.", ar: "بناء جدول التعرض: كل سنة مفتوحة وكل نزاع مفتوح والمبلغ المقيّم أو المعرض للخطر والاحتمال وذيل الفوائد والجزاءات — فالجدول يسعر التعويض الضريبي والضمان المقيّد." } },
      { id: "tx-4", ref: "VAT law 67/2016", text: { en: "Test the VAT engine: registration scope, correct rates by product, input recovery discipline, and the treatment of exports and zero-rate supplies — VAT errors compound monthly and transfer with the entity.", ar: "اختبار محرك القيمة المضافة: نطاق التسجيل والنسب الصحيحة لكل منتج وانضباط استرداد المدخل ومعاملة الصادرات والتوريدات الصفرية — فأخطاء المضافة تتراكم شهريًا وتنتقل مع الكيان." } },
      { id: "tx-5", ref: "DD practice", text: { en: "Check withholding taxes on the flows: royalties, fees, interest, and cross-border payments — un-withheld amounts become the buyer's liability plus the seniority of penalties.", ar: "فحص الضرائب المنبعية على التدفقات: إتاوات وأجور وفوائد ومدفوعات عابرة للحدود — فالمبالغ غير المخصومة تصبح التزام المشتري يضاف إليها أقدمية الجزاءات." } },
      { id: "tx-6", ref: "Transfer pricing rules", text: { en: "Where the group deals cross-border, review the transfer pricing file: comparability, methods, and documentation depth — the buyer inherits the audit posture with the entity.", ar: "حيث تتعدى تعاملات المجموعة الحدود، مراجعة ملف أسعار التحويل: القابلية للمقارنة والمناهج وعمق التوثيق — فالمشتري يرث موقف الفحص مع الكيان." } },
      { id: "tx-7", ref: "IAS 12", text: { en: "Model the structure's tax mechanics with the deal lawyers: share vs. asset deal basis, loss survival, stamp and capital gains taxes, and the step-up's future shield — the structure decision is often worth more than the price negotiation.", ar: "نمذجة ميكانيكا الهيكل الضريبي مع محامي الصفقة: صفقة أسهم مقابل أصول وبقاء الخسائر وضرائب الدمغة والأرباح الرأسمالية ودرع الرفع المستقبلي — فقرار الهيكل يساوي أحيانًا أكثر من مفاوضة السعر." } },
      { id: "tx-8", ref: "DD practice", text: { en: "Obtain the tax clearance certificates available for the deal's structure (and where they cannot be obtained, document why) — clearances move tax exposure from the price to the authority, which is where it belongs.", ar: "الحصول على شهادات براءة الذمة الضريبية المتاحة لهيكل الصفقة (وحيث لا يمكن، توثيق السبب) — فالبراءات تنقل التعرض الضريبي من السعر إلى الجهة، وهو موضعه الصحيح." } },
    ],
    analytics: [
      { en: "Effective tax rate vs. statutory, 3 years — and the reasons map", ar: "المعدل الضريبي الفعلي مقابل النظامي لثلاث سنوات — وخريطة الأسباب" },
      { en: "VAT gap: output tax implied by sales vs. declared, by month", ar: "فجوة القيمة المضافة: الضريبة المستحقة بتضمين المبيعات مقابل المعلنة شهريًا" },
      { en: "Open-years exposure: assessed + at-risk amounts with probability weighting", ar: "تعرض السنوات المفتوحة: المقيم والمعرض للخطر بترجيح الاحتمال" },
      { en: "Penalty and interest tail on the exposure schedule", ar: "ذيل الجزاءات والفوائد على جدول التعرض" },
      { en: "Loss carryforwards: amount, expiry, and survival under the deal structure", ar: "الخسائر المرحلة: المبلغ والانتهاء والبقاء بموجب هيكل الصفقة" },
    ],
    redFlags: [
      { text: { en: "Declarations materially below books for any tax in any year.", ar: "إقرارات دون الدفاتر جوهريًا في أي ضريبة بأي سنة." }, critical: true },
      { text: { en: "No VAT reconciliation exists — or it exists and does not tie.", ar: "لا توجد تسوية ضريبة قيمة مضافة — أو توجد ولا تنعقد." } },
      { text: { en: "Disputes at appeal with the statutory window about to close.", ar: "نزاع في الطعن توشك نافذته القانونية أن تغلق." } },
      { text: { en: "Cross-border related-party flows with no transfer pricing file at all.", ar: "تدفقات أطراف ذات علاقة عابرة للحدود بلا أي ملف أسعار تحويل." } },
    ],
  },
]
