import type { DDSection } from "./types"

/** Legal due diligence — the company's legal right to exist, own, contract,
 *  and defend itself. Seven workstreams, L-01 … L-07. Grounded in Egyptian
 *  law (Companies Law 159/1981, Civil Code 131/1948, IP Law 82/2002, Labor
 *  Law 14/2025, Data Protection Law 151/2020) with IFRS/FRA touchpoints
 *  where the legal finding becomes a financial statement item. */
export const DD_LEGAL: DDSection[] = [
  {
    id: "corporate-structure",
    code: "L-01",
    scope: "legal",
    group: null,
    icon: "landmark",
    title: { en: "Corporate Standing & Structure", ar: "الكيان القانوني والهيكل" },
    scopeNote: {
      en: "Incorporation, shareholding, corporate governance and the target's whole group structure — confirming the seller actually owns what is being sold, and the entity was validly formed and remains in good standing.",
      ar: "التأسيس وحركة الأسهم والحوكمة وهيكل المجموعة كاملًا — للتأكد من أن البائع يملك فعلًا ما يبيعه، وأن الكيان أُنشأ بشكل صحيح ولا يزال قائمًا بحالته السارية.",
    },
    why: [
      { en: "Establish that the target exists validly, is permitted to conduct its stated business, and has no dissolution or merger pending against it.", ar: "إثبات أن الهدف قائم بشكل صحيح ومرخّص لمزاولة نشاطه المعلن، ولا يوجد بحقه قرار حل أو اندماج معلق." },
      { en: "Map the cap table: who owns what percentage, fully paid or not, and whether any share is pledged, frozen, or subject to pre-emption rights.", ar: "رسم خريطة الملكية: من يملك أي نسبة، وهل الأسهم مدفوعة بالكامل، وهل يوجد رهن أو حجز أو حق أولوية على أي منها." },
      { en: "Confirm every subsidiary and affiliate in the structure is included in (or consciously excluded from) the transaction perimeter.", ar: "التأكد من أن كل شركة تابعة أو زميلة في الهيكل داخلة في محيط الصفقة (أو مستبعدة منها عن قصد)." },
      { en: "Verify the signatories on the sale documents actually hold current, unrevoked authority to bind the target.", ar: "التحقق من أن الموقعين على مستندات البيع يملكون تفويضًا ساريًا غير مسحوبًا لإلزام الهدف." },
    ],
    documents: [
      { en: "Commercial register extract (fresh, ≤ 3 months) and tax card", ar: "شهادة سجل تجاري حديثة (≤ 3 أشهر) والبطاقة الضريبية" },
      { en: "Memorandum & articles of association with every amendment since incorporation", ar: "عقد التأسيس ونظامه الأساسي مع كل تعديل منذ التأسيس" },
      { en: "Cap table: shareholders' register, share certificates, transfer Forms (Form 12), GAFI/investor notifications", ar: "سجل المساهمين وشهادات الأسهم ونماذج الانتقال (نموذج 12) وإخطارات هيئة الاستثمار" },
      { en: "Board and general-assembly minutes for the last 3 years (plus any written resolutions)", ar: "محاضر مجلس الإدارة والجمعية العمومية لآخر 3 سنوات (وأي قرارات كتابية)" },
      { en: "Organization chart of the whole group with ownership percentages and jurisdictions", ar: "الهيكل التنظيمي للمجموعة كاملة بنسب الملكية ودول التأسيس" },
      { en: "Powers of attorney currently in force (especially banking and litigation POAs)", ar: "التوكيلات الرسمية السارية (خاصة توكيلات البنوك والتقاضي)" },
    ],
    procedures: [
      { id: "cs-1", ref: "Companies Law 159/1981", text: { en: "Obtain a fresh commercial register extract and reconcile it to the articles: legal name, legal form, registered objects, capital, and managers — every mismatch is a finding, however small.", ar: "الحصول على شهادة سجل تجاري حديثة ومطابقتها بالنظام الأساسي: الاسم القانوني والشكل القانوني والأغراض ورأس المال والمديرين — أي اختلاف يمثل ملاحظة مهما صغر." } },
      { id: "cs-2", ref: "DD practice", text: { en: "Trace 100% of the share capital: current register, issued certificates, and the last 5 years of transfers — each transfer checked for board approval, stamp duty, and registration in the shareholders' register.", ar: "تتبع 100% من رأس المال: السجل الحالي والشهادات الصادرة وتحويلات آخر 5 سنوات — ولف كل انتقال قرار من مجلس الإدارة وسداد رسم النقل وقيد في سجل المساهمين." } },
      { id: "cs-3", ref: "Companies Law 159/1981", text: { en: "Verify shares are fully paid: bank evidence of capital deposits or auditor certificates; unpaid capital is a cash-in obligation the buyer inherits on day one.", ar: "التحقق من سداد قيمة الأسهم بالكامل: مستندات بنكية على إيداع رأس المال أو شهادات المراجع؛ رأس المال غير المسدد التزامٌ بالنقد يرثه المشتري من اليوم الأول." } },
      { id: "cs-4", ref: "DD practice", text: { en: "Search the pledged-shares registers (bank liens, court freezes, usufruct) for every shareholder of record — a pledged share cannot be cleanly transferred without the pledgee's consent.", ar: "الاستعلام عن سجلات رهن الأسهم (رهون بنكية أو حجوز قضائية أو حق انتفاع) لكل مساهم مقيد — فالسهم المرهون لا ينتقل بشكل سليم دون موافقة الدائن المرتهن." } },
      { id: "cs-5", ref: "Companies Law 159/1981", text: { en: "Read the last 3 years of minutes for: approved related-party transactions, dividend decisions, guarantees given, and any dissent or reserved matters — the minutes are where the undisclosed story usually surfaces.", ar: "قراءة محاضر آخر 3 سنوات بحثًا عن: معاملات الأطراف ذات العلاقة المعتمدة وقرارات التوزيعات والضمانات الممنوحة وأي اعتراضات أو أمور محجوزة — فالمحاضر هي حيث تطفو القصة غير المفصح عنها عادة." } },
      { id: "cs-6", ref: "FRA rules", text: { en: "For FRA-listed targets, confirm free-float, disclosure filings, and major-shareholder notifications are current — gaps expose the buyer to succession liability with the regulator.", ar: "للأهداف المقيدة في الهيئة العامة للرقابة المالية، التأكد من نسبة التداول الحر والإفصاحات المقدمة وإخطارات المساهمين الرئيسيين — فأي قصور يعرّض المشتري لمسؤولية تبعية أمام الجهة الرقابية." } },
      { id: "cs-7", ref: "Civil Code 131/1948", text: { en: "Verify each subsidiary in the deal perimeter separately — same file as the parent: standing, cap table, liens — and reconcile the group chart against the audited consolidation to catch stealth exclusions.", ar: "التحقق من كل شركة تابعة داخل محيط الصفقة على حدة — بالملف نفسه الخاص بالأم: القيام وسجل الملكية والرهون — ومطابقة مخطط المجموعة بالقوائم المدونة لاكتشاف الاستبعادات الخفية." } },
      { id: "cs-8", ref: "DD practice", text: { en: "Confirm authority chains: who can sign the SPA, the deed, and the banking mandates; obtain the actual resolutions and verify against the articles' quorum and majority rules.", ar: "التأكد من سلاسل الصلاحيات: من يوقع اتفاق البيع والعقد والتفويضات البنكية؛ والحصول على القرارات الفعلية ومطابقتها بقواعد النصاب والأغلبية في النظام الأساسي." } },
      { id: "cs-9", ref: "DD practice", text: { en: "Check for corporate-record red flags in the register itself: frequent manager changes, re-registration of capital, address changes, or conversion of legal form within the last 24 months — each is a story to ask about.", ar: "فحص السجل نفسه بحثًا عن مؤشرات خطر: تغييرات متكررة للمديرين أو إعادة قيد رأس المال أو تغيير المقر أو تحول الشكل القانوني خلال آخر 24 شهرًا — كل واحدة قصة تستحق السؤال." } },
      { id: "cs-10", ref: "IFRS 3 / IAS 27", text: { en: "Hand every structure finding to the financial workstream: step acquisitions, control vs. joint-arrangement classification, and unpaid capital all land in purchase-price allocation and the opening balance sheet.", ar: "تمرير كل ملاحظة هيكلية إلى فريق العناية المالية: عمليات الاستحواذ المرحلة وتصنيف السيطرة مقابل الترتيبات المشتركة ورأس المال غير المسدد — كلها تنعكس في توزيع ثمن الشراء وفي الميزانية الافتتاحية." } },
    ],
    redFlags: [
      { text: { en: "The seller cannot produce registered title to the shares being sold — the deal cannot close as structured.", ar: "البائع لا يملك ملكية مقيدة للأسهم المعروضة للبيع — لا يمكن إتمام الصفقة بهيكلها الحالي." }, critical: true },
      { text: { en: "Share registers missing, back-dated, or inconsistent with GAFI/commercial-register filings.", ar: "سجلات المساهمين مفقودة أو مؤرخة بأثر رجعي أو غير متسقة مع قيود هيئة الاستثمار أو السجل التجاري." } },
      { text: { en: "Undisclosed pledge or court freeze over the shares discovered late.", ar: "اكتشاف رهن أو حجز قضائي غير مفصح عنه على الأسهم في وقت متأخر." } },
      { text: { en: "A subsidiary quietly moved out of the group before signing (perimeter leakage).", ar: "انتقال إحدى الشركات التابعة بهدوء خارج المجموعة قبل التوقيع (تسرب من محيط الصفقة)." } },
    ],
  },

  {
    id: "contracts",
    code: "L-02",
    scope: "legal",
    group: null,
    icon: "file-text",
    title: { en: "Material Contracts", ar: "العقود الجوهرية" },
    scopeNote: {
      en: "The contracts the business actually runs on — customers, suppliers, distributors, leases, loans — hunting the clauses that survive a change of control and can reprice or kill the deal.",
      ar: "العقود التي يقوم عليها النشاط فعلًا — العملاء والموردون والموزعون والإيجارات والقروض — بحثًا عن البنود التي تبقى سارية بعد تغير السيطرة والتي يمكن أن تعيد تسعير الصفقة أو تقتلها.",
    },
    why: [
      { en: "Identify change-of-control and anti-assignment clauses: contracts that terminate or require consent the moment the buyer steps in.", ar: "تحديد بنود تغير السيطرة وحظر التنازل: العقود التي تنفسخ أو تتطلب موافقة لحظة دخول المشتري." },
      { en: "Separate real contracted revenue from relationships — the buyer pays for the contract, not the friendship.", ar: "الفصل بين الإيرادات التعاقدية الحقيقية والعلاقات الشخصية — فالمشتري يدفع مقابل العقد لا مقابل الصداقة." },
      { en: "Surface guarantees, exclusivity, price locks, and penalties that bind the target for years after closing.", ar: "إبراز الضمانات والاستئثار وتثبيت الأسعار والجزاءات التي تقيد الهدف سنوات بعد الإغلاق." },
      { en: "Confirm no contract was amended, extended, or re-priced shortly before signing (the anesthetic deal).", ar: "التأكد من عدم تعديل أي عقد أو تمديده أو إعادة تسعيره قبيل التوقيع مباشرة (الصفقة التجميلية)." },
    ],
    documents: [
      { en: "Top-20 customer and top-20 supplier contracts by annual value", ar: "أكبر 20 عقد عملاء و20 عقد موردين بالقيمة السنوية" },
      { en: "All distribution, agency, franchise and licensing agreements", ar: "كل اتفاقيات التوزيع والوكالة والامتياز والترخيص" },
      { en: "Property leases and usufruct agreements for every location", ar: "عقود إيجار العقارات وحقوق الانتفاع لكل موقع" },
      { en: "Loan agreements, facilities, and intercompany financing contracts", ar: "اتفاقيات القروض والتسهيلات وعقود التمويل بين الشركات" },
      { en: "Guarantees, letters of comfort, and performance bonds given or received", ar: "الضمانات وخطابات الطمأنة وكفالات حسن التنفيذ الممنوحة أو المقبوضة" },
      { en: "Contracts amended, renewed, or newly signed within 90 days of the deal", ar: "العقود المعدلة أو المجددة أو الموقعة حديثًا خلال 90 يومًا من الصفقة" },
    ],
    procedures: [
      { id: "ct-1", ref: "DD practice", text: { en: "Build the materiality net first: contracts above the threshold (e.g. >1% of revenue or a fixed EGP floor) plus any contract regardless of size containing exclusivity, guarantee, or term > 3 years.", ar: "تحديد شبكة الأهمية أولًا: العقود التي تتجاوز الحد (مثلًا >1% من الإيرادات أو حد مطلق بالجنيه) إضافة إلى أي عقد أيًا كان حجمه يتضمن استئثارًا أو ضمانًا أو مدة تتجاوز 3 سنوات." } },
      { id: "ct-2", ref: "Civil Code 131/1948", text: { en: "Read every material contract for change-of-control, assignment, and termination-for-convenience clauses — and quantify each one: which contract, what annual value, what notice period.", ar: "قراءة كل عقد جوهري بحثًا عن بنود تغير السيطرة والتنازل والفسخ المريح — وتقدير أثر كل بند: أي عقد وأي قيمة سنوية وأي مدة إخطار." } },
      { id: "ct-3", ref: "DD practice", text: { en: "Verify the counterparty chain: is the contracting party the target, a subsidiary, or the founder personally? Founder-held contracts must be assigned in — or the revenue walks out with him.", ar: "التحقق من طرف العقد: هل المتعاقد هو الهدف أم شركة تابعة أم المؤسس شخصيًا؟ العقود باسم المؤسس يجب نقلها إلى الكيان وإلا خرجت الإيرادات معه." } },
      { id: "ct-4", ref: "DD practice", text: { en: "Test for the anesthetic deal: compare pricing, volume, and terms of contracts signed or amended within 90 days of signing against their history — sweetened contracts unwind after closing.", ar: "اختبار الصفقة التجميلية: مقارنة الأسعار والأحجام وشروط العقود الموقعة أو المعدلة خلال 90 يومًا من التوقيع بتاريخها — فالعقود المحسّنة تصطدم بالواقع بعد الإغلاق." } },
      { id: "ct-5", ref: "IFRS 15", text: { en: "Cross-read revenue contracts with the financial workstream: multiple-element bundles, rebates, volume discounts, and minimum-purchase commitments all shift reported revenue quality.", ar: "قراءة عقود الإيراد مع فريق العناية المالية: الحزم متعددة العناصر والخصومات ومكافآت الحجم والتزامات الشراء الدنيا — كلها تحرك جودة الإيراد المعلن." } },
      { id: "ct-6", ref: "IAS 37", text: { en: "Extract every onerous clause: unconditional purchase commitments, take-or-pay, liquidated damages, and penalty schedules — these are the liabilities that become debt-like items in the price.", ar: "استخراج كل بند مُرهق: التزامات شراء غير مشروطة وبنود خذ-أو-ادفع وشرط جزائي المقادير وجداول الغرامات — هذه هي الالتزامات التي تتحول إلى بنود شبيهة بالدين في السعر." } },
      { id: "ct-7", ref: "DD practice", text: { en: "Confirm contracts are in force: renewal dates, cure periods already triggered, notice windows missed — a contract in technical breach is not an asset.", ar: "التأكد من سريان العقود: تواريخ التجديد ومهل الإصلاح المستهدفة بالفعل ومواعيد الإخطار الفائتة — فالعقد في إخلال فني ليس أصلًا." } },
      { id: "ct-8", ref: "FRA rules", text: { en: "For listed or regulated targets, check the related-party contracts especially: terms at arm's length, board approval, and disclosure — the regulator inherits these with you.", ar: "للأهداف المقيدة أو الخاضعة للرقابة، فحص عقود الأطراف ذات العلاقة خصوصًا: الشروط بمعاملة مطلقة واعتماد مجلس الإدارة والإفصاح — فالجهة الرقابية ترثها معك." } },
      { id: "ct-9", ref: "DD practice", text: { en: "Obtain a bring-down: management's written list of material contracts, certified complete — then reconcile it against the data room index and the revenue ledger; gaps are findings.", ar: "الحصول على إقرار استكمال: قائمة الإدارة المكتوبة بالعقود الجوهرية معتمدةً كاملة — ثم مطابقتها بفهرس غرفة البيانات ودفتر الإيرادات؛ فالفجوات ملاحظات." } },
      { id: "ct-10", ref: "DD practice", text: { en: "Flag every contract requiring third-party consent to survive closing, and start the consent solicitations before signing — consent is a closing condition, not a post-closing chore.", ar: "وسم كل عقد يتطلب موافقة طرف ثالث ليبقى بعد الإغلاق، وبدء طلب الموافقات قبل التوقيع — فالموافقة شرط إغلاق لا عملٌ مؤجل بعده." } },
    ],
    redFlags: [
      { text: { en: "A top-5 customer contract terminates automatically on change of control — no consent mechanism at all.", ar: "عقد من أكبر 5 عملاء ينفسخ تلقائيًا عند تغير السيطرة — دون أي آلية موافقة." }, critical: true },
      { text: { en: "Contracts personally held by the founder with no assignment pathway into the target.", ar: "عقود مسجلة باسم المؤسس شخصيًا دون مسار لنقلها إلى الهدف." } },
      { text: { en: "Sudden price increases or term extensions granted to customers within 90 days of signing.", ar: "زيادات مفاجئة في الأسعار أو تمديدات لمدد العقود لصالح العملاء خلال 90 يومًا من التوقيع." } },
      { text: { en: "Data-room contract copies that differ from the executed versions in the target's own files.", ar: "نسخ العقود في غرفة البيانات تختلف عن النسخ المنفذة في ملفات الهدف نفسه." } },
    ],
  },

  {
    id: "litigation",
    code: "L-03",
    scope: "legal",
    group: null,
    icon: "gavel",
    title: { en: "Litigation, Claims & Contingencies", ar: "التقاضي والمطالبات والالتزامات المحتملة" },
    scopeNote: {
      en: "Every dispute the target is party to — in court, in arbitration, with the tax authority or a regulator — and the unrecorded liabilities hiding inside them.",
      ar: "كل نزاع يكون الهدف طرفًا فيه — أمام القضاء أو التحكيم أو مصلحة الضرائب أو جهة رقابية — والالتزامات غير المسجلة الكامنة فيها.",
    },
    why: [
      { en: "Quantify the maximum realistic exposure of each case and decide who bears it — price reduction, escrow, or specific indemnity.", ar: "تقدير أقصى تعرض واقعي لكل قضية وتقرير من يتحمله — تخفيض سعر أو حساب ضمان أو تعويض خاص." },
      { en: "Catch the cases management did not list: searches, minutes, legal-expense analysis, and the auditors' contingency workpapers.", ar: "اكتشاف القضايا التي لم تدرجها الإدارة: بالاستعلامات والمحاضر وتحليل المصروفات القانونية وأوراق عمل مخصصات المراجع." },
      { en: "Identify enforcement risk on judgments the target won — a paper win with no assets to execute against is worth nothing.", ar: "تحديد مخاطر التنفيذ على الأحكام التي كسبها الهدف — فالفوز الورقي بلا أصول تنفذ عليها لا يساوي شيئًا." },
    ],
    documents: [
      { en: "Litigation schedule from management: case, court, stage, counsel's view, amount", ar: "جدول التقاضي من الإدارة: القضية والمحكمة والمرحلة ورأي المحامي والمبلغ" },
      { en: "Counsel's written assessment per material case (pleadings + strategy)", ar: "تقييم كتابي من المحامي لكل قضية جوهرية (المذكرات والاستراتيجية)" },
      { en: "Powers of attorney to external lawyers — scope reveals the real dispute map", ar: "التوكيلات للمحامين الخارجيين — نطاقها يكشف خريطة النزاعات الحقيقية" },
      { en: "Legal expense ledger for 3 years (catches the cases nobody listed)", ar: "دفتر المصروفات القانونية لثلاث سنوات (يكشف القضايا غير المدرجة)" },
      { en: "Tax authority assessments, objections, and appeals in progress", ar: "تقييمات مصلحة الضرائب والاعتراضات والطعون الجارية" },
      { en: "Auditor's litigation-inquiry letters and management representation letters", ar: "خطابات استفسار المراجع عن التقاضي وخطابات إقرار الإدارة" },
    ],
    procedures: [
      { id: "lt-1", ref: "DD practice", text: { en: "Reconcile three independent sources for the case list: management's schedule, the legal-expense ledger, and the POAs issued — a case appearing in two of three and missing from the schedule is the finding that matters.", ar: "مطابقة ثلاثة مصادر مستقلة لقائمة القضايا: جدول الإدارة ودفتر المصروفات القانونية والتوكيلات الصادرة — فالقضية الظاهرة في مصدرين والغائبة عن الجدول هي الملاحظة الأهم." } },
      { id: "lt-2", ref: "IAS 37", text: { en: "Test provisioning: each material case classified as provision, contingent liability, or none — against IAS 37's probable-outflow threshold; the gap between counsel's view and the books is a price item.", ar: "اختبار المخصصات: تصنيف كل قضية جوهرية بين مخصص والتزام محتمل أو لا شيء — وفق عتبة التدفق المحتمل في IAS 37؛ والفرق بين رأي المحامي والدفاتر بند في السعر." } },
      { id: "lt-3", ref: "DD practice", text: { en: "Obtain counsel's candid assessment per case — not the pleading posture — including realistic settlement ranges and timing; pleadings advocate, counsel advises.", ar: "الحصول على تقييم المحامي الصريح لكل قضية — لا الموقف الخصومي — بما فيه نطاقات التسوية الواقعية والتوقيت؛ فالمذكرات تجادل والمحامي ينصح." } },
      { id: "lt-4", ref: "DD practice", text: { en: "Search the court registers and official gazette for cases against the target and its managers — the search itself is evidence, keep the certificates in the file.", ar: "الاستعلام في سجلات المحاكم والجريدة الرسمية عن قضايا على الهدف ومديريه — فشهادة الاستعلام نفسها دليل تُحفظ في الملف." } },
      { id: "lt-5", ref: "IAS 37", text: { en: "Review tax disputes with the tax workstream: open assessments, penalty exposure, statute-of-limitation windows — tax cases follow their own procedural clock.", ar: "مراجعة منازعات الضرائب مع فريق الضرائب: التقييمات المفتوحة والتعرض للغرامات وموانع التقادم — فقضايا الضرائب تسير بساعة إجرائية خاصة." } },
      { id: "lt-6", ref: "DD practice", text: { en: "Check the enforcement side: judgments won by the target — their age, debtor solvency, and any attached assets; wins past limitation or against insolvent debtors are written down to zero.", ar: "فحص جانب التنفيذ: الأحكام التي كسبها الهدف — عمرها وملاءة المحكوم عليه وأي أصول محجوزة؛ فالأحكام البالغة التقادم أو الصادرة على مدين معسر تُخفض إلى الصفر." } },
      { id: "lt-7", ref: "DD practice", text: { en: "Interview the general counsel or outside counsel on unfiled threats: demand letters, pre-litigation negotiations, and employment disputes brewing — the next case file is usually already open.", ar: "مقابلة المستشار القانوني أو المحامي الخارجي بشأن التهديدات غير المقاضاة: خطابات المطالبة والتفاوضات القضائية الوليدة ونزاعات العمالة المحتدمة — فملف القضية القادمة يكون عادة مفتوحًا بالفعل." } },
      { id: "lt-8", ref: "IAS 10", text: { en: "Cut off at the balance-sheet date and again at signing: post-date events (a lost case, a new filing) adjust price or shift to indemnities under the SPA's update mechanism.", ar: "ضبط الاستقطاع عند تاريخ الميزانية ثم عند التوقيع: الأحداث اللاحقة (خسارة قضية أو دعوى جديدة) تعدل السعر أو تتحول إلى تعويضات ضمن آلية التحديث في اتفاق البيع." } },
      { id: "lt-9", ref: "DD practice", text: { en: "Quantify every exposure twice — best case and counsel's worst case — and hand both to the deal model; a litigation schedule without a worst-case column is a summary, not diligence.", ar: "تقدير كل تعرض مرتين — أفضل الحالات وأسوأ تقدير للمحامي — وتسليمهما لنموذج الصفقة؛ فجدول تقاضٍ بلا عمود أسوأ الحالات ملخصٌ لا عناية." } },
    ],
    redFlags: [
      { text: { en: "Management's case list is materially shorter than the POA and legal-expense evidence shows.", ar: "قائمة قضايا الإدارة أقصر بكثير مما تظهره أدلة التوكيلات والمصروفات القانونية." }, critical: true },
      { text: { en: "A judgment against the target in enforcement with assets already attached.", ar: "حكم نهائي على الهدف قيد التنفيذ مع حجز أصول بالفعل." } },
      { text: { en: "Tax assessments covering open years that exceed the deal's contingency buffer.", ar: "تقييمات ضريبية تغطي سنواتًا مفتوحة تتجاوز هامش الطوارئ في الصفقة." } },
      { text: { en: "Same counterparty appearing in litigation, customer, and supplier lists — a related-party dispute wearing three hats.", ar: "الطرف نفسه يظهر في قوائم التقاضي والعملاء والموردين — نزاع أطراف ذات علاقة يلبس ثلاث قبعات." } },
    ],
  },

  {
    id: "ip",
    code: "L-04",
    scope: "legal",
    group: null,
    icon: "lightbulb",
    title: { en: "Intellectual Property", ar: "الملكية الفكرية" },
    scopeNote: {
      en: "The registered and unregistered IP the business depends on — trademarks, patents, software, content, domain names — and whether the target actually owns it, or merely borrows it from the founder, an ex-employee, or a licensing house.",
      ar: "الملكية الفكرية المسجلة وغير المسجلة التي يعتمد عليها النشاط — العلامات والبراءات والبرمجيات والمحتوى وأسماء النطاقات — وهل يملكها الهدف فعلًا أم يستعيرها من المؤسس أو موظف سابق أو بيت ترخيص.",
    },
    why: [
      { en: "Confirm title: the IP is registered in the target's name (not the founder's, not a sister company) with renewals current.", ar: "تأكيد الملكية: أن الملكية الفكرية مسجلة باسم الهدف (لا باسم المؤسس ولا شركة شقيقة) وبسداد رسوم التجديد." },
      { en: "Map third-party IP the business uses: in-licenses (scope, exclusivity, term) and out-licenses (royalties, encumbrances).", ar: "رسم خريطة الملكية المرخصة للطرف الثالث: التراخيص الواردة (النطاق والاستئثار والمدة) والصادرة (العوائدات والقيود)." },
      { en: "Check the chain from creator to company: employee/inventor assignments actually signed — unassigned developer rights are a hole in the moat.", ar: "فحص السلسلة من المبدع إلى الشركة: تنازلات الموظفين والمخترعين الموقعة فعلًا — فحقوق المطور غير المتنازل عنها ثغرة في الخندق." },
      { en: "Assess infringement exposure both ways: is the target free to operate, and is anyone free-riding on its IP?", ar: "تقييم تعرض التعدي في الاتجاهين: هل الهدف حر في التشغيل؟ وهل يعتدي أحد على ملكيته؟" },
    ],
    documents: [
      { en: "Trademark, patent, and industrial-design registers held in the target's name (with renewal receipts)", ar: "سجلات العلامات والبراءات والنماذج الصناعية المسجلة باسم الهدف (مع إيصالات التجديد)" },
      { en: "Software, content, and database inventory: what exists, who built it, under what contract", ar: "جرد البرمجيات والمحتوى وقواعد البيانات: ما الموجود ومن بناه وبأي عقد" },
      { en: "Employee IP-assignment clauses and contractor development agreements", ar: "بنود تنازل الموظفين عن الملكية الفكرية وعقود المطورين المستقلين" },
      { en: "In-bound and out-bound license agreements with royalty schedules", ar: "اتفاقيات الترخيص الواردة والصادرة مع جداول العوائد" },
      { en: "Domain names, social-media handles, and mobile-app store accounts (with control credentials)", ar: "أسماء النطاقات وحسابات التواصل الاجتماعي وحسابات متاجر التطبيقات (مع بيانات التحكم)" },
      { en: "Any cease-and-desist letters sent or received in the last 3 years", ar: "أي خطابات إنذار ووقف مرسلة أو مستلمة خلال آخر 3 سنوات" },
    ],
    procedures: [
      { id: "ip-1", ref: "IP Law 82/2002", text: { en: "Search the trademark and patent registers for the target's marks and inventions — certificate of each registration in the target's own name, classes covering its actual goods/services, renewals paid.", ar: "الاستعلام في سجلات العلامات والبراءات عن علامات الهدف واختراعاته — شهادة كل تسجيل باسم الهدف نفسه وبالفئات التي تغطي منتجاته وخدماته الفعلية مع سداد التجديد." } },
      { id: "ip-2", ref: "IP Law 82/2002", text: { en: "Verify assignments: for every acquired or employee-created asset, the signed deed transferring rights to the target — an invention still registered to its inventor is not the company's asset.", ar: "التحقق من التنازلات: لكل أصل مشترى أو منتج بجهود الموظفين، عقد التنازل الموقع الذي ينقل الحقوق إلى الهدف — فالاختراع المسجل باسم مخترعه ليس أصلًا للشركة." } },
      { id: "ip-3", ref: "DD practice", text: { en: "Reconcile the brand the market knows with the brand the register holds: trading names, logos on invoices, domain names, and store listings — the gap between commercial identity and legal title is where buyers get hurt.", ar: "مطابقة العلامة التي يعرفها السوق بالعلامة التي يحملها السجل: الأسماء التجارية والشعارات على الفواتير وأسماء النطاقات وقوائم المتاجر — فالفجوة بين الهوية التجارية والملكية القانونية موضع أذى المشترين." } },
      { id: "ip-4", ref: "DD practice", text: { en: "For proprietary software, walk the provenance: in-house (assignment clauses), outsourced (work-for-hire with full transfer), or open-source — and scan the open-source licenses for copyleft terms that infect the core product.", ar: "للبرمجيات المملوكة، تتبع المصدر: تطوير داخلي (بنود تنازل) أم خارجي (عقد مقابل أجر بنقل كامل) أم مفتوح المصدر — مع فحص تراخيص المصدر المفتوح بحثًا عن بنود Copyleft التي تلحق بالنواة." } },
      { id: "ip-5", ref: "DD practice", text: { en: "Read in-licenses for change-of-control traps — agency, franchise, and technology agreements frequently reprice or lapse when ownership flips.", ar: "قراءة التراخيص الواردة بحثًا عن فخاخ تغير السيطرة — فاتفاقيات الوكالة والامتياز والتقنية كثيرًا ما تُعاد تسعيرها أو تنقضي عند انتقال الملكية." } },
      { id: "ip-6", ref: "IAS 38", text: { en: "Hand the IP inventory to the financial workstream: capitalization, amortization lives, and impairment indicators — and to the valuation model as the intangible-asset identification list (IFRS 3 requires it).", ar: "تمرير جرد الملكية الفكرية إلى فريق العناية المالية: الرسملة وأعمار الإهلاك ومؤشرات الانخفاض — وإلى نموذج التقييم كقائمة تحديد الأصول غير الملموسة (يتطلبها IFRS 3)." } },
      { id: "ip-7", ref: "DD practice", text: { en: "Test freedom to operate: search for conflicting registrations and prior uses in the target's key classes and markets — a senior conflicting mark is a litigation schedule item with a price tag.", ar: "اختبار حرية التشغيل: البحث عن تسجيلات متعارضة واستخدامات سابقة في فئات الهدف وأسواقه الرئيسية — فالعلامة الأقدم المتعارضة بند في جدول التقاضي وله ثمن." } },
      { id: "ip-8", ref: "DD practice", text: { en: "Confirm control of the digital estate: domain registrant records, app-store and ad-network accounts, and social handles — all held in the company's name with credentials the company (not an agency or ex-employee) controls.", ar: "التأكد من السيطرة على الأصول الرقمية: بيانات مسجلي النطاقات وحسابات المتاجر وشبكات الإعلان وحسابات التواصل — كلها باسم الشركة وببياتن تحكم تملكها الشركة (لا وكالة ولا موظف سابق)." } },
      { id: "ip-9", ref: "Data Protection Law 151/2020", text: { en: "Where the business monetizes data, confirm the lawful basis: consent records, processing notices, and cross-border transfer mechanisms — data the company does not lawfully hold is not an asset at all.", ar: "حيث يُتاجر النشاط بالبيانات، التأكد من السند القانوني: سجلات الموافقة وإشعارات المعالجة وآليات النقل عبر الحدود — فالبيانات التي لا تحوزها الشركة بمشروعية ليست أصلًا أصلًا." } },
    ],
    redFlags: [
      { text: { en: "The core trademark or platform is registered to the founder personally and no assignment deed exists.", ar: "العلامة الأساسية أو المنصة مسجلة باسم المؤسس شخصيًا ولا يوجد عقد تنازل." }, critical: true },
      { text: { en: "Key software built by contractors under agreements with no clear IP transfer clause.", ar: "برمجيات جوهرية بناها مقاولون بعقود بلا بند صريح لنقل الملكية الفكرية." } },
      { text: { en: "Open-source copyleft components embedded in the flagship product.", ar: "مكونات مفتوحة المصدر بتراخيص Copyleft داخل المنتج الرئيسي." } },
      { text: { en: "Domain, app-store, or ad accounts controlled by an outside agency's credentials.", ar: "النطاقات أو حسابات المتاجر أو الإعلانات محكومة ببيانات دخول وكالة خارجية." } },
    ],
  },

  {
    id: "regulatory",
    code: "L-05",
    scope: "legal",
    group: null,
    icon: "badge-check",
    title: { en: "Regulatory & Licenses", ar: "التراخيص والالتزام التنظيمية" },
    scopeNote: {
      en: "Every license, permit, and registration the business needs to operate lawfully — and the compliance posture with each regulator that issues them.",
      ar: "كل ترخيص وموافقة وقيد يحتاجه النشاط ليعمل بشرعية — وموقف الالتزام أمام كل جهة رقابية تمنحها.",
    },
    why: [
      { en: "Confirm the license inventory is complete and current — operating without a required license can suspend the revenue the price is built on.", ar: "التأكد من أن جرد التراخيص كامل وسارٍ — فالعمل بلا ترخيص واجب قد يوقف الإيرادات التي بُني عليها السعر." },
      { en: "Identify licenses that are personal to the founder or expire on change of control — the regulator's consent becomes a closing condition.", ar: "تحديد التراخيص الشخصية للمؤسس أو المنتهية عند تغير السيطرة — فموافقة الجهة الرقابية تصبح شرطًا للإغلاق." },
      { en: "Assess the penalty history and open inspections: fines, warnings, and corrective orders are both a liability and a map of where operations hurt.", ar: "تقييم تاريخ الجزاءات والتفتيش المفتوح: الغرامات والإنذارات وأوامر التصحيح التزامٌ وخريطة لمواضع الخلل التشغيلي معًا." },
    ],
    documents: [
      { en: "Complete license & permit inventory with issuing authority, number, issue/expiry dates", ar: "جرد كامل للتراخيص والموافقات: الجهة المانحة والرقم وتاريخا الإصدار والانتهاء" },
      { en: "Sector-specific approvals (import cards, industrial registry, FDA/pharma, CBE/insurance/FRA registrations as applicable)", ar: "الموافقات القطاعية (بطاقات الاستيراد والسجل الصناعي وتراخيص الدواء وقيود البنك المركزي والهيئات حسب النشاط)" },
      { en: "Inspection reports and regulator correspondence for the last 3 years", ar: "تقارير التفتيش ومراسلات الجهات الرقابية لآخر 3 سنوات" },
      { en: "Fines and penalties paid or appealed, with receipts and case status", ar: "الغرامات والجزاءات المسددة أو المستأنفة مع الإيصالات وحالة كل قضية" },
      { en: "Environmental permits and emission/effluent clearances where the sector requires them", ar: "التراخيص البيئية وموافقات الانبعاثات والصرف حيث يتطلبها القطاع" },
      { en: "Customs registrations, AEO status, and trade-compliance programs", ar: "قيد الجمارك وصفة المشغل الاقتصادي المعتمد وبرامج الامتثال التجاري" },
    ],
    procedures: [
      { id: "rg-1", ref: "DD practice", text: { en: "Build the license inventory from scratch — do not accept management's list: walk the business process end-to-end and list every permit each activity legally requires, then reconcile against what exists.", ar: "بناء جرد التراخيص من الصفر — لا يُقبل جدول الإدارة: تتبع العملية التشغيلية من أولها لآخرها وحصر كل تصريح يتطلبه النشاط قانونيًا ثم مطابقته بالموجود." } },
      { id: "rg-2", ref: "DD practice", text: { en: "For each license: verify validity (not just existence), renewal lead-times, fees current, and any conditions attached — a license with an unmet condition is a suspended license waiting for its inspection.", ar: "لكل ترخيص: التحقق من السريان (لا مجرد الوجود) ومواعيد التجديد المطلوبة وسداد الرسوم وأي شروط مرفقة — فالترخيص المشروط بشرط غير مُنفذ ترخيص معلق ينتظر تفتيشه." } },
      { id: "rg-3", ref: "DD practice", text: { en: "Flag every license that is personal (held by the founder or a named manager) or that requires regulator consent on transfer — these move to the closing-conditions list with realistic timelines.", ar: "وسم كل ترخيص شخصي (باسم المؤسس أو مدير بعينه) أو يتطلب موافقة الجهة عند الانتقال — تنتقل هذه إلى قائمة شروط الإغلاق بجداول زمنية واقعية." } },
      { id: "rg-4", ref: "DD practice", text: { en: "Read 3 years of regulator correspondence chronologically — the pattern (escalating warnings, repeat findings) matters more than any single letter.", ar: "قراءة مراسلات الجهات الرقابية لثلاث سنوات زمنيًا — فالنمط (إنذارات متصاعدة وملاحظات متكررة) أهم من أي خطاب منفرد." } },
      { id: "rg-5", ref: "IAS 37", text: { en: "Quantify penalty exposure: accrued fines, appeal prospects, and the tail of inspections still open at signing — and hand the number to the price mechanism.", ar: "تقدير التعرض للجزاءات: الغرامات المستحقة وفرص الاستئناف وذيل التفتيشات المفتوحة حتى التوقيع — وتسليم الرقم لآلية السعر." } },
      { id: "rg-6", ref: "DD practice", text: { en: "Where the sector is licensed (banking, insurance, pharma, food), book a courtesy meeting with the regulator through counsel if possible — the regulator's view of the change of control is diligence gold.", ar: "حيث يكون القطاع مرخصًا (بنوك، تأمين، أدوية، أغذية)، ترتيب اجتماع ودّي مع الجهة الرقابية عبر المحامي إن أمكن — فوجهة نظر الجهة في تغير السيطرة معلومة ثمينة للعناية." } },
      { id: "rg-7", ref: "DD practice", text: { en: "Test trade compliance for importers/exporters: customs classifications used, duty reliefs claimed (temporary admission, drawback), and exposure if a classification is challenged retroactively.", ar: "اختبار الامتثال التجاري للمستوردين والمصدرين: بنود التعرفة المستخدمة والإعفاءات المطلوبة (إدخال مؤقت، استرداد) والتعرض عند الطعن في التصنيف بأثر رجعي." } },
      { id: "rg-8", ref: "DD practice", text: { en: "Check the anti-corruption posture: gifts policy, government-intermediary arrangements, and any prior investigations — successor liability for past practices is a buyer's problem in most regimes.", ar: "فحص موقف مكافحة الفساد: سياسة الهدايا وترتيبات الوسطاء مع الجهات العامة وأي تحقيقات سابقة — فالمسؤولية التبعية عن الممارسات السابقة مشكلة المشتري في معظم الأنظمة." } },
      { id: "rg-9", ref: "IFRS practice", text: { en: "Reconcile the license inventory to the balance sheet: capitalized licenses, renewal liabilities, and any regulatory capital requirement that constrains post-closing dividends.", ar: "مطابقة جرد التراخيص بالميزانية: التراخيص المرسملة والتزامات التجديد وأي متطلب رأسمال تنظيمي يقيد التوزيعات بعد الإغلاق." } },
    ],
    redFlags: [
      { text: { en: "A license essential to core revenue is expired or held personally by the founder.", ar: "ترخيص جوهري للإيرادات الأساسية منتهٍ أو مسجل باسم المؤسس شخصيًا." }, critical: true },
      { text: { en: "Open regulatory enforcement with suspension powers over a main business line.", ar: "إجراء تنفيذي رقابي مفتوح بسلطة إيقاف خط نشاط رئيسي." } },
      { text: { en: "Licenses renewed routinely late with fines normalized in the P&L.", ar: "تجديدات تراخيص متأخرة دوما مع اعتياد غراماتها في الأرباح والخسائر." } },
      { text: { en: "Government business won through intermediaries with opaque arrangements.", ar: "أعمال حكومية مكتسبة عبر وسطاء بترتيبات غير واضحة." } },
    ],
  },

  {
    id: "employment",
    code: "L-06",
    scope: "legal",
    group: null,
    icon: "users",
    title: { en: "Employment & Labor", ar: "العمالة وعلاقات العمل" },
    scopeNote: {
      en: "The workforce as a legal exposure: contracts, social insurance, end-of-service accruals, key-person retention, and the labor claims that transfer with the business.",
      ar: "قوة العمل كتعرض قانوني: العقود والتأمينات الاجتماعية ومخصصات نهاية الخدمة والاحتفاظ بالكوادر الجوهرية ودعاوى العمال التي تنتقل مع النشاط.",
    },
    why: [
      { en: "Verify every employee is properly contracted, insured, and paid through the bank — undeclared labor is inherited liability with penalties.", ar: "التحقق من أن كل موظف موظف بعقد ومؤمَّن عليه ويتقاضى عبر البنك — فالعمالة غير المعلنة التزام موروث بجزاءاته." },
      { en: "Quantify end-of-service and leave accruals — the gap between the books and the legal entitlement is an immediate price adjustment.", ar: "تقدير مخصصات نهاية الخدمة والأجازات — فالفرق بين الدفاتر والاستحقاق القانوني تعديل فوري في السعر." },
      { en: "Identify key people and secure them: retention agreements before signing, or the asset walks out at closing.", ar: "تحديد الكوادر الجوهرية وتأمينها: اتفاقيات احتفاظ قبل التوقيع وإلا خرج الأصل عند الإغلاق." },
    ],
    documents: [
      { en: "Employee roster: name, role, hire date, salary, contract type, nationality", ar: "كشف العاملين: الاسم والوظيفة وتاريخ التعيين والأجر ونوع العقد والجنسية" },
      { en: "Employment contracts (or the standard form + deviations list)", ar: "عقود العمل (أو النموذج المعتمد وقائمة الاستثناءات)" },
      { en: "Social insurance (form 1/6) and subscriptions registers, with reconciliation to the payroll", ar: "سجلات التأمينات الاجتماعية (نموذج 1/6) والاشتراكات ومطابقتها بالأجور" },
      { en: "Payroll bank-transfer evidence and payroll tax (Form 4) filings", ar: "مستندات تحويل الأجور بنكيًا وإقرارات ضريبة كسب العمل (نموذج 4)" },
      { en: "End-of-service, leave balance, and bonus accrual calculations", ar: "حسابات مخصصات نهاية الخدمة وأرصدة الأجازات والحوافز" },
      { en: "Org chart with key-person flags and any retention/equity promises made", ar: "الهيكل التنظيمي بوسم الكوادر الجوهرية وأي وعود احتفاظ أو حوافز أسهم" },
      { en: "Labor-office inspections, complaints, and pending cases", ar: "تفتيش مكاتب العمل والشكاوى والقضايا الجارية" },
    ],
    procedures: [
      { id: "em-1", ref: "Labor Law 14/2025", text: { en: "Reconcile the roster to three sources: payroll register, social-insurance forms, and payroll-tax filings — headcount that appears in one and not the others is undeclared labor with a penalty tail.", ar: "مطابقة كشف العاملين بثلاثة مصادر: سجل الأجور ونماذج التأمينات وإقرارات ضريبة المرتبات — فالعامل الظاهر في مصدر دون غيره عمالة غير معلنة بذيل جزاءات." } },
      { id: "em-2", ref: "Labor Law 14/2025", text: { en: "Test contracts against the law's mandatory terms: wage components, probation, notice, leave — unlawful terms are unenforceable in the employee's disfavor and carry exposure on the collective scale.", ar: "اختبار العقود مقابل البنود الآمرة في القانون: مكونات الأجر والاختبار والإخطار والأجازات — فالشروط المخالفة لا تُنفذ ضد العامل وتحمل تعرضًا على المستوى الجماعي." } },
      { id: "em-3", ref: "Social insurance law", text: { en: "Verify insurance wages match actual wages (the classic gap: insured at minimum wage, paid at market) — the arrears, interest, and penalties transfer with the entity.", ar: "التحقق من أن أجر التأمين يطابق الأجر الفعلي (الفجوة الكلاسيكية: تأمين بالحد الأدنى ودفع بالسوق) — فالفروق والفوائد والغرامات تنتقل مع الكيان." } },
      { id: "em-4", ref: "IAS 19", text: { en: "Recompute end-of-service and leave accruals independently from the roster and compare to the books — the shortfall is a debt-like item in the funds-flow statement.", ar: "إعادة احتساب مخصصات نهاية الخدمة والأجازات بشكل مستقل من كشف العاملين ومقارنتها بالدفاتر — فالعجز بند شبيه بالدين في قائمة التدفقات." } },
      { id: "em-5", ref: "Labor Law 14/2025", text: { en: "Ask the labor question that transfers: pending cases, settled cases with res judicata risk, and the labor office's inspection history — labor claims follow the undertaking, not the seller.", ar: "طرح سؤال العمالة الذي ينتقل: القضايا الجارية والمحسومة القابلة للنقض وتاريخ تفتيش مكتب العمل — فدعاوى العمل تلحق بالمنشأة لا بالبائع." } },
      { id: "em-6", ref: "DD practice", text: { en: "Map key people before signing: who runs revenue, systems, and licenses personally — and paper their retention (bonus, notice periods, non-competes where enforceable) as a closing condition.", ar: "رسم خريطة الكوادر الجوهرية قبل التوقيع: من يدير الإيرادات والأنظمة والتراخيص بشخصه — وتوثيق احتفاظهم (مكافأة، مهل إخطار، عدم منافسة حيث تنفذ) كشرط إغلاق." } },
      { id: "em-7", ref: "DD practice", text: { en: "Check the change-of-control mechanics for staff: who must be consulted (unions, committees), what severance is triggered, and the cost of the social plan the buyer inherits.", ar: "فحص آثار تغير السيطرة على العاملين: من يجب استشارته (نقابات ولجان) وأي تعويض فصل يُستحق وكلفة الخطة الاجتماعية التي يرثها المشتري." } },
      { id: "em-8", ref: "DD practice", text: { en: "For foreign staff: work permits, quota compliance, and visa validity — an undocumented expatriate workforce is a regulatory and continuity exposure at once.", ar: "للعاملين الأجانب: تصاريح العمل والالتزام بالنسب وسريان التأشيرات — فالكادر الأجنبي غير الموثق تعرض تنظيمي واستمرارية معًا." } },
      { id: "em-9", ref: "IFRS 3", text: { en: "Hand the people numbers to the deal model: severance, retention cost, and the accrual shortfall move the price; key-person risk moves the structure (earn-out, escrow).", ar: "تمرير أرقام العنصر البشري لنموذج الصفقة: تعويضات الفصل وكلفة الاحتفاظ وعجز المخصصات تحرك السعر؛ ومخاطر الكوادر تحرك الهيكل (دفعات معلقة، ضمان)." } },
    ],
    redFlags: [
      { text: { en: "A large share of the workforce insured at minimum wage while actually paid multiples higher.", ar: "شريحة كبيرة من العاملين مؤمَّن عليها بالحد الأدنى بينما تتقاضى أضعافه فعليًا." }, critical: true },
      { text: { en: "Revenue-critical systems or licenses held personally by one or two employees with no retention plan.", ar: "أنظمة أو تراخيص جوهرية للإيرادات بيد موظف أو اثنين بلا خطة احتفاظ." } },
      { text: { en: "End-of-service accruals computed on insured (minimum) wages rather than actual wages.", ar: "حساب مخصصات نهاية الخدمة على أجور التأمين (الدنيا) لا الأجور الفعلية." } },
      { text: { en: "Founders' relatives on the payroll with no operational role.", ar: "أقارب المؤسسين على كشف الأجور دون دور تشغيلي." } },
    ],
  },

  {
    id: "real-estate",
    code: "L-07",
    scope: "legal",
    group: null,
    icon: "building-2",
    title: { en: "Real Estate & Title", ar: "العقارات والملكية العقارية" },
    scopeNote: {
      en: "Every location the business occupies — owned, leased, or borrowed — and whether the company's right to occupy each one survives the deal and the next renewal.",
      ar: "كل موقع يشغله النشاط — مملوك أو مستأجر أو مستعار — وهل يبقى حق الشركة في شغله بعد الصفقة وعند التجديد التالي.",
    },
    why: [
      { en: "Confirm title or leasehold for every operating site — occupancy without documented right is a continuity risk to revenue.", ar: "تأكيد الملكية أو حق الإيجار لكل موقع تشغيلي — فالشغل بلا حق موثق خطر استمرارية على الإيرادات." },
      { en: "Read leases for change-of-control, rent escalation, and reinstatement obligations — the lease profile is a committed cost curve the buyer inherits.", ar: "قراءة العقود بحثًا عن تغير السيطرة وسلالم الإيجار والتزامات إعادة الحال — فملف الإيجار منحنى كلفة ملتزم بها يرثه المشتري." },
      { en: "Catch unregistered transfers and properties still held in a founder's name — a handshake ownership is not ownership.", ar: "اقتناص الانتقالات غير المسجلة والعقارات الباقية باسم المؤسس — فالملكية بالمصافحة ليست ملكية." },
    ],
    documents: [
      { en: "Title deeds / ownership certificates for owned property (fresh extracts)", ar: "أسن الملكية / شهادات الملكية للعقارات المملوكة (شهادات حديثة)" },
      { en: "Registered lease contracts with all amendments and renewal notices", ar: "عقود الإيجار المقيدة بكل ملحقاتها وإخطارات التجديد" },
      { en: "Site list: location, area, use, ownership basis, expiry, annual cost", ar: "قائمة المواقع: الموقع والمساحة والاستخدام وسند الشغل وتاريخ الانتهاء والكلفة السنوية" },
      { en: "Mortgages, liens, and seizures registered over the properties", ar: "الرهون والحجوز المسجلة على العقارات" },
      { en: "Utility accounts and industrial-land allocation decisions (with conditions)", ar: "حسابات المرافق وقرارات تخصيص الأراضي الصناعية (بشروطها)" },
      { en: "Construction licenses and building-status certificates", ar: "تراخيص البناء وشهادات حالة المباني" },
    ],
    procedures: [
      { id: "re-1", ref: "Real estate registration law", text: { en: "For owned property, obtain fresh ownership certificates and verify: owner of record is the target, area matches the books, and no mortgage, lien, or seizure annotation exists.", ar: "للعقارات المملوكة، الحصول على شهادات ملكية حديثة والتحقق: أن المالك المقيد هو الهدف، والمساحة تطابق الدفاتر، ولا يوجد قيد رهن أو حجز." } },
      { id: "re-2", ref: "Civil Code 131/1948", text: { en: "For leases: verify registration where required, the counterparty's ownership or agency, the escalation formula, and the notice window for renewal — a missed notice is an eviction on a timer.", ar: "للإيجارات: التحقق من القيد حيث يجب، وملكية المؤجر أو وكالته، ومعادلة الزيادة، وميعاد إخطار التجديد — فالإخطار الفائت إخلاء بعدّاد زمني." } },
      { id: "re-3", ref: "DD practice", text: { en: "Reconcile the fixed-asset register to the site list to the legal documents — three-way: every site physically occupied appears in all three, with no orphan assets or ghost sites.", ar: "مطابقة سجل الأصول الثابتة بقائمة المواقع بالمستندات القانونية — اتجاه ثلاثي: كل موقع مشغول فعليًا يظهر في الثلاثة، بلا أصول يتيمة ولا مواقع أشباح." } },
      { id: "re-4", ref: "DD practice", text: { en: "Inspect the property that anchors revenue (flagship site, plant, warehouse) physically and legally — the site where operations concentrate deserves a visit and a file of its own.", ar: "فحص العقار الذي يرتكز عليه الإيراد (الموقع الرئيسي أو المصنع أو المستودع) ماديًا وقانونيًا — فالموقع الذي تتركز فيه العمليات يستحق زيارة وملفًا خاصًا." } },
      { id: "re-5", ref: "DD practice", text: { en: "Quantify reinstatement and make-good obligations at exit — the deferred cost of handed-back premises belongs in the debt-like items schedule.", ar: "تقدير التزامات إعادة الحال عند الإخلاء — فالكلفة المؤجلة للمواقع المستردة تدرج في جدول البنود الشبيهة بالدين." } },
      { id: "re-6", ref: "DD practice", text: { en: "Check industrial land allocations: the decision's conditions (investment size, employment, timeline) still unfulfilled are obligations the buyer assumes, with clawback risk.", ar: "فحص تخصيصات الأراضي الصناعية: شروط القرار (حجم الاستثمار والتشغيل والجدول الزمني) غير المنفذة تبقى التزامات يتحملها المشتري مع خطر استرداد." } },
      { id: "re-7", ref: "IFRS 16", text: { en: "Hand the lease file to the financial workstream: every lease identified means a right-of-use asset and lease liability on the closing balance sheet — missed leases misstate net debt on day one.", ar: "تمرير ملف الإيجار لفريق العناية المالية: كل إيجار يُحدد يعني أصل حق استخدام والتزام إيجار في ميزانية الإغلاق — فالإيجارات الفائتة تُغلط صافي الدين من اليوم الأول." } },
      { id: "re-8", ref: "DD practice", text: { en: "Verify utilities and access: meters, connections, and rights of way — a plant served by a neighbor's private road needs that easement papered, not presumed.", ar: "التحقق من المرافق والوصول: العدادات والتوصيلات وحقوق المرور — فالمصنع الذي يخدمه طريق خاص لجاره يحتاج ارتفاقًا موثقًا لا مفترضًا." } },
    ],
    redFlags: [
      { text: { en: "The main operating site is owned by the founder with no lease or sale structure in place.", ar: "الموقع التشغيلي الرئيسي مملوك للمؤسس دون هيكل إيجار أو بيع معروض." }, critical: true },
      { text: { en: "Leases unregistered where registration is required for enforceability against third parties.", ar: "عقود إيجار غير مقيدة حيث يشترط القيد للنفاذ في مواجهة الغير." } },
      { text: { en: "Mortgage discovered over a property the balance sheet shows as unencumbered.", ar: "اكتشاف رهن على عقار تظهره الميزانية خاليًا من الرهون." } },
      { text: { en: "Industrial land conditions (employment or investment thresholds) unmet with clawback exposure.", ar: "شروط الأراضي الصناعية (حدود تشغيل أو استثمار) غير محققة مع خطر الاسترداد." } },
    ],
  },
]
