import type { DDSection } from "./types"

/** Operational due diligence — whether the business actually runs as a
 *  business: can it operate without its founders, at what cost quality, and
 *  with what resilience. Six workstreams, O-01 … O-06. */
export const DD_OPS: DDSection[] = [
  {
    id: "organization",
    code: "O-01",
    scope: "ops",
    group: null,
    icon: "network",
    title: { en: "Organization & Key People", ar: "التنظيم والكوادر الجوهرية" },
    scopeNote: {
      en: "How the company is actually run day to day — who decides, who knows, who sells — and how much of the business lives in the heads of one or two people.",
      ar: "كيف تُدار الشركة فعلًا يومًا بيوم — من يقرر ومن يعلم ومن يبيع — وكم من النشاط يعيش في رأس شخص أو اثنين.",
    },
    why: [
      { en: "Test founder dependency: decisions, relationships, and technical knowledge concentrated in one person is a structural discount, not a footnote.", ar: "اختبار الاعتماد على المؤسس: تركّز القرارات والعلاقات والمعرفة الفنية في شخص واحد خصمٌ هيكلي في القيمة لا مجرد ملاحظة." },
      { en: "Verify the management layer below the founders can run the business — the layer the buyer actually keeps.", ar: "التحقق من أن طبقة الإدارة دون المؤسسين قادرة على إدارة النشاط — فهي الطبقة التي يحتفظ بها المشتري فعلًا." },
      { en: "Surface the informal organization: the real reporting lines that never made the org chart.", ar: "إبراز التنظيم غير الرسمي: خطوط التبعية الحقيقية التي لم تدخل المخطط التنظيمي قط." },
    ],
    documents: [
      { en: "Current org chart (with headcount per unit) vs. 3 years ago", ar: "المخطط التنظيمي الحالي (بأعداد كل وحدة) مقارنة بقبل 3 سنوات" },
      { en: "CVs / role notes for the top-15 managers and technical leads", ar: "سير ذاتية أو بطاقات أدوار لأفضل 15 مديرًا وقائدًا فنيًا" },
      { en: "Delegation-of-authority matrix: who approves what, up to which amount", ar: "مصفوفة التفويض: من يعتمد ماذا وإلى أي حد مالي" },
      { en: "Sales team structure, territories, and individual targets vs. achievement", ar: "هيكل فريق البيع والمناطق ومستهدفات كل فرد مقارنة بالإنجاز" },
      { en: "Turnover statistics by department for 3 years (with exit reasons)", ar: "إحصاءات دوران العمالة بكل إدارة لثلاث سنوات (مع أسباب المغادرة)" },
      { en: "Minutes of the real decision bodies (even informal ones) for the last year", ar: "محاضر هيئات القرار الفعلية (ولو غير رسمية) للسنة الأخيرة" },
    ],
    procedures: [
      { id: "or-1", ref: "DD practice", text: { en: "Interview the top layer one-on-one: each executive asked the same five questions (strategy, top risk, what breaks first, who replaces you, why now to sell) — the variance between answers is the diligence signal.", ar: "مقابلة الطبقة العليا فرديًا: نفس الأسئلة الخمسة لكل تنفيذي (الاستراتيجية، أكبر خطر، ما ينكسر أولًا، من يحل محلك، لماذا البيع الآن) — فالتباين بين الإجابات هو إشارة العناية." } },
      { id: "or-2", ref: "DD practice", text: { en: "Run the bus-factor test per critical function: sales, production, IT, licenses, key relationships — count the people who could each be hit by a bus tomorrow without stopping the function; a bus factor of one is a priced risk.", ar: "تطبيق اختبار معامل النجاة لكل وظيفة حرجة: البيع والإنتاج وتقنية المعلومات والتراخيص والعلاقات الرئيسية — بعدد الأشخاص الذين يمكن أن يغيب أحدهم غدًا دون توقف الوظيفة؛ فمعامل يساوي واحدًا خطر مسعّر." } },
      { id: "or-3", ref: "DD practice", text: { en: "Trace ten real decisions through the authority matrix: procurement above threshold, discounts, hires, payments — who actually signed vs. who the matrix says should.", ar: "تتبع عشر قرارات حقيقية عبر مصفوفة الصلاحيات: شراء فوق الحد وخصومات وتعيينات ومدفوعات — من وقّع فعلًا مقابل من تقول المصفوفة إنه ينبغي أن يوقع." } },
      { id: "or-4", ref: "DD practice", text: { en: "Analyze sales concentration among people, not just customers: if 60% of revenue is personally carried by one commercial director, the retention plan for that person is a deal term.", ar: "تحليل تركّز البيع بين الأشخاص لا العملاء فقط: إذا كان 60% من الإيراد يحمله مدير تجاري بعينه، فخطة احتفاظه بند في الصفقة." } },
      { id: "or-5", ref: "DD practice", text: { en: "Walk the middle-management layer: interview 5-8 managers below the executives — do they know the numbers, the plan, and their own authority? This layer is what the buyer inherits.", ar: "فحص طبقة الإدارة الوسطى: مقابلة 5-8 مديرين دون التنفيذيين — هل يعرفون الأرقام والخطة وصلاحياتهم؟ هذه الطبقة هي ما يرثه المشتري." } },
      { id: "or-6", ref: "DD practice", text: { en: "Quantify turnover in the roles that matter: sales engineers, machine operators, developers — replacing them has a recruitment cost, a learning curve, and a customer-relationship cost.", ar: "تقدير دوران العمالة في الأدوار المهمة: مهندسو البيع ومشغلو الماكينات والمطورون — فاستبدالهم له كلفة توظيف ومنحنى تعلم وكلفة علاقة مع العملاء." } },
      { id: "or-7", ref: "DD practice", text: { en: "Map the informal organization: who does management call at 11 pm when production stops, and is that person on the org chart at all?", ar: "رسم التنظيم غير الرسمي: من يتصل به الإدارة في الحادية عشرة مساء عند توقف الإنتاج؟ وهل هذا الشخص على المخطط أصلًا؟" } },
      { id: "or-8", ref: "DD practice", text: { en: "Check the governance reality: board meetings that actually convene, information packs management actually reads, and KPIs actually tracked — governance that exists only on paper is discovered, always, by the buyer.", ar: "فحص واقع الحوكمة: اجتماعات مجلس تنعقد فعلًا وحزم معلومات تقرأها الإدارة فعلًا ومؤشرات تُتابع فعلًا — فالحوكمة الورقية يكتشفها المشتري دائمًا." } },
      { id: "or-9", ref: "DD practice", text: { en: "Hand the people map to the deal model: retention packages, severance costs, and the recruitment/replacement budget become integration cost in the price.", ar: "تمرير خريطة الكوادر لنموذج الصفقة: حزم الاحتفاظ وكلف الفصل وموازنة الاستبدال تصبح كلفة دمج في السعر." } },
    ],
    redFlags: [
      { text: { en: "The founder personally holds the key customer relationships, pricing authority, and the bank relationships — no second layer exists.", ar: "المؤسس يحمل شخصيًا علاقات العملاء الرئيسية وصلاحية التسعير وعلاقات البنوك — لا توجد طبقة ثانية." }, critical: true },
      { text: { en: "Middle managers cannot state the company's plan or their own budgets.", ar: "مديرو الطبقة الوسطى لا يستطيعون بيان خطة الشركة أو موازناتهم." } },
      { text: { en: "Delegation matrix exists on paper but 10/10 real decisions bypassed it.", ar: "مصفوفة التفويض موجودة ورقيًا لكن 10 من 10 قرارات فعلية تجاوزتها." } },
      { text: { en: "Turnover in critical roles spiking in the last 12 months (people sense the sale first).", ar: "ارتفاع حاد في مغادرة الأدوار الحرجة آخر 12 شهرًا (الناس يستشعرون البيع أولًا)." } },
    ],
  },

  {
    id: "processes",
    code: "O-02",
    scope: "ops",
    group: null,
    icon: "settings",
    title: { en: "Operations & Processes", ar: "العمليات والعمليات التشغيلية" },
    scopeNote: {
      en: "How work actually flows: order to cash, procurement to payment, production planning and quality control — the machine the buyer is purchasing, examined part by part.",
      ar: "كيف يتدفق العمل فعلًا: من الطلب إلى التحصيل، ومن الشراء إلى الدفع، وتخطيط الإنتاج وضبط الجودة — الآلة التي يشتريها المشتري تُفحص قطعة قطعة.",
    },
    why: [
      { en: "Understand how the money is actually made — which process converts materials into margin, and where it is fragile.", ar: "فهم كيف يُصنع المال فعلًا — أي عملية تحول المواد إلى هامش، وأين تكون هشة." },
      { en: "Identify the capacity and bottleneck structure: what constrains growth, and what capex releases it.", ar: "تحديد بنية الطاقة الاستيعابية والاختناقات: ما يقيد النمو وأي إنفاق رأسمالي يحرره." },
      { en: "Benchmark process maturity: manual workarounds and Excel-spined processes are integration cost after closing.", ar: "قياس نضج العمليات: الحلول اليدوية والعمليات القائمة على Excel كلفة دمج بعد الإغلاق." },
    ],
    documents: [
      { en: "Process maps for order-to-cash and procure-to-pay (as-is, honestly drawn)", ar: "خرائط عمليات الطلب-إلى-التحصيل والشراء-إلى-الدفع (كما هي بصدق)" },
      { en: "Production data: capacity, utilization, OEE or its equivalent, downtime log", ar: "بيانات الإنتاج: الطاقة والاستغلال والكفاءة الشاملة وسجل التوقفات" },
      { en: "Standard operating procedures that exist in writing (and a list of the ones that don't)", ar: "إجراءات التشغيل القياسية المكتوبة (وقائمة الغائب منها)" },
      { en: "Quality system: ISO certificates, defect/returns statistics, CAPA logs", ar: "نظام الجودة: شهادات ISO وإحصاءات العيوب والمرتجعات وسجل الإجراءات التصحيحية" },
      { en: "Maintenance records and the capex log for the last 3 years", ar: "سجلات الصيانة وسجل الإنفاق الرأسمالي لآخر 3 سنوات" },
      { en: "Production cost build-up per main product family", ar: "مكونات تكلفة الإنتاج لكل عائلة منتجات رئيسية" },
    ],
    procedures: [
      { id: "pr-1", ref: "DD practice", text: { en: "Walk order-to-cash physically: pick 10 live orders and follow each from inquiry to cash receipt — count the systems, handoffs, and manual interventions per order; every intervention is latency and error surface.", ar: "تتبع دورة الطلب-إلى-التحصيل ميدانيًا: اختيار 10 أوامر حية ومرافقة كل منها من الاستفسار إلى التحصيل — مع عد الأنظمة ونقاط التسليم والتدخلات اليدوية لكل أمر؛ فكل تدخل تأخيرٌ وسطح خطأ." } },
      { id: "pr-2", ref: "DD practice", text: { en: "Same for procure-to-pay: 10 purchases from requisition to payment — approval chain, three-bids evidence, receiving control, and invoice matching.", ar: "وكذلك الشراء-إلى-الدفع: 10 عمليات شراء من الطلب إلى الدفع — سلسلة الاعتماد ودليل المناقصات الثلاث وضبط الاستلام ومطابقة الفواتير." } },
      { id: "pr-3", ref: "DD practice", text: { en: "Measure the real bottleneck: where does work queue? (production stage, approvals, logistics) — utilization figures per stage expose the constraint the growth plan depends on.", ar: "قياس الاختناق الحقيقي: أين تتراكم الأعمال؟ (مرحلة إنتاج أو اعتمادات أو لوجستيات) — فأرقام الاستغلال بكل مرحلة تكشف القيد الذي تعتمد عليه خطة النمو." } },
      { id: "pr-4", ref: "DD practice", text: { en: "Test quality reality: returns and complaint rates trended over 3 years, mapped to customers and product families — a rising curve contradicts every marketing deck.", ar: "اختبار واقع الجودة: اتجاه معدلات المرتجعات والشكاوى عبر 3 سنوات موزعًا على العملاء وعائلات المنتجات — فالمنحني الصاعد يكذب كل عرض تسويقي." } },
      { id: "pr-5", ref: "DD practice", text: { en: "Assess maintenance truth: downtime trend, mean-time-between-failures on critical machines, and the deferred-maintenance backlog — deferred maintenance is debt denominated in future capex.", ar: "تقييم حقيقة الصيانة: اتجاه التوقفات والزمن المتوسط بين أعطال الماكينات الحرجة ومتأخرات الصيانة المؤجلة — فالصيانة المؤجلة دينٌ مقوم بإنفاق رأسمالي مستقبلي." } },
      { id: "pr-6", ref: "DD practice", text: { en: "Reconcile unit economics: pick the top-3 products and rebuild their cost per unit from the floor (materials, labor, machine time, scrap) — compare to the standard cost the P&L uses.", ar: "مطابقة اقتصاديات الوحدة: اختيار أكبر 3 منتجات وإعادة بناء تكلفتها للوحدة من أرض الموقع (مواد وأجور وزمن ماكينة وهوادر) ومقارنتها بالتكلفة المعيارية في الأرباح والخسائر." } },
      { id: "pr-7", ref: "DD practice", text: { en: "Inventory the process debt: processes run on personal spreadsheets, tribal knowledge, and one person's mailbox — list them; they set the integration budget.", ar: "جرد دين العمليات: العمليات التي تسير على جداول شخصية ومعرفة قبلية وبريد شخص واحد — إدراجها؛ فهي تحدد موازنة الدمج." } },
      { id: "pr-8", ref: "DD practice", text: { en: "Compare stated capacity to demonstrated output: best month ever vs. average month — and what it took (overtime, outsourcing, corners) to hit the best month.", ar: "مقارنة الطاقة المعلنة بالمخرج المثبت: أفضل شهر على الإطلاق مقابل متوسط الشهور — وما تكلف الوصول للأفضل (وقت إضافي، إسناد خارجي، اختصارات)." } },
      { id: "pr-9", ref: "DD practice", text: { en: "Feed the operational findings to the financial workstream: scrap rates, downtime, and the manual-process map explain margin variance and normalize the EBITDA the price is built on.", ar: "تمرير نتائج التشغيل لفريق العناية المالية: نسب الهدر والتوقفات وخريطة العمليات اليدوية تفسر تباين الهامش وتطبع الأرباح التي بُني عليها السعر." } },
    ],
    redFlags: [
      { text: { en: "The production process cannot be run by anyone except the shift supervisor who threatened to leave.", ar: "لا يمكن تشغيل عملية الإنتاج إلا مشرف الوردية الذي هدد بالمغادرة." } },
      { text: { en: "Standard costs untouched for years while input prices moved — margins are fiction.", ar: "تكاليف معيارية لم تُمس سنوات بينما تحركت أسعار المدخلات — الهوامش خيال." } },
      { text: { en: "Returns/complaints rising while the sales pitch claims quality leadership.", ar: "المرتجعات والشكاوى ترتفع بينما يزعم عرض البيع الريادة في الجودة." } },
      { text: { en: "Growth plan requires capacity the bottleneck analysis shows does not exist.", ar: "خطة النمو تتطلب طاقة استيعابية يُظهر تحليل الاختناقات أنها غير موجودة." } },
    ],
  },

  {
    id: "it-cyber",
    code: "O-03",
    scope: "ops",
    group: null,
    icon: "server",
    title: { en: "IT Systems & Cybersecurity", ar: "الأنظمة والأمن السيبراني" },
    scopeNote: {
      en: "The systems the business runs on, the data it holds, and its resilience to the cyber events that now decide whether day one after closing is business as usual or a crisis.",
      ar: "الأنظمة التي يعمل عليها النشاط والبيانات التي يحوزها ومرونته أمام الأحداث السيبرانية التي تقرر اليوم هل يكون اليوم الأول بعد الإغلاق عملًا كالمعتاد أم أزمة.",
    },
    why: [
      { en: "Map the system estate: which ERP, which data flows, which single points of failure — and what an ERP migration would cost if forced.", ar: "رسم خريطة منظومة الأنظمة: أي ERP وأي تدفقات بيانات وأي نقاط فشل مفردة — وكم يكلف الانتقال إلى نظام آخر إن اضطُر إليه." },
      { en: "Verify license compliance across the estate — unlicensed software is inherited legal exposure with a price tag.", ar: "التحقق من امتثال التراخيص عبر المنظومة — فالبرمجيات غير المرخصة تعرض قانوني موروث له ثمن." },
      { en: "Assess the cyber posture: the target's data (customer, payroll, health, payment) makes it exactly the prey profile ransomware hunts.", ar: "تقييم الموقف السيبراني: بيانات الهدف (عملاء وأجور وصحة ومدفوعات) تجعله على وجه التحديد هو الفريسة التي يطاردها فيروس الفدية." },
    ],
    documents: [
      { en: "System inventory: applications, versions, hosting (cloud/on-prem), owners", ar: "جرد الأنظمة: التطبيقات والإصدارات والاستضافة والمالك" },
      { en: "ERP/finance system architecture and the integration map between systems", ar: "هيكل نظام تخطيط الموارد وخريطة التكامل بين الأنظمة" },
      { en: "Software license positions (Microsoft, Oracle, industry tools) and true-up history", ar: "مواقف تراخيص البرمجيات ومايكروسوفت وأوراكل وأدوات القطاع وسجل التسوية" },
      { en: "Security posture: last penetration test / vulnerability assessment, findings, remediation status", ar: "الموقف الأمني: آخر اختبار اختراق أو تقييم ثغرات والنتائج وحالة المعالجة" },
      { en: "Backup regime: what, how often, where, and the last successful restore test", ar: "نظام النسخ الاحتياطي: ماذا وكم مرة وأين وآخر اختبار استعادة ناجح" },
      { en: "IT team structure, outsourced IT contracts, and key-person dependencies", ar: "هيكل فريق تقنية المعلومات وعقود الإسناد الخارجي واعتماديات الأفراد" },
      { en: "Data map: personal data held, where, retention, and cross-border flows", ar: "خريطة البيانات: البيانات الشخصية المحوزة وأينها ومدد الحفظ والتدفقات العابرة للحدود" },
    ],
    procedures: [
      { id: "it-1", ref: "DD practice", text: { en: "Draw the system map on one page: every application that touches money (sales, invoicing, inventory, payroll, reporting) with its hosting, owner, and license status — the buyer's day-one IT is this page.", ar: "رسم خريطة الأنظمة في صفحة واحدة: كل تطبيق يلمس المال (بيع وفوترة ومخزون وأجور وتقارير) باستضافته ومالكه ووضع ترخيصه — فتقنية معلومات المشتري في اليوم الأول هي هذه الصفحة." } },
      { id: "it-2", ref: "DD practice", text: { en: "Test the finance system's integrity at the source: who can post journals, who can change master data, and whether the audit trail is on — an ERP everyone can edit is not a system of record.", ar: "اختبار سلامة النظام المالي من المنبع: من يستطيع ترحيل القيود ومن يعدل البيانات الأساسية وهل سجل التتبع مفعّل — فنظام يستطيع الجميع تعديله ليس نظام سجل معتمد." } },
      { id: "it-3", ref: "DD practice", text: { en: "Verify the numbers' pipeline: how data flows from POS/machine/CRM to the GL — manual re-typing steps in that pipeline are both error and manipulation surface.", ar: "التحقق من خط أنابيب الأرقام: كيف تسري البيانات من نقاط البيع أو الماكينات أو إدارة العلاقات إلى الدفتر العام — فخطوات إعادة الكتابة اليدوية في الخط سطح خطأ وتلاعب معًا." } },
      { id: "it-4", ref: "DD practice", text: { en: "Review the last penetration test line by line: findings by severity, what was fixed, what was accepted as risk — and ask for the one before it; recurring findings mean management treats security as paperwork.", ar: "مراجعة آخر اختبار اختراق بندًا بندًا: النتائج بدرجاتها وما عولج وما قُبل كخطر — وطلب سابقه أيضًا؛ فالنتائج المتكررة تعني أن الإدارة تتعامل مع الأمن كأعمال ورقية." } },
      { id: "it-5", ref: "DD practice", text: { en: "Witness a restore test or read the log of the last one: backups that have never been restored are a belief, not a control.", ar: "مشاهدة اختبار استعادة أو قراءة سجل آخر واحد: فالنسخ الاحتياطية التي لم تُستعن قط عقيدة لا رقابة." } },
      { id: "it-6", ref: "Data Protection Law 151/2020", text: { en: "Map personal-data flows against the law: consent basis, retention actually enforced, cross-border transfer mechanisms — the buyer inherits the entire compliance gap at closing.", ar: "مطابقة تدفقات البيانات الشخصية بالقانون: سند الموافقة والمدد المنفذة فعليًا وآليات النقل عبر الحدود — فالمشتري يرث فجوة الامتثال كاملة عند الإغلاق." } },
      { id: "it-7", ref: "DD practice", text: { en: "Check IT key-person and vendor locks: the ERP partner, the website agency, the outsourced admin — contract terms, notice periods, and hostage risk (credentials, source code, domain).", ar: "فحص أقفال الأفراد والموردين في تقنية المعلومات: شريك النظام ووكالة الموقع والمسؤول الخارجي — شروط العقود ومهل الإخطار وخطر الرهينة (بيانات الدخول، الكود المصدري، النطاق)." } },
      { id: "it-8", ref: "DD practice", text: { en: "Estimate the separation scenario: if the target shares systems with the founder's other companies (a common structure), price the carve-out: new licenses, migration, TSA duration.", ar: "تقدير سيناريو الفصل: إذا شارك الهدف أنظمته مع شركات المؤسس الأخرى (هيكل شائع)، فتسعير الانتزاع: تراخيص جديدة وهجرة واتفاقية خدمات انتقالية." } },
      { id: "it-9", ref: "DD practice", text: { en: "Review incident history: past breaches, ransomware events, fraud attempts — and how they were detected (or not); the answer shapes the cyber-insurance decision and the integration plan.", ar: "مراجعة تاريخ الحوادث: اختراقات سابقة وحوادث فدية ومحاولات احتيال — وكيف اكتُشفت أو لم تُكتشف؛ فالإجابة تشكل قرار التأمين السيبراني وخطة الدمج." } },
    ],
    redFlags: [
      { text: { en: "No backup restore has ever been tested — or backups live on the same server they protect.", ar: "لم يختبر استعادة نسخة احتياطية قط — أو أن النسخ على الخادم نفسه الذي تحميه." }, critical: true },
      { text: { en: "Core financial data passes through the founder's personal spreadsheets or mailbox.", ar: "البيانات المالية الجوهرية تمر بجداول المؤسس الشخصية أو بريده." } },
      { text: { en: "Shared systems with the seller's other businesses with no separation plan.", ar: "أنظمة مشتركة مع أعمال البائع الأخرى دون خطة فصل." } },
      { text: { en: "Unlicensed or cracked software in production use.", ar: "برمجيات غير مرخصة أو مكسورة الحماية في الاستخدام الفعلي." } },
    ],
  },

  {
    id: "supply-chain",
    code: "O-04",
    scope: "ops",
    group: null,
    icon: "truck",
    title: { en: "Supply Chain & Customers", ar: "سلسلة الإمداد والعملاء" },
    scopeNote: {
      en: "The commercial machine viewed from both ends: the suppliers the target depends on and the customers who pay for everything — concentration, dependency, and switching risk at each end.",
      ar: "الآلة التجارية من طرفيها: الموردون الذين يعتمد عليهم الهدف والعملاء الذين يدفعون ثمن كل شيء — التركز والاعتماد وخطر التحول عند كل طرف.",
    },
    why: [
      { en: "Quantify concentration both ways: a top customer or a sole-source supplier above threshold is a negotiation the buyer must win before closing.", ar: "تقدير التركز في الاتجاهين: عميل أول أو مورد وحيد فوق الحد هو تفاوض يجب أن يكسبه المشتري قبل الإغلاق." },
      { en: "Test substitutability: how long and how costly to switch each critical supplier or replace each major customer.", ar: "اختبار قابلية الإحلال: كم يستغرق وكم يكلف استبدال كل مورد حرج أو تعويض كل عميل رئيسي." },
      { en: "Verify the revenue quality behind the customer list: contracted vs. discretionary, recurring vs. one-off, related-party vs. arm's-length.", ar: "التحقق من جودة الإيراد خلف قائمة العملاء: تعاقدي مقابل تقديري، ومتكرر مقابل لمرة واحدة، وأطراف ذات علاقة مقابل تعامل مطلق." },
    ],
    documents: [
      { en: "Supplier spend analysis: top-20 suppliers, 3-year spend, contract status, alternates", ar: "تحليل الإنفاق على الموردين: أكبر 20 موردًا وإنفاق 3 سنوات ووضع العقود والبدائل" },
      { en: "Customer revenue analysis: top-20 customers, 3-year revenue, churn, contract status", ar: "تحليل إيراد العملاء: أكبر 20 عميلًا وإيراد 3 سنوات والدوران ووضع العقود" },
      { en: "Sole-source and single-point-of-failure supplier register", ar: "سجل الموردين وحيدي المصدر ونقاط الفشل المفردة" },
      { en: "Pricing history by customer segment and the mechanism (contract, list, negotiation)", ar: "تاريخ التسعير بشريحة العملاء وآليته (عقد، قائمة، تفاوض)" },
      { en: "Logistics map: incoterms, lead times, freight contracts, customs exposure", ar: "خريطة اللوجستيات: شروط التسليم ومهل التوريد وعقود الشحن والتعرض الجمركي" },
      { en: "Customer credit-loss and dispute history", ar: "تاريخ خسائر الائتمان والمنازعات مع العملاء" },
    ],
    procedures: [
      { id: "sc-1", ref: "DD practice", text: { en: "Compute concentration honestly: top-1, top-5, top-10 customer and supplier shares of revenue and spend, trended 3 years — both rising concentration and falling (churn) are stories.", ar: "احتساب التركز بصدق: حصص العميل الأول والخمسة والعشرة والموردين من الإيراد والإنفاق عبر 3 سنوات — فالتركز الصاعد والهابط (الدوران) كلاهما قصة." } },
      { id: "sc-2", ref: "DD practice", text: { en: "For each critical supplier, run the switch test: alternative source, qualification time, cost delta, and contract exit cost — sole-source with long qualification is a business risk, not a procurement detail.", ar: "لكل مورد حرج، اختبار الإحلال: مصدر بديل وزمن التأهيل وفرق الكلفة وكلفة الخروج من العقد — فالوحيد المصدر بتأهيل طويل خطر على النشاط لا تفصيلة مشتريات." } },
      { id: "sc-3", ref: "DD practice", text: { en: "Interview the top-5 customers (through management, or at least the ones who agreed): satisfaction, switching intentions, and what they think of the sale — the customers always know more than the data room shows.", ar: "مقابلة أكبر 5 عملاء (عبر الإدارة أو من وافق على الأقل): الرضا ونوايا التحول ورأيهم في البيع — فالعملاء يعلمون دائمًا أكثر مما تظهره غرفة البيانات." } },
      { id: "sc-4", ref: "IFRS 15", text: { en: "Decompose revenue quality: recurring/subscription vs. transactional, contracted vs. discretionary, and the retention rate of each — a growth story built on one-off wins reprices fast.", ar: "تفكيك جودة الإيراد: متكرر/اشتراك مقابل معاملات، وتعاقدي مقابل تقديري، ومعدل الاحتفاظ بكل نوع — فقصة نمو مبنية على مكاسب لمرة واحدة يعاد تسعيرها سريعًا." } },
      { id: "sc-5", ref: "IAS 24", text: { en: "Filter related parties out of the customer and supplier lists and re-run concentration: the related-party shadow business disappears at closing — the question is how much revenue walks with it.", ar: "إقصاء الأطراف ذات العلاقة من قائمتي العملاء والموردين وإعادة احتساب التركز: فالأعمال الظل للأطراف ذات العلاقة تختفي عند الإغلاق — والسؤال كم إيرادًا يرحل معها." } },
      { id: "sc-6", ref: "DD practice", text: { en: "Stress the supply chain: FX exposure on imported inputs, single-country sourcing, and what the last disruption (port, pandemic, canal) actually cost — resilience is proven by history, not claims.", ar: "إجهاد سلسلة الإمداد: التعرض العملات على المدخلات المستوردة والتوريد من بلد واحد وما كلف آخر اضطراب (ميناء أو وباء أو قناة) فعلًا — فالمرونة تثبتها السابقة لا الادعاءات." } },
      { id: "sc-7", ref: "DD practice", text: { en: "Reconcile the customer list to revenue and to receivables: names in one and not the other, revenue with no receivable (cash sales?), receivables with no revenue (dead balances).", ar: "مطابقة قائمة العملاء بالإيراد وبالذمم المدينة: أسماء في قائمة دون أخرى، وإيراد بلا مدين (بيع نقدي؟)، ومدينون بلا إيراد (أرصدة ميتة)." } },
      { id: "sc-8", ref: "DD practice", text: { en: "Analyze pricing power: price changes passed to customers over 3 years vs. input-cost changes — the pass-through rate is the margin's real moat.", ar: "تحليل قوة التسعير: التغيرات التي مررت للعملاء عبر 3 سنوات مقابل تغيرات كلفة المدخلات — فمعدل التمرير هو الخندق الحقيقي للهامش." } },
    ],
    redFlags: [
      { text: { en: "A related party is also a top customer or supplier at non-market terms — revenue and margin both need restating.", ar: "طرف ذو علاقة هو أيضًا من كبار العملاء أو الموردين بشروط غير سوقية — الإيراد والهامش كلاهما يحتاج إعادة عرض." }, critical: true },
      { text: { en: "Top customer >25% of revenue with no contract and a personal relationship to the founder.", ar: "أكبر عميل يفوق 25% من الإيراد بلا عقد وبعلاقة شخصية بالمؤسس." } },
      { text: { en: "Sole-source supplier with no alternate qualified and long lead times.", ar: "مورد وحيد المصدر بلا بديل مؤهل وبمهل توريد طويلة." } },
      { text: { en: "Customer churn accelerating in the last 12 months while the pipeline story stays rosy.", ar: "تسارع دوران العملاء آخر 12 شهرًا بينما تبقى قصة الفرص وردية." } },
    ],
  },

  {
    id: "qhse",
    code: "O-05",
    scope: "ops",
    group: null,
    icon: "shield",
    title: { en: "Quality, Health, Safety & Environment", ar: "الجودة والصحة والسلامة والبيئة" },
    scopeNote: {
      en: "The permits-and-accidents side of operations: QHSE certifications, incident history, environmental exposure, and the capex the next inspection will demand.",
      ar: "الوجه التصاريح والحوادث من العمليات: شهادات الجودة والسلامة والبيئة وتاريخ الحوادث والتعرض البيئي والإنفاق الرأسمالي الذي سيطلبه التفتيش القادم.",
    },
    why: [
      { en: "Verify certifications are real, current, and scope-covering — an expired ISO or HACCP certificate is a customer-contract problem in regulated supply chains.", ar: "التحقق من أن الشهادات حقيقية وسارية وتغطي النطاق — فشهادة ISO أو HACCP منتهية مشكلة عقود عملاء في سلاسل الإمداد المنظمة." },
      { en: "Quantify incident and claims history: the pattern predicts the successor's liability and the insurer's price.", ar: "تقدير تاريخ الحوادث والمطالبات: فالنمأ يتنبأ بمسؤولية الخلف وسعر المؤمن." },
      { en: "Surface environmental exposure: emissions, effluent, waste — remediation costs are the classic post-closing surprise.", ar: "إبراز التعرض البيئي: الانبعاثات والصرف والمخلفات — فتكاليف المعالجة هي المفاجأة الكلاسيكية بعد الإغلاق." },
    ],
    documents: [
      { en: "QHSE certificates (ISO 9001/14001/45001, HACCP, sector-specific) with scope and expiry", ar: "شهادات الجودة والسلامة والبيئة (ISO 9001/14001/45001 وHACCP وقطاعية) بالنطاق والانتهاء" },
      { en: "Incident/accident register for 3 years with investigations and outcomes", ar: "سجل الحوادث لثلاث سنوات بالتحقيقات والنتائج" },
      { en: "Environmental permits, monitoring reports, and any violations/fines", ar: "التراخيص البيئية وتقارير الرصد وأي مخالفات أو غرامات" },
      { en: "Waste management: contracts, manifests, hazardous-waste disposal certificates", ar: "إدارة المخلفات: العقود والمانيفستات وشهادات التخلص من المخلفات الخطرة" },
      { en: "Insurance portfolio: policies, claims history, loss runs for 3 years", ar: "محفظة التأمين: الوثائق وتاريخ المطالبات وسجل الخسائر لثلاث سنوات" },
      { en: "CAPA log and internal/external audit findings status", ar: "سجل الإجراءات التصحيحية ووضع ملاحظات التدقيق الداخلي والخارجي" },
    ],
    procedures: [
      { id: "qh-1", ref: "DD practice", text: { en: "Verify each certificate at the issuer (registry check, not the framed copy on the wall) — scope, sites covered, expiry, and any suspension history.", ar: "التحقق من كل شهادة لدى الجهة المانحة (بفحص السجل لا النسخة المأطرة على الحائط) — النطاق والمواقع المغطاة والانتهاء وأي تاريخ إيقاف." } },
      { id: "qh-2", ref: "DD practice", text: { en: "Analyze the incident register for pattern, not anecdotes: frequency and severity trend, repeat root causes, and what changed after each serious event.", ar: "تحليل سجل الحوادث بحثًا عن النمأ لا الحكايات: اتجاه التكرار والشدة والأسباب الجذرية المتكررة وما تغير بعد كل حادث جسيم." } },
      { id: "qh-3", ref: "DD practice", text: { en: "Reconcile the incident register to the insurance claims and to the medical/leave records — incidents that appear in none of the three were never recorded at all.", ar: "مطابقة سجل الحوادث بمطالبات التأمين وبسجلات العلاج والأجازات — فالحادث الغائب عن الثلاثة لم يسجل أصلًا." } },
      { id: "qh-4", ref: "Environment law 4/1994", text: { en: "For industrial targets, walk the environmental file: permits vs. actual operations, monitoring reports vs. limits, and the visible state of the site (effluent, dust, noise) — then price the gap to compliance.", ar: "للأهداف الصناعية، فحص الملف البيئي: التراخيص مقابل التشغيل الفعلي وتقارير الرصد مقابل الحدود والحالة الظاهرة للموقع (صرف وأتربة وضجيج) — ثم تسعير الفجوة حتى الامتثال." } },
      { id: "qh-5", ref: "DD practice", text: { en: "Test the insurance spine: sums insured vs. replacement values, coverage gaps (business interruption, cyber, environmental liability), and the claims history the insurer will load the renewal on.", ar: "اختبار العمود الفقري للتأمين: المبالغ المؤمنة مقابل قيم الاستبدال والفجوات (انقطاع النشاط، السيبراني، المسؤولية البيئية) وتاريخ المطالبات الذي سيحمل به المؤمن التجديد." } },
      { id: "qh-6", ref: "DD practice", text: { en: "Estimate deferred QHSE capex: what the next audit cycle, inspection, or regulation will force (equipment, treatment plant, monitoring) — unspent compliance capex is inherited debt.", ar: "تقدير الإنفاق الرأسمالي البيئي المؤجل: ما سيفرضه دورة التدقيق أو التفتيش أو التنظيم القادم (معدات ومحطة معالجة ورصد) — فالإنفاق الامتثالي غير المنفق دين موروث." } },
      { id: "qh-7", ref: "DD practice", text: { en: "Inspect the floor with the safety officer: housekeeping, PPE discipline, machine guarding, fire routes — 60 minutes on the floor beats 60 pages of policy in the data room.", ar: "تفتيش أرض الموقع مع مسؤول السلامة: النظام وارتداء مهمات الوقاية وحواجز الماكينات ومسارات الحريق — فستون دقيقة في الموقع تغلب ستين صفحة سياسات في غرفة البيانات." } },
    ],
    redFlags: [
      { text: { en: "A fatal or serious incident with an open investigation and uninsured exposure.", ar: "حادث جسيم أو مميت بتحقيق مفتوح وتعرض غير مؤمن." }, critical: true },
      { text: { en: "Operating beyond permitted capacity or emissions limits (documented by the target's own monitoring).", ar: "تشغيل يتجاوز الطاقة أو الحدود المسموحة (بإثبات رصد الهدف نفسه)." } },
      { text: { en: "Hazardous waste disposed without certificates for years.", ar: "تخلص من مخلفات خطرة بلا شهادات لسنوات." } },
      { text: { en: "Certificates expired or scoped to fewer sites than the business operates.", ar: "شهادات منتهية أو محدودة النطاق عن مواقع أقل من المشغلة فعليًا." } },
    ],
  },

  {
    id: "continuity",
    code: "O-06",
    scope: "ops",
    group: null,
    icon: "activity",
    title: { en: "Business Continuity & Risk", ar: "استمرارية الأعمال والمخاطر" },
    scopeNote: {
      en: "What happens when something breaks — the continuity plans, the tested recovery, and the risk register the target actually uses to run the business.",
      ar: "ماذا يحدث حين ينكسر شيء ما — خطط الاستمرارية والاستعادة المختبرة وسجل المخاطر الذي يستخدمه الهدف فعلًا لإدارة النشاط.",
    },
    why: [
      { en: "Verify continuity claims are tested: plans that exist but were never rehearsed fail exactly when needed.", ar: "التحقق من أن ادعاءات الاستمرارية مختبرة: فالخطط الموجودة التي لم تُجرَّب تفشل في اللحظة التي تحتاجها بالضبط." },
      { en: "Identify single points of failure across the whole system: site, supplier, system, person, customer, license.", ar: "تحديد نقاط الفشل المفردة عبر المنظومة كلها: موقع ومورد ونظام وشخص وعميل وترخيص." },
      { en: "Read the risk register the target runs by — what management itself fears is the most honest document in the data room.", ar: "قراءة سجل المخاطر الذي يدير به الهدف نشاطه — فما تخشاه الإدارة نفسها أصدق مستند في غرفة البيانات." },
    ],
    documents: [
      { en: "Business continuity / disaster recovery plans (with last test date and report)", ar: "خطط استمرارية الأعمال والتعافي (بتاريخ آخر اختبار وتقريره)" },
      { en: "The target's own risk register (current and 2 years back for comparison)", ar: "سجل مخاطر الهدف نفسه (الحالي وقبل سنتين للمقارنة)" },
      { en: "Crisis management structure and the last incident's post-mortem", ar: "هيكل إدارة الأزمات ومراجعة آخر حادث" },
      { en: "Dependency map: single sites, single suppliers, single systems, single people", ar: "خريطة الاعتماديات: مواقع وموردون وأنظمة وأفراد وحيدون" },
      { en: "FX, interest-rate, and commodity exposure policies and hedge instruments", ar: "سياسات التعرض للعملات والفائدة والسلع وأدوات التحوط" },
    ],
    procedures: [
      { id: "cn-1", ref: "DD practice", text: { en: "Read the risk register against reality: which risks closed, which grew, which materialized — and compare the 2-year-ago register to today's; a register that never changes is decoration.", ar: "قراءة سجل المخاطر مقابل الواقع: أي المخاطر أُغلقت وأيها نما وأيها تحقق — ومقارنة سجل قبل سنتين بالحالي؛ فالسجل الذي لا يتغير ديكور." } },
      { id: "cn-2", ref: "DD practice", text: { en: "Build the single-point-of-failure matrix across six axes (site, supplier, system, person, customer, license) with impact and time-to-recover for each — then check which have mitigations that actually exist.", ar: "بناء مصفوفة نقاط الفشل المفردة على ستة محاور (موقع، مورد، نظام، شخص، عميل، ترخيص) بأثر وزمن التعافي لكل منها — ثم فحص أيها له تخفيف موجود فعلًا." } },
      { id: "cn-3", ref: "DD practice", text: { en: "Test continuity evidence: last fire drill, last failover, last restore — with dates and participants; untested continuity is a hypothesis.", ar: "اختبار أدلة الاستمرارية: آخر تجربة إخلاء وآخر تحول احتياطي وآخر استعادة — بالتواريخ والمشاركين؛ فالاستمرارية غير المختبرة فرضية." } },
      { id: "cn-4", ref: "IFRS 9", text: { en: "Verify hedge accounting claims: are the derivative instruments real, documented, and effective per IFRS 9 — or is 'hedging' just the CFO watching the FX rate?", ar: "التحقق من ادعاءات محاسبة التغطية: هل الأدوات المشتقة حقيقية وموثقة وفعالة وفق IFRS 9 — أم أن «التغطية» مجرد متابعة المدير المالي لسعر الصرف؟" } },
      { id: "cn-5", ref: "DD practice", text: { en: "Scenario the top-3 risks with management: what happened last time, what it cost, how long it lasted — history is the only honest stress test.", ar: "تمثيل أكبر 3 مخاطر مع الإدارة: ماذا حدث آخر مرة وكم كلف وكم استغرق — فالتاريخ هو اختبار الإجهاد الصادق الوحيد." } },
      { id: "cn-6", ref: "DD practice", text: { en: "Check the crisis communication plan for the deal itself: who tells the customers, staff, and regulator on signing day — continuity during ownership transfer is the riskiest week of all.", ar: "فحص خطة إدارة الأزمة للصفقة نفسها: من يخبر العملاء والعاملين والجهة الرقابية يوم التوقيع — فالاستمرارية أثناء انتقال الملكية أخطر أسبوع على الإطلاق." } },
      { id: "cn-7", ref: "DD practice", text: { en: "Test whether continuity is a living system or a binder: when did the plan last change, who owns it, and can the night-shift manager lay hands on it at 3 a.m. — an unowned, outdated, unreachable plan failed its only test already.", ar: "اختبار هل الاستمرارية نظام حي أم ملف في رفّ: متى تغيرت الخطة آخر مرة ومن يملكها وهل يقدر مدير الوردية الليلية على الوصول إليها في الثالثة فجرًا — فالخطة بلا مالك وبلا تحديث وبلا وصول سقطت في اختبارها الوحيد مسبقًا." } },
    ],
    redFlags: [
      { text: { en: "A single site carries >70% of production with no recovery arrangement at all.", ar: "موقع واحد يحمل أكثر من 70% من الإنتاج بلا أي ترتيب تعافٍ." } },
      { text: { en: "Risk register copy-pasted from a template, never reviewed, no owners.", ar: "سجل مخاطر منسوخ من قالب، لم يُراجع قط، بلا مالكين." } },
      { text: { en: "FX exposure on a large imported cost base with no instruments and repeated margin damage.", ar: "تعرض عملات على قاعدة تكاليف مستوردة كبيرة بلا أدوات ومع أضرار متكررة بالهامش." } },
      { text: { en: "The last serious incident had no post-mortem — nothing changed.", ar: "آخر حادث جسيم بلا مراجعة لاحقة — لم يتغير شيء." } },
    ],
  },
]
