/** IAS 39 — Financial Instruments: Recognition and Measurement (legacy) */

import type { Standard } from "../types"

export const IAS_39: Standard = {
  code: "IAS 39",
  title: { en: "Financial Instruments: Recognition and Measurement (legacy)", ar: "الأدوات المالية: الاعتراف والقياس (القديم)" },
  topic: "instruments",
  effective: { en: "Superseded by IFRS 9 for annual periods starting on/after 1 Jan 2018", ar: "ألغي بـ IFRS 9 للفترات التي تبدأ في ١ يناير ٢٠١٨ أو بعده" },
  replaces: { en: "Still cited for unamortised-cost comparisons and hedge docs pre-IFRS 9", ar: "يشار إليه للمقارنات التاريخية ووثائق التغطية قبل IFRS 9" },
  blocks: [
    { kind: "h", text: { en: "Why a 'dead' standard still matters", ar: "لماذا يهم معيار «ميت» بعد" } },
    {
      kind: "p",
      text: {
        en: "IFRS 9 replaced IAS 39 for periods starting on/after 1 Jan 2018 — but IAS 39 lives on in three places: (1) the MACRO-HEDGING carve-out (portfolio hedge of interest-rate risk stays on IAS 39 until the IASB finishes its project), (2) comparative history and transition bridges (first-time adopters sometimes meet old-classification vocabulary), and (3) EXAM CROSSOVERS — SBR/AAA questions ask 'how did IFRS 9 change…', and the answer is always a contrast against the IAS 39 world.",
        ar: "أبدله IFRS 9 للفترات التي تبدأ في ١ يناير ٢٠١٨ — لكنه يبقى حيًا في ثلاثة مواضع: (١) استثناء التغطية الكلية (تغطية محفظة مخاطر الفائدة تظل على IAS 39 حتى ينجز المجلس مشروعه)، (٢) جسور التاريخ والمقارنات الانتقالية، (٣) أسئلة المقارنة الامتحانية «كيف غيّر IFRS 9…» وجوابها دائمًا مقابلة مع عالم IAS 39.",
      },
    },
    { kind: "h", text: { en: "The old four-category world", ar: "عالم الفئات الأربع القديم" } },
    {
      kind: "tree",
      root: { en: "IAS 39 classification (by INTENT & ability at initial recognition)", ar: "تصنيف IAS 39 (بالنية والقدرة عند النشأة)" },
      branches: [
        {
          when: { en: "FAIR VALUE THROUGH PROFIT OR LOSS — held for trading + derivatives + the FV option election", ar: "بالعادلة عبر الأرباح — للمتاجرة + المشتقات + انتخاب العادلة" },
          then: { en: "FVTPL; held-for-trading = acquired for selling short-term", ar: "عادلة بالأرباح؛ والمتاجرة تعني الشراء لبيع قريب" },
        },
        {
          when: { en: "HELD TO MATURITY — debt with the POSITIVE INTENT AND ABILITY to hold to maturity", ar: "الاحتفاظ حتى الاستحقاق — دين بنية وقدرة مؤكدتين" },
          then: { en: "AMORTISED COST — but the 'tainting' rules punished sales (the whole category was reclassified out on breach)", ar: "التكلفة المدمجة — وقواعد «التلوث» كانت تعاقب البيع (تخرج الفئة كلها عند الإخلال)", red: true },
        },
        {
          when: { en: "LOANS AND RECEIVABLES — not quoted, generated by the entity", ar: "قروض ومدينون — غير مقتبسة وناشئة من تعامل المنشأة" },
          then: { en: "AMORTISED COST", ar: "التكلفة المدمجة", red: true },
        },
        {
          when: { en: "AVAILABLE FOR SALE — the residual bucket for everything else", ar: "متاح للبيع — الحاوية المتبقية لكل ما سواها" },
          then: { en: "FAIR VALUE THROUGH OCI — gains/losses parked in equity, RECYCLED to P&L on sale (the old FVOCI)", ar: "عادلة عبر الدخل الشامل — فروق تنتظر في حقوق الملكية وتعاد للأرباح عند البيع", red: true },
        },
      ],
    },
    {
      kind: "p",
      text: {
        en: "The critique that killed it: classification depended on INTENT (an unreliable, easily-managed driver) — an identical bond could sit in three different buckets in two banks. IFRS 9 replaced intent with the two OBJECTIVE tests (business model + SPPI) — this contrast sentence is worth a whole exam part.",
        ar: "النقد الذي قتله: كان التصنيف معتمدًا على النية (محرّك غير موثوق يسير بالتلاعب) — فالسند ذاته قد يسكن ثلاث حاويات في بنكين. فأبدله IFRS 9 بالاختبارين الموضوعيين (النموذج + SPPI) — وهذه الجملة المقابلة تستهلك جزءًا امتحانيًا كاملًا.",
      },
    },
    { kind: "h", text: { en: "The incurred-loss impairment world", ar: "عالم الخسائر الواقعة" } },
    {
      kind: "list",
      items: [
        { en: "IAS 39 waited for a TRIGGER EVENT (objective evidence of impairment: default, bankruptcy, disappearance of an active market) before booking ANY loss", ar: "انتظر IAS 39 حدثًا محفزًا (دليل موضوعي: تعثر، إعسار، اختفاء سوق نشطة) قبل حجز أي خسارة" },
        { en: "The loss = the difference between the carrying amount and the PV of expected (contractual) cash flows, discounted at the ORIGINAL EIR", ar: "الخسارة = الفرق بين الدفترية والقيمة الحالية للتدفقات التعاقدية المتوقعة بالفائدة الفعلية الأصلية" },
        { en: "Interest on impaired assets: the EIR applied to the NET carrying amount (the old 'reduced yield')", ar: "فائدة الأصول المعسرة: بالفائدة الأصلية على الدفترية الصافية" },
        { en: "The crisis lesson: waiting for evidence meant banks booked losses YEARS too late — ECL was the regulatory answer", ar: "درس الأزمة: انتظار الدليل أخّر الاعتراف سنوات — فكانت الخسائر المتوقعة جواب التنظيم" },
      ],
    },
    { kind: "h", text: { en: "Embedded derivatives & the old hedge rules", ar: "المشتقات المضمنة وقواعد التغطية القديمة" } },
    {
      kind: "list",
      items: [
        { en: "IAS 39 forced BIFURCATION: separate every embedded derivative from the host unless 'closely related' (the old long lists of close-relationship tests)", ar: "ألزم IAS 39 الفصل: افصل كل مشتق مضمّن عن المضيف إلا إذا كان «وثيق الصلة» (قوائم الاختبارات الطويلة القديمة)" },
        { en: "IFRS 9 replaced bifurcation with the SPPI whole-hybrid FVTPL answer — only financial assets with non-closely-related features get separated, and most hybrids go WHOLE to FVTPL", ar: "أبدله IFRS 9 بجواب الهجين الكامل — فلا فصل إلا لميزات محددة، ومعظم الهجين يذهب كله إلى FVTPL" },
        { en: "Old hedge effectiveness: the 80–125% bright line (prospective & retrospective tests) — replaced by the qualitative economic-relationship requirement", ar: "فاعلية التغطية القديمة: حد ٨٠–١٢٥٪ — أبدلته العلاقة الاقتصادية النوعية" },
        { en: "Fair-value-option election (irrevocable at inception to remove an accounting mismatch) — retained by IFRS 9 in a refined form", ar: "انتخاب العادلة (لا رجعة فيه لإزالة عدم التماثل) — أبقاه IFRS 9 بصياغة منقحة" },
      ],
    },
    { kind: "h", text: { en: "Where IAS 39 still runs today", ar: "حيث يعمل IAS 39 اليوم" } },
    {
      kind: "p",
      text: {
        en: "The macro-hedging carve-out (IFRS 9.2.6): an entity may apply IAS 39's fair-value hedge accounting to a PORTFOLIO hedge of interest-rate risk — the last big IAS 9→ unfinished project. Insurers' temporary exemption expired (2023 — IFRS 17 took over). First-time adopters under IFRS 1 find IAS 39 references in transition-date analyses for pre-2018 comparatives.",
        ar: "استثناء التغطية الكلية (IFRS 9.2.6): يجوز تطبيق محاسبة تغطية القيمة العادلة وفق IAS 39 على تغطية محفظة لمخاطر الفائدة — آخر مشاريع المجلس غير المنجزة. وانتهى إعفاء شركات التأمين المؤقت (٢٠٢٣ — تولى IFRS 17). ويجد المتبنون الأوائل إشارات IAS 39 في تحليلات المقارنات السابقة لـ٢٠١٨.",
      },
    },
    {
      kind: "formula",
      title: { en: "The old-vs-new cheat table", ar: "جدول الغش القديم-الجديد" },
      lines: [
        { en: "Classification: intent (IAS 39) → business model + SPPI (IFRS 9)", ar: "التصنيف: النية ← النموذج الائتماني + SPPI" },
        { en: "Categories: 4 (FVTPL/HTM/L&R/AFS) → 3 (AC/FVOCI/FVTPL) + equity FVOCI election", ar: "الفئات: ٤ ← ٣ مع انتخاب ملكية FVOCI" },
        { en: "Impairment: incurred-loss trigger → 3-stage ECL (12-month / lifetime / credit-impaired)", ar: "الانخفاض: محفز الخسارة الواقعة ← خسائر متوقعة ثلاثية المراحل" },
        { en: "Embedded derivatives: bifurcation-by-default → SPPI whole-hybrid test", ar: "المضمنة: الفصل افتراضيًا ← اختبار الهجين الكامل" },
        { en: "Hedging: 80–125% bright line → economic-relationship judgement + rebalancing", ar: "التغطية: حد ٨٠–١٢٥٪ ← حكم العلاقة الاقتصادية مع إعادة الموازنة" },
      ],
    },
    {
      kind: "tip",
      text: {
        en: "When the exam says 'explain how IFRS 9 changed the accounting', answer in PAIRS (old rule → new rule) across classification, impairment, embedded derivatives and hedging — the contrast table IS the marking scheme.",
        ar: "إذا قال الامتحان «اشرح كيف غيّر IFRS 9 المحاسبة» فأجب بأزواج (قاعدة قديمة ← جديدة) عبر التصنيف والانخفاض والمضمنة والتغطية — فجدول المقابلة هو مخطط الدرجات ذاته.",
      },
    },
    {
      kind: "tip",
      text: {
        en: "The AFS bucket's OCI-parking with recycling is the single most contrasted IFRS 9 change: today's FVOCI-debt recycles ONLY through derecognition, and FVOCI-equity never recycles — candidates who answer 'recycled on disposal' for EQUITY still earn zero.",
        ar: "حاوية «متاح للبيع» بتخزين الدخل الشامل وإعادة تدويرها أشد ما يقابل في IFRS 9: فديون FVOCI اليوم تعاد فقط عند الاستبعاد، وملكية FVOCI لا تعاد أبدًا — ومن يجيب «تدور عند البيع» عن الملكية يظل بلا درجة.",
      },
    },
    {
      kind: "note",
      text: {
        en: "Do not mix: the 'effective interest' label exists in both regimes; the difference is in classification and impairment — not in the interest arithmetic itself.",
        ar: "لا تخلط: تسمية «فائدة فعلية» موجودة في العهدين؛ الفرق في التصنيف والانخفاض لا في حساب الفائدة ذاته.",
      },
    },
  ],
}
