/** IAS 39 — Financial Instruments: Recognition and Measurement (legacy) */

import type { Standard } from "../types"

export const IAS_39: Standard = {
  code: "IAS 39",
  title: { en: "Financial Instruments: Recognition and Measurement (legacy)", ar: "الأدوات المالية: الاعتراف والقياس (القديم)" },
  topic: "instruments",
  effective: { en: "Superseded by IFRS 9 for annual periods starting on/after 1 Jan 2018", ar: "ألغي بـ IFRS 9 للفترات التي تبدأ في ١ يناير ٢٠١٨ أو بعده" },
  replaces: { en: "Still cited for unamortised-cost comparisons and hedge docs pre-IFRS 9", ar: "يشار إليه للمقارنات التاريخية ووثائق التغطية قبل IFRS 9" },
  blocks: [
    { kind: "h", text: { en: "Why a 'dead' standard still matters", ar: "لماذا يهم معيار «ميت» بعد" } },
    {
      kind: "p",
      text: {
        en: "IFRS 9 replaced IAS 39 for periods starting on/after 1 Jan 2018 — but IAS 39 lives on in three places: (1) the MACRO-HEDGING carve-out (portfolio hedge of interest-rate risk stays on IAS 39 until the IASB finishes its project), (2) comparative history and transition bridges (first-time adopters sometimes meet old-classification vocabulary), and (3) EXAM CROSSOVERS — SBR/AAA questions ask 'how did IFRS 9 change…', and the answer is always a contrast against the IAS 39 world. Its four categories, its incurred-loss trigger and its 80–125% line are the 'before' photograph every IFRS 9 'after' is marked against.",
        ar: "أبدله IFRS 9 للفترات التي تبدأ في ١ يناير ٢٠١٨ — لكنه يبقى حيًا في ثلاثة مواضع: (١) استثناء التغطية الكلية (تغطية محفظة مخاطر الفائدة تظل على IAS 39 حتى ينجز المجلس مشروعه)، (٢) جسور التاريخ والمقارنات الانتقالية، (٣) أسئلة المقارنة الامتحانية «كيف غيّر IFRS 9…» وجوابها دائمًا مقابلة مع عالم IAS 39. ففئاته الأربع ومحفز خسائره الواقعة وحدوده ٨٠–١٢٥٪ هي «صورة القبل» التي تُقاس عليها كل «صورة بعد» لـIFRS 9.",
      },
    },
    { kind: "h", text: { en: "Scope & where it still runs", ar: "النطاق وحيث ما يزال يعمل" } },
    {
      kind: "p",
      text: {
        en: "Where an entity applies IFRS 9, IAS 39's classification, impairment and micro-hedge rules are gone — but IFRS 9 itself carries a survival clause: entities MAY continue to apply IAS 39's fair-value-hedge accounting for a PORTFOLIO hedge of interest-rate risk (the macro-hedging carve-out), because IFRS 9's own machinery was never finished for that job. Insurers' temporary exemption expired with IFRS 17 (2023). Everything else of IAS 39 you meet today is history: comparatives, transition-date analysis, and the vocabulary of pre-2018 audit files.",
        ar: "حيث تطبق المنشأة IFRS 9 فقد زالت قواعد IAS 39 للتصنيف والانخفاض والتغطية الدقيقة — لكن IFRS 9 ذاته يحمل بند بقاء: يجوز الاستمرار في محاسبة تغطية القيمة العادلة وفق IAS 39 لتغطية محفظة لمخاطر الفائدة (استثناء التغطية الكلية)، لأن آلة IFRS 9 لم تُكمل لهذه المهمة قط. وانتهى الإعفاء المؤقت لشركات التأمين بقدوم IFRS 17 (٢٠٢٣). وكل ما تبقى من IAS 39 اليوم تاريخ: مقارنات، وتحليلات تاريخ انتقال، ومفردات ملفات تدقيق ما قبل ٢٠١٨.",
      },
    },
    { kind: "h", text: { en: "The old four-category world", ar: "عالم الفئات الأربع القديم" } },
    {
      kind: "tree",
      root: { en: "IAS 39 classification (by INTENT & ability at initial recognition)", ar: "تصنيف IAS 39 (بالنية والقدرة عند النشأة)" },
      branches: [
        {
          when: { en: "FAIR VALUE THROUGH PROFIT OR LOSS — held for trading + derivatives + the FV option election", ar: "بالعادلة عبر الأرباح — للمتاجرة + المشتقات + انتخاب العادلة" },
          then: { en: "FVTPL; held-for-trading = acquired for selling short-term", ar: "عادلة بالأرباح؛ والمتاجرة تعني الشراء لبيع قريب" },
        },
        {
          when: { en: "HELD TO MATURITY — debt with the POSITIVE INTENT AND ABILITY to hold to maturity", ar: "الاحتفاظ حتى الاستحقاق — دين بنية وقدرة مؤكدتين" },
          then: { en: "AMORTISED COST — but the 'tainting' rules punished sales (the whole category was reclassified out on breach)", ar: "التكلفة المطفأة — وقواعد «التلوث» كانت تعاقب البيع (تخرج الفئة كلها عند الإخلال)", red: true },
        },
        {
          when: { en: "LOANS AND RECEIVABLES — not quoted, generated by the entity", ar: "قروض ومدينون — غير مقتبسة وناشئة من تعامل المنشأة" },
          then: { en: "AMORTISED COST", ar: "التكلفة المطفأة", red: true },
        },
        {
          when: { en: "AVAILABLE FOR SALE — the residual bucket for everything else", ar: "متاح للبيع — الحاوية المتبقية لكل ما سواها" },
          then: { en: "FAIR VALUE THROUGH EQUITY — gains/losses parked in the AFS reserve, RECYCLED to P&L on sale (the old FVOCI)", ar: "عادلة عبر حقوق الملكية — فروق تنتظر في احتياطي المتاح للبيع وتعاد للأرباح عند البيع", red: true },
        },
      ],
    },
    {
      kind: "p",
      text: {
        en: "The critique that killed it: classification depended on INTENT (an unreliable, easily-managed driver) — an identical bond could sit in three different buckets in two banks, and moving a security from AFS to HTM could re-gear a whole balance sheet. IFRS 9 replaced intent with two OBJECTIVE tests (business model + SPPI) — this contrast sentence is worth a whole exam part. Note the geography: L&R and HTM at amortised cost, AFS with FV through equity and recycling, FVTPL with everything in P&L — four buckets, three different earnings stories.",
        ar: "النقد الذي قتله: كان التصنيف معتمدًا على النية (محرّك غير موثوق سهل التلاعب به) — فالسند ذاته قد يسكن ثلاث حاويات في بنكين، ونقل ورقة من المتاح للبيع إلى الاحتفاظ حتى الاستحقاق يعيد تعشيق ميزانية كاملة. فأبدله IFRS 9 بالاختبارين الموضوعيين (نموذج الأعمال + SPPI) — وهذه الجملة المقابلة تستهلك جزءًا امتحانيًا كاملًا. ولاحظ الجغرافيا: القروض والمدينون والاحتفاظ بالتكلفة المطفأة، والمتاح للبيع بعادلة عبر حقوق الملكية مع التدوير، وFVTPL بكل شيء في الأرباح — أربع حاويات وثلاث حكايات أرباح مختلفة.",
      },
    },
    { kind: "h", text: { en: "Held to maturity & the tainting rules", ar: "الاحتفاظ حتى الاستحقاق وقواعد التلوث" } },
    {
      kind: "p",
      text: {
        en: "HTM classification demanded POSITIVE INTENT AND ABILITY to hold — and the tainting rules policed it brutally: selling more than an insignificant amount before maturity (other than the narrow exceptions) forced the ENTIRE HTM portfolio out of amortised cost, into AFS or FVTPL, and banned the entity from HTM for the following two years. A liquidity-driven sale of one bond could therefore re-price a whole sovereign book — the rule that made banks avoid the category altogether once the crisis started.",
        ar: "تطلب تصنيف الاحتفاظ حتى الاستحقاق نيةً وقدرة مؤكدتين — وتراقبه قواعد التلوث بوحشية: بيع قدر غير ضئيل قبل الاستحقاق (خارج الاستثناءات الضيقة) كان يجبر محفظة HTM كلها خارج التكلفة المطفأة إلى المتاح للبيع أو FVTPL، ويحظر على المنشأة الفئة سنتين تاليتين. فبيع سند واحد لدواعي السيولة كان يعيد تسعير دفتر سيادي كاملًا — القاعدة التي جعلت البنوك تهجر الفئة جملة عند اشتعال الأزمة.",
      },
    },
    {
      kind: "list",
      items: [
        { en: "Sold CLOSE to maturity (rate moves no longer move the value materially)", ar: "بيع قريب من الاستحقاق (فتحركات المعدل لم تعد تحرك القيمة جوهريًا)" },
        { en: "Sold after collecting SUBSTANTIALLY ALL of the principal", ar: "بيع بعد تحصيل جوهر الأصل كله" },
        { en: "Sale forced by an ISOLATED event beyond the entity's control that could not be anticipated and will not recur (e.g. a country's tax law removing tax-exempt status)", ar: "بيع أجبره حدث معزول خارج سيطرة المنشأة لم يكن متوقعًا ولن يتكرر (كإلغاء قانون دولة إعفاءً ضريبيًا)" },
        { en: "Everything else tainted the portfolio — two-year ban from HTM follows", ar: "ما عدا ذلك لوّث المحفظة — ويتبعه حظر سنتين عن الفئة" },
      ],
    },
    { kind: "h", text: { en: "Trading & the fair value option", ar: "المتاجرة وانتخاب العادلة" } },
    {
      kind: "p",
      text: {
        en: "Held-for-trading meant acquired PRINCIPALLY for selling in the near term — derivatives were automatically in, however long the entity intended to keep them. The FAIR VALUE OPTION let the entity irrevocably designate any financial asset or liability at FVTPL on day one, but only through two gates: the designation eliminates or reduces a measurement or recognition INCONSISTENCY (an accounting mismatch), or a group of financial assets/liabilities/both is managed and its performance evaluated on a fair value basis, documented in the entity's risk management. Elections could not be given or withdrawn one instrument at a time.",
        ar: "«المتاجرة» تعني الاقتناء أساسًا للبيع القريب — والمشتقات داخلة تلقائيًا مهما طالت نية الاحتفاظ. وسمح «انتخاب العادلة» بتسمية أي أصل أو التزام مالي بـFVTPL بلا رجعة في اليوم الأول، لكن عبر بوابتين: أن تزيل التسمية أو تقلص عدم اتساقًا في القياس أو الاعتراف (عدم تماثل محاسبي)، أو أن تُدار مجموعة أدوات ويقاس أداؤها على أساس القيمة العادلة، بتوثيقٍ في إدارة مخاطر المنشأة. ولا يجوز منح الانتخاب أو سحبه أداةً أداة.",
      },
    },
    { kind: "h", text: { en: "Initial & subsequent measurement (legacy)", ar: "القياس الأولي واللاحق (قديمًا)" } },
    {
      kind: "p",
      text: {
        en: "Initial measurement was fair value plus transaction costs for everything except FVTPL (costs expensed) — the same day-one discipline IFRS 9 kept. Subsequent measurement followed the category: amortised cost (HTM, L&R), fair value with changes in equity (AFS — with equity instruments' dividends in P&L and no impairment recycling), fair value through P&L (trading, derivatives, elected FVO). Items with no reliable fair value (unquoted equities and their derivatives payable only on such equities) ran at COST with an impairment test — the escape hatch IFRS 9 abolished.",
        ar: "كان القياس الأولي قيمة عادلة زائد تكاليف المعاملة لكل شيء عدا FVTPL (تُصرف التكاليف) — انضباط اليوم الأول ذاته الذي أبقاه IFRS 9. ويتبع القياس اللاحق الفئة: تكلفة مطفاة (HTM والقروض والمدينون)، أو عادلة بتغيرات في حقوق الملكية (المتاح للبيع — وتوزيعات الملكيات فيه بالأرباح بلا تدوير انخفاض)، أو عادلة بالأرباح (المتاجرة والمشتقات والمنتقاة). والبنود التي لا عادلة موثوقة لها (ملكيات غير مقتبسة ومشتقات تُسدد بمثلها فقط) سارت بالتكلفة مع اختبار انخفاض — المخرج الذي ألغاه IFRS 9.",
      },
    },
    { kind: "h", text: { en: "The legacy amortised-cost entries", ar: "قيود التكلفة المطفأة القديمة" } },
    {
      kind: "journal",
      title: { en: "The same bond as IFRS 9's example — the EIR arithmetic never changed (967 carrying, EIR 5.77%)", ar: "السند ذاته في مثال IFRS 9 — حساب الفائدة الفعلية لم يتغير قط (دفترية ٩٦٧ وفائدة فعلية ٥٫٧٧٪)" },
      rows: [
        { dr: { en: "HTM / L&R investment 967", ar: "استثمار احتفاظ حتى الاستحقاق / قروض ومدينون ٩٦٧" }, cr: { en: "Cash 967 (957 price + 10 costs)", ar: "نقد ٩٦٧ (سعر ٩٥٧ + تكاليف ١٠)" }, red: true },
        { dr: { en: "Cash 50 (coupon)", ar: "نقد ٥٠ (كوبون)" }, cr: { en: "Interest income (EIR) 55.8", ar: "إيراد فائدة (فعلي) ٥٥٫٨" } },
        { dr: { en: "Investment (accretion) 5.8", ar: "الاستثمار (تضخم) ٥٫٨" }, cr: { en: "— — carrying to 972.8", ar: "— — الدفترية إلى ٩٧٢٫٨" } },
      ],
    },
    { kind: "h", text: { en: "Available-for-sale & the recycling world", ar: "متاح للبيع وعالم التدوير" } },
    {
      kind: "p",
      text: {
        en: "AFS was the catch-all with a split personality: fair value on the balance sheet, but the FV delta parked in equity (the AFS reserve) until sale, when it RECYCLED to P&L. Debt AFS carried its interest through P&L at EIR; equity AFS took only dividends to P&L. Impairment forced the accumulated loss out of equity and into P&L — a recycling event the impairment rules controlled. This bucket-plus-reserve machinery is what IFRS 9 rebuilt as FVOCI-debt (recycling kept) and killed for equity (no recycling ever).",
        ar: "كان المتاح للبيع الحاوية الجامعة بشخصية منشطرة: قيمة عادلة في الميزانية، لكن فرقها يُركن في حقوق الملكية (احتياطي المتاح للبيع) حتى البيع فيعاد تدويره إلى الأرباح. وحمل دين المتاح للبيع فوائده بالأرباح بالفائدة الفعلية؛ ولم يأخذ ملكُه سوى التوزيعات. والانخفاض كان يجبر الخسارة المتراكمة خارج حقوق الملكية إلى الأرباح — واقعة تدوير تحكمها قواعد الانخفاض. وهذه الآلة (حاوية + احتياطي) هي ما أعاد IFRS 9 بناءه كديون FVOCI (بإبقاء التدوير) وقتله للملكية (بلا تدوير أبدًا).",
      },
    },
    {
      kind: "journal",
      title: { en: "AFS lifecycle — buy 500, FV to 540, sell 560: the reserve recycles", ar: "دورة المتاح للبيع — شراء ٥٠٠، العادلة إلى ٥٤٠، بيع ٥٦٠: الاحتياطي يعاد تدويره" },
      rows: [
        { dr: { en: "AFS investment 500", ar: "استثمار متاح للبيع ٥٠٠" }, cr: { en: "Cash 500", ar: "نقد ٥٠٠" } },
        { dr: { en: "AFS investment 40", ar: "استثمار متاح للبيع ٤٠" }, cr: { en: "AFS reserve (equity) 40", ar: "احتياطي المتاح للبيع (حقوق ملكية) ٤٠" }, red: true },
        { dr: { en: "Cash 560", ar: "نقد ٥٦٠" }, cr: { en: "AFS investment 540", ar: "استثمار متاح للبيع ٥٤٠" } },
        { cr: { en: "Gain on sale (P&L) 20", ar: "ربح بيع (بالأرباح) ٢٠" } },
        { dr: { en: "AFS reserve 40", ar: "احتياطي المتاح للبيع ٤٠" }, cr: { en: "Gain on sale (P&L) — RECYCLED 40", ar: "ربح بيع (بالأرباح) — معاد تدويره ٤٠" }, red: true },
      ],
    },
    { kind: "h", text: { en: "The incurred-loss impairment world", ar: "عالم الخسائر الواقعة" } },
    {
      kind: "list",
      items: [
        { en: "IAS 39 waited for a TRIGGER EVENT (objective evidence of impairment: default, bankruptcy, disappearance of an active market) before booking ANY loss", ar: "انتظر IAS 39 حدثًا محفزًا (دليل موضوعي: تعثر، إعسار، اختفاء سوق نشطة) قبل حجز أي خسارة" },
        { en: "The loss = the difference between the carrying amount and the PV of expected (contractual) cash flows, discounted at the ORIGINAL EIR", ar: "الخسارة = الفرق بين الدفترية والقيمة الحالية للتدفقات التعاقدية المتوقعة بالفائدة الفعلية الأصلية" },
        { en: "Interest on impaired assets: the EIR applied to the NET carrying amount (the old 'reduced yield')", ar: "فائدة الأصول المعسرة: بالفائدة الأصلية على الدفترية الصافية" },
        { en: "The crisis lesson: waiting for evidence meant banks booked losses YEARS too late — ECL was the regulatory answer", ar: "درس الأزمة: انتظار الدليل أخّر الاعتراف سنوات — فكانت الخسائر المتوقعة جواب التنظيم" },
      ],
    },
    {
      kind: "tree",
      root: { en: "Is there OBJECTIVE EVIDENCE of impairment from a PAST event?", ar: "هل ثمة دليل موضوعي على انخفاض من حدث ماضٍ؟" },
      branches: [
        {
          when: { en: "YES — borrower significant financial difficulty, probable default/bankruptcy, disappearance of an active market, concession granted", ar: "نعم — صعوبات مالية جوهرية للمقترض، تعثر أو إعسار مرجح، اختفاء سوق نشطة، تنازل ممنوح" },
          then: { en: "Impairment loss = carrying − PV (re-estimated cash flows at ORIGINAL EIR); AFS losses also leave equity for P&L", ar: "خسارة الانخفاض = الدفترية − القيمة الحالية (التدفقات المعاد تقديرها بالفائدة الأصلية)؛ وخسائر المتاح للبيع تغادر حقوق الملكية إلى الأرباح أيضًا", red: true },
        },
        {
          when: { en: "NO — merely a fall in fair value from rate moves or market sentiment", ar: "لا — مجرد هبوط عادلة بحركات معدلات أو مزاج سوق" },
          then: { en: "NO impairment: AFS stays in equity; HTM/L&R carry on at cost — the waiting game that delayed the crisis losses", ar: "لا انخفاض: يبقى المتاح للبيع في حقوق الملكية ويواصل HTM والقروض بالتكلفة — لعبة الانتظار التي أخّرت خسائر الأزمة", red: true },
        },
      ],
    },
    {
      kind: "formula",
      title: { en: "The incurred-loss engine", ar: "محرك الخسائر الواقعة" },
      lines: [
        { en: "Impairment loss = carrying amount − PV (re-estimated contractual cash flows at the ORIGINAL EIR)", ar: "خسارة الانخفاض = القيمة الدفترية − القيمة الحالية (التدفقات التعاقدية المعاد تقديرها بالفائدة الفعلية الأصلية)" },
        { en: "The discount rate NEVER changes — original EIR at initial recognition, for better and for worse", ar: "معدل الخصم لا يتغير أبدًا — الفائدة الفعلية الأصلية عند الاعتراف الأولي، في الإساءة والإحسان" },
        { en: "Post-impairment interest = net carrying × original EIR (the reduced yield)", ar: "فائدة ما بعد الانخفاض = الدفترية الصافية × الفائدة الأصلية (العائد المخفض)" },
        { en: "Reversal: when the increase relates objectively to an event after the impairment was recognised (debt → P&L; equity AFS → back through equity)", ar: "الاسترداد: إذا تعلق التحسن موضوعيًا بحدث لاحق للاعتراف بالانخفاض (الدين ← الأرباح؛ وملكية المتاح للبيع ← عبر حقوق الملكية)" },
      ],
    },
    {
      kind: "example",
      title: { en: "An incurred loss, the old way", ar: "خسارة واقعة على الطريقة القديمة" },
      lines: [
        { en: "Loan carrying 1,000; trigger event: the borrower's bankruptcy filing; only 900 is now expected, in exactly 2 years; original EIR 10%", ar: "قرض دفتريته ١٬٠٠٠؛ والحدث المحفز: إفلاس المقترض؛ والمتوقع الآن ٩٠٠ فقط بعد سنتين بالضبط؛ والفائدة الأصلية ١٠٪" },
        { en: "PV = 900 ÷ 1.10² = 900 ÷ 1.21 = 743.8 → impairment loss = 1,000 − 743.8 = 256.2", ar: "القيمة الحالية = ٩٠٠ ÷ ١٫١٠² = ٩٠٠ ÷ ١٫٢١ = ٧٤٣٫٨ ← خسارة الانخفاض = ١٬٠٠٠ − ٧٤٣٫٨ = ٢٥٦٫٢" },
        { en: "Next year interest = 743.8 × 10% = 74.4 on the NET (year 2 adds 81.8 → the loan accretes exactly to 900 received)", ar: "فائدة السنة التالية = ٧٤٣٫٨ × ١٠٪ = ٧٤٫٤ على الصافي (وتضيف السنة الثانية ٨١٫٨ فينمو القرض إلى ٩٠٠ المستلمة بالضبط)" },
        { en: "Under IFRS 9 the SAME loan books ECL from day one — the contrast is the whole answer", ar: "وتحت IFRS 9 يحجز القرض ذاته خسائره المتوقعة من اليوم الأول — والمقابلة هي الجواب كله" },
      ],
    },
    {
      kind: "journal",
      title: { en: "Incurred-loss entries (numbers above)", ar: "قيود الخسائر الواقعة (بالأرقام أعلاه)" },
      rows: [
        { dr: { en: "Impairment loss (P&L) 256.2", ar: "خسارة انخفاض (بالأرباح) ٢٥٦٫٢" }, cr: { en: "Loan / impairment allowance 256.2", ar: "القرض / مخصص الانخفاض ٢٥٦٫٢" }, red: true },
        { dr: { en: "Loan (accretion on the net) 74.4", ar: "القرض (تضخم على الصافي) ٧٤٫٤" }, cr: { en: "Interest income (reduced yield) 74.4", ar: "إيراد فائدة (العائد المخفض) ٧٤٫٤" } },
      ],
    },
    { kind: "h", text: { en: "AFS impairment — the OCI shuffle", ar: "انخفاض المتاح للبيع — خفة الدخل الشامل" } },
    {
      kind: "p",
      text: {
        en: "An AFS debt instrument's fair-value dip sat harmlessly in equity — until objective evidence of impairment arrived, when the CUMULATIVE loss (carrying − PV at original EIR) was reclassified from equity to P&L, even though most of it was already sitting in the AFS reserve. Reversals for debt went back through P&L; for equity instruments, impairment went to P&L but reversals could NOT — they returned to equity. The examiner's version: 'the AFS reserve is a waiting room, and impairment is the door to P&L' — know which assets may walk back out of it.",
        ar: "هبوط عادلة دين المتاح للبيع جلس في حقوق الملكية بلا ضرر — حتى يبلغ دليل الانخفاض الموضوعي، فيعاد تصنيف الخسارة التراكمية (الدفترية − القيمة الحالية بالفائدة الأصلية) من حقوق الملكية إلى الأرباح، ولو كان جلها جالسًا في احتياطي المتاح للبيع أصلًا. وتعود استردادات الدين عبر الأرباح؛ أما ملكيات المتاح للبيع فيذهب انخفاضها إلى الأرباح ولا يجوز رجوعها — بل تعود إلى حقوق الملكية. وصيغة الممتحن: «احتياطي المتاح للبيع غرفة انتظار، والانخفاض بابها إلى الأرباح» — فاعرف أي الأصول يجوز لها الخروج عائدة.",
      },
    },
    {
      kind: "example",
      title: { en: "The AFS reserve door — debt edition", ar: "باب احتياطي المتاح للبيع — نسخة الديون" },
      lines: [
        { en: "AFS bond: carrying 1,000 (its fair value, with a 70 loss already parked in the AFS reserve)", ar: "سند متاح للبيع: دفتريته ١٬٠٠٠ (وهي عادلته، وخسارة ٧٠ جالسة أصلًا في الاحتياطي)" },
        { en: "Impairment evidence arrives; PV of re-estimated flows = 900 → cumulative loss 100, not 70", ar: "يبلغ دليل الانخفاض؛ والقيمة الحالية للتدفقات المعاد تقديرها ٩٠٠ ← خسارة تراكمية ١٠٠ لا ٧٠" },
        { en: "Dr Impairment loss (P&L) 100 / Cr AFS investment 100 — of which 70 vacates the reserve and 30 marks the instrument further down", ar: "مدين خسارة انخفاض (بالأرباح) ١٠٠ / دائن الاستثمار ١٠٠ — منها ٧٠ تُخلي الاحتياطي و٣٠ تخفض الأداة زيادة" },
        { en: "A later objective recovery (e.g. upgraded to performing): reverse through P&L, capped at the amortised cost the carrying would have reached had no impairment occurred", ar: "وتحسن موضوعي لاحق (كترقية إلى سليم): يُسترد عبر الأرباح بحد أقصى التكلفة المطفأة التي كانت بلغتها الدفترية لو لم يقع الانخفاض" },
      ],
    },
    { kind: "h", text: { en: "Embedded derivatives & bifurcation", ar: "المشتقات المضمنة والفصل" } },
    {
      kind: "list",
      items: [
        { en: "IAS 39 forced BIFURCATION: separate every embedded derivative from the host unless 'closely related' (the old long lists of close-relationship tests)", ar: "ألزم IAS 39 الفصل: افصل كل مشتق مضمّن عن المضيف إلا إذا كان «وثيق الصلة» (قوائم الاختبارات الطويلة القديمة)" },
        { en: "IFRS 9 replaced bifurcation with the SPPI whole-hybrid FVTPL answer for financial ASSETS — only liability/non-financial hosts keep separation", ar: "أبدله IFRS 9 بجواب الهجين الكامل بـFVTPL في الأصول المالية — ولا يبقى الفصل إلا لمضيفات الالتزامات وغير المالية" },
        { en: "Old hedge effectiveness: the 80–125% bright line (prospective & retrospective tests) — replaced by the qualitative economic-relationship requirement", ar: "فاعلية التغطية القديمة: حد ٨٠–١٢٥٪ — أبدلته العلاقة الاقتصادية النوعية" },
        { en: "Fair-value-option election (irrevocable at inception to remove an accounting mismatch) — retained by IFRS 9 in a refined form", ar: "انتخاب العادلة (لا رجعة فيه لإزالة عدم التماثل) — أبقاه IFRS 9 بصياغة منقحة" },
      ],
    },
    { kind: "h", text: { en: "Derecognition — risks & rewards & control", ar: "الاستبعاد — المخاطر والمنافع والسيطرة" } },
    {
      kind: "p",
      text: {
        en: "The derecognition machine IAS 39 built is the one IFRS 9 still runs, almost verbatim: first EXPIRY of rights, then the RISKS-AND-REWARDS test (substantially transferred → derecognise; retained → the proceeds are a secured borrowing), and only in the grey middle the CONTROL test — derecognise to the extent the transferee can sell the asset, keep a continuing-involvement asset for the rest. Securitisations, repos and factoring lived and died by this waterfall; exam answers still draw it today even though the label on top now reads IFRS 9.",
        ar: "آلة الاستبعاد التي بناها IAS 39 هي التي يشغلها IFRS 9 إلى اليوم، حرفيًا تقريبًا: أولًا انقضاء الحقوق، ثم اختبار المخاطر والمنافع (انتقل جوهرها ← استبعد؛ واختُزن ← المتحصلات اقتراض مضمون)، وفي المنطقة الرمادية فقط اختبار السيطرة — استبعد بحد قدرة المتنقل عليه على بيع الأصل وأبقِ أصل تورط مستمر للباقي. وعاشت التوريقات وإعادة الشراء والتخصيم وماتت بهذه الشلالة؛ ولا تزال الإجابات الامتحانية ترسمها اليوم ولو صار الاسم فوقها IFRS 9.",
      },
    },
    {
      kind: "tree",
      root: { en: "The IAS 39 pass-through waterfall (inherited by IFRS 9)", ar: "شلالة النقل في IAS 39 (ورثها IFRS 9)" },
      branches: [
        {
          when: { en: "Rights to the cash flows EXPIRED", ar: "انقضت حقوق التدفقات" },
          then: { en: "Derecognise — no further test needed", ar: "استبعد — لا حاجة لمزيد من الاختبارات", red: true },
        },
        {
          when: { en: "Risks & rewards SUBSTANTIALLY RETAINED (recourse factoring, repo at a fixed buy-back)", ar: "احتُجز جوهر المخاطر والمنافع (تخصيم بمظلة رجوع، إعادة شراء بسعر ثابت)" },
          then: { en: "SECURED BORROWING — the asset stays; proceeds are a liability that accretes to the repurchase price", ar: "اقتراض مضمون — يبقى الأصل والمتحصلات التزامًا ينمو حتى سعر إعادة الشراء", red: true },
        },
        {
          when: { en: "Risks & rewards substantially transferred → does the TRANSFEREE have the practical ability to sell?", ar: "انتقل جوهر المخاطر والمنافع ← هل للمتنقل إليه قدرة عملية على البيع؟" },
          then: { en: "Yes → DERECOGNISE fully; No → CONTINUING INVOLVEMENT: derecognise only to the extent of that ability", ar: "نعم ← استبعاد كامل؛ ولا ← تورط مستمر: استبعد بحد تلك القدرة فقط", red: true },
        },
      ],
    },
    {
      kind: "journal",
      title: { en: "Derecognition vs secured borrowing — same cash, opposite answers", ar: "الاستبعاد مقابل الاقتراض المضمون — نقد واحد وجوابان متعاكسان" },
      rows: [
        { dr: { en: "Cash 850", ar: "نقد ٨٥٠" }, cr: { en: "Receivables (carrying) 800", ar: "مدينون (الدفترية) ٨٠٠" } },
        { cr: { en: "Gain on derecognition (risks transferred) 50", ar: "ربح الاستبعاد (انتقلت المخاطر) ٥٠" }, red: true },
        { dr: { en: "Cash 700 (borrowed against receivables 800, full recourse)", ar: "نقد ٧٠٠ (مقترض مقابل مدينين ٨٠٠ بمظلة رجوع كاملة)" }, cr: { en: "Secured borrowing 700 — receivables STAY on the books", ar: "اقتراض مضمون ٧٠٠ — والمدينون يبقون في الدفاتر" }, red: true },
      ],
    },
    { kind: "h", text: { en: "The old hedge rules", ar: "قواعد التغطية القديمة" } },
    {
      kind: "list",
      items: [
        { en: "Same three hedge types (fair value, cash flow, net investment) — but effectiveness was a NUMBER, not a judgement", ar: "الأنواع الثلاثة ذاتها (عادلة، تدفقات، استثمار صافٍ) — لكن الفاعلية كانت رقمًا لا حكمًا" },
        { en: "The 80–125% bright line: the ratio of hedging-instrument change to hedged-item change had to land inside the band, prospectively AND retrospectively", ar: "حد ٨٠–١٢٥٪: كان على نسبة تغير أداة التغطية إلى تغير المغطى أن تقع داخل النطاق، مستقبليًا ورجعيًا" },
        { en: "Fail the band → discontinue immediately; no rebalancing existed — the relationship died and restart was from scratch", ar: "الخروج من النطاق ← إيقاف فوري؛ ولا إعادة موازنة كانت موجودة — تموت العلاقة ويبدأ الشروع من الصفر" },
        { en: "Hedging documentation at inception was already compulsory (the requirement IFRS 9 kept word for word)", ar: "كانت وثائق التغطية عند النشأة إلزامية أصلًا (وهو المطلب الذي أبقاه IFRS 9 حرفيًا)" },
        { en: "MACRO hedge of interest-rate risk (portfolio fair value hedge) — the carve-out that still runs on IAS 39 today", ar: "التغطية الكلية لمخاطر الفائدة (تغطية قيمة عادلة للمحفظة) — الاستثناء الذي ما يزال يعمل بـIAS 39 اليوم" },
      ],
    },
    {
      kind: "p",
      text: {
        en: "The 80–125% world had a virtue (mechanical comparability) and a vice (hedge accounting flipped on and off with the ratio), so IFRS 9 swapped the number for a judgement: an ECONOMIC RELATIONSHIP must exist, credit risk must not dominate, and the hedge ratio must match risk management — then rebalancing keeps a drifting relationship alive. In exam answers, pair the two regimes explicitly: 'IAS 39 tested a 80–125% band; IFRS 9 requires an economic relationship and allows rebalancing instead of discontinuation.'",
        ar: "كان لعالم ٨٠–١٢٥٪ فضيلة (قابلية مقارنة ميكانيكية) ورذيلة (محاسبة التغطية تشتعل وتنطفئ مع النسبة)، فأبدله IFRS 9 بحكم: يجب أن توجد علاقة اقتصادية، وألا تهيمن مخاطر الائتمان، وأن توافق نسبة التغطية إدارة المخاطر — ثم تُبقي إعادة الموازنة العلاقة المنزاحة حية. وفي الإجابات الامتحانية قارن النظامين صراحةً: «كان IAS 39 يختبر نطاق ٨٠–١٢٥٪؛ وIFRS 9 يشترط علاقة اقتصادية ويجيز إعادة الموازنة بدل الإيقاف».",
      },
    },
    {
      kind: "formula",
      title: { en: "The old-vs-new cheat table", ar: "جدول الغش القديم-الجديد" },
      lines: [
        { en: "Classification: intent (IAS 39) → business model + SPPI (IFRS 9)", ar: "التصنيف: النية ← نموذج الأعمال + SPPI" },
        { en: "Categories: 4 (FVTPL/HTM/L&R/AFS) → 3 (AC/FVOCI/FVTPL) + equity FVOCI election", ar: "الفئات: ٤ ← ٣ مع انتخاب ملكية FVOCI" },
        { en: "Impairment: incurred-loss trigger → 3-stage ECL (12-month / lifetime / credit-impaired)", ar: "الانخفاض: محفز الخسارة الواقعة ← خسائر متوقعة ثلاثية المراحل" },
        { en: "Embedded derivatives: bifurcation-by-default → SPPI whole-hybrid test", ar: "المضمنة: الفصل افتراضيًا ← اختبار الهجين الكامل" },
        { en: "Hedging: 80–125% bright line → economic-relationship judgement + rebalancing", ar: "التغطية: حد ٨٠–١٢٥٪ ← حكم العلاقة الاقتصادية مع إعادة الموازنة" },
      ],
    },
    { kind: "h", text: { en: "Where IAS 39 still runs today", ar: "حيث يعمل IAS 39 اليوم" } },
    {
      kind: "p",
      text: {
        en: "The macro-hedging carve-out (IFRS 9's own scope paragraph): an entity may apply IAS 39's fair-value hedge accounting to a PORTFOLIO hedge of interest-rate risk — the last unfinished corner of the instruments project. Insurers' temporary exemption expired (2023 — IFRS 17 took over). First-time adopters under IFRS 1 find IAS 39 references in transition-date analyses for pre-2018 comparatives, and the IFRS 9 transition reconciliations themselves are written in the old categories: 'AFS debt became FVOCI' is a sentence you must be able to finish.",
        ar: "استثناء التغطية الكلية (فقرة نطاق IFRS 9 ذاتها): يجوز تطبيق محاسبة تغطية القيمة العادلة وفق IAS 39 على تغطية محفظة لمخاطر الفائدة — آخر زاوية غير مكتملة من مشروع الأدوات. وانتهى إعفاء شركات التأمين المؤقت (٢٠٢٣ — تولى IFRS 17). ويجد المتبنون الأوائل وفق IFRS 1 إشارات IAS 39 في تحليلات تاريخ الانتقال للمقارنات السابقة لـ٢٠١٨، وتُكتب تسويات انتقال IFRS 9 ذاتها بمفردات الفئات القديمة: «صار دين المتاح للبيع FVOCI» جملة يجب أن تحسن إتمامها.",
      },
    },
    { kind: "h", text: { en: "Legacy vocabulary you still meet", ar: "مفردات قديمة ما تزال تلقاها" } },
    {
      kind: "list",
      items: [
        { en: "Tainting — the HTM sale that exiled the whole category for two years", ar: "التلوث — بيع HTM الذي نفى الفئة كلها سنتين" },
        { en: "AFS reserve — the equity waiting room where fair-value deltas sat until sale or impairment recycled them", ar: "احتياطي المتاح للبيع — غرفة الانتظار في حقوق الملكية حيث جلست فروق العادلة حتى يدورها بيع أو انخفاض" },
        { en: "Incurred-loss trigger — the objective evidence gate that held losses off the books", ar: "محفز الخسارة الواقعة — بوابة الدليل الموضوعي التي أبعدت الخسائر عن الدفاتر" },
        { en: "Bifurcation — the forced separation of embedded derivatives from their hosts", ar: "الفصل — اقتطاع المشتقات المضمنة عن مضيفاتها قسرًا" },
        { en: "The 80–125% test — the numeric hedge-effectiveness band", ar: "اختبار ٨٠–١٢٥٪ — نطاق فاعلية التغطية الرقمي" },
        { en: "L&R — loans and receivables: the unquoted, originated-at-amortised-cost category", ar: "L&R — قروض ومدينون: فئة غير المقتبس الناشئ من تعامل المنشأة بالتكلفة المطفأة" },
      ],
    },
    { kind: "h", text: { en: "The succession map", ar: "خريطة الخلافة" } },
    {
      kind: "p",
      text: {
        en: "What moved where: classification & measurement → IFRS 9 chapter 5 (two objective tests); impairment → IFRS 9 chapter 5.5 (ECL); hedge accounting → IFRS 9 chapter 6 (economic relationship); derecognition → carried over essentially verbatim; presentation → IAS 32 unchanged; disclosures → IFRS 7 rewritten around the new categories; the macro-hedge carve-out → still IAS 39. Interactions today: IFRS 1 transition bridges, the 2018 restatement mechanics (opening equity, no comparative restatement), and every 'how did IFRS 9 change X' exam question — the succession map IS the marking scheme.",
        ar: "ما انتقل إلى أين: التصنيف والقياس ← الفصل الخامس من IFRS 9 (الاختباران الموضوعيان)؛ والانخفاض ← الفصل ٥٫٥ (الخسائر المتوقعة)؛ ومحاسبة التغطية ← الفصل السادس (العلاقة الاقتصادية)؛ والاستبعاد ← نُقل شبه حرفيًا؛ والعرض ← IAS 32 دون تغيير؛ والإفصاحات ← IFRS 7 أعيدت كتابته حول الفئات الجديدة؛ واستثناء التغطية الكلية ← ما يزال IAS 39. والتفاعلات اليوم: جسور انتقال IFRS 1، وميكانيكا إعادة العرض ٢٠١٨ (حقوق ملكية افتتاحية دون إعادة عرض المقارنات)، وكل سؤال «كيف غيّر IFRS 9 كذا» — فخريطة الخلافة هي ذاتها مخطط الدرجات.",
      },
    },
    {
      kind: "tip",
      text: {
        en: "When the exam says 'explain how IFRS 9 changed the accounting', answer in PAIRS (old rule → new rule) across classification, impairment, embedded derivatives and hedging — the contrast table IS the marking scheme.",
        ar: "إذا قال الامتحان «اشرح كيف غيّر IFRS 9 المحاسبة» فأجب بأزواج (قاعدة قديمة ← جديدة) عبر التصنيف والانخفاض والمضمنة والتغطية — فجدول المقابلة هو مخطط الدرجات ذاته.",
      },
    },
    {
      kind: "tip",
      text: {
        en: "The AFS bucket's OCI-parking with recycling is the single most contrasted IFRS 9 change: today's FVOCI-debt recycles ONLY through derecognition, and FVOCI-equity never recycles — candidates who answer 'recycled on disposal' for EQUITY still earn zero.",
        ar: "حاوية «متاح للبيع» بتخزين حقوق الملكية وإعادة تدويرها أشد ما يقابل في IFRS 9: فديون FVOCI اليوم تعاد فقط عند الاستبعاد، وملكية FVOCI لا تعاد أبدًا — ومن يجيب «تدور عند البيع» عن الملكية يظل بلا درجة.",
      },
    },
    {
      kind: "tip",
      text: {
        en: "A CURRENT-period question (any period starting after 1 Jan 2018) never wants an IAS 39 answer — quoting HTM, AFS or the 80–125% line for a 2024 scenario is an instant fail. Reach for the legacy rules only when the question explicitly asks about the change or the transition.",
        ar: "سؤال الفترة الجارية (أي فترة تبدأ بعد ١ يناير ٢٠١٨) لا يريد إجابة IAS 39 أبدًا — فالاستشهاد بـHTM أو المتاح للبيع أو حد ٨٠–١٢٥٪ لسيناريو ٢٠٢٤ رسوب فوري. ولا تمد يدك للقواعد القديمة إلا إذا سأل السؤال صراحةً عن التغيير أو الانتقال.",
      },
    },
    {
      kind: "note",
      text: {
        en: "Do not mix: the 'effective interest' label exists in both regimes; the difference is in classification and impairment — not in the interest arithmetic itself.",
        ar: "لا تخلط: تسمية «فائدة فعلية» موجودة في العهدين؛ الفرق في التصنيف والانخفاض لا في حساب الفائدة ذاته.",
      },
    },
    {
      kind: "note",
      text: {
        en: "IAS 39's derecognition waterfall and hedge-documentation-at-inception rules survive inside IFRS 9 almost word for word — the successor kept the machinery and replaced the drivers.",
        ar: "شلالة الاستبعاد في IAS 39 وشرط وثائق التغطية عند النشأة يبقيان داخل IFRS 9 شبه كلمة بكلمة — فالخليفة أبقى الآلة وأبدل المحركات.",
      },
    },
  ],
}
