import { SeedCourse } from "./types"

export const evd500: SeedCourse = {
  slug: "audit-evidence-documentation",
  code: "EVD-500",
  title: "Audit Evidence & Documentation Mastery",
  subtitle: "ISA 500 and ISA 230: build evidence that persuades and files that survive inspection.",
  description:
    "The difference between a junior and a senior auditor is evidence judgement: knowing what proves what, and how to document it so a reviewer, inspector or court can reconstruct the conclusion years later. This course covers the ISA 500 evidence framework, the reliability hierarchy, sampling logic under ISA 530, and the ISA 230 documentation discipline — working papers, amendments, completion and archiving.",
  category: "International Standards",
  level: "Foundation",
  cpeHours: 5,
  instructorName: "Dina El-Sherif",
  instructorTitle: "ACCA, CIA · Audit Methodology Director",
  instructorBio:
    "Dina spent fourteen years in Big-4 external audit in Cairo and Dubai, then moved into audit methodology design, where she rebuilt risk-based audit templates used across the Middle East region.",
  rating: 4.7,
  ratingCount: 189,
  studentsCount: 867,
  icon: "folder-search",
  accent: "emerald",
  featured: false,
  order: 6,
  modules: [
    {
      title: "Evidence",
      description: "The ISA 500 framework: what evidence is, what makes it persuasive, and how sampling logic scales it.",
      lessons: [
        {
          title: "The Hierarchy of Audit Evidence",
          type: "lesson",
          durationMin: 13,
          xp: 10,
          content: {
            intro:
              "Not all evidence persuades equally. ISA 500 gives the auditor a mental ranking system — a reliability hierarchy — that should shape every procedure choice. Evidence from independent external sources beats evidence generated internally; evidence obtained directly by the auditor beats evidence provided by the client; and original documents beat copies, faxes and — today — screenshots of documents.",
            sections: [
              {
                heading: "The Reliability Ranking",
                body: "The hierarchy, from most to least persuasive: (1) evidence obtained directly by the auditor — confirmations, physical observation, reperformance; (2) external evidence generated by third parties and sent directly to the auditor; (3) external evidence held by the client (supplier invoices, contracts); (4) internal evidence produced by the client under effective controls; (5) internal evidence in weak control environments; and last, verbal inquiry alone. Where the stakes rise — significant risks — the design should climb this hierarchy deliberately.",
                bullets: [
                  "Auditor-obtained > externally generated > internally generated",
                  "Original documents > copies; controlled systems > ad hoc records",
                  "Written inquiry > verbal inquiry, always",
                ],
              },
              {
                heading: "Relevance: The Often-Forgotten Twin",
                body: "Appropriateness has two dimensions: reliability and relevance. A bank confirmation is maximally reliable — but it is only relevant to the assertions it covers (existence of the balance at the confirmation date; loan balances where confirmed). It says nothing about rights (pledged accounts), completeness of guarantees disclosed, or subsequent movement. Procedure design must match reliability WITH relevance to the tested assertion: the most reliable evidence pointed at the wrong assertion is decoration.",
              },
              {
                heading: "Information Produced by the Entity",
                body: "Modern audits run on client-produced reports: aged listings, trial balances, system extracts. ISA 500 requires the auditor to evaluate the accuracy and completeness of such information — testing the report's reconciliation to the ledger, examining the query logic, or verifying the extraction process. The habit of writing 'obtained aged receivables listing, agreed to trial balance' is exactly the discipline: one line of testing that converts client data into usable evidence.",
              },
            ],
            keyPoints: [
              "Climb the reliability hierarchy as risk rises — external and auditor-obtained first",
              "Relevance matches evidence to assertion; reliability alone is not enough",
              "Client-produced reports need accuracy/completeness testing before use",
              "Inquiry is never sufficient on its own for material judgements",
            ],
            example: {
              title: "The Screenshot That Wasn't Evidence",
              context:
                "To verify a client's cash balance at an unconfirmed subsidiary account, a junior documented a screenshot of the bank's web portal provided by the client's accountant.",
              analysis:
                "The screenshot fails on multiple hierarchy dimensions: client-provided, undated by a trusted process, easily editable, and not obtained directly by the auditor. Upgrades: obtain the bank confirmation directly; or access the portal with the auditor's own eyes during fieldwork and document the observation; or test the year-end bank statement (original) with subsequent movement reconciliation. Same account, same effort — a completely different evidential weight.",
            },
            takeaway:
              "Every procedure has an evidential ceiling set by the hierarchy — design upward for significant risks and never let client-provided artifacts stand in for auditor-obtained evidence.",
          },
        },
        {
          title: "Relevance & Reliability in the Digital Age",
          type: "lesson",
          durationMin: 13,
          xp: 10,
          content: {
            intro:
              "Audit evidence has gone digital: system extracts, e-invoices, portal confirmations, e-signatures and API-delivered data. ISA 500's principles map cleanly onto digital artifacts — but the testing moves upstream, from documents to the systems and interfaces that generate them.",
            sections: [
              {
                heading: "Egypt's E-Invoicing Reality",
                body: "Egypt's mandatory e-invoicing (ETA system) and e-receipt mandates changed revenue testing fundamentally. Every B2B invoice now exists in the taxpayer's portal with a UUID; the population itself is system-anchored. For the auditor: completeness testing can reconcile the ETA portal to the revenue ledger; existence testing can verify UUIDs exist and were accepted; and the client's own invoice register becomes inherently more reliable — but only when the auditor understands the portal data's scope (which transactions, which entities, which acceptance statuses). Digital evidence is abundant; its scope discipline is the skill.",
                bullets: [
                  "ETA e-invoicing: UUID-anchored population enables new completeness procedures",
                  "Portal-to-ledger reconciliation is now a standard revenue procedure in Egypt",
                  "Scope questions: which transaction types and statuses does the extract cover?",
                ],
              },
              {
                heading: "System Extracts and Their Pedigree",
                body: "When evidence is an extract, the audit question becomes pedigree: who extracted it, from which system, with which query, on which date, and who controls changes to that query. A listing extracted by the auditor with read-only access, cross-checked to the GL control account, has strong pedigree. The same listing emailed by the client with no reconciliation has weak pedigree regardless of its accuracy. Documenting pedigree is what makes digital evidence inspectable years later.",
              },
              {
                heading: "Third-erm Verification in a Digital World",
                body: "Digital confirmations — bank portals, e-confirmation platforms, custodian statements accessed via secure channels — now match or exceed paper confirmation reliability when the auditor controls the addressing/access. What degrades them: client-mediated access (the client logs in and shows you), unverified portal ownership, and forwarded emails. The principle is unchanged from paper: the auditor must stand in the evidence chain between the third party and the conclusion.",
              },
            ],
            keyPoints: [
              "Digital evidence shifts testing upstream to systems, queries and interfaces",
              "Document extract pedigree: who, what query, when, and how reconciled",
              "Auditor-controlled digital channels preserve third-party reliability",
              "E-invoicing portals enable new completeness procedures in Egypt",
            ],
            example: {
              title: "Reconciling Two Universes",
              context:
                "A distributor's revenue ledger shows EGP 480m; the ETA portal extract shows EGP 465m of accepted B2B invoices.",
              analysis:
                "First reaction: is EGP 15m unrecorded revenue? Investigate before concluding: the portal may exclude B2C receipts (e-receipt system), export invoices (different rules), credit notes in pending status, or intercompany eliminations. The reconciliation becomes a scoping exercise between two populations with different definitions — and the auditor's understanding of both definitions is the evidence. This is the new craft: population reconciliation discipline in a multi-system world.",
            },
            takeaway:
              "Digital evidence is not weaker or stronger — it is upstream: verify the system, the query and the population definitions, and the extracts become the strongest evidence you own.",
          },
        },
        {
          title: "Sampling Logic Meets Evidence (ISA 530)",
          type: "lesson",
          durationMin: 14,
          xp: 10,
          content: {
            intro:
              "Auditors cannot test everything, so ISA 530 governs how evidence scales through sampling. The core ideas are intuitive — sample size responds to risk and tolerable error — but the discipline of population definition, selection method and deviation evaluation is where files win or lose.",
            sections: [
              {
                heading: "Populations, Sampling Units and Stratification",
                body: "The population is the complete set of items from which the sample is drawn — and it must match the tested assertion. Testing revenue occurrence? The population is recorded sales. Testing revenue completeness? Recording a sample from the ledger proves nothing — the population is shipping documents or portal data. Getting the population right is 80% of sampling competence. Stratification then concentrates effort where exposure concentrates: test the top 20 customers 100%, sample the remainder. Monetary Unit Sampling in most audit software operationalizes this automatically.",
                bullets: [
                  "Population definition must match the assertion direction",
                  "Stratify by value: 100% examination above thresholds, sampling below",
                  "Monetary Unit Sampling weights probability by dollar (pound) amount",
                ],
              },
              {
                heading: "Selection Methods and Their Character",
                body: "Random selection (via software) provides statistical defensibility. Systematic selection (every Nth) approximates randomness if the population is not patterned — beware invoice numbering patterns that align with the interval. Haphazard selection is acceptable for non-statistical work but must be genuinely without pattern or bias. Judgmental/ targeted selection is not 'sampling' at all — it is specific-item testing, appropriate for high-risk items (related parties, round numbers, unusual entries), and it does not support projection to the population. Choose the method consciously and document the rationale.",
              },
              {
                heading: "When Deviations Appear",
                body: "A deviation in a controls sample (missing approval, signature absent) is not automatically a control failure — it is data. The auditor investigates nature and cause: systematic (the control is not operating) or isolated (a trained performer on leave, a documented exception). Project the deviation rate, compare to tolerable rate, and if it exceeds: extend testing, reject control reliance, or perform compensating substantive work. In substantive sampling, misstatements are projected to the population (with consideration of sampling risk) and evaluated against tolerable misstatement under ISA 450. The file must show the projection arithmetic, not just the found items.",
              },
            ],
            keyPoints: [
              "Population definition is the critical sampling judgement",
              "Method choice (random/systematic/haphazard/targeted) must be conscious and documented",
              "Deviations are investigated for cause before conclusions are drawn",
              "Misstatement projection arithmetic belongs in the file",
            ],
            example: {
              title: "The Wrong Population",
              context:
                "To address completeness of revenue, a team selected a random sample of invoices from the sales ledger and agreed them to shipping documents. All 25 items agreed. Conclusion drafted: 'revenue completeness tested, no exceptions.'",
              analysis:
                "The procedure tests occurrence (recorded → shipped), not completeness. Completeness sampling must run the other direction: sample from shipping documents (or the ETA portal population) and trace INTO the ledger. The conclusion was not just weak — it was structurally wrong, and no sample size could fix the direction. Population and direction discipline comes before every other sampling decision.",
            },
            takeaway:
              "Sampling is applied logic: define the population to match the assertion, select consciously, and when deviations appear, investigate cause before concluding — the arithmetic follows the thinking.",
          },
        },
      ],
    },
    {
      title: "Documentation",
      description: "ISA 230: working papers that pass review, amendment discipline, completion and archiving.",
      lessons: [
        {
          title: "Working Papers That Pass Review",
          type: "lesson",
          durationMin: 14,
          xp: 10,
          content: {
            intro:
              "The working paper is the unit of audit thought. A great working paper lets a reviewer reconstruct your conclusion without asking you a single question — source, procedure, result, conclusion, cross-reference. ISA 230 defines the standard; review experience defines the craft.",
            sections: [
              {
                heading: "The Anatomy of a Working Paper",
                body: "Every working paper answers five questions explicitly: What did I test? (assertion and population) From what source? (document/extract identification with pedigree) What did I do? (the procedure, precisely stated — 'agreed 25 invoices selected systematically to shipping documents and portal UUIDs') What did I find? (results, including exceptions and their resolution) What do I conclude? (a conclusion sentence that names the assertion and references the risk it addresses). Missing conclusions are the single most common review note; a working paper without a conclusion is an unfinished sentence.",
                bullets: [
                  "Purpose + source + procedure + result + conclusion",
                  "Tickmarks must be explained in a legend on the same paper",
                  "Cross-reference both directions: risk memo ↔ program ↔ working paper",
                ],
              },
              {
                heading: "The Reviewer's Sixty Seconds",
                body: "Reviewers triage files in under a minute per paper: they scan the conclusion first, then check that the procedure stated plausibly supports it, then sample the tickmarks. Design for that read: conclusion at the top, procedure statement precise, exceptions highlighted rather than buried. A paper that takes the reviewer three minutes to decode creates review friction that compounds across a file — and eventually surfaces as an unresolved review note at completion.",
              },
              {
                heading: "Documentation of Judgement",
                body: "ISAs require documenting not just procedures and results but the reasoning behind significant judgements: why this benchmark for materiality, why that risk was not significant, why the explanation for a variance was accepted. The discipline is proportionate: a paragraph of reasoning on material judgements, not essays on every decision. If a conclusion could be challenged, the reasoning paragraph is your defence — 'why did you accept this?' is the question inspectors ask most, and the file should answer it in your absence.",
              },
            ],
            keyPoints: [
              "Five-part anatomy: what, source, procedure, result, conclusion",
              "Design papers for the reviewer's sixty-second scan",
              "Document reasoning on significant judgements, proportionately",
              "Cross-referencing makes the file navigable — in both directions",
            ],
            example: {
              title: "Two Versions of the Same Test",
              context:
                "Version A: a spreadsheet of 40 vendor payments with ticks, titled 'Testing'. Version B: the same spreadsheet, titled 'Completeness of December payables — unrecorded liability search', with a procedure note ('inspected all payments > EGP 50k from 1 Jan-28 Feb, matched to invoice dates'), an exceptions section ('3 pre-year-end invoices found, EGP 1.2m proposed adjustment') and a conclusion referencing the risk memo line R4.",
              analysis:
                "Same data, different professional products. Version B survives reviewer, EQCR and inspection without a single question; Version A generates three review notes and an unresolved thread. The ten minutes of structure in Version B is the cheapest quality investment in the entire audit — and it is entirely learnable.",
            },
            takeaway:
              "Write working papers as if the reader will never meet you: source, procedure, result, conclusion, reasoning — complete sentences that stand alone.",
          },
        },
        {
          title: "Amendments, Completion & Archival Discipline",
          type: "lesson",
          durationMin: 12,
          xp: 10,
          content: {
            intro:
              "Audit files live long after the opinion: the ISA 230 assembly discipline — a complete final file within 60 days of the report date, with a controlled amendment process thereafter — is what makes audit evidence reconstructible years later when litigation, inspection or regulator inquiry arrives.",
            sections: [
              {
                heading: "The 60-Day Assembly Rule",
                body: "After the report date, the team has 60 days to assemble the final file: clear all review notes, incorporate final statements and reports, index, and lock. After finalization, no document may be added or removed — only appended under a documented amendment process with a new report date where required (in Egypt, following local statutory archiving rules as well). This discipline protects against the classic failure: 'improving' a file when a regulator calls. The audit file is a historical record, not a living document.",
              },
              {
                heading: "Superseding and Version Control",
                body: "During fieldwork, documents supersede each other constantly: draft statements, revised listings, updated memos. The final file should contain the versions actually used for the conclusion — not a museum of drafts. Version control discipline (file naming, dated extracts, clear identification of final versions) prevents the notorious inspection finding where the file contains two conflicting versions of the same schedule and no indication which one supported the opinion.",
              },
              {
                heading: "Retention and Egyptian Practice",
                body: "ISA 230's baseline is retention no shorter than five years in Egypt (per local regulatory requirements, longer where sector rules or engagement letters specify). Practically: firm-wide archiving policies, retrieval drills, and for listed entities, coherence between the archived audit file and what was filed with regulators. The auditor's ability to produce a complete, ordered, final file years later is the visible tip of documentation discipline — and the first thing every inspection tests.",
              },
            ],
            keyPoints: [
              "Final file assembled within 60 days of the report date, then locked",
              "Post-finalization changes follow a documented amendment process only",
              "The file is a historical record — no retrospective 'improvement'",
              "Retention: minimum five years in Egypt; verify sector-specific rules",
            ],
            example: {
              title: "The Regulator's Request, Three Years Later",
              context:
                "A FRA inquiry into a former client requests the complete audit file. The firm retrieves it — but the file contains an unindexed folder of 'latest versions', and two contradictory receivables reconciliations with no dates.",
              analysis:
                "The retrieval exposes the failure: the file was never truly finalized under ISA 230 discipline — it was merely archived when the team moved on. The defense that 'we found the right version eventually' is weaker than the version control that would have made the question trivial. Assembly discipline, locking and clean version control are not bureaucracy; they are the file's ability to defend the opinion years after the team has dispersed.",
            },
            takeaway:
              "Treat the file as a legal artifact: assemble within 60 days, lock it, archive it, and never touch it again except through the documented amendment door.",
          },
        },
        {
          title: "Knowledge Check: Evidence & Documentation",
          type: "quiz",
          durationMin: 8,
          xp: 25,
          content: {
            intro: "Confirm your evidence and documentation judgement. 70% to pass.",
            sections: [],
            keyPoints: [],
            takeaway: "",
          },
          quiz: {
            title: "Audit Evidence & Documentation — Knowledge Check",
            passScore: 70,
            questions: [
              {
                question:
                  "Which of the following is generally the MOST reliable evidence for the existence of a client's cash balance?",
                options: [
                  "A bank statement provided by the client's accountant",
                  "A screenshot of the online banking portal taken by the client",
                  "A bank confirmation obtained directly by the auditor from the bank",
                  "The cash book balance agreed to the trial balance",
                ],
                correctIndex: 2,
                explanation:
                  "ISA 500's hierarchy: evidence obtained directly by the auditor from an external source (the confirmation) outranks client-provided statements, screenshots and internal records.",
              },
              {
                question:
                  "An auditor uses a client-produced aged receivables listing as the basis for ECL testing. The required additional procedure is:",
                options: [
                  "No additional procedure — the listing is client data and usable as-is",
                  "Test the accuracy and completeness of the listing, e.g., agree totals to the ledger and verify extraction",
                  "Re-perform the aging calculation for every customer",
                  "Request management representation that the listing is correct",
                ],
                correctIndex: 1,
                explanation:
                  "ISA 500: information produced by the entity must be evaluated for accuracy and completeness — reconciling to the ledger and verifying the extraction converts client data into usable audit evidence.",
              },
              {
                question:
                  "To test the COMPLETENESS of revenue, the auditor should select a sample from:",
                options: [
                  "The recorded sales ledger",
                  "Shipping documents / e-invoicing portal records, tracing into the ledger",
                  "The cash receipts journal",
                  "The customer master file",
                ],
                correctIndex: 1,
                explanation:
                  "Completeness runs from source population into the ledger. Sampling recorded sales tests existence/occurrence — the wrong direction for completeness.",
              },
              {
                question:
                  "A control deviation is found in a sample (one missing approval out of 40). The auditor should FIRST:",
                options: [
                  "Conclude the control is ineffective",
                  "Ignore it as immaterial",
                  "Investigate the nature and cause of the deviation — systematic vs isolated",
                  "Double the sample size automatically",
                ],
                correctIndex: 2,
                explanation:
                  "ISA 530: understand the deviation before responding. A systematic failure (control not operating) and an isolated lapse (documented exception) lead to entirely different conclusions and responses.",
              },
              {
                question:
                  "Under ISA 230, after the audit report date, the final assembly of the complete file must occur within:",
                options: [
                  "30 days",
                  "60 days",
                  "90 days",
                  "One year",
                ],
                correctIndex: 1,
                explanation:
                  "ISA 230: the final file must be assembled within 60 days of the report date; thereafter, changes only through a documented amendment process — no additions or deletions.",
              },
            ],
          },
        },
      ],
    },
  ],
}
