import { qs, type RawBankQ } from "./seed-types"

/* Reporting cluster (ISA 700/701/705/706/710/720), ISQM 1, and overall
   quality/ethics-adjacent firm-level items. */

const isa700: RawBankQ[] = [
  { code: "ISA700-01", diff: 1, stem: "The auditor expresses an unmodified opinion when concluding that the financial statements are prepared, in all material respects, in accordance with:", options: ["The applicable financial reporting framework", "Management's preferences", "The previous year's presentation", "The auditor's own valuation model"], answer: 0, explanation: "The unmodified (formerly 'unqualified') opinion affirms fair presentation (or, for a compliance framework, truthful presentation) under the applicable framework." },
  { code: "ISA700-02", diff: 2, stem: "Which element is NOT part of the auditor's report?", options: ["The client's marketing strategy", "Opinion, Basis for Opinion, and Auditor's Responsibilities sections", "Key Audit Matters (for listed entities)", "Management's Responsibilities section"], answer: 0, explanation: "The report's fixed architecture: title, addressee, Opinion, Basis for Opinion, KAM, responsibilities of both parties, signature, date, location. The client's marketing has no place." },
  { code: "ISA700-03", diff: 2, stem: "The auditor's report must be dated:", options: ["No earlier than the date the auditor has obtained sufficient appropriate evidence", "On the balance sheet date", "When the engagement letter is signed", "On the file assembly deadline"], answer: 0, explanation: "The report date anchors the subsequent-events period — it cannot precede the point where evidence is sufficient." },
  { code: "ISA700-04", diff: 2, stem: "When the framework is a fair presentation framework, the opinion wording refers to:", options: ["Whether the FS present fairly, in all material respects, in accordance with the framework", "Whether the FS comply exactly with every rule", "Whether the FS match the tax return", "Whether the FS match the budget"], answer: 0, explanation: "Fair presentation frameworks (IFRS) use 'present fairly... in accordance with'; compliance frameworks use 'prepared in accordance with'." },
  { code: "ISA700-05", diff: 3, stem: "The auditor is unable to complete the audit because a material component is inaccessible, but the FS contain adequate disclosure. The opinion is:", options: ["Qualified ('except for' the scope limitation) if not pervasive, disclaimed if pervasive", "Unmodified with an EOM", "Adverse", "Unmodified — disclosure cures everything"], answer: 0, explanation: "Scope limitations follow ISA 705: qualified when confined, disclaimed when pervasive. Disclosure does not substitute for missing evidence." },
]

const isa701: RawBankQ[] = [
  { code: "ISA701-01", diff: 1, stem: "Key Audit Matters are:", options: ["Those matters that, in the auditor's professional judgment, were of most significance in the audit of the current period's FS", "All significant risks regardless of judgment", "All matters discussed with the audit committee", "Every estimate in the FS"], answer: 0, explanation: "KAMs are selected from matters communicated to TCWG, filtered by significance — judgment-driven selectivity is the standard." },
  { code: "ISA701-02", diff: 2, stem: "KAM communication applies to audits of:", options: ["Listed entities, and optionally other entities where the auditor decides", "All entities mandatorily", "Only banks", "Only state-owned entities"], answer: 0, explanation: "The mandate covers listed entities; other audits may include KAMs when the auditor judges it appropriate — or the regulator requires it." },
  { code: "ISA701-03", diff: 2, stem: "Which item should NOT ordinarily be described as a KAM?", options: ["A matter addressed in the Material Uncertainty Related to Going Concern paragraph", "A significant estimate like ECL on a distressed customer book", "A related-party transaction cluster under ISA 550", "Revenue cut-off testing in a December-loaded business"], answer: 0, explanation: "The MUM paragraph carries going-concern doubt; duplicating it as a KAM is explicitly avoided (cross-reference instead)." },
  { code: "ISA701-04", diff: 3, stem: "A KAM description should:", options: ["Explain why the matter was significant and how it was addressed in the audit — without providing the auditor's original opinion-level conclusion on it", "Give a clean bill of health per KAM", "List every procedure performed", "Duplicate the Basis for Opinion"], answer: 0, explanation: "KAM text = why it mattered + how it was audited; it does not certify the matter nor modify the opinion." },
  { code: "ISA701-05", diff: 2, stem: "A matter giving rise to a modified opinion:", options: ["Is disclosed in the KAM section with a cross-reference to the Basis for Modified Opinion", "Is excluded entirely from KAMs", "Replaces the KAM section", "Is only communicated orally"], answer: 0, explanation: "Modifying matters appear in both sections — the Basis explains the modification; the KAM section cross-references to avoid contradiction." },
]

const isa705: RawBankQ[] = [
  { code: "ISA705-01", diff: 1, stem: "The three types of modified opinions are:", options: ["Qualified, adverse, and disclaimer of opinion", "Qualified, emphasized, and restricted", "Adverse, delayed, and withdrawn", "Conditional, partial, and provisional"], answer: 0, explanation: "ISA 705 recognizes exactly three modifications: qualified (material, not pervasive), adverse (material and pervasive misstatement), disclaimer (pervasive inability to obtain evidence)." },
  { code: "ISA705-02", diff: 2, stem: "A material but NOT pervasive misstatement (management refuses to adjust):", options: ["Qualified opinion — 'except for' the effects of the matter", "Adverse opinion", "Disclaimer", "Unmodified with EOM"], answer: 0, explanation: "The 'except-for' qualification isolates the material-but-confined misstatement; pervasiveness is the hinge between qualified and adverse/disclaimer." },
  { code: "ISA705-03", diff: 2, stem: "Pervasiveness means:", options: ["The effects are widespread, fundamental to users' understanding, or confined to neither a single element nor a narrow set", "The amount exceeds 1% of assets", "The client is listed", "The error was intentional"], answer: 0, explanation: "Pervasiveness is about spread and structural importance, not intent or listing status — it decides qualified vs adverse/disclaimer." },
  { code: "ISA705-04", diff: 2, stem: "A pervasive inability to obtain sufficient appropriate evidence leads to:", options: ["Disclaimer of opinion", "Adverse opinion", "Qualified opinion", "Unmodified opinion with emphasis"], answer: 0, explanation: "Missing evidence that is both material and pervasive disclaims the opinion — the auditor cannot conclude at all." },
  { code: "ISA705-05", diff: 3, stem: "A pervasive misstatement from a wrong accounting-policy choice (e.g., going-concern basis inappropriate) leads to:", options: ["Adverse opinion", "Qualified opinion", "Disclaimer", "Unmodified with MUM"], answer: 0, explanation: "Material AND pervasive misstatement = adverse: the FS as a whole do not present fairly. The 'inappropriate GC basis' is the classic adverse example." },
  { code: "ISA705-06", diff: 3, stem: "An immaterial but deliberate management nondisclosure detected near the report date signals:", options: ["An integrity concern — evaluate fraud risk and the reliability of management representations before concluding on scope", "An automatic disclaimer", "Nothing since immaterial", "A fee reduction"], answer: 0, explanation: "Intent re-opens the risk assessment: deliberate nondisclosure questions whether other representations can be trusted, whatever the amount." },
]

const isa706: RawBankQ[] = [
  { code: "ISA706-01", diff: 1, stem: "An Emphasis of Matter paragraph:", options: ["Highlights a matter appropriately presented and disclosed that is fundamental to users' understanding — without modifying the opinion", "Qualifies the opinion softly", "Adds the auditor's own conclusion on the matter", "Is used for disagreements"], answer: 0, explanation: "EOM = spotlight, not verdict: the matter is properly in the FS and the opinion stays unmodified; the paragraph points users to the disclosure." },
  { code: "ISA706-02", diff: 2, stem: "An Other Matter paragraph is used when:", options: ["Something OTHER than the FS needs communicating that is not disclosed elsewhere in the report — e.g., a restriction on distribution or prior-statement reference", "The auditor wants to praise management", "A misstatement exists", "KAMs are insufficient"], answer: 0, explanation: "Other Matter covers auditor-side context (use of a predecessor's work, report distribution limits) — never matters already disclosed in the FS." },
  { code: "ISA706-03", diff: 2, stem: "EOM placement in the report:", options: ["Immediately after the Opinion and Basis for Opinion sections, with an explicit reference to where the disclosure sits", "Before the addressee", "At the very end, unsigned", "Inside the Management Responsibilities section"], answer: 0, explanation: "Placement and cross-referencing rules make the report read as one coherent document and prevent EOM misuse as a hidden qualification." },
  { code: "ISA706-04", diff: 3, stem: "EOM misuse to flag an inadequately disclosed going-concern uncertainty is:", options: ["Not permitted — inadequate disclosure calls for a qualified or adverse opinion under ISA 570/705", "Acceptable practice", "Required by convention", "The auditor's choice"], answer: 0, explanation: "An EOM presupposes adequate disclosure; using it to paper over missing disclosure converts a clear modification case into a misleading report." },
]

const isa710: RawBankQ[] = [
  { code: "ISA710-01", diff: 2, stem: "When prior-period figures contain material misstatements not corrected, the auditor evaluates whether:", options: ["The misstatements still have a material effect on the current period's FS, possibly leading to a modified opinion referencing comparatives", "The prior year can be ignored entirely", "The predecessor must reissue", "It is always irrelevant"], answer: 0, explanation: "Comparatives are part of the current FS — uncorrected prior-period misstatements flow into current-period conclusions and possibly the current opinion." },
  { code: "ISA710-02", diff: 3, stem: "The predecessor's report was modified; the current auditor's report on comparatives:", options: ["May reference the predecessor's modification if it is relevant to the current period's comparatives", "Must repeat the modification verbatim", "Must never mention it", "Requires a disclaimer"], answer: 0, explanation: "The incoming auditor may disclose a prior-period modification of the predecessor's report when relevant — with care about responsibility boundaries." },
]

const isa720: RawBankQ[] = [
  { code: "ISA720-01", diff: 2, stem: "'Other information' means financial and non-financial information (other than the FS and the auditor's report) included in:", options: ["An entity's annual report (or similar document) that contains the audited FS", "Any client website content", "Internal budgets", "Press interviews"], answer: 0, explanation: "ISA 720 targets the annual-report package — directors' report, MD&A, corporate governance statements — the document the market actually reads alongside the FS." },
  { code: "ISA720-02", diff: 2, stem: "On reading other information and finding a material inconsistency with the audited FS, the auditor should first:", options: ["Discuss with management and request resolution/correction of the inconsistency", "Report the client to the regulator", "Withdraw immediately", "Qualify the FS opinion"], answer: 0, explanation: "Inconsistency resolution starts with management discussion; escalation follows only if unresolved — with reporting-consequence ladders under ISA 720." },
  { code: "ISA720-03", diff: 3, stem: "The auditor's responsibility for other information is:", options: ["To read it and consider material inconsistencies and material misstatements of fact — not to audit it", "To audit it with the same rigor as the FS", "None whatsoever", "To rewrite it for the client"], answer: 0, explanation: "Read, consider, report — an evidence standard far below audit, but a defined duty with defined escalation paths." },
]

const isqm1: RawBankQ[] = [
  { code: "ISQM1-01", diff: 1, stem: "ISQM 1 requires firms to establish:", options: ["A system of quality management covering all engagements, with 8 components including governance, risk assessment, and monitoring", "An annual fee review only", "A marketing strategy", "A single quality partner for the whole firm with no further structure"], answer: 0, explanation: "The 2022 ISQM 1 regime: quality risks are identified and responded to across 8 components — governance/leadership, risk assessment, engagement acceptance, engagement performance, resources, information/communication, monitoring, remediation." },
  { code: "ISQM1-02", diff: 2, stem: "Under ISQM 1, who bears ultimate responsibility for the firm's system of quality management?", options: ["The firm's leadership (chief executive/partners) — responsibility cannot be delegated away", "The head of audit training", "The external quality reviewer", "The professional body"], answer: 0, explanation: "ISQM 1 makes leadership accountable for SQM design, implementation and operation — titles and delegations do not transfer ultimate responsibility." },
  { code: "ISQM1-03", diff: 2, stem: "The quality objective for engagement acceptance is best served when the firm:", options: ["Accepts only engagements it can competently and ethically perform — evaluating integrity, competence, capacity, and independence first", "Accepts every engagement for growth", "Accepts anything billed hourly", "Delegates acceptance to juniors"], answer: 0, explanation: "Client acceptance filters integrity of principals, firm competence/capacity, and ethics — the acceptance file documents all three." },
  { code: "ISQM1-04", diff: 3, stem: "Egyptian audit firms aligning with international quality regimes typically map ISQM 1 components to:", options: ["Local ESAA/ESOA quality guidance and IESBA ethics requirements", "Tax authority circulars", "Stock exchange listing rules only", "HR policy manuals"], answer: 0, explanation: "In the Egyptian framework, firms blend ISQM 1 with local Egyptian Standards on Auditing and ESAA professional-guidance structures — international components, local anchoring." },
  { code: "ISQM1-05", diff: 2, stem: "A cold (post-issuance) review of a completed audit file is part of:", options: ["The firm's monitoring of quality management (engagement-level monitoring)", "The engagement team's own review", "Client acceptance", "External audit of the firm"], answer: 0, explanation: "Periodic file inspections feed the monitoring component, whose findings drive the remediation process under ISQM 1." },
]

export const REPORTING = [
  ...qs("ISA 700", "auditing", isa700),
  ...qs("ISA 701", "auditing", isa701),
  ...qs("ISA 705", "auditing", isa705),
  ...qs("ISA 706", "auditing", isa706),
  ...qs("ISA 710", "auditing", isa710),
  ...qs("ISA 720", "auditing", isa720),
  ...qs("ISQM 1", "auditing", isqm1),
]
