import { qs, type RawBankQ } from "./seed-types"

/* Accounting & IFRS section (~90 items): the standards Egyptian exam
   blueprints over-sample — revenue, financial instruments, leases,
   impairment, presentation, consolidation. */

const ifrs15: RawBankQ[] = [
  { code: "IFRS15-01", diff: 1, stem: "IFRS 15's five-step model starts with:", options: ["Identify the contract with a customer", "Recognize the revenue when invoiced", "Set the price by the sales manager", "Confirm the shipment"], answer: 0, explanation: "The ladder: contract → performance obligations → transaction price → allocation → recognition as obligations are satisfied." },
  { code: "IFRS15-02", diff: 2, stem: "A bundled sale of equipment + 2-year maintenance for one price requires:", options: ["Allocating the transaction price to each performance obligation on relative standalone-selling-price basis", "Recognizing everything on delivery", "Deferring everything over 2 years", "Using cost-plus for the whole bundle"], answer: 0, explanation: "Distinct obligations (equipment, service) each get their share of the price — observable SSP first, estimation methods (residual, expected cost plus margin) when needed." },
  { code: "IFRS15-03", diff: 2, stem: "Over time (percentage of completion style) recognition requires at least one qualifying criterion, such as:", options: ["The customer simultaneously receives and consumes the benefits as the entity performs", "Contract length over one year", "The customer pays in advance", "The goods are generic"], answer: 0, explanation: "The three over-time tests: simultaneous consumption, customer-controlled asset creation, or no alternative use + enforceable right to payment for performance to date." },
  { code: "IFRS15-04", diff: 3, stem: "A contract has a single performance obligation satisfied over time, and measuring progress by outputs is unreliable. The acceptable alternative is:", options: ["Input methods (e.g., costs incurred relative to total expected costs) as a measure of progress", "Postponing all revenue until contract end", "Cash-basis recognition", "The completed-contract method regardless of IFRS 15"], answer: 0, explanation: "IFRS 15 prefers the single measure that best depicts transfer — input methods substitute when outputs are unreliable, subject to the unbilled/receivable presentation rules." },
  { code: "IFRS15-05", diff: 2, stem: "Variable consideration (rebates, penalties) is included in the transaction price only to the extent of:", options: ["The amount highly probable NOT to reverse significantly when the uncertainty resolves (constraint)", "The maximum possible amount", "The minimum possible amount always", "Management's best-case scenario"], answer: 0, explanation: "Two-step: estimate (expected value or most-likely amount) then apply the constraint against significant revenue reversal." },
  { code: "IFRS15-06", diff: 3, stem: "Billings exceed revenue recognized on a long-term contract (costs to date low, billings high). The balance sheet shows:", options: ["A contract liability (deferred revenue) for the excess", "A contract asset", "A receivable", "Accrued income"], answer: 0, explanation: "Billing ahead of performance = contract liability; performance ahead of billing (with unconditional right) = receivable, otherwise contract asset." },
  { code: "IFRS15-07", diff: 2, stem: "Principal-vs-agent analysis under IFRS 15 determines:", options: ["Whether revenue is gross (principal) or net of the third party's share (agent)", "Whether VAT applies", "The lease classification", "The segment allocation"], answer: 0, explanation: "Control of the good/service before transfer decides it: gross revenue when the entity controls it first, net (fee/commission) when it never does." },
  { code: "IFRS15-08", diff: 3, stem: "A December FOB shipping-point sale is loaded on 2 January. For the auditor testing cut-off, the revenue belongs to:", options: ["Next year — FOB shipping point means control passes on shipment (which happened in January)", "This year, since the contract was signed in December", "Whichever year helps the budget", "Both years, split 50/50"], answer: 0, explanation: "FOB shipping point + January loading = transfer of control in January. Recognition follows the transfer of control, not paperwork dates — the classic cut-off trap." },
]

const ifrs9: RawBankQ[] = [
  { code: "IFRS9-01", diff: 1, stem: "IFRS 9's classification of debt instruments depends on:", options: ["The business model and the contractual cash flow characteristics (SPPI)", "Management's intent alone", "The instrument's listing status", "Its currency"], answer: 0, explanation: "Two tests: the business model (hold to collect vs sell vs other) and whether cash flows are solely payments of principal and interest — deciding amortized cost, FVOCI, or FVTPL." },
  { code: "IFRS9-02", diff: 2, stem: "Expected credit losses under IFRS 9 follow a:", options: ["Three-stage model driven by significant increases in credit risk and credit impairment events", "One-stage incurred-loss model", "Fair-value-only model", "Regulatory formula set by the stock exchange"], answer: 0, explanation: "Stage 1: 12-month ECL and interest on gross; Stage 2 (SICR): lifetime ECL, still gross interest; Stage 3 (credit-impaired): lifetime ECL, interest on net." },
  { code: "IFRS9-03", diff: 2, stem: "A trade receivable under IFRS 9's simplified approach carries:", options: ["A lifetime ECL provision from initial recognition", "A 12-month ECL only", "No provision until a dispute exists", "A tax-based reserve"], answer: 0, explanation: "Trade receivables use the simplified approach — always lifetime ECL, no SICR tracking required." },
  { code: "IFRS9-04", diff: 3, stem: "Significant increase in credit risk (Stage 2) is assessed by considering:", options: ["Reasonable and supportable forward-looking information, including actual or expected significant changes in the borrower's circumstances", "Only the counterparty's last payment", "The auditor's preference", "The Egyptian exchange rate"], answer: 0, explanation: "SICR judgments compare the risk of default over the instrument's life at reporting vs initial recognition, using historical, current and forward-looking data." },
  { code: "IFRS9-05", diff: 2, stem: "IFRS 7 requires extensive risk-related financial-instrument disclosures, including:", options: ["Credit risk, liquidity risk, and market risk exposures plus the ECL measurement inputs", "Only the bank balances", "The auditor's opinion on credit", "Names of all debtors"], answer: 0, explanation: "The disclosure package (which the auditor tests) covers significance of instruments and the nature and extent of risks — credit, liquidity, market — with ECL detail." },
]

const ifrs16: RawBankQ[] = [
  { code: "IFRS16-01", diff: 1, stem: "Under IFRS 16, a lessee recognizes:", options: ["A right-of-use asset and a lease liability for virtually all leases", "Operating lease expense straight-line", "Nothing until renewal", "Contingent rent only"], answer: 0, explanation: "The single lessee model capitalizes nearly all leases: ROU asset + liability at discounted payments, with depreciation + interest." },
  { code: "IFRS16-02", diff: 2, stem: "The initial lease liability is measured at:", options: ["The present value of unpaid lease payments discounted at the rate implicit in the lease (or the lessee's incremental borrowing rate)", "Total undiscounted payments", "One year's payments", "Fair value of the asset"], answer: 0, explanation: "PV of lease payments over the term — discounting at the implicit rate when determinable, else the IBR." },
  { code: "IFRS16-03", diff: 2, stem: "Which would NOT normally be part of the ROU asset's initial cost?", options: ["The next year's renewal payments beyond the lease term", "Initial direct costs", "Payments made at or before commencement", " Restoration cost obligations"], answer: 0, explanation: "The ROU asset includes the liability, prepayments, initial direct costs and dismantling estimates — not payments from renewal periods not in the lease term." },
  { code: "IFRS16-04", diff: 3, stem: "The IFRS 16 effect on a lessee's EBITDA versus the old operating-lease treatment is normally:", options: ["Higher EBITDA — rent expense is replaced by depreciation and interest below the line", "Lower EBITDA", "No change ever", "EBITDA becomes irrelevant"], answer: 0, explanation: "Rent (an operating cost) disappears into D&A and interest — EBITDA rises while profit typically dips early in the lease term — a covenant and KPI matter for auditors." },
]

const ias1: RawBankQ[] = [
  { code: "IAS1-01", diff: 1, stem: "A complete set of financial statements under IAS 1 includes:", options: ["Statement of financial position, income statement, statement of comprehensive income where applicable, changes in equity, cash flows, and notes", "Only the balance sheet", "Balance sheet and cash flow only", "Whatever management prefers"], answer: 0, explanation: "The full set plus comparative information; the auditor's opinion covers this complete set, not just the SOFP." },
  { code: "IAS1-02", diff: 2, stem: "Going-concern assessment responsibility under IAS 1 rests with:", options: ["Management — which prepares the FS on a going-concern basis unless it intends to liquidate or has no realistic alternative", "The auditor", "The tax authority", "The audit committee chair alone"], answer: 0, explanation: "IAS 1 makes it management's call; ISA 570 then makes the auditor's job to independently evaluate it." },
  { code: "IAS1-03", diff: 2, stem: "Material misclassifications (e.g., current vs non-current) concern the assertion of:", options: ["Presentation and disclosure (classification)", "Occurrence", "Rights and obligations", "Existence"], answer: 0, explanation: "Presentation/classification is a full assertion family — a materially wrong current/non-current split misleads users about liquidity even if totals are right." },
]

const ias36: RawBankQ[] = [
  { code: "IAS36-01", diff: 1, stem: "IAS 36 impairment testing applies to:", options: ["Goodwill, intangibles without fixed useful lives, and other long-lived assets when indicators exist", "Inventory only", "Cash", "Trade receivables (handled by IFRS 9)"], answer: 0, explanation: "IAS 36's scope: non-financial long-lived assets. Receivables have their own ECL regime under IFRS 9 — a classification question exams love." },
  { code: "IAS36-02", diff: 2, stem: "Goodwill is tested:", options: ["Annually and whenever indicators exist, at the cash-generating-unit level", "Only when indicators appear", "Monthly", "Only at acquisition"], answer: 0, explanation: "Goodwill has no standalone cash flows — the CGU carries the test, annually at a minimum, regardless of indicators." },
  { code: "IAS36-03", diff: 2, stem: "Recoverable amount is:", options: ["The higher of fair value less costs of disposal and value in use", "The lower of the two", "Always fair value", "Carrying amount"], answer: 0, explanation: "The entity can always choose the better exit — so recoverable amount is the HIGHER of FVLCD and VIU (PV of future cash flows)." },
  { code: "IAS36-04", diff: 3, stem: "A VIU model uses management's growth rate of 12% forever while the industry grows at 4%. The auditor's primary concern is:", options: ["The assumption's reasonableness — a perpetual growth rate far above economic growth is an estimate-integrity red flag under ISA 540", "The discount rate only", "Nothing — management's model is theirs", "The currency of the cash flows"], answer: 0, explanation: "Assumption reasonableness against external benchmarks is core ISA 540 work; terminal growth above GDP is a classic bias signal." },
]

const ias37: RawBankQ[] = [
  { code: "IAS37-01", diff: 1, stem: "A provision is recognized when:", options: ["A present obligation from a past event exists, outflow is probable, and the amount can be reliably estimated", "Management decides to be prudent", "Any lawsuit is filed", "The auditor suggests it"], answer: 0, explanation: "The three-part test defines a provision; without a present obligation there is nothing to provide for (contingent-liability territory instead)." },
  { code: "IAS37-02", diff: 2, stem: "A remote-likelihood contingent liability is:", options: ["Disclosed only if... actually NOT recognized and not disclosed — remote likelihood is ignored", "Recognized at full amount", "Recognized at 50%", "Always disclosed"], answer: 0, explanation: "IAS 37: probable → provision; possible → disclose; remote → ignore. The probability ladder drives the whole standard." },
  { code: "IAS37-03", diff: 2, stem: "Provisions are measured at:", options: ["The best estimate of the expenditure required to settle the obligation, discounted where the effect is material", "The maximum conceivable loss", "The minimum possible", "Zero until settled"], answer: 0, explanation: "Best estimate (expected value for populations, most-likely outcome for single events), with time-value discounting for long horizons." },
]

const ias2: RawBankQ[] = [
  { code: "IAS2-01", diff: 1, stem: "Inventory is measured at:", options: ["The lower of cost and net realizable value", "Cost only", "Fair value", "Selling price less margin"], answer: 0, explanation: "LCNRV is the rule; NRV = estimated selling price less estimated completion and selling costs." },
  { code: "IAS2-02", diff: 2, stem: "Which cost is NOT included in inventory cost?", options: ["Selling costs of the marketing department", "Import duties on raw materials", "Direct labour", "Production overheads allocated on a normal-capacity basis"], answer: 0, explanation: "Costs of sale, general admin unrelated to production, abnormal waste and storage (unless needed in production) stay out of inventory." },
  { code: "IAS2-03", diff: 2, stem: "Obsolete dyes in a warehouse with NRV below cost require:", options: ["A write-down to NRV — recognized as an expense in the period of the write-down", "Reclassification to PPE", "Disclosure only", "No action until sold"], answer: 0, explanation: "Write-downs hit the period's P&L; reversals (capped at original cost) are possible when NRV recovers — a common Egyptian textiles/chemicals audit adjustment." },
]

const ias16: RawBankQ[] = [
  { code: "IAS16-01", diff: 1, stem: "Under IAS 16, PPE is initially measured at:", options: ["Cost — including directly attributable costs of bringing the asset to working condition", "Fair value at each period", "Market value at acquisition", "Replacement cost"], answer: 0, explanation: "Cost includes purchase price (net of trade discounts), import duties, and directly attributable costs — site preparation, delivery, installation, testing." },
  { code: "IAS16-02", diff: 2, stem: "Which item is capitalized into PPE?", options: ["Costs of testing whether the asset functions properly (net of sale proceeds of test products)", "Staff training on the new line", "Relocation of production during a later year", "Marketing launch costs"], answer: 0, explanation: "Directly attributable costs of bringing the asset to the location and condition needed — test runs qualify (net of proceeds); training, later relocations, marketing do not." },
  { code: "IAS16-03", diff: 2, stem: "The revaluation model under IAS 16 requires:", options: ["Fair value to be measured reliably and applied to the whole class consistently with regular revaluations", "Applying it to a single building only", "Annual revaluation exactly", "Management's cost estimate"], answer: 0, explanation: "Revaluation is a class-level election with a reliable fair value and a frequency that keeps carrying amounts near fair value — piecemeal revaluation is not allowed." },
]

const ias38: RawBankQ[] = [
  { code: "IAS38-01", diff: 1, stem: "Which of the following is most likely to qualify as an intangible asset under IAS 38?", options: ["A purchased patent", "Internally generated goodwill", "The company's brand built over years internally", "Staff loyalty"], answer: 0, explanation: "Identifiability, control and future benefits gate recognition: purchased patents pass; internally generated goodwill/brands and workforce do not." },
  { code: "IAS38-02", diff: 2, stem: "Development expenditure is capitalized only when ALL of the listed criteria are met, including:", options: ["Technical feasibility, intention and ability to complete, probable benefits, available resources, measurability", "Management's promise to fund it", "The CFO's approval", "A tax ruling"], answer: 0, explanation: "IAS 38.57's six criteria are cumulative — one failure sends the whole outflow to expense; the capitalization memo is a standard audit deliverable." },
  { code: "IAS38-03", diff: 2, stem: "Research expenditure is:", options: ["Expensed as incurred, always", "Capitalized", "Amortized over 5 years", "Held in suspense until patent grant"], answer: 0, explanation: "Research has no demonstrable future-benefit control — the standard mandates expensing, and 'research' mislabeled as 'development' is a frequent audit adjustment." },
]

const ias10: RawBankQ[] = [
  { code: "IAS10-01", diff: 1, stem: "IAS 10 distinguishes events by:", options: ["Whether conditions arose after the reporting period or existed at the reporting date", "Their monetary size", "Who discovered them", "Their tax effect"], answer: 0, explanation: "Adjusting events (conditions existed) → adjust; non-adjusting (conditions arose after) → disclose if material. The conceptual twin of ISA 560's audit-side split." },
  { code: "IAS10-02", diff: 2, stem: "A dividend declared AFTER the reporting period is:", options: ["Not a liability at the reporting date — disclosure only", "A liability to accrue", "An equity distribution to book", "Deferred income"], answer: 0, explanation: "Post-reporting-date declarations create no present obligation at the balance sheet date — the classic exam pairing with ISA 570's going-concern interaction on liquidity." },
]

const ifrs13: RawBankQ[] = [
  { code: "IFRS13-01", diff: 1, stem: "Fair value under IFRS 13 is:", options: ["The price that would be received to sell an asset in an orderly transaction between market participants at the measurement date", "Book value", "Replacement cost", "Whatever the buyer paid last"], answer: 0, explanation: "An exit price, market-participant based, at the measurement date — the definition anchors every fair-value hierarchy question." },
  { code: "IFRS13-02", diff: 2, stem: "The fair value hierarchy's Level 1 is:", options: ["Quoted prices in active markets for identical assets", "Unobservable inputs", "Management's model", "The auditor's valuation"], answer: 0, explanation: "L1 = quoted prices for identical items; L2 = observable inputs other than quotes; L3 = unobservable (model) inputs — disclosure intensity rises down the ladder." },
  { code: "IFRS13-03", diff: 3, stem: "A Level 3 valuation uses a model with significant unobservable inputs. For the auditor this typically means:", options: ["A significant-risk estimate under ISA 540 — testing model, data, assumptions, and management bias", "Automatic qualification", "Accepting the number as given", "Revaluing it with Level 1 data"], answer: 0, explanation: "Level 3 = estimation uncertainty + subjectivity = high assessed risk, driving ISA 540's full procedure battery." },
]

const ias7: RawBankQ[] = [
  { code: "IAS7-01", diff: 1, stem: "Interest paid is classified under IAS 7 as:", options: ["Operating or financing (per the entity's policy choice for interest paid), consistently applied", "Always investing", "Always financing only", "Non-cash"], answer: 0, explanation: "IAS 7 (and its amendments) permit interest paid in operating or financing — the auditor tests consistency of the policy, not just the arithmetic." },
  { code: "IAS7-02", diff: 2, stem: "A company's profit rises while operating cash flow turns deeply negative due to ballooning receivables. This divergence most directly signals:", options: ["Potential revenue-recognition or collection problems — an audit red flag warranting substantive response", "Healthy growth", "A tax planning opportunity", "A presentation choice only"], answer: 0, explanation: "Earnings-cash divergence is the classic fraud/screening red flag — accrual-heavy profit with weak cash conversion is precisely what analytics (ISA 520) exist to catch." },
]

const ias12: RawBankQ[] = [
  { code: "IAS12-01", diff: 1, stem: "Deferred tax arises from:", options: ["Temporary differences between the carrying amount and tax base of assets and liabilities", "Late filing penalties", "Permanent differences like non-deductible fines", "VAT balances"], answer: 0, explanation: "Taxable/deductible temporary differences create deferred liabilities/assets; permanent differences never do — a favorite conceptual pairing." },
  { code: "IAS12-02", diff: 2, stem: "A deferred tax asset is recognized only to the extent that:", options: ["Future taxable profits are probable against which it can be utilized", "Management requests it", "The tax office pre-approves", "It equals the deferred tax liability"], answer: 0, explanation: "Probable utilization gates DTA recognition — loss-making entities with history of losses face DTA skepticism, a recurring audit judgment." },
]

const consolidation: RawBankQ[] = [
  { code: "IFRS10-01", diff: 1, stem: "Under IFRS 10, control exists when the investor has:", options: ["Power over the investee, exposure to variable returns, and the ability to use its power to affect those returns", "Over 50% of shares always", "Board seats only", "Joint influence"], answer: 0, explanation: "The three-element control model replaced the mechanical majority test — de-facto control (via contracts, potential votes) can consolidate below 50%." },
  { code: "IFRS03-01", diff: 2, stem: "Under IFRS 3, goodwill on acquisition is measured as:", options: ["Consideration transferred plus NCI plus previously-held interest, minus the identifiable net assets acquired", "Purchase price minus book equity", "The target's brand value", "The excess of revenue over cost"], answer: 0, explanation: "Goodwill = the residual of the business-combination equation — including the NCI measurement (fair value or proportionate share) policy choice." },
  { code: "IFRS03-02", diff: 2, stem: "Contingent consideration in a business combination is:", options: ["Recognized at fair value at acquisition and remeasured through P&L (if not equity-classified) as estimates change", "Ignored until paid", "Recognized at nominal value only", "Never part of cost"], answer: 0, explanation: "IFRS 3 mandates day-one fair value; subsequent remeasurement (for asset-classified contingents) hits earnings — an estimate-heavy post-acquisition audit area." },
  { code: "IAS33-01", diff: 2, stem: "Basic EPS is computed as:", options: ["Profit attributable to ordinary shareholders divided by the weighted average number of ordinary shares", "Net profit divided by year-end shares", "Revenue per share", "Book value per share"], answer: 0, explanation: "The numerator adjusts for preference dividends and minority interests; the denominator is the time-weighted share count — dilution (options, converts) then layers on." },
]

export const IFRS = [
  ...qs("IFRS 15", "accounting", ifrs15),
  ...qs("IFRS 9", "accounting", ifrs9),
  ...qs("IFRS 7", "accounting", ifrs9.filter((_, i) => i === 4).map((q) => ({ ...q, code: "IFRS7-05" }))),
  ...qs("IFRS 16", "accounting", ifrs16),
  ...qs("IAS 1", "accounting", ias1),
  ...qs("IAS 36", "accounting", ias36),
  ...qs("IAS 37", "accounting", ias37),
  ...qs("IAS 2", "accounting", ias2),
  ...qs("IAS 16", "accounting", ias16),
  ...qs("IAS 38", "accounting", ias38),
  ...qs("IAS 10", "accounting", ias10),
  ...qs("IFRS 13", "accounting", ifrs13),
  ...qs("IAS 7", "accounting", ias7),
  ...qs("IAS 12", "accounting", ias12),
  ...qs("IFRS 3", "accounting", consolidation.filter((_, i) => i === 1 || i === 2)),
  ...qs("IFRS 10", "accounting", consolidation.filter((_, i) => i === 0)),
  ...qs("IAS 33", "accounting", consolidation.filter((_, i) => i === 3)),
]
