import { qs, type RawBankQ } from "./seed-types"

/* Egyptian regulatory & professional framework — solid-ground items only:
   Accountancy Profession Law 133/1951, Companies Law 159/1981, Banking Law
   194/2020, institutional roles (FRA / CBE / CAO), tax basics, and the
   Egyptian Accounting Standards' IFRS convergence model. */

const prof: RawBankQ[] = [
  { code: "EGY-PROF-01", diff: 1, stem: "Which law regulates the accountancy and audit profession in Egypt and governs registration in the general register of practitioners?", options: ["Accountancy Profession Law 133 of 1951 and its amendments", "Companies Law 159 of 1981", "Central Bank Law 194 of 2020", "Civil Code"], answer: 0, explanation: "Law 133/1951 is the profession's charter: the register of practitioners (سجل مزاولة المهنة), the registration examination, and professional discipline." },
  { code: "EGY-PROF-02", diff: 2, stem: "To be registered in the general register of practitioners (permitting audit practice), an applicant must (among other conditions):", options: ["Pass the profession's registration examination after practical experience, alongside the qualification and good-standing requirements", "Hold any university degree only", "Be an employee of the Central Auditing Organization", "Own an audit firm"], answer: 0, explanation: "The route combines accounting education, supervised practical experience, and passing the register's professional examinations — the Egyptian practice-exam system the Exam Center's blueprint models." },
  { code: "EGY-PROF-03", diff: 2, stem: "The professional body historically issuing the Egyptian Standards on Auditing (the Arabic ISA equivalents) is:", options: ["The Egyptian Society of Accountants and Auditors (ESAA)", "The Central Bank of Egypt", "The Egyptian Exchange", "The Ministry of Interior"], answer: 0, explanation: "The Egyptian Society of Accountants and Auditors issues the ESAs, which adopt the ISAs with Egyptian adaptations; registered auditors must apply them." },
  { code: "EGY-PROF-04", diff: 3, stem: "An auditor registered to audit listed companies in Egypt must additionally be:", options: ["Registered with the Financial Regulatory Authority (FRA) for the relevant listing categories", "An employee of the Egyptian Exchange", "A member of parliament", "Appointed by the Central Auditing Organization"], answer: 0, explanation: "FRA maintains the register of auditors eligible to audit entities under its supervision (listed companies, non-bank financial institutions), with eligibility conditions and rotation discipline." },
]

const companies: RawBankQ[] = [
  { code: "EGY-CO-01", diff: 1, stem: "Under Companies Law 159/1981, the statutory auditor of an S.A.E. (joint stock company) is appointed by:", options: ["The ordinary general assembly of shareholders", "The chairman alone", "The board of directors", "The tax authority"], answer: 0, explanation: "The general assembly appoints (and fixes the fees of) the auditor — the auditor's mandate flows from the shareholders, not management." },
  { code: "EGY-CO-02", diff: 2, stem: "The statutory auditor's duties under the Companies Law include:", options: ["Verifying the company's books and records, attending general assemblies, and reporting on the FS in the legally prescribed form", "Approving the dividend policy", "Setting executive salaries", "Signing the tax return"], answer: 0, explanation: "The law frames the auditor as the assembly's watchdog: full access to books, mandatory assembly attendance, and the statutory auditor's report in the prescribed format." },
  { code: "EGY-CO-03", diff: 2, stem: "The statutory auditor of an Egyptian company must be independent of it. Which is the clearest breach?", options: ["The auditor is a member of the company's board of directors", "The auditor audited the same company last year with no rotation breach", "The auditor's firm bought goods from the company at arm's length", "The auditor attended the general assembly"], answer: 0, explanation: "Board membership is an outright prohibition — being a director while auditing destroys the independence the law and the IESBA Code both demand." },
  { code: "EGY-CO-04", diff: 3, stem: "An Egyptian S.A.E.'s auditor discovers acts by management that gravely harm the company. Under the Companies Law's spirit and the ESAs, the auditor's appropriate channel is:", options: ["Report the matter in the general assembly (those charged with governance) — and follow statutory reporting duties where they apply", "Publish a newspaper notice first", "Quietly resign without saying why", "Bill the company for the investigation"], answer: 0, explanation: "The assembly is the statutory forum; escalation beyond it follows specific legal duties (e.g., FRA rules for supervised entities) — not unilateral publicity." },
]

const banking: RawBankQ[] = [
  { code: "EGY-BANK-01", diff: 2, stem: "Under Banking Law 194/2020, Egyptian banks must appoint:", options: ["Two external auditors, one of whom must be registered with the Central Bank of Egypt's framework for bank auditors", "One external auditor only", "The Central Auditing Organization as sole auditor", "Internal auditors instead of external ones"], answer: 0, explanation: "Egyptian banks carry a dual-auditor regime under CBE supervision — a distinctive feature of the Egyptian audit environment exam candidates are expected to know." },
  { code: "EGY-BANK-02", diff: 2, stem: "External auditors of Egyptian banks are supervised primarily by:", options: ["The Central Bank of Egypt, including through its framework for auditor oversight and meetings on findings", "The Egyptian Exchange", "The Ministry of Tourism", "The general commercial register only"], answer: 0, explanation: "CBE supervises bank audits: auditor registration criteria, tripartite/three-way meetings with bank management and auditors, and access to auditor workpapers on CBE request." },
  { code: "EGY-BANK-03", diff: 3, stem: "Egyptian banks apply the CBE's instructions on credit-loss provisioning. For the external auditor this means:", options: ["Evaluating the bank's ECL/IFRS 9 implementation against both the framework and CBE instructions — a specialized, high-risk audit area", "Blindly accepting CBE provisioning as GAAP", "Ignoring provisioning because the CBE has already reviewed it", "Delegating provisioning review to internal audit"], answer: 0, explanation: "The auditor tests the bank's model, data and governance — CBE instructions define the regulatory floor, but the audit opinion is still the auditor's own under the applicable framework." },
]

const institutions: RawBankQ[] = [
  { code: "EGY-INST-01", diff: 1, stem: "The Financial Regulatory Authority (FRA) supervises:", options: ["Non-bank financial services and capital markets — listed companies, brokerage, mutual funds, insurance, mortgage finance and leasing", "Commercial banking only", "State administrative audits", "Auditing standards drafting"], answer: 0, explanation: "FRA (founded 2009, superseding EFSA/CMA) is the capital-markets and non-bank financial-services regulator — its register governs which auditors may audit the entities under its umbrella." },
  { code: "EGY-INST-02", diff: 1, stem: "The Central Auditing Organization (CAO / الجهاز المركزي للمحاسبات) is responsible for:", options: ["Auditing state bodies, public-sector entities and public funds", "Regulating the stock exchange", "Issuing IFRS", "Auditing all private companies"], answer: 0, explanation: "The CAO is the state's audit institution — control over public entities and public money — constitutionally distinct from private-practice external audit." },
  { code: "EGY-INST-03", diff: 2, stem: "Egyptian Accounting Standards (EAS) are best described as:", options: ["A national framework substantially converged with IFRS, with local adaptations and Egyptian-specific standards where needed", "A translation of US GAAP", "Fully identical to IFRS in every respect", "An entirely standalone system unrelated to IFRS"], answer: 0, explanation: "The EAS family converges with IFRS while keeping local standards (e.g., investment in real estate) and prescribed formats — the auditor's framework reference is the EAS text as issued." },
]

const tax: RawBankQ[] = [
  { code: "EGY-TAX-01", diff: 1, stem: "The standard corporate income tax rate for most Egyptian companies under the Unified Tax Law 91/2005 is:", options: ["22.5%", "14%", "20% flat on revenue", "0% for audited companies"], answer: 0, explanation: "22.5% on net taxable profits is the standard rate (with special regimes — e.g., petroleum and Suez Canal percentages — outside it)." },
  { code: "EGY-TAX-02", diff: 1, stem: "The standard VAT rate in Egypt under Law 67/2016 is:", options: ["14%", "22.5%", "10%", "5%"], answer: 0, explanation: "14% is the standard VAT rate, with zero-rated and exempt categories and a higher rate on a short negative list (e.g., telecommunication services)." },
  { code: "EGY-TAX-03", diff: 2, stem: "Payroll (salaries) tax in Egypt is:", options: ["Progressive over annual brackets, rising to a top marginal rate of 27.5%", "A flat 14%", "A flat 22.5%", "Exempt for seniors only"], answer: 0, explanation: "The 2023-updated progressive ladder tops at 27.5% — payroll computation and compliance is a recurring audit area for Egyptian entities." },
  { code: "EGY-TAX-04", diff: 2, stem: "For the external auditor, the tax balances and computations are tested mainly against which assertions/risk pairs?", options: ["Completeness of tax liabilities/charges and accuracy of computations, including deferred tax under the framework", "Only the cash paid figure", "Management's intention to pay", "The auditor's own tax opinion"], answer: 0, explanation: "Taxes are completeness-and-accuracy territory: unrecorded VAT or payroll charges, and deferred-tax measurement, dominate Egyptian audit adjustments." },
  { code: "EGY-TAX-05", diff: 3, stem: "A company capitalizes VAT input on a mixed-use expense without the required allocation. The most direct audit concern is:", options: ["Overstated recoverable VAT (an asset valuation and compliance exposure)", "Revenue cut-off", "Going concern", "Related-party disclosure"], answer: 0, explanation: "Mixed-use input VAT requires apportionment; full recovery claims overstate the VAT receivable and create a compliance exposure — a factual misstatement risk." },
]

const eas: RawBankQ[] = [
  { code: "EAS-01", diff: 1, stem: "Egyptian Accounting Standard No. 1 corresponds most closely to which IFRS/IAS topic?", options: ["Presentation of financial statements", "Leases", "Revenue recognition", "Employee benefits"], answer: 0, explanation: "EAS 1 governs presentation of financial statements — the Egyptian counterpart of IAS 1, with local format prescriptions." },
  { code: "EAS-04", diff: 2, stem: "EAS 4 (Income Statement) is notable because it:", options: ["Prescribes the Egyptian income statement presentation/formats that listed financial statements follow", "Abolishes accrual accounting", "Requires single-step statements only", "Applies only to banks"], answer: 0, explanation: "EAS 4 anchors the local income-statement format — presentation checks in an Egyptian audit reference the EAS-prescribed line items." },
  { code: "EAS-05", diff: 2, stem: "Under EAS 5, the statement of cash flows classifies flows as:", options: ["Operating, investing, and financing activities (with the Egyptian format notes)", "Operating and non-operating only", "Cash and bank only", "None — cash flows are optional"], answer: 0, explanation: "EAS 5 follows the three-way classification of IAS 7 adapted to the Egyptian presentation environment." },
  { code: "EAS-10", diff: 2, stem: "EAS 10 covers:", options: ["Events after the balance sheet date — the adjusting/non-adjusting distinction", "Leases", "Goodwill", "Hedge accounting"], answer: 0, explanation: "EAS 10 mirrors IAS 10: conditions existing at year-end adjust; conditions arising after are disclosed when material." },
  { code: "EAS-12", diff: 2, stem: "EAS 12 addresses:", options: ["Income taxes, including deferred tax accounting", "Inventory costing", "Segment reporting", "Borrowing costs"], answer: 0, explanation: "EAS 12 is the income-tax standard — current and deferred tax measurement and presentation in the Egyptian framework." },
  { code: "EAS-13", diff: 3, stem: "EAS 13 (Investment in Real Estate) is distinctive because it:", options: ["Provides an Egyptian-specific treatment for income-producing real estate", "Prohibits property accounting entirely", "Applies only to hotels", "Duplicates EAS 17 exactly"], answer: 0, explanation: "EAS 13 is one of the Egyptian-specific standards — real estate investment accounting with its own measurement options, distinct from owner-occupied PPE under EAS 17." },
  { code: "EAS-17", diff: 1, stem: "EAS 17 deals with:", options: ["Property, plant and equipment", "Revenue", "Financial instruments", "Provisions"], answer: 0, explanation: "EAS 17 = PPE: capitalization, depreciation, and the measurement bases permitted under the Egyptian standard." },
  { code: "EAS-20", diff: 2, stem: "EAS 20 requires disclosure of:", options: ["Related-party relationships and transactions, including amounts and balances", "Only the directors' names", "Salaries of all staff", "Customer lists"], answer: 0, explanation: "EAS 20 mirrors IAS 24 — related-party disclosure obligations the auditor tests for completeness (the hardest assertion)." },
  { code: "EAS-CONV-01", diff: 2, stem: "When an EAS diverges in wording from IFRS, the Egyptian auditor's primary reference is:", options: ["The EAS as issued in Egypt — the applicable framework for Egyptian statutory financial statements", "The IFRS text", "The IFRS for SMEs", "Management's preference"], answer: 0, explanation: "The applicable framework governs: where the EAS departs from IFRS, the Egyptian standard is the measurement basis for statutory statements (with the EAS/IFRS relationship understood for analysis)." },
  { code: "EAS-CONV-02", diff: 3, stem: "An Egyptian listed company claims an IFRS-only treatment that contradicts its EAS counterpart. The auditor's first evaluation is:", options: ["Whether the treatment complies with the EAS — the applicable framework for the statutory statements — with any non-compliance evaluated for materiality and reporting consequences", "Whether IFRS is more popular globally", "Whether the analyst community prefers it", "Whether the tax effect is favourable"], answer: 0, explanation: "Framework compliance is binary: the FS claim 'prepared in accordance with EAS', and departures are potential misstatements, whatever their international pedigree." },
]

export const EGYPT = [
  ...qs("Egypt — Profession", "egypt", prof),
  ...qs("Egypt — Companies Law", "egypt", companies),
  ...qs("Egypt — Banking", "egypt", banking),
  ...qs("Egypt — Institutions", "egypt", institutions),
  ...qs("Egypt — Tax", "egypt", tax),
  ...qs("EAS", "egypt", eas),
]
