import { qs, type RawBankQ } from "./seed-types"

/* ISA 500–620: evidence, confirmations, sampling, estimates, related
   parties, subsequent events, going concern, representations, groups,
   internal audit, experts. */

const isa500: RawBankQ[] = [
  { code: "ISA500-01", diff: 1, stem: "Sufficient appropriate audit evidence means evidence that is:", options: ["Both adequate in quantity (sufficiency) and relevant and reliable in quality (appropriateness)", "Always documentary", "Enough to satisfy the client", "The cheapest available"], answer: 0, explanation: "Sufficiency = quantity (driven by risk and materiality); appropriateness = relevance + reliability of the evidence." },
  { code: "ISA500-02", diff: 2, stem: "Which is generally the MOST reliable audit evidence?", options: ["Evidence obtained directly by the auditor (e.g., physical inspection, direct confirmation)", "A verbal statement from management", "A photocopy provided by the client", "A management-internal memo"], answer: 0, explanation: "Reliability increases when evidence is obtained directly by the auditor, from external sources, in writing, under effective controls, and originals over copies." },
  { code: "ISA500-03", diff: 2, stem: "Information produced by the client (e.g., an aging report) may be used as audit evidence when:", options: ["The auditor evaluates its accuracy and completeness by testing the underlying data and controls over its preparation", "Management signs it", "It is printed on official letterhead", "It reconciles to the ledger at a high level"], answer: 0, explanation: "Client-produced information must itself be validated — accuracy and completeness testing of source data is a precondition of its use as evidence." },
  { code: "ISA500-04", diff: 2, stem: "Audit evidence is meant to be:", options: ["Cumulative — gathered from risk assessment, controls testing, and substantive procedures together", "Only from substantive testing", "Only from the final trial balance", "Fixed at the planning stage"], answer: 0, explanation: "Evidence accumulates across the audit; each phase informs the next, and conclusions rest on the whole body of evidence." },
  { code: "ISA500-05", diff: 3, stem: "The reliability of evidence generated externally but held by the entity is increased when:", options: ["The source is independent, knowledgeable, and the information is held unaltered by a controlled process", "It is emailed by the CFO", "It is older", "It agrees with management's expectations"], answer: 0, explanation: "External-source evidence is stronger when the entity cannot alter it and the source is competent — which is why original confirmations and sealed records outrank forwarded emails." },
  { code: "ISA501-01", diff: 2, stem: "For inventory existence, ISA 501 requires attendance at physical counts unless:", options: ["Impracticable — in which case alternative procedures (inspection of later sales/purchases or roll-back to records) provide evidence", "The client says the count is accurate", "The fee is too small", "Inventory is under 5% of assets"], answer: 0, explanation: "Attendance at counts is the default for existence; impracticability triggers alternatives like roll-forward/back procedures on reliable records." },
  { code: "ISA501-02", diff: 2, stem: "Inventory held by a third party (public warehouse) is best verified by:", options: ["Obtaining a direct confirmation from the custodian and considering its integrity and competence, or inspecting the goods", "The client's warehouse receipt alone", "Management's representation", "The prior year file"], answer: 0, explanation: "Third-party-held inventory: confirm with the custodian directly, supplement with inspection or other reports (e.g., warehouse's own audit) when risk is high." },
  { code: "ISA501-03", diff: 2, stem: "For litigation and claims, the most direct evidence is:", options: ["A response to a letter of inquiry from the entity's external legal counsel", "Management's legal provisions schedule", "Court filings found online", "The CFO's summary of expected outcomes"], answer: 0, explanation: "Direct communication with legal counsel through the inquiry letter is the mandated primary procedure for completeness of claims and assessed outcomes." },
  { code: "ISA501-04", diff: 3, stem: "For segments disclosed under IFRS 8, the auditor's procedures include:", options: ["Obtaining an understanding of management's segment identification process and analytical procedures consistent with that process, plus tests where risk warrants", "Recomputing the consolidated totals only", "Confirming segments with the stock exchange", "Nothing — segments are management's own choice"], answer: 0, explanation: "Segment disclosures follow management's internal reporting model; the auditor tests that process and applies analytics to disclosed segment data." },
]

const isa505: RawBankQ[] = [
  { code: "ISA505-01", diff: 1, stem: "Positive confirmation requests ask the confirming party to:", options: ["Respond in all cases — whether agreeing or disagreeing with the recorded amount", "Respond only if disagreeing", "Sign and return the reconciliation", "Call the auditor"], answer: 0, explanation: "Positive = respond either way. Negative = respond only if disagreeing — with far weaker evidential force." },
  { code: "ISA505-02", diff: 2, stem: "A negative confirmation may only be appropriate when:", options: ["Risk of material misstatement is low, the population has many small homogeneous items, and a high response rate of non-receipt can be expected", "The balance is large and significant", "Fraud risk is high", "The client refuses confirmations"], answer: 0, explanation: "Three cumulative conditions — low risk, many small items, expected high non-response rate — make the absence of a reply corroborative; otherwise positives are required." },
  { code: "ISA505-03", diff: 2, stem: "The auditor maintains control over confirmation requests by:", options: ["Selecting items, preparing and sending requests, and receiving responses directly — never letting the client intermediate", "Emailing blank requests to the client to forward", "Letting the CFO's assistant collect replies", "Posting requests through the client's mailroom"], answer: 0, explanation: "Confirmation reliability collapses if the client controls the channel — the auditor selects, sends, and receives directly." },
  { code: "ISA505-04", diff: 2, stem: "A bank confirmation reply reveals a previously unrecorded loan. This indicates a potential:", options: ["Completeness misstatement in borrowings", "Occurrence issue in revenue", "Valuation issue in inventory", "Presentation issue in equity"], answer: 0, explanation: "Confirmations excel at completeness of balances and terms — the undisclosed loan is the classic bank-confirmation catch." },
  { code: "ISA505-05", diff: 3, stem: "An electronically returned confirmation (e-mail/web) is acceptable when the auditor:", options: ["Verifies the sender's authenticity through direct contact or established secure channels", "Prints it on the client's printer first", "Accepts any email address", "Considers all emails reliable"], answer: 0, explanation: "Electronic responses are usable once the auditor authenticates their source — confirming the respondent's address through independent means." },
  { code: "ISA505-06", diff: 3, stem: "No reply to a positive receivables confirmation after follow-up. The auditor performs alternative procedures such as:", options: ["Inspecting subsequent cash receipts, sales contracts, shipping documents, and the sales cycle records", "Asking the sales manager for assurance", "Extending the reporting deadline", "Qualifying immediately without alternatives"], answer: 0, explanation: "ISA 505's alternative-procedure ladder: subsequent receipts, contracts, shipping docs; only if those fail does a scope limitation/opinion issue arise." },
]

const isa510: RawBankQ[] = [
  { code: "ISA510-01", diff: 2, stem: "In an INITIAL audit engagement, the auditor's objective for opening balances is to obtain evidence that:", options: ["Opening balances contain no misstatements materially affecting the current period, and accounting policies are consistently applied", "Opening balances equal the prior year's published closing exactly in all cases", "The predecessor auditor was competent", "The prior year was free of fraud"], answer: 0, explanation: "ISA 510: opening balances are fairly stated and policies are consistent — with prior-year adjustment effects correctly passed forward." },
  { code: "ISA510-02", diff: 2, stem: "If the predecessor's working papers are unavailable and inventory opening balances cannot be verified, potential outcomes include:", options: ["A qualified or disclaimed opinion depending on materiality and pervasiveness", "An unmodified opinion with an EOM", "An adverse opinion always", "No effect — opening balances never affect the opinion"], answer: 0, explanation: "Inability to obtain evidence about opening balances — where the effects could be material — results in modified opinions per ISA 705." },
  { code: "ISA510-03", diff: 2, stem: "Reading the predecessor's most recent financial statements and the predecessor's report helps the auditor determine:", options: ["Whether there are matters (including accounting policies and qualifications) affecting the current period", "The predecessor's fee level", "Whether to hire the predecessor's staff", "The client's credit rating"], answer: 0, explanation: "Prior-period qualifications, estimate-heavy areas, and accounting-policy choices carry directly into the current audit." },
]

const isa520: RawBankQ[] = [
  { code: "ISA520-01", diff: 1, stem: "Substantive analytical procedures consist of:", options: ["Evaluations of financial information through analysis of plausible relationships among financial and non-financial data", "Recalculation of depreciation", "Physical inspection of assets", "Confirmations with banks"], answer: 0, explanation: "Analytics study relationships — financial vs financial, financial vs non-financial — against expectations formed independently by the auditor." },
  { code: "ISA520-02", diff: 2, stem: "When are substantive analytics alone usually sufficient?", options: ["Rarely for significant risks — they cannot alone provide sufficient appropriate evidence for significant risks", "Always for revenue", "Never under any circumstance", "Only for payroll"], answer: 0, explanation: "ISA 330/520: significant risks require tests of details; analytics can complement but never carry a significant risk alone." },
  { code: "ISA520-03", diff: 2, stem: "Expectations for analytics are more precise when:", options: ["Data is disaggregated (monthly, by location/product line), predictable, and from a reliable information system", "Data is annual and aggregated only", "Management provides the expectation", "The account is small"], answer: 0, explanation: "Disaggregation and predictability sharpen the expectation — an annual blended number hides exactly the anomalies analytics should catch." },
  { code: "ISA520-04", diff: 3, stem: "The auditor investigates differences between expectations and recorded amounts by:", options: ["Inquiring of management and corroborating management's responses, and performing other procedures when the responses are unsatisfactory", "Adjusting the expectation until it matches", "Ignoring differences under 10%", "Documenting the difference as a sampling error"], answer: 0, explanation: "Differences above the acceptable threshold require inquiry + corroboration; the auditor cannot close them by revising expectations to fit the data." },
]

const isa530: RawBankQ[] = [
  { code: "ISA530-01", diff: 1, stem: "Sampling risk is:", options: ["The risk that the auditor's conclusion based on a sample differs from the conclusion if the entire population were tested", "The risk of picking the wrong ledger", "The same as non-sampling risk", "The risk the client rejects the sample"], answer: 0, explanation: "Sampling risk comes from testing less than 100%; non-sampling risk comes from anything else (wrong procedures, mistakes) and is not reduced by bigger samples." },
  { code: "ISA530-02", diff: 2, stem: "For tests of details, sampling risk manifests when the auditor:", options: ["Concludes a balance is not materially misstated when it is, or rejects it when it is fine", "Uses wrong exchange rates", "Misses the reporting deadline", "Counts inventory on the wrong date"], answer: 0, explanation: "The two faces of detail-testing sampling risk: incorrect acceptance (risk of wrong opinion) and incorrect rejection (efficiency loss)." },
  { code: "ISA530-03", diff: 2, stem: "Statistical sampling permits the auditor to:", options: ["Measure and control sampling risk through statistical theory", "Skip documentation", "Ignore stratification", "Skip evaluating the population's completeness"], answer: 0, explanation: "Statistics quantify sampling risk; the auditor still must consider population completeness and representativeness of the sample." },
  { code: "ISA530-04", diff: 2, stem: "Before sampling, the auditor tests that the population is:", options: ["Complete and appropriate for the audit objective — e.g., all items processed in the period appear in the population", "As small as possible", "Sorted alphabetically", "Approved by management"], answer: 0, explanation: "A sample from an incomplete population cannot detect completeness misstatements — the missing items are precisely where fraud hides." },
  { code: "ISA530-05", diff: 3, stem: "The auditor discovers a sample deviation in a key control. The auditor should:", options: ["Investigate the nature and cause, consider the effect on the risk assessment, and may extend testing or conclude the control is ineffective", "Ignore a single deviation", "Immediately issue a disclaimer", "Let management choose another sample"], answer: 0, explanation: "Deviations are diagnosed first — systematic vs anomalous, fraud-related vs error — then the response follows: expanded testing or abandoning control reliance." },
]

const isa540: RawBankQ[] = [
  { code: "ISA540-01", diff: 1, stem: "ISA 540 (Revised) covers accounting estimates, including:", options: ["Fair value estimates and related disclosures", "Cash balances", "Trade receivable confirmation", "Fixed asset physical verification"], answer: 0, explanation: "The revised ISA 540 spans all accounting estimates — including fair value — and their disclosure, with a stepped approach to complexity and estimation uncertainty." },
  { code: "ISA540-02", diff: 2, stem: "The auditor's objective for estimates is to obtain sufficient appropriate evidence that accounting estimates are:", options: ["Reasonable in the context of the applicable framework and appropriately measured and disclosed", "Exactly equal to management's number", "Conservative (always understated)", "Zero unless proven"], answer: 0, explanation: "Framework-reasonableness: the point estimate or range within which the true amount lies is measured and disclosed per the framework." },
  { code: "ISA540-03", diff: 2, stem: "Estimation uncertainty:", options: ["Is the susceptibility of an estimate to an inherent lack of precision, driving risk assessment and the response", "Means the auditor cannot test the estimate at all", "Requires automatic qualification", "Applies only to level-3 fair values"], answer: 0, explanation: "Higher estimation uncertainty raises assessed risk and expands procedures: how-acquired data, methods, assumptions, and management's bias evaluation." },
  { code: "ISA540-04", diff: 3, stem: "The 'stand-back' requirement means the auditor:", options: ["Steps back and evaluates whether the overall picture of the estimate (point estimate, range, disclosures) is reasonable in the context of the audited FS", "Physically stands back from the workpaper", "Delegates review to internal audit", "Recomputes the estimate with the client's model only"], answer: 0, explanation: "The stand-back is a holistic reasonableness check of estimate outcomes and disclosures — catching directionally biased estimates that pass item-by-item testing." },
  { code: "ISA540-05", diff: 3, stem: "For management's significant assumptions, the auditor evaluates whether they are:", options: ["Reasonable and consistent with the framework, the entity's circumstances, and the auditor's understanding of the business and industry", "Always conservative", "Identical to last year's", "Provided by the auditor"], answer: 0, explanation: "Assumptions face three tests: framework reasonableness, internal consistency, and consistency with industry and entity facts." },
  { code: "ISA540-06", diff: 2, stem: "When an ECL (expected credit loss) provision on receivables is the estimate, the most responsive test of the MODELS is:", options: ["Testing the model's logic and data, back-testing prior estimates against outcomes, and evaluating assumptions against external data", "Recomputing one invoice's aging", "Confirming the receivable balance with the customer", "Inspecting the aging report print date"], answer: 0, explanation: "Estimate audits test model + data + assumptions + back-testing; confirming the balance tests existence, not the estimate's measurement." },
]

const isa550: RawBankQ[] = [
  { code: "ISA550-01", diff: 1, stem: "A related party exists when one party:", options: ["Controls, significant influence, joint control, or key management relationships exist with the reporting entity", "Owes the entity money on trade terms", "Is a customer over 10% of revenue only", "Shares the same tax office"], answer: 0, explanation: "Related parties: control, joint control, significant influence, key management personnel and their close families — plus the entity's own transactions with them." },
  { code: "ISA550-02", diff: 2, stem: "The auditor's risk assessment for related parties requires awareness that:", options: ["Related-party transactions may be motivated by fraud — they are a fraud risk factor to evaluate, not a separate sub-ledger", "All related-party transactions are illegal", "Related parties must be eliminated at the entity level", "Family relationships always involve fees"], answer: 0, explanation: "ISA 550 + ISA 240: related-party relationships carry fraud risk channels — undisclosed control, misrepresented transfers, disguised loans." },
  { code: "ISA550-03", diff: 2, stem: "If the auditor identifies significant transactions outside the normal course of business, the auditor should:", options: ["Inspect the underlying agreements and evaluate the business rationale (or absence of one) and whether disclosure is adequate", "Record them as normal sales", "Wait for management to disclose", "Qualify the opinion automatically"], answer: 0, explanation: "Out-of-the-ordinary transactions are exactly where undisclosed related-party dealing hides — the auditor inspects terms and asks for the rationale." },
  { code: "ISA550-04", diff: 3, stem: "Management discloses that transactions with a major distributor 'were made on terms equivalent to arm's length'. The auditor should:", options: ["Obtain evidence supporting the assertion — comparing terms to market equivalents — before accepting the disclosure", "Accept it since management asserted it", "Delete the assertion from the FS", "Qualify without testing"], answer: 0, explanation: "Management's arm's-length assertions are precisely the kind of statement requiring substantiation with comparable evidence, not mere acceptance." },
]

const isa560: RawBankQ[] = [
  { code: "ISA560-01", diff: 1, stem: "The auditor's responsibility for subsequent events extends:", options: ["To the date of the auditor's report — events after that date are not the auditor's responsibility to detect, though facts discovered later have rules", "Forever after year-end", "Only to year-end", "Until the tax return is filed"], answer: 0, explanation: "Active procedures run to the report date; facts becoming known to the auditor AFTER the report trigger the dual-dated/withdrawal regime." },
  { code: "ISA560-02", diff: 2, stem: "A customer bankruptcy in February (year-end 31 Dec, report in March) indicates:", options: ["A condition existing at the balance sheet date — evaluate whether the receivable was recoverable at year-end and adjust", "Only a year 2 event — no adjustment ever", "A disclosure-only matter always", "Force majeure"], answer: 0, explanation: "Bankruptcy following sustained distress is typically an adjusting event: the credit loss existed at year-end and the FS must reflect it." },
  { code: "ISA560-03", diff: 2, stem: "A warehouse fire in January, after year-end, destroying goods in transit not yet sold. This is:", options: ["A non-adjusting event — disclose if material, no adjustment", "An adjusting event requiring inventory write-down", "Ignored entirely", "A scope limitation"], answer: 0, explanation: "The fire's conditions arose after year-end — no effect on year-end balances, but material non-adjusting events are disclosed." },
  { code: "ISA560-04", diff: 3, stem: "The auditor becomes aware, after issuance, of a misstatement whose existence was known before the report date. The auditor should:", options: ["Assess the effect and follow procedures — potentially amending the report — because facts existing at the report date change the responsibility", "Do nothing — the report is final", "Silently fix next year", "Sue the client"], answer: 0, explanation: "Knowledge of facts EXISTING at the report date (even learned after) reactivates the auditor's duty — amendment, new report, or communication per ISA 560." },
]

const isa570: RawBankQ[] = [
  { code: "ISA570-01", diff: 1, stem: "Management's assessment of going concern covers at minimum:", options: ["The period from the date of approval of the financial statements, without being less than twelve months", "One year from year-end exactly", "Five years", "No specific period"], answer: 0, explanation: "The assessment period runs at least 12 months from FS approval — not from the balance sheet date — a common exam trap." },
  { code: "ISA570-02", diff: 2, stem: "A material uncertainty related to going concern exists when:", options: ["Events or conditions may cast significant doubt on the entity's ability to continue as a going concern", "The entity is profitable", "The auditor simply feels uneasy", "Cash declined 5%"], answer: 0, explanation: "Material uncertainty = doubt so significant it must be disclosed; its existence (given adequate disclosure) triggers the MUM paragraph, not a qualification." },
  { code: "ISA570-03", diff: 2, stem: "Adequate disclosure of a material uncertainty + unmodified opinion:", options: ["The auditor adds a Material Uncertainty Related to Going Concern paragraph — the opinion itself stays unmodified", "Requires a qualified opinion", "Requires an adverse opinion", "Requires a disclaimer"], answer: 0, explanation: "MUM paragraph = unmodified opinion + highlighted uncertainty. Qualification arises only when disclosure is inadequate (or the basis is wrong)." },
  { code: "ISA570-04", diff: 3, stem: "Management intends to pay a large dividend AFTER year-end that would break a covenant, and the FS assume going concern. The auditor should:", options: ["Evaluate whether the intended dividend is compatible with the going-concern basis and the assessment period facts", "Accept the intention since dividends are decided post year-end", "Ignore — dividends are never audit matters", "Qualify because the dividend is not paid"], answer: 0, explanation: "Intentions affecting liquidity within the assessment period (like draining cash) are part of going-concern evaluation — future intentions are not free of consequences." },
  { code: "ISA570-05", diff: 3, stem: "Management refuses to extend its going-concern assessment beyond six months. The auditor's likely conclusion is:", options: ["A scope limitation — potentially a disclaimer if the possible effects are material and pervasive", "Unmodified with EOM", "Adverse opinion", "Withdrawal is the only option"], answer: 0, explanation: "ISA 570: refusal to assess or extend beyond management's (too short) period is a limitation on evidence; the response climbs the opinion ladder per ISA 705." },
]

const isa580: RawBankQ[] = [
  { code: "ISA580-01", diff: 1, stem: "Written representations are:", options: ["Necessary audit evidence — the auditor requests management to provide written representations on matters material to the FS", "Optional if other evidence exists", "A substitute for procedures", "Only for listed clients"], answer: 0, explanation: "The general representation (responsibility + completeness of information and transactions) is mandatory; specific representations accompany significant judgments." },
  { code: "ISA580-02", diff: 2, stem: "The representation letter should be dated:", options: ["As of the same date as the auditor's report (or as near as possible)", "At the start of fieldwork", "On the last day of the prior year", "By the client's lawyer"], answer: 0, explanation: "Dating at (or near) the report date ensures it covers events to the audit's completion." },
  { code: "ISA580-03", diff: 2, stem: "If management does not provide requested written representations, the auditor should:", options: ["Express a qualified or disclaimed opinion or, where possible, withdraw", "Proceed — other evidence compensates", "Perform more analytics", "Note it in the file only"], answer: 0, explanation: "Refusal is a scope limitation on matters the ISAs require — the ladder of ISA 706/705 applies, up to withdrawal where permitted." },
  { code: "ISA580-04", diff: 3, stem: "A representation that materially contradicts other audit evidence means the auditor:", options: ["Investigates the conflict and may conclude the reliability of other evidence is affected — possibly a scope limitation or fraud consideration", "Always accepts the written word", "Drops the contradictory evidence", "Replaces management"], answer: 0, explanation: "Contradiction undermines the whole body of evidence — ISA 580 makes this a serious matter for investigation and re-evaluation of everything touching it." },
]

const isa600: RawBankQ[] = [
  { code: "ISA600-01", diff: 2, stem: "Under ISA 600, the group auditor's responsibility for components is:", options: ["Full responsibility for the group opinion — component auditor work is only a means to that end", "None — components are the component auditor's problem", "Limited to consolidation eliminations", "Only for domestic components"], answer: 0, explanation: "The group engagement partner owns the group opinion entirely; component auditors' work is integrated and directed, never outsourced responsibility." },
  { code: "ISA600-02", diff: 2, stem: "'Significant components' for group audit purposes include:", options: ["Components of individual financial significance and components with significant risks due to their nature or circumstances", "Only the largest revenue entities", "Only foreign components", "Only newly acquired subsidiaries"], answer: 0, explanation: "Two buckets: individually significant components, and those with significant risks (specialized, or engaged in unusual transactions)." },
  { code: "ISA600-03", diff: 3, stem: "The group auditor's decision to assume responsibility for the component auditor's work depends on:", options: ["The group team's involvement in the component's risk assessment and reviews, and the component auditor's compliance with the group audit instructions", "The component auditor's fee", "The time zones", "Tax grouping rules"], answer: 0, explanation: "Involvement (direction, review of working papers, access to documentation) and explicit instructions define whether the group auditor uses the work — and how." },
  { code: "ISA600-04", diff: 3, stem: "The group team must perform consolidation procedures including:", options: ["Checking the consolidation adjustments, eliminations, translation of foreign operations under the framework, and assessing component reporting-date consistency", "Only footing the consolidation schedule", "Reperforming every component's entire audit", "Confirming the group structure with legal counsel only"], answer: 0, explanation: "Consolidation procedures cover eliminations, uniform reporting dates/policies adjustments, and translation — the heart of group-audit risk." },
]

const isa610: RawBankQ[] = [
  { code: "ISA610-01", diff: 2, stem: "Using internal audit work is permissible when the external auditor evaluates internal audit as having:", options: ["Objectivity, technical competence, and a systematic and disciplined approach (and applies it to the relevant work)", "The lowest cost", "The most staff", "Reporting to the CFO only"], answer: 0, explanation: "Three evaluation axes — objectivity, competence, systematic discipline — decide whether internal audit's work can be used and for what." },
  { code: "ISA610-02", diff: 3, stem: "The external auditor may NEVER delegate to internal audit:", options: ["Judgments and evaluations of evidence — these stay with the external team", "Walkthrough documentation", "File assembly", "Meeting logistics"], answer: 0, explanation: "The external auditor may use internal audit's work as input, but all significant judgments, risk assessment, and evidence evaluation remain external." },
]

const isa620: RawBankQ[] = [
  { code: "ISA620-01", diff: 2, stem: "The auditor's expert may be needed when:", options: ["The matter involves specialized skills or knowledge beyond the team's — e.g., valuation, actuarial, or engineering issues", "The fee budget is large", "The client insists", "The deadline is tight"], answer: 0, explanation: "Expertise gaps — measurement techniques, assumptions, models — trigger the use of the auditor's expert (distinct from management's expert, which is tested, not used)." },
  { code: "ISA620-02", diff: 3, stem: "The auditor must evaluate the expert's:", options: ["Competence, capabilities, and objectivity, and the adequacy of the expert's work as audit evidence for the relevant assertion", "Degrees only", "Fee arrangement only", "Nationality"], answer: 0, explanation: "Competence + capability + objectivity, then the adequacy of the work product itself: sources, assumptions, and reasonableness of results." },
  { code: "ISA620-03", diff: 2, stem: "The report references the auditor's expert when:", options: ["The expert's work is of such importance that non-reference would be misleading", "The expert billed the client directly", "Always — every expert is named", "Never"], answer: 0, explanation: "Reference is exceptional: only when the expert's contribution is so central that silence would mislead users about where the opinion rests." },
]

export const ISA_EVIDENCE = [
  ...qs("ISA 500", "auditing", isa500.filter((q) => q.code.startsWith("ISA500"))),
  ...qs("ISA 501", "auditing", isa500.filter((q) => q.code.startsWith("ISA501"))),
  ...qs("ISA 505", "auditing", isa505),
  ...qs("ISA 510", "auditing", isa510),
  ...qs("ISA 520", "auditing", isa520),
  ...qs("ISA 530", "auditing", isa530),
  ...qs("ISA 540", "auditing", isa540),
  ...qs("ISA 550", "auditing", isa550),
  ...qs("ISA 560", "auditing", isa560),
  ...qs("ISA 570", "auditing", isa570),
  ...qs("ISA 580", "auditing", isa580),
  ...qs("ISA 600", "auditing", isa600),
  ...qs("ISA 610", "auditing", isa610),
  ...qs("ISA 620", "auditing", isa620),
]
