import { qs, type RawBankQ } from "./seed-types"

/* IESBA Code of Ethics — threats, safeguards, independence, NOCLAR,
   fees, professional behaviour. */

const threats: RawBankQ[] = [
  { code: "ETH-THR-01", diff: 1, stem: "The IESBA Code's five categories of threats are:", options: ["Self-interest, self-review, advocacy, familiarity, and intimidation", "Audit risk, business risk, fraud risk, tax risk, IT risk", "Fee, fee, fee, fee and fee", "Independence, objectivity, integrity, competence, diligence"], answer: 0, explanation: "The five threats are the Code's analytical backbone — every rules-based question resolves into identifying the threat, evaluating significance, and applying safeguards." },
  { code: "ETH-THR-02", diff: 2, stem: "An audit partner owns shares in an audit client. This is a:", options: ["Self-interest threat", "Advocacy threat", "Intimidation threat", "No threat at all"], answer: 0, explanation: "A direct financial interest in the client is the archetypal self-interest threat — under independence rules for audit clients it is prohibited outright, not merely safeguarded." },
  { code: "ETH-THR-03", diff: 2, stem: "The audit firm also prepares the client's financial statements that it then audits. This creates:", options: ["A self-review threat", "A familiarity threat", "An advocacy threat", "No threat if fees are low"], answer: 0, explanation: "Auditing your own work — the self-review threat. For audit clients, preparing the FS generally crosses the line (subject to the permitted statutory/accounting-services exceptions the Code carves). " },
  { code: "ETH-THR-04", diff: 2, stem: "A senior manager has audited the same client for nine consecutive years and now golf-partners with the CFO. This is:", options: ["A familiarity threat", "Self-interest only", "Intimidation", "Professional courtesy"], answer: 0, explanation: "Long association + personal relationships breed familiarity — the Code's answer for audit clients is rotation and a cooling-off period for key partners." },
  { code: "ETH-THR-05", diff: 2, stem: "The client's CEO threatens to switch auditors unless the partner drops a proposed audit adjustment. This is:", options: ["An intimidation threat", "An advocacy threat", "Self-review", "Acceptable negotiation"], answer: 0, explanation: "Pressure to replace the partner or lose the client is classic intimidation — documented, escalated to those charged with governance, and never resolved by quiet surrender." },
  { code: "ETH-THR-06", diff: 3, stem: "The conceptual framework approach of the Code requires the auditor to:", options: ["Identify threats, evaluate their significance, and apply safeguards to eliminate or reduce them to an acceptable level — documenting the analysis", "Follow a checklist of prohibited clients", "Refuse every non-audit service", "Rely on the client's ethics policy"], answer: 0, explanation: "Framework over rules: identify → evaluate → safeguard → document. Where no safeguard can reduce the threat, the interest or relationship must be eliminated." },
]

const independence: RawBankQ[] = [
  { code: "ETH-IND-01", diff: 1, stem: "Independence of mind means:", options: ["A state of mind permitting an opinion without effects that compromise professional judgment", "Never meeting the client", "A written declaration", "Rotation every year regardless"], answer: 0, explanation: "Independence comprises independence of mind (the actual state) and independence in appearance (what informed third parties would conclude) — both are required." },
  { code: "ETH-IND-02", diff: 2, stem: "For listed audit clients, partner rotation rules require a key audit partner to:", options: ["Rotate after no more than seven years (with a cooling-off period of two years before returning in the same role)", "Rotate every three years", "Never rotate", "Rotate only when the client asks"], answer: 0, explanation: "IESBA: seven years on, two off for the engagement partner role; the cooling-off period depends on the role the partner would return to." },
  { code: "ETH-IND-03", diff: 2, stem: "A firm may NOT audit a listed client when:", options: ["Total fees from that client exceed 15% of the firm's total fees for two consecutive years (prohibition with transition)", "Fees exceed 5% once", "The client is foreign", "Any non-audit service is provided"], answer: 0, explanation: "The 15% concentration rule for listed clients (checked over two consecutive years, with a pre-prohibition disclosure regime) guards against economic dependence." },
  { code: "ETH-IND-04", diff: 3, stem: "An audit team member's spouse works in the client's finance department on the closing team. The correct response is:", options: ["Remove the team member from the engagement (or the spouse's involvement creates an unmanageable self-interest/familiarity threat) after evaluating the role", "Ignore it — family is private", "Disclose to the client and continue regardless", "Reduce the audit fee"], answer: 0, explanation: "A close family member in a financial-reporting role for the audited entity is on the Code's restricted list — evaluation leads, in practice, to removal because safeguards rarely suffice." },
]

const fees: RawBankQ[] = [
  { code: "ETH-FEE-01", diff: 2, stem: "A contingent fee for an audit engagement is:", options: ["Prohibited", "Permitted with disclosure", "Permitted for listed clients", "Permitted if small"], answer: 0, explanation: "Contingent fees on audits (and other assurance engagements with opinion-level outcomes) are prohibited outright — the fee must not depend on the opinion's outcome." },
  { code: "ETH-FEE-02", diff: 2, stem: "A fee quoted 40% below the prior year for the same scope requires the firm to:", options: ["Evaluate whether the fee permits ISA-compliant performance and document the basis before accepting", "Decline always", "Accept without thought", "Accept and reduce scope"], answer: 0, explanation: "Low-ball fees are a self-interest threat to quality — acceptance requires a documented evaluation that the engagement can be resourced to standard." },
  { code: "ETH-FEE-03", diff: 3, stem: "Long-outstanding audit fees from prior years most directly create:", options: ["A self-interest threat (the firm becomes a creditor of its client)", "An intimidation threat only", "No threat once invoiced", "An advocacy threat"], answer: 0, explanation: "Owed fees resemble a loan to the client — the Code treats significant overdue fees as a threat requiring evaluation and typically payment or safeguards before continuing." },
]

const noclar: RawBankQ[] = [
  { code: "ETH-NC-01", diff: 1, stem: "NOCLAR stands for:", options: ["Non-Compliance with Laws and Regulations", "New Client Legal Audit Requirements", "National Code of Litigation And Reporting", "No Client Liability Accepted Route"], answer: 0, explanation: "The NOCLAR framework guides professional accountants who become aware of suspected illegal acts by clients or employers." },
  { code: "ETH-NC-02", diff: 2, stem: "When an auditor in practice identifies non-compliance with laws and regulations, the NOCLAR framework's first consideration is:", options: ["Whether the matter's effect is material to the FS or reflects an integrity/ethics issue — then consider internal escalation and, if unaddressed, further action per law and the Code", "Immediate public disclosure", "Resignation without explanation", "Silence under confidentiality"], answer: 0, explanation: "The escalation ladder: understand the facts, discuss with management/TCWG, consider legal advice, then evaluate reporting responsibilities and withdrawal — public disclosure is a defined last resort with legal protection conditions." },
  { code: "ETH-NC-03", diff: 3, stem: "Confidentiality under the Code:", options: ["Yields to legal or professional duties to disclose (e.g., NOCLAR reporting routes) — disclosure by law is not a breach", "Is absolute in all circumstances", "Applies only to tax data", "Ends when the fee is paid"], answer: 0, explanation: "The Code's hierarchy: disclosure permitted/required by law, authorized by the client, or a professional duty/right — NOCLAR carved explicit room for public-interest disclosure." },
]

const conduct: RawBankQ[] = [
  { code: "ETH-GEN-01", diff: 1, stem: "The Code's five fundamental principles are:", options: ["Integrity, objectivity, professional competence and due care, confidentiality, and professional behaviour", "Fees, rotation, independence, quality, and monitoring", "Planning, evidence, reporting, documentation, and review", "Honesty, loyalty, obedience, diligence, and frugality"], answer: 0, explanation: "The five principles anchor every engagement — the framework's threats-and-safeguards machinery exists to protect them." },
  { code: "ETH-GEN-02", diff: 2, stem: "Professional competence and due care requires the auditor to:", options: ["Act diligently in accordance with standards, maintain knowledge at the level required, and work within competence", "Work unlimited hours", "Know every client's industry exhaustively", "Delegate judgment to specialists"], answer: 0, explanation: "Diligence + standards compliance + staying current + knowing the limits of one's competence — knowing when to call the auditor's expert is itself part of the principle." },
  { code: "ETH-GEN-03", diff: 2, stem: "Acting 'with integrity' includes:", options: ["Being straightforward and honest in all professional and business relationships", "Never disagreeing with a client", "Never qualifying an opinion", "Following the client's instructions always"], answer: 0, explanation: "Straightforwardness and honesty — the principle that makes truthful reporting (including modifications when warranted) non-negotiable." },
  { code: "ETH-GEN-04", diff: 3, stem: "A firm discovers an undetected misstatement in a previously issued audit report. Professional behaviour and the framework require:", options: ["Timely remediation: assess the effect, consult law, and cooperate with the firm's quality and remediation processes — concealment is the gravest breach", "Waiting for the client's consent to act", "Correcting it silently in next year's audit", "Selling the practice"], answer: 0, explanation: "Integrity and professional behaviour demand confronting the error — the reputational cost of remediation is never an argument for concealment." },
  { code: "ETH-GEN-05", diff: 2, stem: "Under professional behaviour, marketing of audit services must:", options: ["Not overstate services, or create expectations of outcomes the auditor cannot influence", "Guarantee unmodified opinions", "Promise the lowest fees in the market", "Name the client list always"], answer: 0, explanation: "Marketing must not bring the profession into disrepute — no opinion-shopping signals, no outcome guarantees." },
  { code: "ETH-EGY-01", diff: 2, stem: "In Egypt, the audit profession's ethics framework combines the IESBA Code with:", options: ["The profession's law and ESAA guidance (Law 133/1951 and the Egyptian Society of Accountants and Auditors' rules)", "Only company marketing policies", "The Central Bank's lending manual", "The labor law exclusively"], answer: 0, explanation: "Egyptian registered auditors apply the ESAs and the profession's ethics expectations anchored in the profession law and ESAA — the IESBA concepts operating inside the Egyptian legal frame." },
]

export const ETHICS = [
  ...qs("Ethics — Threats", "ethics", threats),
  ...qs("Ethics — Independence", "ethics", independence),
  ...qs("Ethics — Fees", "ethics", fees),
  ...qs("Ethics — NOCLAR", "ethics", noclar),
  ...qs("Ethics — Fundamentals", "ethics", conduct),
]
