import { qs, type RawBankQ } from "./seed-types"

/* ISA 200–330: objectives, quality, documentation, fraud, laws, governance,
   planning, materiality, risk assessment, responses. 104 items. */

const isa200: RawBankQ[] = [
  { code: "ISA200-01", diff: 1, stem: "What are the overall objectives of the auditor under ISA 200?", options: ["To obtain reasonable assurance about whether the financial statements are free from material misstatement and to report on the financial statements and communicate as required by the ISAs", "To certify the absolute accuracy of the financial statements", "To detect all fraud committed by management", "To prepare the financial statements on behalf of management"], answer: 0, explanation: "ISA 200 sets two overall objectives: (a) obtain reasonable assurance that the FS as a whole are free from material misstatement, whether caused by fraud or error, enabling the auditor to express an opinion, and (b) report on the FS and communicate further as required by the ISAs." },
  { code: "ISA200-02", diff: 1, stem: "The concept of reasonable assurance means the auditor:", options: ["Exercises professional judgment and maintains professional skepticism to reduce risk to an acceptably low level — not absolute assurance", "Guarantees that no misstatements exist", "Relies entirely on management representations", "Only tests material balances above 5% of revenue"], answer: 0, explanation: "Reasonable assurance is a high but not absolute level of assurance — achieved by exercising professional judgment and skepticism, acknowledging inherent limitations of an audit." },
  { code: "ISA200-03", diff: 2, stem: "Which of the following is NOT an inherent limitation of an audit?", options: ["Use of testing (samples rather than 100% examination)", "Management may collude to conceal fraud", "Judgments involve subjectivity", "The auditor's failure to verify every journal entry in the general ledger manually"], answer: 3, explanation: "The first three are recognized inherent limitations (nature of evidence, fraud collusion, subjectivity). Manually verifying every entry is a scope issue, not an inherent limitation — sampling itself is the recognized limitation." },
  { code: "ISA200-04", diff: 2, stem: "Under ISA 200, the auditor's responsibility for the financial statements is to:", options: ["Express an opinion on whether they are prepared, in all material respects, in accordance with the applicable financial reporting framework", "Prepare the financial statements", "Design and implement internal control", "Prevent and detect all fraud"], answer: 0, explanation: "Management is responsible for preparation; the auditor's responsibility is to express an opinion — the respective responsibilities section of the engagement letter reflects this split." },
  { code: "ISA200-05", diff: 2, stem: "Professional skepticism is best described as:", options: ["An attitude that includes a questioning mind, being alert to conditions indicating possible misstatement, and a critical assessment of audit evidence", "Distrusting every management assertion", "Refusing to accept management's written representations", "Auditing at 100% coverage to remove all doubt"], answer: 0, explanation: "Skepticism is a questioning mindset with critical evaluation of evidence — not paranoia, and it certainly does not replace evidence with suspicion." },
  { code: "ISA200-06", diff: 3, stem: "When the auditor cannot reduce audit risk to an acceptably low level, ISA 200 requires:", options: ["The auditor to express a qualified opinion or disclaim an opinion, or withdraw where withdrawal is possible under applicable law", "The auditor to extend testing indefinitely until satisfied", "Issuing an unmodified opinion with an emphasis of matter", "Relying fully on management's internal audit function"], answer: 0, explanation: "If audit risk cannot be reduced to acceptably low (e.g., scope limitations), the auditor considers the effect on the opinion — qualified or disclaimer — or withdrawal where legally possible." },
  { code: "ISA200-07", diff: 2, stem: "Audit risk is the product of:", options: ["Inherent risk × control risk × detection risk", "Business risk × fraud risk × sampling risk", "Materiality × significance × threshold", "Control risk × sampling risk × non-sampling risk"], answer: 0, explanation: "The risk model: AR = IR × CR × DR. The assessed risks of material misstatement (inherent × control) drive the acceptable level of detection risk." },
  { code: "ISA200-08", diff: 1, stem: "Which assertion relates to whether all transactions recorded actually occurred?", options: ["Occurrence", "Completeness", "Accuracy", "Classification"], answer: 0, explanation: "Occurrence addresses whether recorded transactions/events actually happened — the mirror image of completeness (everything that happened is recorded)." },
]

const isa210: RawBankQ[] = [
  { code: "ISA210-01", diff: 1, stem: "The objective of ISA 210 is to ensure the auditor agrees the terms of the engagement with:", options: ["Management or those charged with governance, as appropriate", "The predecessor auditor", "The client's legal counsel", "The tax authority"], answer: 0, explanation: "ISA 210 requires the auditor to agree engagement terms with management or TCWG and confirm both parties understand them — recorded in an engagement letter." },
  { code: "ISA210-02", diff: 2, stem: "If management imposes a scope limitation before the audit begins and the auditor expects to be unable to obtain sufficient appropriate evidence, the auditor should:", options: ["Not accept the engagement unless required by law, in which case communicate the limitation in the report", "Accept and issue an unmodified opinion", "Accept and simply reduce the fee", "Accept and rely on analytics alone"], answer: 0, explanation: "ISA 210: an incoming auditor should not accept an engagement with a pre-existing scope limitation expected to require opinion modification — unless law or regulation requires acceptance, and then the reporting implications are disclosed in the report." },
  { code: "ISA210-03", diff: 2, stem: "Recurring audits: when is a new engagement letter normally NOT required?", options: ["When there is no change in circumstances and management has confirmed the continuing terms", "Never — a letter is required every year by law", "Only when the fee increases", "When management changes the CFO"], answer: 0, explanation: "For recurring audits the auditor assesses whether circumstances changed; absent changes and with an appropriate confirmation to management, the original letter remains in effect." },
  { code: "ISA210-04", diff: 2, stem: "The engagement letter should include:", options: ["The objective and scope of the audit, auditor responsibilities, management responsibilities, the applicable framework, reference to the expected form of report, and fees arrangements", "Only the fee", "Only the partner's CV", "A guarantee of an unmodified opinion"], answer: 0, explanation: "ISA 210 Appendix 2 lists the required contents — objectives/scope, responsibilities of both parties, framework, report form, and fee/billing arrangements." },
  { code: "ISA210-05", diff: 3, stem: "Management refuses to accept the terms in the engagement letter. The auditor should:", options: ["Not commence the audit until agreement is reached, and evaluate the effect on accepting a recurring engagement", "Commence anyway and settle terms later", "Commence and qualify the opinion", "Report management to the regulator immediately"], answer: 0, explanation: "The audit should not begin before terms are agreed; for recurring engagements the auditor should also consider whether the refusal signals governance problems affecting continuance." },
]

const isa220: RawBankQ[] = [
  { code: "ISA220-01", diff: 1, stem: "Under ISA 220, overall responsibility for the quality of each audit engagement rests with:", options: ["The engagement partner", "The quality control reviewer", "Every team member equally", "The firm's managing partner"], answer: 0, explanation: "The engagement partner has overall responsibility for quality on the engagement — direction, supervision, review, and the hot review for listed clients." },
  { code: "ISA220-02", diff: 2, stem: "An engagement quality control review (hot review) is required for:", options: ["Audits of listed entities and other engagements the firm determines involve significant risk", "Every audit the firm performs", "Only first-year audits", "Only audits with qualified opinions"], answer: 0, explanation: "ISQM 1 / ISA 220 require an EQCR for listed-entity audits and any other engagements the firm judges to involve significant risks — not for every audit." },
  { code: "ISA220-03", diff: 2, stem: "The engagement partner's review of significant judgments must occur:", options: ["On or before the date of the auditor's report", "After the financial statements are published", "Only during planning", "Only if a qualification is expected"], answer: 0, explanation: "The partner's evaluation of significant judgments and conclusions must be complete on or before the report date — review cannot trail the opinion." },
  { code: "ISA220-04", diff: 2, stem: "Direction of the engagement team by the partner involves:", options: ["Informing the team of its responsibilities, the nature of the entity's business, risk areas, and problems that may arise", "Assigning only junior staff to risky areas", "Withholding the risk assessment from staff", "Delegating the audit to internal audit"], answer: 0, explanation: "Direction means the team knows the engagement's risks and its own responsibilities — a team told nothing cannot be expected to recognize problems." },
  { code: "ISA220-05", diff: 3, stem: "A team member fails to perform procedures in the time budget and conceals the shortfall by marking steps complete. Under ISA 220 the correct response is:", options: ["Re-perform the affected work, remove the member from the team, and document the remediation", "Accept the work since the file looks complete", "Have the member sign a declaration", "Reduce the audit fee proportionally"], answer: 0, explanation: "Suspected non-compliance with firm policies requires the partner to take responsibility for remediation — re-performance where needed — and address the personnel breach." },
]

const isa230: RawBankQ[] = [
  { code: "ISA230-01", diff: 1, stem: "The primary purpose of audit documentation is to:", options: ["Enable an experienced auditor to understand the work performed, evidence obtained, and significant judgments — and to confirm the ISAs were followed", "Provide billing support to the client", "Replace the client's accounting records", "Serve as a marketing brochure"], answer: 0, explanation: "ISA 230: documentation must let an experienced auditor, with no prior connection to the audit, understand the nature, timing, extent of procedures, evidence, and conclusions." },
  { code: "ISA230-02", diff: 2, stem: "The file must be assembled on a timely basis — normally not later than:", options: ["60 days after the date of the auditor's report", "One year after year-end", "30 days after fieldwork begins", "There is no deadline"], answer: 0, explanation: "The final assembly deadline is 60 days after the report date. After assembly, documentation must not be deleted or discarded before the retention period ends." },
  { code: "ISA230-03", diff: 2, stem: "Audit documentation retention begins:", options: ["From the date of the auditor's report", "From the balance sheet date", "From the engagement letter date", "From the file assembly date"], answer: 0, explanation: "The retention period (often 7 years under Egyptian practice and firm policy) runs from the report date, not from assembly." },
  { code: "ISA230-04", diff: 2, stem: "Which is the LEAST acceptable form of documentation for a significant judgment?", options: ["A verbal explanation given to the reviewer", "A memo documenting alternatives considered and the conclusion", "A signed-off checklist with cross-references", "A summary memorandum of the engagement team discussion"], answer: 0, explanation: "Documentation means records — verbal explanations may clarify but cannot be the evidence; significant judgments need to be documented in the working papers." },
  { code: "ISA230-05", diff: 3, stem: "After the final file has been assembled, the auditor may:", options: ["Add or amend documentation only in limited circumstances, documenting when and by whom changes were made and why", "Freely rewrite conclusions before the retention period ends", "Delete superseded drafts", "Remove evidence contradicting the opinion"], answer: 0, explanation: "Post-assembly changes are exceptional: the auditor must document the reasons, who made them, when, and the effect — a clear trail of any modification." },
  { code: "ISA230-06", diff: 2, stem: "A 'tick' on a schedule means nothing until:", options: ["A legend/tick-mark key explains what the tick represents and who performed it", "The partner initials the last page", "The client signs the schedule", "It is cross-referenced to the opinion"], answer: 0, explanation: "Tick marks are a language — their meanings, performer and reviewer identities, and dates must be documented." },
]

const isa240: RawBankQ[] = [
  { code: "ISA240-01", diff: 1, stem: "Under ISA 240, the primary responsibility for the prevention and detection of fraud rests with:", options: ["Management and those charged with governance", "The external auditor", "The internal audit function", "The audit committee chair alone"], answer: 0, explanation: "Those charged with governance and management bear the primary responsibility — the auditor's role is limited to obtaining reasonable assurance that the FS are not materially misstated due to fraud." },
  { code: "ISA240-02", diff: 1, stem: "Which fraud risk factor is ALWAYS presumed under ISA 240?", options: ["Improper revenue recognition", "Inventory overstatement", "Capitalization of costs", "Related-party transactions"], answer: 0, explanation: "The auditor always presumes a risk of fraud in revenue recognition unless rebuttable with reasons documented — the one irrebuttable-presumption area." },
  { code: "ISA240-03", diff: 2, stem: "The fraud triangle consists of:", options: ["Incentive/pressure, opportunity, and rationalization/attitude", "Motive, means, and opportunity", "Greed, access, and time", "Pressure, concealment, and conversion"], answer: 0, explanation: "The classic fraud triangle: incentive or pressure to commit fraud, a perceived opportunity, and the ability to rationalize the act." },
  { code: "ISA240-04", diff: 2, stem: "Unusual journal entries posted late at night or on weekends by senior management most directly indicate:", options: ["Risk of management override of controls", "Strong work ethic", "Effective closing controls", "Understaffing during close"], answer: 0, explanation: "ISA 240 identifies journal entries made at odd times, by unexpected users, or round-figure amounts as red flags for override — tested through the journal entry testing procedures." },
  { code: "ISA240-05", diff: 2, stem: "The auditor's procedures over journal entries and adjustments address primarily which risk?", options: ["Management override of controls", "Control risk in payroll", "Inherent risk in inventory counts", "Sampling risk in confirmations"], answer: 0, explanation: "Journal entry testing (JET) is the mandated response to the presumed significant risk of management override — selecting entries based on risk characteristics." },
  { code: "ISA240-06", diff: 3, stem: "Management refuses to provide the complete journal entry population. The auditor should:", options: ["Treat it as a scope limitation with potential opinion effects and communicate with TCWG", "Accept management's sample of entries", "Issue an unmodified opinion with EOM", "Ignore it if the preliminary analytics look fine"], answer: 0, explanation: "Without the full population, journal entry testing cannot be performed as required — this is evidence the auditor needs for a mandated significant-risk response, escalating to opinion implications." },
  { code: "ISA240-07", diff: 2, stem: "Which communication does ISA 240 require even when no fraud is identified?", options: ["Written communication to TCWG on the auditor's responsibilities for fraud and the inquiry results", "A report to the tax authority", "A press release", "Notification to the predecessor auditor"], answer: 0, explanation: "The auditor must communicate to TCWG the responsibilities regarding fraud, the inquiry results, and any fraud or suspected fraud identified — even in a clean audit." },
  { code: "ISA240-08", diff: 3, stem: "An auditor discovers a minor misappropriation of assets by a warehouse employee (immaterial). The correct first step is to:", options: ["Communicate the matter to the appropriate level of management and TCWG, considering the implications for the risk assessment", "Issue a qualified opinion", "Report to police immediately", "Ignore it because it is immaterial"], answer: 0, explanation: "Even immaterial fraud gets communicated to management/TCWG — and crucially, the discovery re-opens the risk assessment: what else does this say about controls?" },
]

const isa250: RawBankQ[] = [
  { code: "ISA250-01", diff: 1, stem: "ISA 250 requires the auditor to design procedures to identify:", options: ["Instances of non-compliance with laws and regulations that may have a material effect on the financial statements", "All breaches of any law by any employee", "Personal tax compliance of directors", "Compliance with the firm's quality manual"], answer: 0, explanation: "The auditor's duty covers laws and regulations with a DIRECT material effect on the FS (quantitative disclosures) or a fundamental effect on operations — not every legal breach." },
  { code: "ISA250-02", diff: 2, stem: "The framework distinguishes the effect of non-compliance. Which category includes breach of an operating license that would close the business?", options: ["Non-compliance with a fundamental effect on operations and going concern", "Non-compliance with a direct effect on financial statement amounts", "Non-compliance with disclosure requirements only", "Personal non-compliance of employees"], answer: 0, explanation: "Losing an essential license undermines the entity's ability to continue — this category pulls in ISA 570 going-concern consequences." },
  { code: "ISA250-03", diff: 2, stem: "During the audit the team becomes aware of a deliberate illegal payment (bribe). The auditor should first:", options: ["Understand the nature and circumstances of the act and obtain further information to evaluate the effect on the FS and the audit", "Withdraw immediately", "Qualify the opinion automatically", "Report to the media"], answer: 0, explanation: "ISA 250's sequence: understand the act and its context, evaluate materiality and disclosure, then consider the effect on the report, the client relationship, and possible reporting duties to authorities." },
  { code: "ISA250-04", diff: 3, stem: "Under Egyptian practice, an auditor who suspects money laundering obligations would additionally consider:", options: ["Statutory reporting obligations to the relevant Egyptian authorities, and obtaining legal advice where needed", "Silence to preserve client confidentiality", "Reporting only inside the audit file", "Billing the client for legal research"], answer: 0, explanation: "Where law or regulation establishes reporting duties (e.g., AML regimes), ISA 250 acknowledges the auditor's legal obligation may override confidentiality — legal advice helps navigate the conflict." },
  { code: "ISA250-05", diff: 2, stem: "Written representations under ISA 250 include:", options: ["Management's statement that it has disclosed all known or suspected non-compliance with laws and regulations and the actual or contingent effects of such non-compliance", "A list of every employee's legal issues", "A guarantee there are no lawsuits", "Confirmation of tax computations only"], answer: 0, explanation: "The specific representation: management disclosed all actual or possible non-compliance and their effects — knowledge-based statements from those with responsibility." },
]

const isa260: RawBankQ[] = [
  { code: "ISA260-01", diff: 1, stem: "The purpose of ISA 260 is to establish effective:", options: ["Two-way communication between the auditor and those charged with governance", "Reporting to shareholders", "Communication with the predecessor auditor", "Coordination with internal audit"], answer: 0, explanation: "ISA 260 governs the auditor's communication with TCWG — the audit committee, board — in both directions: planned scope/timing communicated up, and oversight input received back." },
  { code: "ISA260-02", diff: 2, stem: "Matters ordinarily communicated to TCWG include:", options: ["The auditor's responsibilities, planned scope and timing, significant findings, and independence", "Every working paper prepared", "The fee quotation of competitors", "Names of every team member and their CVs"], answer: 0, explanation: "Planned scope/timing, significant findings (misstatements, disagreements, difficulties), and independence matters for listed clients are the core communications." },
  { code: "ISA260-03", diff: 2, stem: "When a significant difficulty was encountered during the audit, the auditor:", options: ["Communicates the difficulty to TCWG", "Withholds it to preserve the relationship", "Records it only in the file", "Reports it to the stock exchange directly"], answer: 0, explanation: "Significant difficulties, management-imposed delays, and unavailability of expected information are communicated to TCWG — they are the client's governance layer." },
  { code: "ISA260-04", diff: 2, stem: "Uncorrected misstatements communicated to TCWG should include:", options: ["The effect of uncorrected misstatements on the auditor's opinion and the effect of prior-period uncorrected misstatements", "Only the largest single item", "Only errors management admits", "No numbers, to avoid alarming them"], answer: 0, explanation: "TCWG need the aggregate effect of uncorrected misstatements — including prior-year carry-forward effects — to discharge their oversight duty." },
  { code: "ISA265-01", diff: 2, stem: "ISA 265 significant deficiencies in internal control must be communicated:", options: ["In writing to management and TCWG on a timely basis", "Orally to the CFO only", "In the auditor's report only", "To the regulator only"], answer: 0, explanation: "Significant deficiencies — those warranting TCWG attention — require timely written communication describing the deficiency and its potential effect plus suggested remediation." },
  { code: "ISA265-02", diff: 2, stem: "A significant deficiency is one where:", options: ["The auditor has determined the design, implementation, or operation of a control is such that it cannot prevent or detect misstatements on a timely basis", "Any control exists at all", "The control was only documented informally", "The client refuses to increase the audit fee"], answer: 0, explanation: "ISA 265 defines significant deficiencies by severity — controls that cannot prevent/detect/correct material misstatements timely merit TCWG attention." },
]

const isa300: RawBankQ[] = [
  { code: "ISA300-01", diff: 1, stem: "The auditor must establish an overall audit strategy that sets:", options: ["The scope, timing, and direction of the audit, and guides the development of the audit plan", "The fee and billing schedule", "The composition of the client's board", "The accounting policies"], answer: 0, explanation: "The strategy is the high-level frame — scope/timing/direction and resource allocation — from which the detailed audit plan flows." },
  { code: "ISA300-02", diff: 2, stem: "The audit plan is more detailed than the strategy and includes:", options: ["The nature, timing, and extent of planned risk assessment and further audit procedures", "Only the timetable of client meetings", "The draft opinion wording", "Only materiality"], answer: 0, explanation: "The plan operationalizes the strategy: the nature/timing/extent of risk assessment procedures, further audit procedures (tests of controls + substantive), and other planned procedures." },
  { code: "ISA300-03", diff: 2, stem: "Planning is:", options: ["A continuing and iterative process throughout the audit, not a one-off phase", "Completed only before fieldwork begins", "Only revisable with the partner's consent and the client's agreement", "Prohibited after the risk assessment"], answer: 0, explanation: "ISA 300 stresses continuity — the plan is revised as risk assessment evolves and findings emerge; plans are living documents." },
  { code: "ISA300-04", diff: 2, stem: "Which item is LEAST likely to be considered when developing the audit strategy?", options: ["The client's marketing plan for next year", "Reporting objectives (deadlines, interim reporting)", "Expected reliance on internal audit work", "The entity's use of IT and its effect on testing"], answer: 0, explanation: "Strategy inputs are reporting, timing, direction, resources, risk areas, and IT environment — not the client's commercial marketing agenda." },
  { code: "ISA300-05", diff: 3, stem: "An unexpected major acquisition closes mid-fieldwork. The team should:", options: ["Revise the overall strategy and audit plan to address the acquisition's risks", "Continue with the original plan to stay within budget", "Issue the report on the original timetable regardless of the new risk", "Treat it as a subsequent event only"], answer: 0, explanation: "Material changes in the entity during the audit trigger a plan revision — scope must follow risk, not the original calendar." },
]

const isa320: RawBankQ[] = [
  { code: "ISA320-01", diff: 1, stem: "Performance materiality is set:", options: ["Lower than overall materiality, to reduce the risk that aggregate uncorrected misstatements exceed overall materiality", "Higher than overall materiality", "Equal to overall materiality", "At 1% of total assets always"], answer: 0, explanation: "Performance materiality (a percentage cut of overall materiality — commonly 50-75%) creates headroom for undetected misstatements accumulating past the overall threshold." },
  { code: "ISA320-02", diff: 2, stem: "Materiality for the financial statements as a whole is set in the context of:", options: ["The entity's circumstances and the common financial information needs of users", "The auditor's fee", "Management's bonus targets", "The smallest ledger account"], answer: 0, explanation: "ISA 320 anchors materiality to user needs — benchmarks like profit, revenue, equity, or total assets are chosen based on what drives user decisions." },
  { code: "ISA320-03", diff: 2, stem: "A 'clearly trivial' threshold is used to:", options: ["Define misstatements below which accumulation is unnecessary", "Set the sampling interval", "Replace performance materiality", "Determine the audit fee"], answer: 0, explanation: "Misstatements below the clearly-trivial threshold (often 1-5% of performance materiality) are not accumulated — the auditor judges them inconsequential." },
  { code: "ISA320-04", diff: 3, stem: "Profit before tax collapsed from 30m to 2m EGP while revenue grew. The most defensible materiality response is to:", options: ["Reassess the benchmark — consider a revenue-based benchmark or normalized profit, given earnings volatility", "Keep the same percentage of the smaller profit", "Set materiality at total assets", "Ignore the change since it is management's problem"], answer: 0, explanation: "A volatile or collapsed benchmark distorts materiality; the auditor reconsiders the benchmark (revenue, or normalized earnings) rather than mechanically applying percentages." },
  { code: "ISA320-05", diff: 2, stem: "Materiality is revised during the audit when:", options: ["New information emerges or circumstances change materially", "The client requests a smaller materiality", "The partner wants a buffer for fee negotiations", "Sampling results are favourable"], answer: 0, explanation: "Materiality is iterative — changes in circumstances (acquisitions, profit collapses) or user-needs information trigger revision with knock-on effects on procedures." },
]

const isa315: RawBankQ[] = [
  { code: "ISA315-01", diff: 1, stem: "The objective of ISA 315 (Revised 2019) is to identify and assess:", options: ["The risks of material misstatement, whether due to fraud or error, at the financial statement and assertion levels", "Only control deficiencies", "Only fraud risks", "Business continuity risks only"], answer: 0, explanation: "Risk identification and assessment — understanding the entity, its environment, its internal control, and using that understanding to drive audit response." },
  { code: "ISA315-02", diff: 1, stem: "A 'significant risk' is:", options: ["An identified and assessed risk of material misstatement for which the assessment of the risk of material misstatement is high", "Any risk in a listed client", "Any risk the CFO flags", "A risk exceeding 10% of revenue"], answer: 0, explanation: "Significant risks get special audit treatment — the auditor evaluates the control environment response and plans procedures addressing the higher assessment." },
  { code: "ISA315-03", diff: 2, stem: "Which component belongs to the five components of internal control?", options: ["Control environment, risk assessment process, information system, control activities, monitoring of controls", "Organizational chart, budget, audit fee, calendar, filing", "Policies, procedures, manuals, forms, systems", "Governance, strategy, marketing, HR, finance"], answer: 0, explanation: "The five-component COSO-style model. The 2019 revision also separates IT controls into general and application levels." },
  { code: "ISA315-04", diff: 2, stem: "The 2019 revision requires the auditor to identify and test controls over:", options: ["System-generated reports and journal entries when relying on system reports or automated controls", "The client's social media", "The cafeteria's food safety", "Employee annual leave"], answer: 0, explanation: "IT-dependent controls and system-generated reports need explicit identification — the auditor tests the underlying data and controls, not just the report output." },
  { code: "ISA315-05", diff: 2, stem: "Risk assessment procedures include:", options: ["Inquiry, analytical procedures, and observation and inspection", "Confirmation and recalculation", "Detail testing of balances", "Management representation only"], answer: 0, explanation: "Risk assessment procedures are inquiry + analytics + observation/inspection — they inform the risk assessment but are not by themselves sufficient appropriate evidence for assertions." },
  { code: "ISA315-06", diff: 3, stem: "In the 2019 spectrum of inherent risk factors, which is a complexity factor?", options: ["Complex transactions involving multiple or unclear standards interpretations", "Susceptibility to management bias", "Volume of transactions", "Degree of subjectivity in measurement"], answer: 0, explanation: "The spectrum's inherent risk factors: complexity, subjectivity, change, uncertainty; plus susceptibility to management bias — complexity is about standards and transaction structure difficulty." },
  { code: "ISA315-07", diff: 2, stem: "Understanding the entity's IT environment includes identifying:", options: ["The applications in use, the nature of IT-dependent controls, and how information flows to financial reporting", "The brand of laptops the team uses", "The IT department's salaries", "The vendor's share price"], answer: 0, explanation: "The auditor maps applications and information flow to FS reporting — that is what makes IT risks audit-relevant." },
  { code: "ISA315-08", diff: 3, stem: "When the auditor plans to test operating effectiveness of controls, the assessed control risk can be:", options: ["Reduced from maximum, decreasing the extent of substantive testing", "Increased to maximum to be safe", "Ignored since substantive tests are mandatory anyway", "Set by the client"], answer: 0, explanation: "Effective tested controls lower control risk — allowing detection risk to rise and substantive procedures to shrink (still never to zero for significant risks)." },
]

const isa330: RawBankQ[] = [
  { code: "ISA330-01", diff: 1, stem: "The nature, timing, and extent of further audit procedures must be:", options: ["Responsive to the assessed risks of material misstatement", "The same for all clients", "Set by the client's CFO", "Limited to substantive procedures"], answer: 0, explanation: "ISA 330's core command: responsiveness. Generic audit programs that ignore the risk assessment fail this requirement." },
  { code: "ISA330-02", diff: 1, stem: "Further audit procedures consist of:", options: ["Tests of controls and substantive procedures", "Only tests of details", "Only analytical procedures", "Confirmations only"], answer: 0, explanation: "Further procedures split into tests of the operating effectiveness of controls and substantive procedures (tests of details + substantive analytics)." },
  { code: "ISA330-03", diff: 2, stem: "For significant risks, substantive procedures must include:", options: ["Tests of details, and if substantive analytics alone cannot provide sufficient appropriate evidence, procedures specifically addressing the risk", "Only analytical procedures", "Only tests of controls", "Management representations"], answer: 0, explanation: "Significant risks demand detail testing; analytics alone cannot carry them, and controls must be tested if the response relies on them." },
  { code: "ISA330-04", diff: 2, stem: "If the auditor intends to rely on controls, but tests show the controls were NOT effective, the auditor should:", options: ["Revise the risk assessment and design substantive procedures addressing the increased risk", "Rely on management's assertion the failures were one-off", "Issue an unmodified opinion with an EOM", "Withdraw from the engagement automatically"], answer: 0, explanation: "Deviation → control risk rises → substantive scope expands. The chain is mechanical: evidence first, then plan updates." },
  { code: "ISA330-05", diff: 2, stem: "Substantive procedures at or near period-end rather than interim are generally required when:", options: ["Control risk is high or the risk involves period-end cut-off", "The fee is small", "The client is unaudited", "The client requests it"], answer: 0, explanation: "High control risk and cut-off-centric risks (revenue, inventory) push timing toward year-end — interim conclusions can be overridden by period-end events." },
  { code: "ISA330-06", diff: 3, stem: "Dual-purpose tests:", options: ["Evaluate both design/implementation and operating effectiveness of controls while gathering substantive evidence", "Test two clients simultaneously", "Cover both interim and final periods automatically", "Satisfy both the ISAs and tax law in one procedure"], answer: 0, explanation: "A dual-purpose test performs control testing and substantive testing together — an efficient response when risk levels permit it." },
  { code: "ISA330-07", diff: 3, stem: "The auditor's procedures for risks the auditor judges to be pervasive to the FS as a whole should include:", options: ["Tests with general applicability across multiple assertions and accounts — e.g., journal entry testing and period-end analytics", "Only balance-sheet detail testing", "Only confirmation of receivables", "Nothing — pervasive risks cannot be tested"], answer: 0, explanation: "Pervasive risks (e.g., integrity of the closing process) call for entity-level responses: JET, overall analytics, walkthroughs of the closing cycle." },
]

const isa402: RawBankQ[] = [
  { code: "ISA402-01", diff: 2, stem: "A service organization provides services that are part of the user entity's information system relevant to financial reporting. The user auditor's primary evidence sources are:", options: ["Type 1 or Type 2 SOC reports and/or performing procedures at the service organization", "The service organization's marketing materials", "The user entity's CEO's confirmation", "Prior year working papers"], answer: 0, explanation: "The user auditor may use a service auditor's SOC 1 report (Type 1 = design; Type 2 = design + operating effectiveness over a period) or test directly at the service organization." },
  { code: "ISA402-02", diff: 2, stem: "Which SOC report covers a PERIOD of time including test of operating effectiveness?", options: ["Type 2", "Type 1", "Both equally", "Neither — that is a SOC 3 concept"], answer: 0, explanation: "Type 2 reports include the service auditor's tests of controls' operating effectiveness over a stated period — essential when the user auditor relies on controls." },
  { code: "ISA402-03", diff: 3, stem: "The user auditor's responsibility when using a Type 2 SOC report is to:", options: ["Understand the services, evaluate the report's suitability (period covered, scope, service auditor's opinion), and perform complementary procedures if needed", "Accept it blindly as the service auditor is independent", "Reject it because it was not performed by the user auditor", "Use it only for tax purposes"], answer: 0, explanation: "The user auditor evaluates the report's relevance and coverage against the assessed risks and complements it where services or periods are not covered." },
]

const isa450: RawBankQ[] = [
  { code: "ISA450-01", diff: 1, stem: "Misstatements are evaluated for their effect on:", options: ["The financial statements as a whole, individually and in aggregate, including prior-period effects", "Only the profit figure", "Only management bonuses", "Only tax"], answer: 0, explanation: "ISA 450 requires evaluation both individually and in aggregate — including the effect of uncorrected prior-period misstatements rolled forward." },
  { code: "ISA450-02", diff: 2, stem: "Misstatements can arise from:", options: ["Inaccuracy in gathering or processing data, differences in judgments on estimates, and differences in accounting policy application", "Only arithmetic errors", "Only fraud", "Only cutoff mistakes"], answer: 0, explanation: "The three sources: factual (inaccuracies), judgmental (estimate differences), and projected misstatements from sampling plus clear anomalies." },
  { code: "ISA450-03", diff: 2, stem: "Management wants to correct only the misstatements that cross materiality and leave smaller ones. The auditor should:", options: ["Consider the nature and cause of each misstatement and the aggregate effect — including whether they indicate fraud risk — before agreeing", "Accept automatically since none crosses materiality alone", "Refuse to continue the audit", "Correct the misstatements himself in the accounts"], answer: 0, explanation: "Aggregation and pattern matter: individually immaterial misstatements may aggregate beyond materiality, or reveal a systematic bias (e.g., always overstating) that signals fraud." },
  { code: "ISA450-04", diff: 3, stem: "Uncorrected misstatements are communicated to:", options: ["Management and those charged with governance, with a request for written representations on uncorrected misstatements", "Only the CFO", "The stock exchange", "The tax authority"], answer: 0, explanation: "TCWG receive the summary of uncorrected misstatements and their effect; management provides a written representation that uncorrected items are immaterial, individually and in aggregate." },
]

export const ISA_CORE = [
  ...qs("ISA 200", "auditing", isa200),
  ...qs("ISA 210", "auditing", isa210),
  ...qs("ISA 220", "auditing", isa220),
  ...qs("ISA 230", "auditing", isa230),
  ...qs("ISA 240", "auditing", isa240),
  ...qs("ISA 250", "auditing", isa250),
  ...qs("ISA 260", "auditing", isa260),
  ...qs("ISA 300", "auditing", isa300),
  ...qs("ISA 320", "auditing", isa320),
  ...qs("ISA 315", "auditing", isa315),
  ...qs("ISA 330", "auditing", isa330),
  ...qs("ISA 402", "auditing", isa402),
  ...qs("ISA 450", "auditing", isa450),
]
